-- Neues Thema Personalwirtschaft im Prüfungskatalog industriekaufmann: 75 neue,
-- selbst formulierte Fragen (30 x multiple, 45 x single). Keine Übernahme aus
-- realen IHK-Prüfungen. Schwerpunkte: Personalplanung und -beschaffung,
-- Arbeitsvertrag und Arbeitsrecht, Arbeitszeit, Entgeltabrechnung, Sozial-
-- versicherung, Personalentwicklung, Mitbestimmung, Arbeitsschutz, Ausbildung
-- nach BBiG, Personalkosten. Fragen sind bewusst aus der HR-Prozess-Perspektive
-- formuliert, nicht aus allgemeiner Wirtschaftskunde-Sicht. Zahlenfragen sind
-- gegenrechnet und geprüft. Source-Key-Präfix: personal-.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'industriekaufmann'
join (values
  -- ============================================================
  -- MULTIPLE CHOICE (30)
  -- ============================================================
  ('Personalwirtschaft', 'personal-m-personalbedarfsermittlung',
   'Welche Aussagen zur Personalbedarfsermittlung treffen zu?',
   'Der Bruttopersonalbedarf ergibt sich aus dem Einsatzbedarf zuzüglich eines Reservebedarfs für Ausfallzeiten wie Urlaub oder Krankheit. Zieht man den bereits vorhandenen, verfügbaren Personalbestand ab, erhält man den Nettopersonalbedarf, der entweder positiv (Neubedarf) oder negativ (Personalüberhang) ausfallen kann.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-interne-personalbeschaffung',
   'Welche Maßnahmen zählen zur internen Personalbeschaffung?',
   'Interne Beschaffung deckt den Bedarf aus der bestehenden Belegschaft: durch Versetzung, innerbetriebliche Ausschreibung oder Mehrarbeit der vorhandenen Mitarbeitenden. Die Schaltung einer Stellenanzeige auf einem externen Jobportal richtet sich dagegen an den externen Arbeitsmarkt.',
   2, 'multiple'),
  ('Personalwirtschaft', 'personal-m-externe-personalbeschaffung',
   'Welche Kanäle zählen zur externen Personalbeschaffung?',
   'Stellenanzeigen auf Jobportalen, die Zusammenarbeit mit der Agentur für Arbeit und die Einschaltung eines Personaldienstleisters richten sich an den externen Arbeitsmarkt. Eine innerbetriebliche Stellenausschreibung wendet sich dagegen ausschließlich an bereits Beschäftigte.',
   2, 'multiple'),
  ('Personalwirtschaft', 'personal-m-bewerbungsunterlagen',
   'Welche Bestandteile gehören üblicherweise zu vollständigen Bewerbungsunterlagen?',
   'Ein Anschreiben, ein Lebenslauf und Zeugniskopien bilden den klassischen Kern einer Bewerbungsmappe. Eine polizeiliche Führungszeugnisvorlage wird nur in bestimmten Berufsfeldern gesondert verlangt und gehört nicht zu den Standardunterlagen jeder Bewerbung.',
   1, 'multiple'),
  ('Personalwirtschaft', 'personal-m-auswahlverfahren',
   'Welche Instrumente werden bei der Personalauswahl typischerweise eingesetzt?',
   'Das strukturierte Vorstellungsgespräch, Arbeitsproben und Assessment-Center-Übungen sind anerkannte Auswahlinstrumente. Eine verbindliche Vorgabe der Konfession des Bewerbers ist unzulässig und mit dem Allgemeinen Gleichbehandlungsgesetz nicht vereinbar.',
   2, 'multiple'),
  ('Personalwirtschaft', 'personal-m-arbeitsvertrag-inhalte',
   'Welche Angaben muss ein Arbeitgeber dem Arbeitnehmer nach dem Nachweisgesetz schriftlich mitteilen?',
   'Das Nachweisgesetz verlangt unter anderem Angaben zu Beginn, Arbeitsort, Tätigkeit, Arbeitszeit und Entgelt. Die private Kontoverbindung des Arbeitnehmers ist dagegen keine Pflichtangabe des Arbeitgebers, sie wird vom Arbeitnehmer selbst für die Gehaltszahlung mitgeteilt.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-befristung-teilzbefg',
   'Welche Aussagen zur Befristung von Arbeitsverträgen nach dem Teilzeit- und Befristungsgesetz treffen zu?',
   'Eine Befristung ohne Sachgrund ist bei einem neuen Arbeitgeber bis zu zwei Jahre zulässig und darf innerhalb dieser Zeit höchstens dreimal verlängert werden. Eine sachgrundlose Befristung ist ausgeschlossen, wenn bereits zuvor ein Arbeitsverhältnis mit demselben Arbeitgeber bestand. Eine Befristung mit Sachgrund, etwa zur Vertretung, kennt dagegen keine gesetzliche Höchstdauer von zwei Jahren.',
   4, 'multiple'),
  ('Personalwirtschaft', 'personal-m-kuendigungsarten',
   'Welche Kündigungsarten kennt das deutsche Arbeitsrecht?',
   'Die ordentliche Kündigung wahrt die gesetzliche oder vertragliche Frist, die außerordentliche Kündigung aus wichtigem Grund beendet das Arbeitsverhältnis fristlos, und die Änderungskündigung verknüpft die Beendigung mit dem Angebot geänderter Bedingungen. Eine "vorläufige Kündigung" als eigenständige Kategorie gibt es rechtlich nicht.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-abmahnung',
   'Welche Aussagen zur Abmahnung im Arbeitsverhältnis treffen zu?',
   'Eine Abmahnung rügt ein konkretes Fehlverhalten, benennt die erwartete künftige Verhaltensänderung und warnt für den Wiederholungsfall vor arbeitsrechtlichen Konsequenzen bis zur Kündigung. Bei einer verhaltensbedingten Kündigung ist sie in der Regel Voraussetzung, bei einer besonders schweren Pflichtverletzung kann sie ausnahmsweise entbehrlich sein.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-arbeitszeitgesetz-grundregeln',
   'Welche Grundregeln legt das Arbeitszeitgesetz für die werktägliche Arbeitszeit fest?',
   'Die werktägliche Arbeitszeit darf grundsätzlich acht Stunden nicht überschreiten, eine Verlängerung auf zehn Stunden ist zulässig, wenn im Ausgleichszeitraum von sechs Kalendermonaten im Schnitt acht Stunden nicht überschritten werden. Nach Arbeitsende ist eine ununterbrochene Ruhezeit von mindestens elf Stunden einzuhalten.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-teilzeit-rechte',
   'Welche Aussagen zum Anspruch auf Teilzeitarbeit nach dem Teilzeit- und Befristungsgesetz treffen zu?',
   'Der Anspruch setzt unter anderem eine Mindestbeschäftigungsdauer und eine bestimmte Mindestbetriebsgröße voraus. Der Arbeitgeber kann den Wunsch aus betrieblichen Gründen ablehnen. Teilzeitbeschäftigte dürfen wegen der Teilzeit nicht schlechter behandelt werden als vergleichbare Vollzeitbeschäftigte, sofern keine sachlichen Gründe eine unterschiedliche Behandlung rechtfertigen.',
   4, 'multiple'),
  ('Personalwirtschaft', 'personal-m-ueberstunden-mehrarbeit',
   'Welche Aussagen zu Überstunden und Mehrarbeit treffen zu?',
   'Überstunden liegen vor, wenn die vertraglich oder betrieblich vereinbarte Arbeitszeit überschritten wird. Ihre Anordnung setzt in der Regel eine arbeitsvertragliche, tarifliche oder betriebliche Grundlage voraus, und der Betriebsrat hat bei der Anordnung von Überstunden ein Mitbestimmungsrecht. Ein pauschaler gesetzlicher Zuschlag von 25 Prozent für jede Überstunde ist gesetzlich nicht vorgeschrieben.',
   4, 'multiple'),
  ('Personalwirtschaft', 'personal-m-lohnbestandteile',
   'Welche Bestandteile gehören zum Bruttoarbeitsentgelt?',
   'Grundlohn, vermögenswirksame Leistungen und ein regelmäßig gezahltes Leistungsentgelt zählen zum steuer- und beitragspflichtigen Bruttoentgelt. Die vom Arbeitgeber einbehaltene und abgeführte Lohnsteuer ist dagegen ein Abzug vom Brutto und selbst kein Bestandteil des Bruttoentgelts.',
   2, 'multiple'),
  ('Personalwirtschaft', 'personal-m-sozialversicherung-zweige',
   'Welche Zweige gehören zur gesetzlichen Sozialversicherung in Deutschland?',
   'Die fünf Säulen sind Kranken-, Renten-, Arbeitslosen-, Pflege- und Unfallversicherung. Die private Haftpflichtversicherung ist keine gesetzliche Pflichtversicherung im Rahmen des Arbeitsverhältnisses, sie wird privat abgeschlossen.',
   1, 'multiple'),
  ('Personalwirtschaft', 'personal-m-beitragstragung',
   'Welche Aussagen zur Tragung der Sozialversicherungsbeiträge treffen zu?',
   'Die Beiträge zur gesetzlichen Unfallversicherung trägt allein der Arbeitgeber. Bei Kranken-, Pflege-, Renten- und Arbeitslosenversicherung teilen sich Arbeitgeber und Arbeitnehmer den Beitrag grundsätzlich hälftig. Der Arbeitgeber behält den Arbeitnehmeranteil vom Bruttolohn ein und führt den Gesamtbeitrag an die zuständige Krankenkasse ab.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-personalentwicklung-massnahmen',
   'Welche Maßnahmen zählen zur betrieblichen Personalentwicklung?',
   'Innerbetriebliche Schulungen, ein systematisches Mitarbeitergespräch mit Zielvereinbarung und die Förderung externer Weiterbildungen sind klassische Instrumente der Personalentwicklung. Eine reine Kürzung des Urlaubsanspruchs gehört nicht dazu, sie ist keine Entwicklungsmaßnahme.',
   2, 'multiple'),
  ('Personalwirtschaft', 'personal-m-zielvereinbarung',
   'Welche Merkmale kennzeichnen eine sinnvolle Zielvereinbarung im Mitarbeitergespräch?',
   'Gute Ziele sind konkret formuliert, in ihrem Erreichungsgrad messbar und innerhalb eines vereinbarten Zeitraums realistisch erreichbar. Ein Ziel, das absichtlich unerreichbar hoch gesetzt wird, motiviert in der Praxis eher weniger und widerspricht dem Grundgedanken der Zielvereinbarung.',
   2, 'multiple'),
  ('Personalwirtschaft', 'personal-m-betriebsrat-wahl',
   'Welche Aussagen zur Wahl des Betriebsrats nach dem Betriebsverfassungsgesetz treffen zu?',
   'Wahlberechtigt sind alle Arbeitnehmerinnen und Arbeitnehmer des Betriebs ab 16 Jahren, wählbar ist grundsätzlich, wer volljährig ist und dem Betrieb eine bestimmte Mindestzeit angehört. Die Amtszeit des Betriebsrats beträgt regelmäßig vier Jahre. Leitende Angestellte im Sinne des Gesetzes gehören nicht zum wahlberechtigten Kreis des Betriebsrats.',
   4, 'multiple'),
  ('Personalwirtschaft', 'personal-m-mitbestimmungsrechte',
   'In welchen Angelegenheiten hat der Betriebsrat nach dem Betriebsverfassungsgesetz ein echtes Mitbestimmungsrecht?',
   'Echte Mitbestimmung betrifft vor allem soziale Angelegenheiten: Beginn und Ende der täglichen Arbeitszeit, die Aufstellung von Urlaubsgrundsätzen und die Einführung technischer Kontrolleinrichtungen. Über das Produktprogramm und unternehmerische Grundsatzentscheidungen entscheidet der Arbeitgeber allein.',
   4, 'multiple'),
  ('Personalwirtschaft', 'personal-m-jav',
   'Welche Aussagen zur Jugend- und Auszubildendenvertretung (JAV) treffen zu?',
   'Die JAV vertritt die Interessen der Auszubildenden und der Arbeitnehmer unter 18 Jahren im Betrieb. Sie kann Anträge an den Betriebsrat richten und hat dort ein Antrags- und Rederecht in eigenen Angelegenheiten. Sie ersetzt den Betriebsrat nicht und trifft keine eigenständigen Mitbestimmungsentscheidungen ohne diesen.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-jugendarbeitsschutz',
   'Welche Regelungen sieht das Jugendarbeitsschutzgesetz für Jugendliche vor?',
   'Die tägliche Arbeitszeit ist grundsätzlich auf acht Stunden begrenzt, Beschäftigung ist grundsätzlich nur am Tag zulässig, und die Arbeitszeit ist auf höchstens fünf Tage in der Woche zu verteilen. Nachtarbeit bleibt bis zur Volljährigkeit mit nur wenigen branchenbezogenen Ausnahmen untersagt.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-mutterschutz',
   'Welche Aussagen zum Mutterschutzgesetz treffen zu?',
   'Das Gesetz sieht grundsätzlich eine Schutzfrist vor und nach der Entbindung vor, in der Regel besteht ein Beschäftigungsverbot. Während der Schutzfristen erhält die Arbeitnehmerin in aller Regel Mutterschaftsleistungen statt des laufenden Gehalts vom Arbeitgeber. Eine Kündigung während Schwangerschaft und Schutzfrist ist nur in eng begrenzten Ausnahmefällen mit behördlicher Zulässigkeitserklärung möglich.',
   4, 'multiple'),
  ('Personalwirtschaft', 'personal-m-elternzeit',
   'Welche Aussagen zur Elternzeit treffen zu?',
   'Elternzeit kann von beiden Elternteilen beansprucht werden und dient der Betreuung eines Kindes, sie ist grundsätzlich unbezahlt. Während der Elternzeit besteht ein besonderer Kündigungsschutz. Das Arbeitsverhältnis selbst bleibt bestehen, es ruht lediglich, es endet nicht automatisch mit dem Antritt der Elternzeit.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-arbeitsschutz-allgemein',
   'Welche Aussagen zum allgemeinen betrieblichen Arbeitsschutz treffen zu?',
   'Der Arbeitgeber ist verpflichtet, eine Gefährdungsbeurteilung für die Arbeitsplätze durchzuführen und die nötigen Schutzmaßnahmen daraus abzuleiten. Beschäftigte sind über Gefahren an ihrem Arbeitsplatz zu unterweisen. Die Bestellung einer Sicherheitsfachkraft entbindet den Arbeitgeber nicht von seiner eigenen Verantwortung für den Arbeitsschutz im Betrieb.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-berufsausbildungsvertrag',
   'Welche Angaben muss ein Berufsausbildungsvertrag nach dem Berufsbildungsgesetz mindestens enthalten?',
   'Der Vertrag muss unter anderem Beginn und Dauer der Ausbildung, die sachliche und zeitliche Gliederung, die tägliche Ausbildungszeit sowie die Höhe der Vergütung enthalten. Eine Verpflichtung des Auszubildenden, nach der Ausbildung eine bestimmte Mindestzeit im Betrieb zu bleiben, ist als Vertragsinhalt unzulässig.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-pflichten-ausbildender-personal',
   'Welche Pflichten treffen den Ausbildenden gegenüber dem Auszubildenden nach dem BBiG?',
   'Der Ausbildende muss die im Ausbildungsrahmenplan vorgesehenen Fertigkeiten und Kenntnisse vermitteln, die dafür nötigen Ausbildungsmittel kostenfrei zur Verfügung stellen und für Berufsschule sowie Prüfungen freistellen. Eine Verpflichtung, private Fahrtkosten zur Berufsschule zu übernehmen, gehört nicht zu den gesetzlichen Pflichten des Ausbildenden.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-ihk-pruefung',
   'Welche Aussagen zum Ablauf der IHK-Abschlussprüfung treffen zu?',
   'Die Zulassung zur Abschlussprüfung setzt unter anderem die ordnungsgemäße Führung des schriftlichen Ausbildungsnachweises voraus. Der Prüfungsausschuss ist paritätisch besetzt, ihm gehören Vertreter der Arbeitgeber- und der Arbeitnehmerseite sowie mindestens eine Lehrkraft an. Bei Nichtbestehen kann die Ausbildungszeit auf Verlangen des Auszubildenden bis zur nächstmöglichen Wiederholungsprüfung verlängert werden, höchstens jedoch um ein Jahr.',
   4, 'multiple'),
  ('Personalwirtschaft', 'personal-m-personalnebenkosten',
   'Welche Kostenarten zählen zu den Personalnebenkosten eines Unternehmens?',
   'Der Arbeitgeberanteil zur Sozialversicherung, Aufwendungen für Fortbildung sowie freiwillige Sozialleistungen wie ein Zuschuss zum Mittagessen gehören zu den Personalnebenkosten. Der laufende Bruttolohn selbst ist dagegen die eigentliche Personalgrundkostenposition und wird begrifflich nicht zu den Nebenkosten gezählt.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-direkte-indirekte-personalkosten',
   'Welche Kostenarten lassen sich den indirekten Personalkosten zuordnen?',
   'Entgeltfortzahlung im Krankheitsfall, bezahlte Urlaubstage und die Kosten der betrieblichen Ausbildung fallen an, ohne dass ihnen eine unmittelbare Arbeitsleistung gegenübersteht, sie zählen zu den indirekten Personalkosten. Der für tatsächlich geleistete Arbeitsstunden gezahlte Grundlohn ist dagegen eine direkte Personalkostenposition.',
   3, 'multiple'),
  ('Personalwirtschaft', 'personal-m-vwl-leistungen',
   'Welche Aussagen zu vermögenswirksamen Leistungen und geldwertem Vorteil treffen zu?',
   'Vermögenswirksame Leistungen sind ein vom Arbeitgeber gezahlter Betrag, der zweckgebunden angelegt wird, etwa in einen Sparvertrag. Ein geldwerter Vorteil entsteht, wenn der Arbeitgeber eine Sachleistung wie die private Nutzung eines Dienstwagens gewährt, dieser Vorteil ist grundsätzlich steuer- und beitragspflichtig wie Bargeldlohn.',
   3, 'multiple'),
  -- ============================================================
  -- SINGLE CHOICE (45)
  -- ============================================================
  ('Personalwirtschaft', 'personal-s-personalbedarf-arten',
   'Wie wird der Personalbedarf bezeichnet, der zusätzlich zum reinen Einsatzbedarf für Ausfallzeiten wie Urlaub und Krankheit vorgehalten wird?',
   'Dieser zusätzliche Bedarf heißt Reservebedarf. Zusammen mit dem Einsatzbedarf ergibt er den Bruttopersonalbedarf.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-stellenausschreibung-intern',
   'Was ist ein typischer Vorteil der internen gegenüber der externen Stellenausschreibung?',
   'Interne Bewerber sind bereits mit den betrieblichen Abläufen vertraut, was Einarbeitungszeit und -kosten senkt. Zudem wirkt eine interne Besetzung oft motivierend, weil sie Aufstiegschancen im Betrieb sichtbar macht.',
   1, 'single'),
  ('Personalwirtschaft', 'personal-s-bewerbungsgespraech-zweck',
   'Was ist das zentrale Ziel eines Vorstellungsgesprächs aus Sicht des Unternehmens?',
   'Es soll prüfen, ob die fachliche Eignung und die persönliche Passung des Bewerbers zur ausgeschriebenen Stelle und zum Team passen. Reine Formfragen wie die Vollständigkeit der Unterlagen sind dagegen bereits vorab geklärt.',
   1, 'single'),
  ('Personalwirtschaft', 'personal-s-assessment-center',
   'Was kennzeichnet ein Assessment-Center als Auswahlverfahren?',
   'Mehrere Bewerber durchlaufen an einem oder mehreren Tagen verschiedene Übungen, etwa Gruppendiskussionen, Präsentationen oder Rollenspiele, und werden dabei von mehreren geschulten Beobachtern beurteilt.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-personalbeschaffung-zeitarbeit',
   'Welches rechtliche Konstrukt liegt der Arbeitnehmerüberlassung (Zeitarbeit) zugrunde?',
   'Der Zeitarbeitnehmer steht in einem Arbeitsverhältnis zum Verleiher, wird aber vertraglich einem Entleihbetrieb zur Arbeitsleistung überlassen, der ihm im Rahmen des Einsatzes Weisungen erteilt.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-probezeit-dauer',
   'Wie lang darf eine vereinbarte Probezeit in einem regulären, unbefristeten Arbeitsverhältnis höchstens dauern?',
   'Die Probezeit darf höchstens sechs Monate betragen. Während dieser Zeit gilt eine verkürzte gesetzliche Kündigungsfrist von zwei Wochen, sofern nichts anderes vereinbart ist.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-kuendigungsfrist-grundfrist-personal',
   'Welche gesetzliche Grundkündigungsfrist gilt nach dem BGB, wenn ein Arbeitnehmer sein Arbeitsverhältnis selbst kündigt?',
   'Die Grundfrist beträgt vier Wochen zum 15. oder zum Ende eines Kalendermonats. Die mit der Betriebszugehörigkeit steigenden längeren Fristen des § 622 Abs. 2 BGB gelten nur für Kündigungen durch den Arbeitgeber.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-kuendigungsfrist-calc-1',
   'Ein Arbeitgeber kündigt einem Arbeitnehmer, der seit sechs Jahren ununterbrochen im Betrieb beschäftigt ist. Welche gesetzliche Kündigungsfrist nach § 622 Abs. 2 BGB muss der Arbeitgeber mindestens einhalten?',
   'Nach fünf Jahren Betriebszugehörigkeit steigt die gesetzliche Frist auf zwei Monate zum Ende eines Kalendermonats. Da sechs Jahre bereits über der Fünf-Jahres-Schwelle liegen und die nächste Stufe erst bei acht Jahren mit drei Monaten greift, gilt hier die Zwei-Monats-Frist.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-kuendigungsfrist-calc-2',
   'Ein Arbeitnehmer ohne besondere vertragliche Kündigungsfrist kündigt sein Arbeitsverhältnis am 10. März. Zu welchem Termin endet das Arbeitsverhältnis frühestens?',
   'Die gesetzliche Frist des Arbeitnehmers beträgt vier Wochen (28 Tage) zum 15. oder zum Monatsende. Vom 10. März aus gerechnet sind 28 Tage später der 7. April erreicht. Der nächste zulässige Termin danach ist der 15. April, denn der 7. April selbst ist weder der 15. noch ein Monatsende.',
   4, 'single'),
  ('Personalwirtschaft', 'personal-s-aenderungskuendigung',
   'Was ist das kennzeichnende Merkmal einer Änderungskündigung?',
   'Der Arbeitgeber kündigt das bestehende Arbeitsverhältnis und bietet gleichzeitig dessen Fortsetzung zu geänderten Bedingungen an. Der Arbeitnehmer kann das Angebot annehmen, ablehnen oder unter Vorbehalt annehmen und die Änderung gerichtlich überprüfen lassen.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-arbeitszeugnis-zwischenzeugnis',
   'Wann besteht in der Regel ein Anspruch auf ein Zwischenzeugnis?',
   'Ein Zwischenzeugnis wird während eines fortbestehenden Arbeitsverhältnisses ausgestellt, etwa bei einem Vorgesetztenwechsel, einer internen Versetzung oder aus einem sonstigen berechtigten Interesse des Arbeitnehmers. Das Arbeitsverhältnis muss dafür nicht beendet sein.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-ruhepause-arbzg',
   'Welche Ruhepause schreibt das Arbeitszeitgesetz bei einer täglichen Arbeitszeit von mehr als neun Stunden vor?',
   'Ab mehr als neun Stunden sind mindestens 45 Minuten Pause vorgeschrieben, bei mehr als sechs bis neun Stunden genügen 30 Minuten. Die Pause darf in Abschnitte von jeweils mindestens 15 Minuten aufgeteilt werden.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-hoechstarbeitszeit',
   'Auf welchen Wert darf die werktägliche Arbeitszeit nach dem Arbeitszeitgesetz im Ausnahmefall verlängert werden, wenn ein entsprechender Ausgleich erfolgt?',
   'Eine Verlängerung auf bis zu zehn Stunden werktäglich ist zulässig, wenn innerhalb von sechs Kalendermonaten oder 24 Wochen im Durchschnitt acht Stunden pro Werktag nicht überschritten werden.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-gleitzeit-begriff',
   'Was kennzeichnet ein Gleitzeitmodell im Unterschied zu starren Arbeitszeiten?',
   'Bei der Gleitzeit können Beschäftigte Beginn und Ende ihrer Arbeitszeit innerhalb eines vorgegebenen Rahmens selbst bestimmen, oft ergänzt um eine Kernarbeitszeit, in der Anwesenheit verpflichtend ist.',
   1, 'single'),
  ('Personalwirtschaft', 'personal-s-ueberstundenverguetung-calc',
   'Ein Arbeitnehmer erhält einen Stundenlohn von 18 Euro. Laut Betriebsvereinbarung wird jede Überstunde mit einem Zuschlag von 25 Prozent vergütet. Wie hoch ist die Vergütung für 8 geleistete Überstunden?',
   'Der Stundensatz für Überstunden beträgt 18 Euro mal 1,25, also 22,50 Euro je Stunde. Bei 8 Überstunden ergibt das 8 mal 22,50 Euro, insgesamt 180 Euro.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-brutto-netto-begriffe',
   'Was versteht man unter dem Nettoarbeitsentgelt?',
   'Das Nettoentgelt ist der Betrag, der dem Arbeitnehmer nach Abzug von Lohnsteuer, Solidaritätszuschlag, gegebenenfalls Kirchensteuer und dem Arbeitnehmeranteil zur Sozialversicherung vom Bruttoentgelt tatsächlich ausgezahlt wird.',
   1, 'single'),
  ('Personalwirtschaft', 'personal-s-lohnsteuerklassen',
   'Wonach richtet sich in Deutschland die Zuordnung eines Arbeitnehmers zu einer Lohnsteuerklasse?',
   'Maßgeblich sind vor allem der Familienstand sowie bei Verheirateten die gewählte Kombination der Steuerklassen. Sie beeinflusst die Höhe des monatlichen Lohnsteuerabzugs, nicht aber die endgültige Steuerschuld, die sich erst aus der Einkommensteuerveranlagung ergibt.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-brutto-netto-calc',
   'Ein Arbeitnehmer hat ein monatliches Bruttoentgelt von 2.800 Euro. Lohnsteuer und Sozialversicherungsbeiträge zusammen betragen laut vereinfachter Abrechnung pauschal 38 Prozent des Bruttoentgelts. Wie hoch ist das Nettoentgelt?',
   'Die Abzüge betragen 38 Prozent von 2.800 Euro, also 1.064 Euro. Das Nettoentgelt ergibt sich aus 2.800 Euro minus 1.064 Euro, also 1.736 Euro. Gleichwertig lässt sich mit dem verbleibenden Anteil von 62 Prozent rechnen: 2.800 Euro mal 0,62 ergibt ebenfalls 1.736 Euro.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-geldwerter-vorteil-begriff',
   'Was versteht man unter einem geldwerten Vorteil im Lohnsteuerrecht?',
   'Ein geldwerter Vorteil liegt vor, wenn der Arbeitgeber dem Arbeitnehmer eine Sachleistung oder einen sonstigen Vorteil gewährt, der einen wirtschaftlichen Wert hat, etwa die private Nutzung eines Dienstwagens. Er wird grundsätzlich wie Bargeldlohn versteuert und verbeitragt.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-vwl-begriff',
   'Wofür werden vermögenswirksame Leistungen (VL) typischerweise verwendet?',
   'Vermögenswirksame Leistungen sind ein zusätzlicher Betrag des Arbeitgebers, der zweckgebunden in einer vom Arbeitnehmer gewählten Anlageform, etwa einem Bausparvertrag oder Fondssparplan, angelegt wird, statt als freier Barlohn ausgezahlt zu werden.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-fuenf-saeulen',
   'Welche der folgenden Versicherungen gehört zu den fünf Zweigen der gesetzlichen Sozialversicherung?',
   'Die Pflegeversicherung ist einer der fünf gesetzlichen Zweige neben Kranken-, Renten-, Arbeitslosen- und Unfallversicherung. Die Hausratversicherung ist eine private, freiwillige Versicherung und kein Teil der Sozialversicherung.',
   1, 'single'),
  ('Personalwirtschaft', 'personal-s-krankenversicherung-pflicht',
   'Ab welchem Zeitpunkt beginnt für einen neu eingestellten sozialversicherungspflichtigen Arbeitnehmer grundsätzlich die Mitgliedschaft in der gesetzlichen Krankenversicherung?',
   'Die Versicherungspflicht beginnt mit dem tatsächlichen Antritt der Beschäftigung, also regelmäßig mit dem ersten Arbeitstag, nicht erst mit der ersten Gehaltszahlung.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-pflegeversicherung-zweck',
   'Welchem Zweck dient die gesetzliche Pflegeversicherung?',
   'Sie sichert einen Teil der finanziellen Belastungen ab, die bei Pflegebedürftigkeit entstehen, etwa für häusliche oder stationäre Pflege. Sie deckt die Kosten dabei grundsätzlich nur teilweise ab und ersetzt keine private Vorsorge vollständig.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-arbeitslosenversicherung-zweck',
   'Welche Hauptleistung erbringt die gesetzliche Arbeitslosenversicherung bei Verlust des Arbeitsplatzes?',
   'Sie zahlt unter bestimmten Voraussetzungen Arbeitslosengeld als zeitlich befristeten Lohnersatz und unterstützt zudem durch Vermittlung und Fördermaßnahmen bei der Wiedereingliederung in den Arbeitsmarkt.',
   1, 'single'),
  ('Personalwirtschaft', 'personal-s-unfallversicherung-traeger',
   'Wer trägt die Beiträge zur gesetzlichen Unfallversicherung?',
   'Die Unfallversicherung wird als einziger Sozialversicherungszweig allein vom Arbeitgeber finanziert, weil sie das betriebliche Risiko von Arbeitsunfällen und Berufskrankheiten absichert.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-fortbildung-weiterbildung-unterschied',
   'Worin unterscheidet sich berufliche Fortbildung typischerweise von allgemeiner Weiterbildung?',
   'Fortbildung baut gezielt auf einer bereits abgeschlossenen Berufsausbildung auf und führt oft zu einem anerkannten höheren Abschluss, etwa dem Meister oder Fachwirt. Weiterbildung ist der weitere Oberbegriff und schließt auch Maßnahmen ohne formalen Abschlussbezug ein.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-personalbeurteilung-zweck',
   'Welchem Zweck dient eine systematische Personalbeurteilung im Unternehmen?',
   'Sie liefert eine strukturierte Grundlage, um Leistung und Verhalten von Mitarbeitenden nachvollziehbar einzuschätzen, etwa für Entscheidungen zu Weiterbildung, Beförderung oder Entgelt.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-mitarbeitergespraech',
   'Was ist ein zentrales Merkmal eines strukturierten jährlichen Mitarbeitergesprächs?',
   'Es findet in der Regel als vertrauliches Vier-Augen-Gespräch zwischen Führungskraft und Mitarbeitendem statt und dient dem Rückblick auf die Zusammenarbeit sowie der Vereinbarung von Zielen für die kommende Periode.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-coaching-mentoring',
   'Was unterscheidet Mentoring von einem klassischen fachlichen Training?',
   'Beim Mentoring begleitet eine erfahrene Person über einen längeren Zeitraum individuell die persönliche und berufliche Entwicklung einer weniger erfahrenen Person, während ein Training meist zeitlich begrenzt bestimmte Fachinhalte vermittelt.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-betriebsrat-groesse',
   'Wovon hängt die Anzahl der Mitglieder eines Betriebsrats nach dem Betriebsverfassungsgesetz ab?',
   'Die Größe des Betriebsrats richtet sich nach der Anzahl der im Betrieb regelmäßig beschäftigten wahlberechtigten Arbeitnehmer, mit steigender Belegschaftsgröße wächst auch die Anzahl der Betriebsratsmitglieder.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-betriebsversammlung',
   'Was ist eine Betriebsversammlung nach dem Betriebsverfassungsgesetz?',
   'Sie ist die Versammlung aller Arbeitnehmer eines Betriebs, auf der der Betriebsrat regelmäßig über seine Tätigkeit berichtet. Sie findet üblicherweise während der Arbeitszeit statt, ohne dass den Teilnehmenden dadurch ein Entgeltnachteil entsteht.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-jav-voraussetzung',
   'Ab welcher Anzahl von wahlberechtigten Jugendlichen und Auszubildenden im Betrieb wird in der Regel eine Jugend- und Auszubildendenvertretung gewählt?',
   'Eine JAV wird gewählt, wenn im Betrieb in der Regel mindestens fünf Arbeitnehmer beschäftigt sind, die noch nicht 18 Jahre alt sind oder sich in Berufsausbildung befinden.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-mitwirkung-vs-mitbestimmung',
   'Worin unterscheidet sich ein reines Mitwirkungsrecht des Betriebsrats von einem echten Mitbestimmungsrecht?',
   'Beim Mitwirkungsrecht kann der Betriebsrat angehört werden und Vorschläge einbringen, die endgültige Entscheidung trifft aber der Arbeitgeber allein. Bei der echten Mitbestimmung ist dagegen die Zustimmung des Betriebsrats erforderlich, ohne sie darf der Arbeitgeber nicht handeln.',
   4, 'single'),
  ('Personalwirtschaft', 'personal-s-jugendarbeitsschutz-mindestalter',
   'Ab welchem Alter dürfen Jugendliche nach dem Jugendarbeitsschutzgesetz grundsätzlich regelmäßig beschäftigt werden?',
   'Das Gesetz erlaubt die reguläre Beschäftigung grundsätzlich ab 15 Jahren, also nach Beendigung der Vollzeitschulpflicht. Für Kinder unter 15 Jahren gelten enge, eng begrenzte Ausnahmen, etwa für bestimmte leichte Tätigkeiten.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-mutterschutzfrist',
   'Wie lange dauert die gesetzliche Schutzfrist nach der Entbindung im Regelfall des Mutterschutzgesetzes?',
   'Im Regelfall dauert die Schutzfrist nach der Entbindung acht Wochen. Bei Frühgeburten, Mehrlingsgeburten oder der Feststellung einer Behinderung des Kindes verlängert sich diese Frist auf zwölf Wochen.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-elternzeit-dauer',
   'Bis zu welchem Alter des Kindes kann Elternzeit grundsätzlich beansprucht werden?',
   'Elternzeit kann grundsätzlich bis zur Vollendung des dritten Lebensjahres des Kindes beansprucht werden, ein Teil davon kann unter bestimmten Voraussetzungen auch auf einen späteren Zeitraum bis zum achten Geburtstag übertragen werden.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-gefaehrdungsbeurteilung',
   'Wer ist im Betrieb grundsätzlich verpflichtet, eine Gefährdungsbeurteilung der Arbeitsplätze durchzuführen?',
   'Die Pflicht zur Gefährdungsbeurteilung trifft nach dem Arbeitsschutzgesetz den Arbeitgeber. Er kann sich dabei fachkundig unterstützen lassen, etwa durch eine Fachkraft für Arbeitssicherheit, die Verantwortung bleibt aber bei ihm.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-probezeit-ausbildung',
   'Wie lang muss die Probezeit in einem Berufsausbildungsverhältnis nach dem BBiG mindestens dauern?',
   'Die Probezeit muss mindestens einen Monat und darf höchstens vier Monate betragen. Während dieser Zeit kann das Ausbildungsverhältnis von beiden Seiten ohne Einhaltung einer Frist und ohne Angabe von Gründen gekündigt werden.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-ausbildungsvertrag-inhalt',
   'Welche Angabe gehört zwingend zu den Mindestinhalten eines Berufsausbildungsvertrags nach dem BBiG?',
   'Die Dauer der Berufsausbildung ist eine der gesetzlich vorgeschriebenen Mindestangaben. Eine Regelung zur Übernahme nach der Ausbildung ist dagegen freiwillig und kein zwingender Vertragsbestandteil.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-zwischenpruefung-zweck',
   'Welchem Zweck dient die Zwischenprüfung während der Berufsausbildung?',
   'Sie stellt den bisherigen Ausbildungsstand fest und gibt Auszubildendem und Ausbildungsbetrieb eine Rückmeldung über den Lernfortschritt. Ihr Ergebnis fließt in der Regel nicht als eigenständige Note in das Ergebnis der Abschlussprüfung ein.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-kuendigung-ausbildungsverhaeltnis',
   'Unter welcher Voraussetzung kann ein Auszubildender das Berufsausbildungsverhältnis nach der Probezeit ordentlich kündigen?',
   'Nach der Probezeit kann der Auszubildende mit einer Frist von vier Wochen kündigen, wenn er die Berufsausbildung ganz aufgeben oder sich für eine andere Berufsausbildung entscheiden will. Eine fristlose Kündigung bleibt daneben bei Vorliegen eines wichtigen Grundes möglich.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-personalnebenkosten-beispiele',
   'Welche der folgenden Positionen ist ein klassisches Beispiel für Personalnebenkosten?',
   'Der Arbeitgeberanteil zur gesetzlichen Sozialversicherung ist eine typische Personalnebenkostenposition, die zusätzlich zum eigentlichen Bruttolohn anfällt.',
   2, 'single'),
  ('Personalwirtschaft', 'personal-s-urlaubsanspruch-austritt-calc',
   'Ein Arbeitnehmer mit einem vertraglichen Jahresurlaub von 28 Tagen scheidet zum 30. Juni aus dem Unternehmen aus, nachdem er seit Jahresbeginn durchgehend beschäftigt war. Wie viele Urlaubstage stehen ihm anteilig für dieses Jahr zu?',
   'Bei unterjährigem Ausscheiden entsteht der Anspruch anteilig mit einem Zwölftel des Jahresurlaubs je vollem Beschäftigungsmonat. Von Januar bis Juni sind das sechs volle Monate. 28 Tage geteilt durch 12 ergibt rund 2,333 Tage pro Monat, multipliziert mit 6 Monaten ergibt das 14 Urlaubstage.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-urlaubsanspruch-eintritt-calc',
   'Ein Arbeitnehmer mit einem vertraglichen Jahresurlaub von 30 Tagen tritt zum 1. September in das Unternehmen ein. Das Urlaubsjahr entspricht dem Kalenderjahr. Wie viele Urlaubstage stehen ihm für den Rest dieses Jahres anteilig zu?',
   'Von September bis Dezember sind vier volle Beschäftigungsmonate erreicht. 30 Tage geteilt durch 12 ergibt 2,5 Tage pro Monat, multipliziert mit 4 Monaten ergibt das 10 Urlaubstage für den Rest des Jahres.',
   3, 'single'),
  ('Personalwirtschaft', 'personal-s-teilurlaubstage-rundung',
   'Ergibt die Berechnung eines anteiligen Urlaubsanspruchs einen Bruchteil von Urlaubstagen, zum Beispiel 14,5 Tage, wie ist nach dem Bundesurlaubsgesetz zu verfahren?',
   'Ergeben sich bei der Berechnung des Teilurlaubs Bruchteile von mindestens einem halben Tag, werden diese nach dem Bundesurlaubsgesetz auf volle Urlaubstage aufgerundet. Aus 14,5 Tagen werden damit 15 volle Urlaubstage.',
   3, 'single')
) as v(topic_name, source_key, q, expl, difficulty, question_type)
on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- personal-m-personalbedarfsermittlung
  ('personal-m-personalbedarfsermittlung', 'Der Bruttopersonalbedarf setzt sich aus Einsatzbedarf und Reservebedarf zusammen', true, 0),
  ('personal-m-personalbedarfsermittlung', 'Der Nettopersonalbedarf ergibt sich aus dem Bruttopersonalbedarf abzüglich des verfügbaren Personalbestands', true, 1),
  ('personal-m-personalbedarfsermittlung', 'Ein negativer Nettopersonalbedarf zeigt einen Personalüberhang an', true, 2),
  ('personal-m-personalbedarfsermittlung', 'Der Reservebedarf berücksichtigt keine Urlaubs- oder Krankheitszeiten', false, 3),
  -- personal-m-interne-personalbeschaffung
  ('personal-m-interne-personalbeschaffung', 'Versetzung eines Mitarbeiters aus einer anderen Abteilung', true, 0),
  ('personal-m-interne-personalbeschaffung', 'Innerbetriebliche Stellenausschreibung', true, 1),
  ('personal-m-interne-personalbeschaffung', 'Anordnung von Mehrarbeit bei vorhandenem Personal', true, 2),
  ('personal-m-interne-personalbeschaffung', 'Schaltung einer Stellenanzeige auf einem externen Jobportal', false, 3),
  -- personal-m-externe-personalbeschaffung
  ('personal-m-externe-personalbeschaffung', 'Stellenanzeige auf einem Online-Jobportal', true, 0),
  ('personal-m-externe-personalbeschaffung', 'Zusammenarbeit mit der Agentur für Arbeit', true, 1),
  ('personal-m-externe-personalbeschaffung', 'Vermittlung durch einen Personaldienstleister', true, 2),
  ('personal-m-externe-personalbeschaffung', 'Innerbetriebliche Stellenausschreibung', false, 3),
  -- personal-m-bewerbungsunterlagen
  ('personal-m-bewerbungsunterlagen', 'Anschreiben', true, 0),
  ('personal-m-bewerbungsunterlagen', 'Lebenslauf', true, 1),
  ('personal-m-bewerbungsunterlagen', 'Kopien relevanter Zeugnisse', true, 2),
  ('personal-m-bewerbungsunterlagen', 'Standardmäßig vorzulegendes polizeiliches Führungszeugnis', false, 3),
  -- personal-m-auswahlverfahren
  ('personal-m-auswahlverfahren', 'Strukturiertes Vorstellungsgespräch', true, 0),
  ('personal-m-auswahlverfahren', 'Arbeitsprobe', true, 1),
  ('personal-m-auswahlverfahren', 'Assessment-Center-Übung', true, 2),
  ('personal-m-auswahlverfahren', 'Verbindliche Vorgabe der Konfession des Bewerbers', false, 3),
  -- personal-m-arbeitsvertrag-inhalte
  ('personal-m-arbeitsvertrag-inhalte', 'Beginn des Arbeitsverhältnisses', true, 0),
  ('personal-m-arbeitsvertrag-inhalte', 'Vereinbarte Arbeitszeit', true, 1),
  ('personal-m-arbeitsvertrag-inhalte', 'Höhe und Zusammensetzung des Arbeitsentgelts', true, 2),
  ('personal-m-arbeitsvertrag-inhalte', 'Private Kontoverbindung des Arbeitnehmers', false, 3),
  -- personal-m-befristung-teilzbefg
  ('personal-m-befristung-teilzbefg', 'Sachgrundlose Befristung ist bei einem neuen Arbeitgeber bis zu zwei Jahre zulässig', true, 0),
  ('personal-m-befristung-teilzbefg', 'Eine sachgrundlose Befristung darf innerhalb der zwei Jahre höchstens dreimal verlängert werden', true, 1),
  ('personal-m-befristung-teilzbefg', 'Sachgrundlose Befristung ist ausgeschlossen, wenn zuvor bereits ein Arbeitsverhältnis mit demselben Arbeitgeber bestand', true, 2),
  ('personal-m-befristung-teilzbefg', 'Eine Befristung mit Sachgrund darf gesetzlich nie länger als zwei Jahre dauern', false, 3),
  -- personal-m-kuendigungsarten
  ('personal-m-kuendigungsarten', 'Ordentliche Kündigung unter Einhaltung der Kündigungsfrist', true, 0),
  ('personal-m-kuendigungsarten', 'Außerordentliche fristlose Kündigung aus wichtigem Grund', true, 1),
  ('personal-m-kuendigungsarten', 'Änderungskündigung mit Angebot geänderter Arbeitsbedingungen', true, 2),
  ('personal-m-kuendigungsarten', 'Vorläufige Kündigung als eigenständige gesetzliche Kategorie', false, 3),
  -- personal-m-abmahnung
  ('personal-m-abmahnung', 'Sie rügt ein konkretes Fehlverhalten des Arbeitnehmers', true, 0),
  ('personal-m-abmahnung', 'Sie warnt für den Wiederholungsfall vor arbeitsrechtlichen Konsequenzen bis zur Kündigung', true, 1),
  ('personal-m-abmahnung', 'Sie ist vor einer verhaltensbedingten Kündigung in der Regel erforderlich', true, 2),
  ('personal-m-abmahnung', 'Sie ist bei jeder Kündigungsart ausnahmslos zwingend erforderlich', false, 3),
  -- personal-m-arbeitszeitgesetz-grundregeln
  ('personal-m-arbeitszeitgesetz-grundregeln', 'Die werktägliche Arbeitszeit darf grundsätzlich acht Stunden nicht überschreiten', true, 0),
  ('personal-m-arbeitszeitgesetz-grundregeln', 'Eine Verlängerung auf zehn Stunden ist bei entsprechendem Ausgleich zulässig', true, 1),
  ('personal-m-arbeitszeitgesetz-grundregeln', 'Nach Arbeitsende ist eine Ruhezeit von mindestens elf Stunden einzuhalten', true, 2),
  ('personal-m-arbeitszeitgesetz-grundregeln', 'Der Ausgleichszeitraum für die Zehn-Stunden-Grenze beträgt zwölf Monate', false, 3),
  -- personal-m-teilzeit-rechte
  ('personal-m-teilzeit-rechte', 'Der Anspruch setzt eine Mindestbeschäftigungsdauer voraus', true, 0),
  ('personal-m-teilzeit-rechte', 'Der Anspruch setzt eine bestimmte Mindestbetriebsgröße voraus', true, 1),
  ('personal-m-teilzeit-rechte', 'Der Arbeitgeber kann den Wunsch aus betrieblichen Gründen ablehnen', true, 2),
  ('personal-m-teilzeit-rechte', 'Teilzeitbeschäftigte dürfen ohne sachlichen Grund schlechter behandelt werden als Vollzeitbeschäftigte', false, 3),
  -- personal-m-ueberstunden-mehrarbeit
  ('personal-m-ueberstunden-mehrarbeit', 'Überstunden liegen vor, wenn die vereinbarte Arbeitszeit überschritten wird', true, 0),
  ('personal-m-ueberstunden-mehrarbeit', 'Ihre Anordnung setzt in der Regel eine vertragliche, tarifliche oder betriebliche Grundlage voraus', true, 1),
  ('personal-m-ueberstunden-mehrarbeit', 'Der Betriebsrat hat bei der Anordnung von Überstunden ein Mitbestimmungsrecht', true, 2),
  ('personal-m-ueberstunden-mehrarbeit', 'Für jede Überstunde ist gesetzlich ein Zuschlag von 25 Prozent vorgeschrieben', false, 3),
  -- personal-m-lohnbestandteile
  ('personal-m-lohnbestandteile', 'Grundlohn', true, 0),
  ('personal-m-lohnbestandteile', 'Vermögenswirksame Leistungen des Arbeitgebers', true, 1),
  ('personal-m-lohnbestandteile', 'Regelmäßig gezahltes Leistungsentgelt', true, 2),
  ('personal-m-lohnbestandteile', 'Die vom Arbeitgeber abgeführte Lohnsteuer', false, 3),
  -- personal-m-sozialversicherung-zweige
  ('personal-m-sozialversicherung-zweige', 'Krankenversicherung', true, 0),
  ('personal-m-sozialversicherung-zweige', 'Rentenversicherung', true, 1),
  ('personal-m-sozialversicherung-zweige', 'Unfallversicherung', true, 2),
  ('personal-m-sozialversicherung-zweige', 'Private Haftpflichtversicherung', false, 3),
  -- personal-m-beitragstragung
  ('personal-m-beitragstragung', 'Die Unfallversicherung trägt allein der Arbeitgeber', true, 0),
  ('personal-m-beitragstragung', 'Kranken-, Pflege-, Renten- und Arbeitslosenversicherung werden grundsätzlich hälftig getragen', true, 1),
  ('personal-m-beitragstragung', 'Der Arbeitgeber behält den Arbeitnehmeranteil ein und führt den Gesamtbeitrag ab', true, 2),
  ('personal-m-beitragstragung', 'Alle Sozialversicherungsbeiträge trägt allein der Arbeitnehmer', false, 3),
  -- personal-m-personalentwicklung-massnahmen
  ('personal-m-personalentwicklung-massnahmen', 'Innerbetriebliche Schulungen', true, 0),
  ('personal-m-personalentwicklung-massnahmen', 'Mitarbeitergespräch mit Zielvereinbarung', true, 1),
  ('personal-m-personalentwicklung-massnahmen', 'Förderung externer Weiterbildungen', true, 2),
  ('personal-m-personalentwicklung-massnahmen', 'Kürzung des gesetzlichen Urlaubsanspruchs', false, 3),
  -- personal-m-zielvereinbarung
  ('personal-m-zielvereinbarung', 'Das Ziel ist konkret formuliert', true, 0),
  ('personal-m-zielvereinbarung', 'Der Zielerreichungsgrad ist messbar', true, 1),
  ('personal-m-zielvereinbarung', 'Das Ziel ist innerhalb des vereinbarten Zeitraums realistisch erreichbar', true, 2),
  ('personal-m-zielvereinbarung', 'Das Ziel wird absichtlich unerreichbar hoch gesetzt', false, 3),
  -- personal-m-betriebsrat-wahl
  ('personal-m-betriebsrat-wahl', 'Wahlberechtigt sind Arbeitnehmer des Betriebs ab 16 Jahren', true, 0),
  ('personal-m-betriebsrat-wahl', 'Wählbar ist grundsätzlich, wer volljährig ist und eine Mindestbetriebszugehörigkeit hat', true, 1),
  ('personal-m-betriebsrat-wahl', 'Die Amtszeit des Betriebsrats beträgt regelmäßig vier Jahre', true, 2),
  ('personal-m-betriebsrat-wahl', 'Leitende Angestellte gehören zum wahlberechtigten Kreis des Betriebsrats', false, 3),
  -- personal-m-mitbestimmungsrechte
  ('personal-m-mitbestimmungsrechte', 'Beginn und Ende der täglichen Arbeitszeit', true, 0),
  ('personal-m-mitbestimmungsrechte', 'Aufstellung allgemeiner Urlaubsgrundsätze', true, 1),
  ('personal-m-mitbestimmungsrechte', 'Einführung technischer Kontrolleinrichtungen', true, 2),
  ('personal-m-mitbestimmungsrechte', 'Festlegung des Produktprogramms des Unternehmens', false, 3),
  -- personal-m-jav
  ('personal-m-jav', 'Sie vertritt Auszubildende und Arbeitnehmer unter 18 Jahren', true, 0),
  ('personal-m-jav', 'Sie kann Anträge an den Betriebsrat richten', true, 1),
  ('personal-m-jav', 'Sie hat im Betriebsrat ein Antrags- und Rederecht in eigenen Angelegenheiten', true, 2),
  ('personal-m-jav', 'Sie ersetzt den Betriebsrat und trifft eigenständige Mitbestimmungsentscheidungen', false, 3),
  -- personal-m-jugendarbeitsschutz
  ('personal-m-jugendarbeitsschutz', 'Die tägliche Arbeitszeit ist grundsätzlich auf acht Stunden begrenzt', true, 0),
  ('personal-m-jugendarbeitsschutz', 'Beschäftigung ist grundsätzlich nur am Tag zulässig', true, 1),
  ('personal-m-jugendarbeitsschutz', 'Die Arbeitszeit ist auf höchstens fünf Wochentage zu verteilen', true, 2),
  ('personal-m-jugendarbeitsschutz', 'Nachtarbeit ist ab dem 16. Geburtstag uneingeschränkt erlaubt', false, 3),
  -- personal-m-mutterschutz
  ('personal-m-mutterschutz', 'Es gilt eine Schutzfrist vor und nach der Entbindung mit in der Regel bestehendem Beschäftigungsverbot', true, 0),
  ('personal-m-mutterschutz', 'Während der Schutzfristen erhält die Arbeitnehmerin in aller Regel Mutterschaftsleistungen statt des laufenden Gehalts', true, 1),
  ('personal-m-mutterschutz', 'Eine Kündigung während Schwangerschaft und Schutzfrist ist nur in eng begrenzten Ausnahmefällen möglich', true, 2),
  ('personal-m-mutterschutz', 'Der Mutterschutz gilt ausschließlich für Arbeitnehmerinnen in Vollzeit', false, 3),
  -- personal-m-elternzeit
  ('personal-m-elternzeit', 'Elternzeit kann von beiden Elternteilen beansprucht werden', true, 0),
  ('personal-m-elternzeit', 'Sie ist grundsätzlich unbezahlt', true, 1),
  ('personal-m-elternzeit', 'Während der Elternzeit besteht besonderer Kündigungsschutz', true, 2),
  ('personal-m-elternzeit', 'Das Arbeitsverhältnis endet automatisch mit Antritt der Elternzeit', false, 3),
  -- personal-m-arbeitsschutz-allgemein
  ('personal-m-arbeitsschutz-allgemein', 'Der Arbeitgeber muss eine Gefährdungsbeurteilung der Arbeitsplätze durchführen', true, 0),
  ('personal-m-arbeitsschutz-allgemein', 'Beschäftigte sind über Gefahren an ihrem Arbeitsplatz zu unterweisen', true, 1),
  ('personal-m-arbeitsschutz-allgemein', 'Die Verantwortung für den Arbeitsschutz bleibt beim Arbeitgeber', true, 2),
  ('personal-m-arbeitsschutz-allgemein', 'Die Bestellung einer Sicherheitsfachkraft entbindet den Arbeitgeber vollständig von der Verantwortung', false, 3),
  -- personal-m-berufsausbildungsvertrag
  ('personal-m-berufsausbildungsvertrag', 'Beginn und Dauer der Berufsausbildung', true, 0),
  ('personal-m-berufsausbildungsvertrag', 'Sachliche und zeitliche Gliederung der Ausbildung', true, 1),
  ('personal-m-berufsausbildungsvertrag', 'Höhe der Ausbildungsvergütung', true, 2),
  ('personal-m-berufsausbildungsvertrag', 'Verpflichtung zu einer Mindestverweildauer im Betrieb nach der Ausbildung', false, 3),
  -- personal-m-pflichten-ausbildender-personal
  ('personal-m-pflichten-ausbildender-personal', 'Vermittlung der im Ausbildungsrahmenplan vorgesehenen Fertigkeiten und Kenntnisse', true, 0),
  ('personal-m-pflichten-ausbildender-personal', 'Kostenfreie Bereitstellung der nötigen Ausbildungsmittel', true, 1),
  ('personal-m-pflichten-ausbildender-personal', 'Freistellung für Berufsschule und Prüfungen', true, 2),
  ('personal-m-pflichten-ausbildender-personal', 'Übernahme privater Fahrtkosten zur Berufsschule', false, 3),
  -- personal-m-ihk-pruefung
  ('personal-m-ihk-pruefung', 'Zulassung setzt unter anderem die ordnungsgemäße Führung des Ausbildungsnachweises voraus', true, 0),
  ('personal-m-ihk-pruefung', 'Der Prüfungsausschuss ist paritätisch mit Arbeitgeber- und Arbeitnehmerseite sowie Lehrkraft besetzt', true, 1),
  ('personal-m-ihk-pruefung', 'Bei Nichtbestehen kann eine Verlängerung bis zur nächsten Wiederholungsprüfung verlangt werden, höchstens um ein Jahr', true, 2),
  ('personal-m-ihk-pruefung', 'Die Prüfung darf beliebig oft ohne zeitliche Begrenzung wiederholt werden', false, 3),
  -- personal-m-personalnebenkosten
  ('personal-m-personalnebenkosten', 'Arbeitgeberanteil zur gesetzlichen Sozialversicherung', true, 0),
  ('personal-m-personalnebenkosten', 'Aufwendungen für Fortbildung der Beschäftigten', true, 1),
  ('personal-m-personalnebenkosten', 'Freiwillige Sozialleistung wie ein Kantinenzuschuss', true, 2),
  ('personal-m-personalnebenkosten', 'Der laufende Bruttolohn selbst', false, 3),
  -- personal-m-direkte-indirekte-personalkosten
  ('personal-m-direkte-indirekte-personalkosten', 'Entgeltfortzahlung im Krankheitsfall', true, 0),
  ('personal-m-direkte-indirekte-personalkosten', 'Bezahlte Urlaubstage', true, 1),
  ('personal-m-direkte-indirekte-personalkosten', 'Kosten der betrieblichen Ausbildung', true, 2),
  ('personal-m-direkte-indirekte-personalkosten', 'Grundlohn für tatsächlich geleistete Arbeitsstunden', false, 3),
  -- personal-m-vwl-leistungen
  ('personal-m-vwl-leistungen', 'Vermögenswirksame Leistungen werden zweckgebunden angelegt, etwa in einen Sparvertrag', true, 0),
  ('personal-m-vwl-leistungen', 'Ein geldwerter Vorteil entsteht durch gewährte Sachleistungen wie einen privat nutzbaren Dienstwagen', true, 1),
  ('personal-m-vwl-leistungen', 'Ein geldwerter Vorteil ist grundsätzlich steuer- und beitragspflichtig wie Bargeldlohn', true, 2),
  ('personal-m-vwl-leistungen', 'Vermögenswirksame Leistungen werden stets bar an den Arbeitnehmer ausgezahlt', false, 3),
  -- personal-s-personalbedarf-arten
  ('personal-s-personalbedarf-arten', 'Reservebedarf', true, 0),
  ('personal-s-personalbedarf-arten', 'Nettopersonalbedarf', false, 1),
  ('personal-s-personalbedarf-arten', 'Ersatzbedarf', false, 2),
  ('personal-s-personalbedarf-arten', 'Neubedarf', false, 3),
  -- personal-s-stellenausschreibung-intern
  ('personal-s-stellenausschreibung-intern', 'Kürzere Einarbeitungszeit, da die betrieblichen Abläufe bereits bekannt sind', true, 0),
  ('personal-s-stellenausschreibung-intern', 'Größerer Bewerberpool durch bundesweite Reichweite', false, 1),
  ('personal-s-stellenausschreibung-intern', 'Automatische Umgehung des Allgemeinen Gleichbehandlungsgesetzes', false, 2),
  ('personal-s-stellenausschreibung-intern', 'Wegfall jeder Probezeit für den neuen Stelleninhaber', false, 3),
  -- personal-s-bewerbungsgespraech-zweck
  ('personal-s-bewerbungsgespraech-zweck', 'Prüfung der fachlichen Eignung und persönlichen Passung des Bewerbers', true, 0),
  ('personal-s-bewerbungsgespraech-zweck', 'Formale Prüfung der Vollständigkeit der eingereichten Unterlagen', false, 1),
  ('personal-s-bewerbungsgespraech-zweck', 'Verhandlung des Sozialversicherungsbeitrags', false, 2),
  ('personal-s-bewerbungsgespraech-zweck', 'Feststellung der Steuerklasse des Bewerbers', false, 3),
  -- personal-s-assessment-center
  ('personal-s-assessment-center', 'Mehrere Bewerber durchlaufen verschiedene Übungen und werden von mehreren Beobachtern beurteilt', true, 0),
  ('personal-s-assessment-center', 'Ein Bewerber wird ausschließlich schriftlich anhand eines Fragebogens getestet', false, 1),
  ('personal-s-assessment-center', 'Es handelt sich um ein rein automatisiertes Online-Auswahlverfahren ohne menschliche Beobachter', false, 2),
  ('personal-s-assessment-center', 'Es ersetzt gesetzlich das Vorstellungsgespräch', false, 3),
  -- personal-s-personalbeschaffung-zeitarbeit
  ('personal-s-personalbeschaffung-zeitarbeit', 'Der Zeitarbeitnehmer ist beim Verleiher angestellt und wird dem Entleihbetrieb zur Arbeitsleistung überlassen', true, 0),
  ('personal-s-personalbeschaffung-zeitarbeit', 'Der Zeitarbeitnehmer schließt für jeden Einsatz einen neuen Arbeitsvertrag mit dem Entleihbetrieb', false, 1),
  ('personal-s-personalbeschaffung-zeitarbeit', 'Der Entleihbetrieb übernimmt automatisch die Lohnabrechnung des Zeitarbeitnehmers', false, 2),
  ('personal-s-personalbeschaffung-zeitarbeit', 'Zeitarbeit ist in Deutschland gesetzlich vollständig verboten', false, 3),
  -- personal-s-probezeit-dauer
  ('personal-s-probezeit-dauer', 'Sechs Monate', true, 0),
  ('personal-s-probezeit-dauer', 'Drei Monate', false, 1),
  ('personal-s-probezeit-dauer', 'Zwölf Monate', false, 2),
  ('personal-s-probezeit-dauer', 'Ein Monat', false, 3),
  -- personal-s-kuendigungsfrist-grundfrist-personal
  ('personal-s-kuendigungsfrist-grundfrist-personal', 'Vier Wochen zum 15. oder zum Ende eines Kalendermonats', true, 0),
  ('personal-s-kuendigungsfrist-grundfrist-personal', 'Zwei Monate zum Ende eines Kalendermonats', false, 1),
  ('personal-s-kuendigungsfrist-grundfrist-personal', 'Zwei Wochen zu jedem beliebigen Tag', false, 2),
  ('personal-s-kuendigungsfrist-grundfrist-personal', 'Sechs Wochen zum Quartalsende', false, 3),
  -- personal-s-kuendigungsfrist-calc-1
  ('personal-s-kuendigungsfrist-calc-1', 'Zwei Monate zum Ende eines Kalendermonats', true, 0),
  ('personal-s-kuendigungsfrist-calc-1', 'Vier Wochen zum 15. oder zum Ende eines Kalendermonats', false, 1),
  ('personal-s-kuendigungsfrist-calc-1', 'Drei Monate zum Ende eines Kalendermonats', false, 2),
  ('personal-s-kuendigungsfrist-calc-1', 'Ein Monat zum Ende eines Kalendermonats', false, 3),
  -- personal-s-kuendigungsfrist-calc-2
  ('personal-s-kuendigungsfrist-calc-2', '15. April', true, 0),
  ('personal-s-kuendigungsfrist-calc-2', '7. April', false, 1),
  ('personal-s-kuendigungsfrist-calc-2', '31. März', false, 2),
  ('personal-s-kuendigungsfrist-calc-2', '30. April', false, 3),
  -- personal-s-aenderungskuendigung
  ('personal-s-aenderungskuendigung', 'Kündigung des bestehenden Vertrags verbunden mit dem Angebot geänderter Bedingungen', true, 0),
  ('personal-s-aenderungskuendigung', 'Kündigung ohne jede Möglichkeit einer Fortsetzung des Arbeitsverhältnisses', false, 1),
  ('personal-s-aenderungskuendigung', 'Eine bloße Ankündigung künftiger Gehaltserhöhungen', false, 2),
  ('personal-s-aenderungskuendigung', 'Eine Kündigung, die nur mündlich ausgesprochen werden darf', false, 3),
  -- personal-s-arbeitszeugnis-zwischenzeugnis
  ('personal-s-arbeitszeugnis-zwischenzeugnis', 'Während eines fortbestehenden Arbeitsverhältnisses bei berechtigtem Interesse, etwa Vorgesetztenwechsel', true, 0),
  ('personal-s-arbeitszeugnis-zwischenzeugnis', 'Ausschließlich nach vollständiger Beendigung des Arbeitsverhältnisses', false, 1),
  ('personal-s-arbeitszeugnis-zwischenzeugnis', 'Nur wenn der Arbeitgeber es von sich aus anbietet', false, 2),
  ('personal-s-arbeitszeugnis-zwischenzeugnis', 'Nur im ersten Monat der Probezeit', false, 3),
  -- personal-s-ruhepause-arbzg
  ('personal-s-ruhepause-arbzg', 'Mindestens 45 Minuten', true, 0),
  ('personal-s-ruhepause-arbzg', 'Mindestens 30 Minuten', false, 1),
  ('personal-s-ruhepause-arbzg', 'Mindestens 15 Minuten', false, 2),
  ('personal-s-ruhepause-arbzg', 'Mindestens 60 Minuten', false, 3),
  -- personal-s-hoechstarbeitszeit
  ('personal-s-hoechstarbeitszeit', 'Zehn Stunden werktäglich', true, 0),
  ('personal-s-hoechstarbeitszeit', 'Zwölf Stunden werktäglich', false, 1),
  ('personal-s-hoechstarbeitszeit', 'Neun Stunden werktäglich', false, 2),
  ('personal-s-hoechstarbeitszeit', 'Acht Stunden werktäglich ohne jede Ausnahme', false, 3),
  -- personal-s-gleitzeit-begriff
  ('personal-s-gleitzeit-begriff', 'Beschäftigte bestimmen Beginn und Ende der Arbeitszeit innerhalb eines vorgegebenen Rahmens selbst', true, 0),
  ('personal-s-gleitzeit-begriff', 'Die Arbeitszeit wird täglich vollständig vom Arbeitgeber ohne Rahmen vorgegeben', false, 1),
  ('personal-s-gleitzeit-begriff', 'Beschäftigte arbeiten ausschließlich im Homeoffice', false, 2),
  ('personal-s-gleitzeit-begriff', 'Es entfällt jede Pflicht zur Arbeitszeiterfassung', false, 3),
  -- personal-s-ueberstundenverguetung-calc
  ('personal-s-ueberstundenverguetung-calc', '180 Euro', true, 0),
  ('personal-s-ueberstundenverguetung-calc', '144 Euro', false, 1),
  ('personal-s-ueberstundenverguetung-calc', '162 Euro', false, 2),
  ('personal-s-ueberstundenverguetung-calc', '198 Euro', false, 3),
  -- personal-s-brutto-netto-begriffe
  ('personal-s-brutto-netto-begriffe', 'Der Betrag, der nach Abzug von Steuern und Sozialversicherungsbeiträgen ausgezahlt wird', true, 0),
  ('personal-s-brutto-netto-begriffe', 'Der volle vertraglich vereinbarte Lohn vor jedem Abzug', false, 1),
  ('personal-s-brutto-netto-begriffe', 'Der Betrag, den der Arbeitgeber als Personalnebenkosten aufwendet', false, 2),
  ('personal-s-brutto-netto-begriffe', 'Der Betrag der jährlichen Einkommensteuererstattung', false, 3),
  -- personal-s-lohnsteuerklassen
  ('personal-s-lohnsteuerklassen', 'Vor allem der Familienstand sowie die gewählte Steuerklassenkombination bei Verheirateten', true, 0),
  ('personal-s-lohnsteuerklassen', 'Ausschließlich die Höhe des Bruttoentgelts', false, 1),
  ('personal-s-lohnsteuerklassen', 'Die Betriebszugehörigkeit des Arbeitnehmers', false, 2),
  ('personal-s-lohnsteuerklassen', 'Die Anzahl der geleisteten Überstunden im Vorjahr', false, 3),
  -- personal-s-brutto-netto-calc
  ('personal-s-brutto-netto-calc', '1.736 Euro', true, 0),
  ('personal-s-brutto-netto-calc', '1.064 Euro', false, 1),
  ('personal-s-brutto-netto-calc', '1.820 Euro', false, 2),
  ('personal-s-brutto-netto-calc', '2.128 Euro', false, 3),
  -- personal-s-geldwerter-vorteil-begriff
  ('personal-s-geldwerter-vorteil-begriff', 'Eine Sachleistung des Arbeitgebers mit wirtschaftlichem Wert, etwa ein privat nutzbarer Dienstwagen', true, 0),
  ('personal-s-geldwerter-vorteil-begriff', 'Ein steuerfreier Bonus, der nicht verbeitragt wird', false, 1),
  ('personal-s-geldwerter-vorteil-begriff', 'Der Arbeitnehmeranteil zur Sozialversicherung', false, 2),
  ('personal-s-geldwerter-vorteil-begriff', 'Eine Rückerstattung zu viel gezahlter Lohnsteuer', false, 3),
  -- personal-s-vwl-begriff
  ('personal-s-vwl-begriff', 'Eine zweckgebundene Geldanlage, etwa in einen Bausparvertrag oder Fondssparplan', true, 0),
  ('personal-s-vwl-begriff', 'Eine freiwillige Einmalzahlung ohne Anlagezweck', false, 1),
  ('personal-s-vwl-begriff', 'Ein Zuschuss ausschließlich zu Fahrtkosten', false, 2),
  ('personal-s-vwl-begriff', 'Eine Sonderform der Überstundenvergütung', false, 3),
  -- personal-s-fuenf-saeulen
  ('personal-s-fuenf-saeulen', 'Pflegeversicherung', true, 0),
  ('personal-s-fuenf-saeulen', 'Hausratversicherung', false, 1),
  ('personal-s-fuenf-saeulen', 'Rechtsschutzversicherung', false, 2),
  ('personal-s-fuenf-saeulen', 'Kaskoversicherung', false, 3),
  -- personal-s-krankenversicherung-pflicht
  ('personal-s-krankenversicherung-pflicht', 'Mit dem tatsächlichen Antritt der Beschäftigung', true, 0),
  ('personal-s-krankenversicherung-pflicht', 'Erst mit Ablauf der Probezeit', false, 1),
  ('personal-s-krankenversicherung-pflicht', 'Erst mit der ersten Gehaltszahlung', false, 2),
  ('personal-s-krankenversicherung-pflicht', 'Erst nach Ablauf von sechs Monaten Beschäftigung', false, 3),
  -- personal-s-pflegeversicherung-zweck
  ('personal-s-pflegeversicherung-zweck', 'Sie sichert einen Teil der finanziellen Belastungen bei Pflegebedürftigkeit ab', true, 0),
  ('personal-s-pflegeversicherung-zweck', 'Sie deckt die vollen Kosten jeder Pflege ohne Eigenanteil', false, 1),
  ('personal-s-pflegeversicherung-zweck', 'Sie ersetzt die Krankenversicherung bei Langzeiterkrankungen', false, 2),
  ('personal-s-pflegeversicherung-zweck', 'Sie zahlt ausschließlich an pflegende Angehörige ein Gehalt', false, 3),
  -- personal-s-arbeitslosenversicherung-zweck
  ('personal-s-arbeitslosenversicherung-zweck', 'Zeitlich befristetes Arbeitslosengeld als Lohnersatz sowie Unterstützung bei der Wiedereingliederung', true, 0),
  ('personal-s-arbeitslosenversicherung-zweck', 'Lebenslange Zahlung in unveränderter Höhe des letzten Gehalts', false, 1),
  ('personal-s-arbeitslosenversicherung-zweck', 'Übernahme der Mietkosten während der gesamten Arbeitslosigkeit', false, 2),
  ('personal-s-arbeitslosenversicherung-zweck', 'Auszahlung einer einmaligen Abfindung an jeden Arbeitslosen', false, 3),
  -- personal-s-unfallversicherung-traeger
  ('personal-s-unfallversicherung-traeger', 'Allein der Arbeitgeber', true, 0),
  ('personal-s-unfallversicherung-traeger', 'Arbeitgeber und Arbeitnehmer jeweils zur Hälfte', false, 1),
  ('personal-s-unfallversicherung-traeger', 'Allein der Arbeitnehmer', false, 2),
  ('personal-s-unfallversicherung-traeger', 'Ausschließlich der Staat aus Steuermitteln', false, 3),
  -- personal-s-fortbildung-weiterbildung-unterschied
  ('personal-s-fortbildung-weiterbildung-unterschied', 'Fortbildung baut auf einer abgeschlossenen Berufsausbildung auf und führt oft zu einem höheren Abschluss', true, 0),
  ('personal-s-fortbildung-weiterbildung-unterschied', 'Beide Begriffe sind rechtlich vollständig identisch und austauschbar', false, 1),
  ('personal-s-fortbildung-weiterbildung-unterschied', 'Weiterbildung ist ausschließlich betrieblich, Fortbildung ausschließlich privat organisiert', false, 2),
  ('personal-s-fortbildung-weiterbildung-unterschied', 'Fortbildung findet nur außerhalb Deutschlands statt', false, 3),
  -- personal-s-personalbeurteilung-zweck
  ('personal-s-personalbeurteilung-zweck', 'Sie liefert eine strukturierte Grundlage für Entscheidungen zu Weiterbildung, Beförderung oder Entgelt', true, 0),
  ('personal-s-personalbeurteilung-zweck', 'Sie dient ausschließlich der Kontrolle der Arbeitszeiterfassung', false, 1),
  ('personal-s-personalbeurteilung-zweck', 'Sie ersetzt den Arbeitsvertrag', false, 2),
  ('personal-s-personalbeurteilung-zweck', 'Sie ist gesetzlich verboten', false, 3),
  -- personal-s-mitarbeitergespraech
  ('personal-s-mitarbeitergespraech', 'Vertrauliches Vier-Augen-Gespräch mit Rückblick und Zielvereinbarung', true, 0),
  ('personal-s-mitarbeitergespraech', 'Öffentliche Bewertung vor der gesamten Belegschaft', false, 1),
  ('personal-s-mitarbeitergespraech', 'Ein rein schriftlicher Fragebogen ohne persönliches Gespräch', false, 2),
  ('personal-s-mitarbeitergespraech', 'Ein ausschließlich disziplinarisches Gespräch nach Fehlverhalten', false, 3),
  -- personal-s-coaching-mentoring
  ('personal-s-coaching-mentoring', 'Mentoring begleitet über einen längeren Zeitraum individuell die persönliche Entwicklung', true, 0),
  ('personal-s-coaching-mentoring', 'Mentoring vermittelt ausschließlich standardisierte Fachinhalte in großen Gruppen', false, 1),
  ('personal-s-coaching-mentoring', 'Mentoring ist gesetzlich vorgeschrieben für jede Neueinstellung', false, 2),
  ('personal-s-coaching-mentoring', 'Mentoring findet ausschließlich online ohne persönlichen Kontakt statt', false, 3),
  -- personal-s-betriebsrat-groesse
  ('personal-s-betriebsrat-groesse', 'Von der Anzahl der regelmäßig beschäftigten wahlberechtigten Arbeitnehmer', true, 0),
  ('personal-s-betriebsrat-groesse', 'Von der Höhe des Unternehmensgewinns', false, 1),
  ('personal-s-betriebsrat-groesse', 'Vom Alter des ältesten Beschäftigten', false, 2),
  ('personal-s-betriebsrat-groesse', 'Von der Anzahl der Auszubildenden allein', false, 3),
  -- personal-s-betriebsversammlung
  ('personal-s-betriebsversammlung', 'Versammlung aller Arbeitnehmer, auf der der Betriebsrat über seine Tätigkeit berichtet', true, 0),
  ('personal-s-betriebsversammlung', 'Eine geschlossene Sitzung ausschließlich der Betriebsratsmitglieder', false, 1),
  ('personal-s-betriebsversammlung', 'Ein Treffen ausschließlich der Geschäftsführung', false, 2),
  ('personal-s-betriebsversammlung', 'Eine Versammlung, die stets in der Freizeit ohne Entgeltfortzahlung stattfindet', false, 3),
  -- personal-s-jav-voraussetzung
  ('personal-s-jav-voraussetzung', 'Mindestens fünf wahlberechtigte Jugendliche oder Auszubildende', true, 0),
  ('personal-s-jav-voraussetzung', 'Mindestens ein Jugendlicher im Betrieb', false, 1),
  ('personal-s-jav-voraussetzung', 'Mindestens zwanzig Jugendliche im Betrieb', false, 2),
  ('personal-s-jav-voraussetzung', 'Die JAV wird unabhängig von der Anzahl immer gebildet', false, 3),
  -- personal-s-mitwirkung-vs-mitbestimmung
  ('personal-s-mitwirkung-vs-mitbestimmung', 'Bei Mitbestimmung ist die Zustimmung des Betriebsrats erforderlich, bei Mitwirkung nicht', true, 0),
  ('personal-s-mitwirkung-vs-mitbestimmung', 'Beide Begriffe bedeuten dasselbe und sind austauschbar', false, 1),
  ('personal-s-mitwirkung-vs-mitbestimmung', 'Mitwirkung ist stärker als Mitbestimmung', false, 2),
  ('personal-s-mitwirkung-vs-mitbestimmung', 'Mitbestimmung betrifft nur die Wahl des Betriebsratsvorsitzenden', false, 3),
  -- personal-s-jugendarbeitsschutz-mindestalter
  ('personal-s-jugendarbeitsschutz-mindestalter', 'Ab 15 Jahren', true, 0),
  ('personal-s-jugendarbeitsschutz-mindestalter', 'Ab 12 Jahren', false, 1),
  ('personal-s-jugendarbeitsschutz-mindestalter', 'Ab 18 Jahren', false, 2),
  ('personal-s-jugendarbeitsschutz-mindestalter', 'Ab 16 Jahren ohne jede Ausnahme darunter', false, 3),
  -- personal-s-mutterschutzfrist
  ('personal-s-mutterschutzfrist', 'Acht Wochen, bei Frühgeburt, Mehrlingsgeburt oder Behinderung des Kindes zwölf Wochen', true, 0),
  ('personal-s-mutterschutzfrist', 'Vier Wochen ohne Ausnahmen', false, 1),
  ('personal-s-mutterschutzfrist', 'Sechs Monate in jedem Fall', false, 2),
  ('personal-s-mutterschutzfrist', 'Zwei Wochen', false, 3),
  -- personal-s-elternzeit-dauer
  ('personal-s-elternzeit-dauer', 'Bis zur Vollendung des dritten Lebensjahres des Kindes', true, 0),
  ('personal-s-elternzeit-dauer', 'Bis zur Vollendung des ersten Lebensjahres des Kindes', false, 1),
  ('personal-s-elternzeit-dauer', 'Bis zur Einschulung ohne feste Altersgrenze', false, 2),
  ('personal-s-elternzeit-dauer', 'Bis zur Volljährigkeit des Kindes', false, 3),
  -- personal-s-gefaehrdungsbeurteilung
  ('personal-s-gefaehrdungsbeurteilung', 'Den Arbeitgeber', true, 0),
  ('personal-s-gefaehrdungsbeurteilung', 'Ausschließlich die Berufsgenossenschaft', false, 1),
  ('personal-s-gefaehrdungsbeurteilung', 'Ausschließlich den einzelnen Beschäftigten selbst', false, 2),
  ('personal-s-gefaehrdungsbeurteilung', 'Ausschließlich den Betriebsrat', false, 3),
  -- personal-s-probezeit-ausbildung
  ('personal-s-probezeit-ausbildung', 'Mindestens einen Monat, höchstens vier Monate', true, 0),
  ('personal-s-probezeit-ausbildung', 'Mindestens sechs Monate', false, 1),
  ('personal-s-probezeit-ausbildung', 'Genau zwei Wochen', false, 2),
  ('personal-s-probezeit-ausbildung', 'Es ist keine Probezeit vorgeschrieben', false, 3),
  -- personal-s-ausbildungsvertrag-inhalt
  ('personal-s-ausbildungsvertrag-inhalt', 'Die Dauer der Berufsausbildung', true, 0),
  ('personal-s-ausbildungsvertrag-inhalt', 'Eine Übernahmezusage nach Ausbildungsende', false, 1),
  ('personal-s-ausbildungsvertrag-inhalt', 'Die private Wohnanschrift der Eltern', false, 2),
  ('personal-s-ausbildungsvertrag-inhalt', 'Eine Vertragsstrafe bei vorzeitigem Ausbildungsabbruch', false, 3),
  -- personal-s-zwischenpruefung-zweck
  ('personal-s-zwischenpruefung-zweck', 'Feststellung des bisherigen Ausbildungsstands und Rückmeldung zum Lernfortschritt', true, 0),
  ('personal-s-zwischenpruefung-zweck', 'Ersatz der gesamten Abschlussprüfung', false, 1),
  ('personal-s-zwischenpruefung-zweck', 'Verlängerung der Ausbildungszeit um ein Jahr', false, 2),
  ('personal-s-zwischenpruefung-zweck', 'Sofortige Beendigung des Ausbildungsverhältnisses bei schlechtem Ergebnis', false, 3),
  -- personal-s-kuendigung-ausbildungsverhaeltnis
  ('personal-s-kuendigung-ausbildungsverhaeltnis', 'Kündigung mit vier Wochen Frist bei Aufgabe oder Wechsel der Berufsausbildung', true, 0),
  ('personal-s-kuendigung-ausbildungsverhaeltnis', 'Kündigung ist nach der Probezeit generell ausgeschlossen', false, 1),
  ('personal-s-kuendigung-ausbildungsverhaeltnis', 'Kündigung ist nur mit Zustimmung der IHK möglich', false, 2),
  ('personal-s-kuendigung-ausbildungsverhaeltnis', 'Kündigung ist jederzeit fristlos ohne wichtigen Grund möglich', false, 3),
  -- personal-s-personalnebenkosten-beispiele
  ('personal-s-personalnebenkosten-beispiele', 'Arbeitgeberanteil zur gesetzlichen Sozialversicherung', true, 0),
  ('personal-s-personalnebenkosten-beispiele', 'Der vereinbarte Bruttogrundlohn', false, 1),
  ('personal-s-personalnebenkosten-beispiele', 'Der an den Arbeitnehmer ausgezahlte Nettolohn', false, 2),
  ('personal-s-personalnebenkosten-beispiele', 'Die vom Kunden gezahlte Umsatzsteuer', false, 3),
  -- personal-s-urlaubsanspruch-austritt-calc
  ('personal-s-urlaubsanspruch-austritt-calc', '14 Urlaubstage', true, 0),
  ('personal-s-urlaubsanspruch-austritt-calc', '28 Urlaubstage', false, 1),
  ('personal-s-urlaubsanspruch-austritt-calc', '12 Urlaubstage', false, 2),
  ('personal-s-urlaubsanspruch-austritt-calc', '16 Urlaubstage', false, 3),
  -- personal-s-urlaubsanspruch-eintritt-calc
  ('personal-s-urlaubsanspruch-eintritt-calc', '10 Urlaubstage', true, 0),
  ('personal-s-urlaubsanspruch-eintritt-calc', '30 Urlaubstage', false, 1),
  ('personal-s-urlaubsanspruch-eintritt-calc', '7,5 Urlaubstage', false, 2),
  ('personal-s-urlaubsanspruch-eintritt-calc', '12 Urlaubstage', false, 3),
  -- personal-s-teilurlaubstage-rundung
  ('personal-s-teilurlaubstage-rundung', 'Aufrundung auf 15 volle Urlaubstage', true, 0),
  ('personal-s-teilurlaubstage-rundung', 'Abrundung auf 14 volle Urlaubstage', false, 1),
  ('personal-s-teilurlaubstage-rundung', 'Der Bruchteil verfällt ersatzlos', false, 2),
  ('personal-s-teilurlaubstage-rundung', 'Der Bruchteil wird stets in Geld statt in Urlaubstagen ausgezahlt', false, 3)
) as v(source_key, text, is_correct, sort_order)
on v.source_key = q.source_key;
