-- Erweiterung des Themengebiets Programmierung für die Prüfung fiae-ae:
-- 38 neue, selbst formulierte Fragen (23 single, 15 multiple).
-- Keine Übernahme aus realen IHK- oder AKA-Aufgaben, alle Fragen wurden aus
-- dem Fachstoff heraus neu geschrieben. Die vorhandenen 37 Programmierfragen
-- wurden vorher ausgewertet, sowohl auf source_key als auch inhaltlich, damit
-- diese Charge echte Lücken füllt: Sortierverfahren, Bäume, Hashing,
-- Entwurfsmuster, SOLID, UML, Git-Workflow, Scrum-Rollen, Sicherheit im Code,
-- Zahlendarstellung und Kontrollfluss.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'fiae-ae'
join (values
  -- Mehrfachauswahl
  ('Programmierung', 'prog-multi-solid-prinzipien',
   'Welche der folgenden Prinzipien gehören zu den SOLID-Prinzipien des objektorientierten Entwurfs?',
   'SOLID ist ein Akronym aus fünf Entwurfsprinzipien, darunter Single Responsibility, Open Closed und Liskov Substitution. KISS und FIFO stammen aus anderen Zusammenhängen und sind kein Bestandteil von SOLID.',
   3, 'multiple'),
  ('Programmierung', 'prog-multi-scrum-rollen',
   'Welche Verantwortlichkeiten sieht das Scrum-Rahmenwerk vor?',
   'Scrum kennt genau drei Verantwortlichkeiten: Product Owner, Scrum Master und die Entwickler. Klassische Rollen wie Projektleiter werden bewusst nicht übernommen, weil die Steuerung im Team und beim Product Owner liegt.',
   2, 'multiple'),
  ('Programmierung', 'prog-multi-git-lokale-befehle',
   'Welche Git-Befehle wirken sich in der Standardkonfiguration ausschließlich auf das lokale Repository aus?',
   'commit, branch und merge arbeiten nur im lokalen Repository. Erst push und fetch tauschen Daten mit dem entfernten Repository aus. Wer das verwechselt, wundert sich, warum Kollegen einen Commit nicht sehen.',
   3, 'multiple'),
  ('Programmierung', 'prog-multi-uml-verhaltensdiagramme',
   'Welche der folgenden UML-Diagrammarten zählen zu den Verhaltensdiagrammen?',
   'Die UML unterteilt sich in Struktur- und Verhaltensdiagramme. Sequenz-, Aktivitäts- und Zustandsdiagramm beschreiben Abläufe über die Zeit, während Klassen- und Komponentendiagramm den statischen Aufbau zeigen.',
   3, 'multiple'),
  ('Programmierung', 'prog-multi-sql-injection-schutz',
   'Welche Maßnahmen schützen eine Anwendung wirksam vor SQL-Injection?',
   'SQL-Injection entsteht, wenn Benutzereingaben als Teil des SQL-Befehls interpretiert werden. Parameterbindung trennt Befehl und Daten sauber, Validierung filtert unpassende Eingaben ab, und ein Datenbankkonto mit wenigen Rechten begrenzt den Schaden. Transportverschlüsselung ändert an der Lücke nichts.',
   3, 'multiple'),
  ('Programmierung', 'prog-multi-sortierverfahren-nlogn',
   'Welche Sortierverfahren erreichen im durchschnittlichen Fall eine Laufzeit von O(n log n)?',
   'Mergesort, Heapsort und Quicksort teilen die Daten auf und benötigen im Mittel n log n Vergleiche. Quicksort kann im ungünstigsten Fall auf O(n²) fallen, gilt im Durchschnitt aber als n log n. Bubblesort und Insertionsort liegen im Mittel bei O(n²).',
   3, 'multiple'),
  ('Programmierung', 'prog-multi-abstrakte-klasse',
   'Welche Aussagen über abstrakte Klassen in Java sind zutreffend?',
   'Eine abstrakte Klasse steht zwischen Interface und konkreter Klasse: Sie kann Zustand und fertige Methoden mitbringen, lässt sich aber nicht selbst instanziieren. Java erlaubt nur einfache Klassenvererbung, mehrere Basisklassen gleichzeitig sind nicht möglich.',
   3, 'multiple'),
  ('Programmierung', 'prog-multi-clean-code-prinzipien',
   'Welche der folgenden Abkürzungen bezeichnen Prinzipien der Codequalität?',
   'DRY warnt vor doppelter Logik, KISS vor unnötiger Komplexität, YAGNI vor Funktionen auf Vorrat. MVC ist ein Architekturmuster und ACID beschreibt Eigenschaften von Datenbanktransaktionen, beides sind keine Codequalitätsprinzipien.',
   2, 'multiple'),
  ('Programmierung', 'prog-multi-http-statuscodes-client',
   'Welche HTTP-Statuscodes signalisieren einen Fehler auf Seiten des Clients?',
   'Die Klasse 4xx steht für Fehler, die der Client verursacht hat, etwa eine fehlerhafte Anfrage, fehlende Berechtigung oder eine nicht vorhandene Ressource. 5xx meldet ein Problem des Servers, 3xx eine Weiterleitung.',
   2, 'multiple'),
  ('Programmierung', 'prog-multi-set-eigenschaften',
   'Welche Aussagen über die Datenstruktur Set (Menge) treffen zu?',
   'Ein Set modelliert eine mathematische Menge: Jedes Element kommt höchstens einmal vor. Hash-basierte Implementierungen finden Elemente im Mittel in konstanter Zeit, geben dafür aber jede Ordnungsgarantie auf. Einen Indexzugriff wie bei einer Liste gibt es nicht.',
   3, 'multiple'),
  ('Programmierung', 'prog-multi-tdd-zyklus',
   'Welche Schritte gehören zum Zyklus der testgetriebenen Entwicklung (TDD)?',
   'TDD folgt dem Ablauf Red, Green, Refactor: erst ein fehlschlagender Test, dann die kleinste Implementierung, die ihn erfüllt, danach die Verbesserung der Struktur bei laufenden Tests. Tests im Nachhinein zu ergänzen ist gerade das Gegenteil davon.',
   2, 'multiple'),
  ('Programmierung', 'prog-multi-rekursion-bestandteile',
   'Was muss eine korrekt arbeitende rekursive Funktion enthalten?',
   'Rekursion braucht einen Selbstaufruf, eine Abbruchbedingung und eine Veränderung der Argumente, die diese Bedingung tatsächlich erreichbar macht. Fehlt die dritte Zutat, greift die Abbruchbedingung nie und der Aufrufstapel läuft über.',
   2, 'multiple'),
  ('Programmierung', 'prog-multi-user-story',
   'Was kennzeichnet eine gut formulierte User Story?',
   'Eine User Story beschreibt einen fachlichen Wunsch aus Sicht einer Rolle samt Nutzen und wird über Akzeptanzkriterien prüfbar gemacht. Die technische Lösung bleibt offen, damit das Team den besten Weg selbst wählen kann.',
   2, 'multiple'),
  ('Programmierung', 'prog-multi-code-smells',
   'Welche der folgenden Merkmale gelten als Code Smell und sind ein Hinweis auf Refactoring-Bedarf?',
   'Code Smells sind Auffälligkeiten, die auf strukturelle Schwächen hindeuten. Überlange Methoden, kopierter Code und lange Parameterlisten erschweren Verständnis und Wartung. Sprechende Namen und Tests sind dagegen Zeichen guter Qualität.',
   2, 'multiple'),
  ('Programmierung', 'prog-multi-passwort-speicherung',
   'Welche Aussagen zur sicheren Speicherung von Benutzerpasswörtern treffen zu?',
   'Passwörter werden nicht verschlüsselt, sondern gehasht, damit sie auch nach einem Datenbankdiebstahl nicht rekonstruierbar sind. Ein individueller Salt verhindert vorberechnete Tabellen, und bewusst langsame Verfahren wie bcrypt oder Argon2 machen massenhaftes Durchprobieren teuer. MD5 ist dafür viel zu schnell.',
   3, 'multiple'),
  -- Einfachauswahl
  ('Programmierung', 'prog-single-hashmap-zugriff',
   'Welche Zeitkomplexität hat der Zugriff auf einen Wert in einer Hash-Map im durchschnittlichen Fall?',
   'Die Hashfunktion berechnet aus dem Schlüssel direkt die Position im Speicher, unabhängig von der Anzahl der Einträge. Erst wenn viele Schlüssel auf dieselbe Position fallen, verschlechtert sich das Verhalten.',
   2, 'single'),
  ('Programmierung', 'prog-single-binaerbaum-inorder',
   'In welcher Reihenfolge liefert eine In-Order-Traversierung die Werte eines binären Suchbaums?',
   'In-Order besucht erst den linken Teilbaum, dann den Knoten, dann den rechten. Da im Suchbaum links immer kleinere und rechts immer größere Werte stehen, ergibt sich daraus die aufsteigende Sortierung.',
   3, 'single'),
  ('Programmierung', 'prog-single-komposition-statt-vererbung',
   'Warum empfiehlt die Regel "Komposition vor Vererbung" den Aufbau aus Teilobjekten?',
   'Vererbung bindet eine Unterklasse fest an die Innereien ihrer Oberklasse, jede Änderung dort schlägt durch. Komposition koppelt nur über eine Schnittstelle, dadurch lässt sich das genutzte Verhalten sogar zur Laufzeit austauschen.',
   3, 'single'),
  ('Programmierung', 'prog-single-liskov',
   'Was fordert das Liskovsche Substitutionsprinzip?',
   'Objekte einer Unterklasse müssen überall dort einsetzbar sein, wo die Oberklasse erwartet wird, ohne dass das Programm sich falsch verhält. Eine Unterklasse darf Zusicherungen der Oberklasse also nicht verschärfen oder brechen.',
   4, 'single'),
  ('Programmierung', 'prog-single-observer-pattern',
   'Welches Problem löst das Entwurfsmuster Observer?',
   'Der Observer entkoppelt Sender und Empfänger: Interessierte Objekte melden sich bei einer Quelle an und werden bei Zustandsänderungen benachrichtigt. Die Quelle muss ihre Beobachter dafür nicht konkret kennen.',
   3, 'single'),
  ('Programmierung', 'prog-single-factory-pattern',
   'Wozu dient das Entwurfsmuster Factory Method?',
   'Die Erzeugung von Objekten wandert in eine eigene Methode, die von Unterklassen überschrieben werden kann. Der aufrufende Code arbeitet nur noch mit dem gemeinsamen Typ und muss die konkrete Klasse nicht kennen.',
   3, 'single'),
  ('Programmierung', 'prog-single-refactoring-definition',
   'Was versteht man unter Refactoring?',
   'Refactoring verbessert die innere Struktur des Codes, ohne das nach außen sichtbare Verhalten zu ändern. Genau deshalb sind automatisierte Tests die Voraussetzung dafür, sie belegen, dass sich das Verhalten wirklich nicht verschoben hat.',
   2, 'single'),
  ('Programmierung', 'prog-single-git-merge-konflikt',
   'Wann entsteht beim Zusammenführen zweier Git-Branches ein Merge-Konflikt?',
   'Git führt Änderungen automatisch zusammen, solange sie unterschiedliche Stellen betreffen. Erst wenn beide Zweige dieselben Zeilen einer Datei unterschiedlich geändert haben, kann das Werkzeug nicht entscheiden und übergibt an den Entwickler.',
   2, 'single'),
  ('Programmierung', 'prog-single-git-revert',
   'Worin unterscheidet sich "git revert" von "git reset --hard" auf einem bereits geteilten Branch?',
   'revert erzeugt einen neuen Commit, der die Änderungen rückgängig macht, die Historie bleibt vollständig erhalten. reset --hard verschiebt den Branchzeiger und verwirft Commits, was bei bereits gepushten Ständen die Historie der Kollegen zerstört.',
   4, 'single'),
  ('Programmierung', 'prog-single-scrum-product-owner',
   'Wofür ist der Product Owner in Scrum verantwortlich?',
   'Der Product Owner verantwortet den Wert des Produkts. Er pflegt und priorisiert das Product Backlog und entscheidet, was in welcher Reihenfolge umgesetzt wird. Wie es umgesetzt wird, bestimmen die Entwickler selbst.',
   2, 'single'),
  ('Programmierung', 'prog-single-wasserfall-nachteil',
   'Was ist der zentrale Nachteil des Wasserfallmodells bei sich ändernden Anforderungen?',
   'Im Wasserfallmodell werden die Anforderungen zu Beginn vollständig festgeschrieben und die Phasen streng nacheinander durchlaufen. Spätere Änderungen erfordern einen Rücksprung über mehrere Phasen und sind entsprechend teuer.',
   2, 'single'),
  ('Programmierung', 'prog-single-uml-vererbung-notation',
   'Wie wird eine Vererbungsbeziehung in einem UML-Klassendiagramm dargestellt?',
   'Die Generalisierung zeigt als durchgezogene Linie mit einer geschlossenen, nicht ausgefüllten Dreiecksspitze immer auf die Oberklasse. Gestrichelte Linien stehen dagegen für Abhängigkeit oder die Realisierung eines Interface.',
   3, 'single'),
  ('Programmierung', 'prog-single-rest-put-post',
   'Worin unterscheiden sich PUT und POST bei einer REST-Schnittstelle?',
   'PUT legt eine Ressource unter einer vom Client bestimmten URI an oder ersetzt sie vollständig, wiederholte Aufrufe führen zum gleichen Ergebnis. POST übergibt Daten an eine Sammlung, die daraus eine neue Ressource erzeugt, mehrfaches Senden legt mehrere an.',
   3, 'single'),
  ('Programmierung', 'prog-single-xss',
   'Was passiert bei einem Cross-Site-Scripting-Angriff (XSS)?',
   'Der Angreifer schleust Skriptcode über ein Eingabefeld ein, den die Anwendung ungeprüft in eine Seite schreibt. Der Browser eines anderen Nutzers führt diesen Code dann im Kontext der vertrauten Seite aus, etwa um Sitzungsdaten abzugreifen.',
   3, 'single'),
  ('Programmierung', 'prog-single-integer-overflow',
   'Was geschieht in Java, wenn zum größten darstellbaren int-Wert 1 addiert wird?',
   'Der Wertebereich eines vorzeichenbehafteten 32-Bit-Integer ist begrenzt. Beim Überschreiten kippt das Ergebnis auf den kleinstmöglichen negativen Wert um, ohne dass eine Ausnahme geworfen wird. Genau das macht Überläufe so schwer zu finden.',
   3, 'single'),
  ('Programmierung', 'prog-single-float-vergleich',
   'Warum sollten zwei Gleitkommazahlen nicht direkt mit dem Operator == verglichen werden?',
   'Viele Dezimalbrüche lassen sich binär nicht exakt darstellen, deshalb entstehen bei Rechenoperationen winzige Rundungsfehler. Sinnvoll ist der Vergleich der Differenz gegen eine kleine Toleranzschwelle.',
   3, 'single'),
  ('Programmierung', 'prog-single-shortcircuit',
   'Was bewirkt die Kurzschlussauswertung beim logischen Operator && ?',
   'Ist der linke Operand bereits false, steht das Gesamtergebnis fest und der rechte Operand wird gar nicht mehr ausgewertet. Deshalb lässt sich damit eine Null-Prüfung elegant vor einen Zugriff schalten.',
   2, 'single'),
  ('Programmierung', 'prog-single-do-while',
   'Worin unterscheidet sich eine do-while-Schleife von einer while-Schleife?',
   'Die do-while-Schleife prüft ihre Bedingung erst am Ende des Durchlaufs, ihr Rumpf wird deshalb mindestens einmal ausgeführt. Die while-Schleife prüft vorher und kann komplett übersprungen werden.',
   1, 'single'),
  ('Programmierung', 'prog-single-struktogramm',
   'Wozu dient ein Struktogramm nach Nassi-Shneiderman?',
   'Das Struktogramm bildet den Ablauf eines Algorithmus aus verschachtelten Rechtecken für Sequenz, Verzweigung und Wiederholung ab. Es ist bewusst sprachunabhängig und zwingt zu strukturierter Programmierung ohne Sprünge.',
   1, 'single'),
  ('Programmierung', 'prog-single-mock-objekt',
   'Wozu wird beim Testen ein Mock-Objekt eingesetzt?',
   'Ein Mock ersetzt eine echte Abhängigkeit wie Datenbank oder Fremdsystem durch ein steuerbares Ersatzobjekt. Der Test wird dadurch schnell, wiederholbar und prüft wirklich nur die eigene Einheit.',
   2, 'single'),
  ('Programmierung', 'prog-single-linear-search',
   'Welche Zeitkomplexität hat die lineare Suche in einem unsortierten Array im schlechtesten Fall?',
   'Ohne Sortierung gibt es keine Möglichkeit, Bereiche auszuschließen. Im ungünstigsten Fall steht das gesuchte Element ganz hinten oder fehlt, sodass alle n Elemente geprüft werden müssen.',
   1, 'single'),
  ('Programmierung', 'prog-single-konstruktor',
   'Welche Aufgabe hat ein Konstruktor in einer Klasse?',
   'Der Konstruktor wird beim Erzeugen eines Objekts automatisch aufgerufen und bringt es in einen gültigen Anfangszustand, indem er die Attribute initialisiert. Einen Rückgabetyp besitzt er nicht.',
   1, 'single'),
  ('Programmierung', 'prog-single-checked-exception',
   'Was kennzeichnet eine Checked Exception in Java?',
   'Der Compiler verlangt, dass eine Checked Exception entweder gefangen oder in der Methodensignatur mit throws deklariert wird. Sie steht für vorhersehbare Störungen von außen, etwa eine fehlende Datei.',
   3, 'single')
) as v(topic_name, source_key, q, expl, difficulty, question_type)
on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- prog-multi-solid-prinzipien
  ('prog-multi-solid-prinzipien', 'Single Responsibility Principle', true, 0),
  ('prog-multi-solid-prinzipien', 'Open Closed Principle', true, 1),
  ('prog-multi-solid-prinzipien', 'Liskov Substitution Principle', true, 2),
  ('prog-multi-solid-prinzipien', 'Keep It Simple, Stupid', false, 3),
  ('prog-multi-solid-prinzipien', 'First In, First Out', false, 4),
  -- prog-multi-scrum-rollen
  ('prog-multi-scrum-rollen', 'Product Owner', true, 0),
  ('prog-multi-scrum-rollen', 'Scrum Master', true, 1),
  ('prog-multi-scrum-rollen', 'Entwickler im Scrum Team', true, 2),
  ('prog-multi-scrum-rollen', 'Projektleiter', false, 3),
  ('prog-multi-scrum-rollen', 'Qualitätsbeauftragter', false, 4),
  -- prog-multi-git-lokale-befehle
  ('prog-multi-git-lokale-befehle', 'git commit', true, 0),
  ('prog-multi-git-lokale-befehle', 'git branch', true, 1),
  ('prog-multi-git-lokale-befehle', 'git merge', true, 2),
  ('prog-multi-git-lokale-befehle', 'git push', false, 3),
  ('prog-multi-git-lokale-befehle', 'git fetch', false, 4),
  -- prog-multi-uml-verhaltensdiagramme
  ('prog-multi-uml-verhaltensdiagramme', 'Sequenzdiagramm', true, 0),
  ('prog-multi-uml-verhaltensdiagramme', 'Aktivitätsdiagramm', true, 1),
  ('prog-multi-uml-verhaltensdiagramme', 'Zustandsdiagramm', true, 2),
  ('prog-multi-uml-verhaltensdiagramme', 'Klassendiagramm', false, 3),
  ('prog-multi-uml-verhaltensdiagramme', 'Komponentendiagramm', false, 4),
  -- prog-multi-sql-injection-schutz
  ('prog-multi-sql-injection-schutz', 'Prepared Statements mit Parameterbindung verwenden', true, 0),
  ('prog-multi-sql-injection-schutz', 'Eingaben serverseitig auf Typ und Wertebereich prüfen', true, 1),
  ('prog-multi-sql-injection-schutz', 'Für die Anwendung ein Datenbankkonto mit minimalen Rechten nutzen', true, 2),
  ('prog-multi-sql-injection-schutz', 'Die Verbindung zwischen Browser und Server per HTTPS verschlüsseln', false, 3),
  ('prog-multi-sql-injection-schutz', 'Längere Passwörter für die Benutzerkonten erzwingen', false, 4),
  -- prog-multi-sortierverfahren-nlogn
  ('prog-multi-sortierverfahren-nlogn', 'Mergesort', true, 0),
  ('prog-multi-sortierverfahren-nlogn', 'Heapsort', true, 1),
  ('prog-multi-sortierverfahren-nlogn', 'Quicksort', true, 2),
  ('prog-multi-sortierverfahren-nlogn', 'Bubblesort', false, 3),
  ('prog-multi-sortierverfahren-nlogn', 'Insertionsort', false, 4),
  -- prog-multi-abstrakte-klasse
  ('prog-multi-abstrakte-klasse', 'Sie kann nicht direkt instanziiert werden', true, 0),
  ('prog-multi-abstrakte-klasse', 'Sie kann bereits fertig implementierte Methoden enthalten', true, 1),
  ('prog-multi-abstrakte-klasse', 'Sie kann Attribute mit Zustand definieren', true, 2),
  ('prog-multi-abstrakte-klasse', 'Sie darf ausschließlich abstrakte Methoden enthalten', false, 3),
  ('prog-multi-abstrakte-klasse', 'Eine Klasse kann gleichzeitig von mehreren abstrakten Klassen erben', false, 4),
  -- prog-multi-clean-code-prinzipien
  ('prog-multi-clean-code-prinzipien', 'DRY', true, 0),
  ('prog-multi-clean-code-prinzipien', 'KISS', true, 1),
  ('prog-multi-clean-code-prinzipien', 'YAGNI', true, 2),
  ('prog-multi-clean-code-prinzipien', 'MVC', false, 3),
  ('prog-multi-clean-code-prinzipien', 'ACID', false, 4),
  -- prog-multi-http-statuscodes-client
  ('prog-multi-http-statuscodes-client', '400 Bad Request', true, 0),
  ('prog-multi-http-statuscodes-client', '403 Forbidden', true, 1),
  ('prog-multi-http-statuscodes-client', '404 Not Found', true, 2),
  ('prog-multi-http-statuscodes-client', '500 Internal Server Error', false, 3),
  ('prog-multi-http-statuscodes-client', '301 Moved Permanently', false, 4),
  -- prog-multi-set-eigenschaften
  ('prog-multi-set-eigenschaften', 'Jedes Element ist höchstens einmal enthalten', true, 0),
  ('prog-multi-set-eigenschaften', 'Bei einer Hash-basierten Umsetzung ist die Prüfung auf Enthaltensein im Mittel sehr schnell', true, 1),
  ('prog-multi-set-eigenschaften', 'Ein HashSet garantiert keine bestimmte Reihenfolge der Elemente', true, 2),
  ('prog-multi-set-eigenschaften', 'Einzelne Elemente lassen sich über einen numerischen Index ansprechen', false, 3),
  ('prog-multi-set-eigenschaften', 'Ein Set speichert grundsätzlich Schlüssel-Wert-Paare', false, 4),
  -- prog-multi-tdd-zyklus
  ('prog-multi-tdd-zyklus', 'Zuerst einen Test schreiben, der zwangsläufig fehlschlägt', true, 0),
  ('prog-multi-tdd-zyklus', 'Nur so viel Produktivcode schreiben, dass der Test durchläuft', true, 1),
  ('prog-multi-tdd-zyklus', 'Den Code anschließend bei laufenden Tests refaktorieren', true, 2),
  ('prog-multi-tdd-zyklus', 'Die Tests erst nach Fertigstellung aller Funktionen ergänzen', false, 3),
  ('prog-multi-tdd-zyklus', 'Vor dem ersten Test eine Testabdeckung von 100 Prozent festlegen', false, 4),
  -- prog-multi-rekursion-bestandteile
  ('prog-multi-rekursion-bestandteile', 'Einen Aufruf der Funktion aus sich selbst heraus', true, 0),
  ('prog-multi-rekursion-bestandteile', 'Mindestens eine Abbruchbedingung', true, 1),
  ('prog-multi-rekursion-bestandteile', 'Eine Veränderung der Argumente in Richtung der Abbruchbedingung', true, 2),
  ('prog-multi-rekursion-bestandteile', 'Eine Schleife im Funktionsrumpf', false, 3),
  ('prog-multi-rekursion-bestandteile', 'Eine statische Zählvariable außerhalb der Funktion', false, 4),
  -- prog-multi-user-story
  ('prog-multi-user-story', 'Sie beschreibt den Wunsch aus Sicht einer Rolle', true, 0),
  ('prog-multi-user-story', 'Sie benennt den fachlichen Nutzen', true, 1),
  ('prog-multi-user-story', 'Sie wird durch Akzeptanzkriterien prüfbar gemacht', true, 2),
  ('prog-multi-user-story', 'Sie legt die technische Umsetzung im Detail fest', false, 3),
  ('prog-multi-user-story', 'Sie benennt verbindlich den zuständigen Entwickler', false, 4),
  -- prog-multi-code-smells
  ('prog-multi-code-smells', 'Methoden mit mehreren hundert Zeilen', true, 0),
  ('prog-multi-code-smells', 'Mehrfach kopierte Codeabschnitte', true, 1),
  ('prog-multi-code-smells', 'Sehr lange Parameterlisten', true, 2),
  ('prog-multi-code-smells', 'Aussagekräftige Methodennamen', false, 3),
  ('prog-multi-code-smells', 'Automatisierte Unit-Tests', false, 4),
  -- prog-multi-passwort-speicherung
  ('prog-multi-passwort-speicherung', 'Speicherung als Hashwert mit einem individuellen Salt je Benutzer', true, 0),
  ('prog-multi-passwort-speicherung', 'Einsatz bewusst rechenintensiver Verfahren wie bcrypt oder Argon2', true, 1),
  ('prog-multi-passwort-speicherung', 'Symmetrische Verschlüsselung mit einem im Quellcode hinterlegten Schlüssel', false, 2),
  ('prog-multi-passwort-speicherung', 'MD5 ohne Salt, da der Hash ohnehin nicht umkehrbar ist', false, 3),
  ('prog-multi-passwort-speicherung', 'Klartextspeicherung in einer separaten, nur für Administratoren lesbaren Tabelle', false, 4),
  -- prog-single-hashmap-zugriff
  ('prog-single-hashmap-zugriff', 'O(1)', true, 0),
  ('prog-single-hashmap-zugriff', 'O(log n)', false, 1),
  ('prog-single-hashmap-zugriff', 'O(n)', false, 2),
  ('prog-single-hashmap-zugriff', 'O(n log n)', false, 3),
  -- prog-single-binaerbaum-inorder
  ('prog-single-binaerbaum-inorder', 'Aufsteigend sortiert', true, 0),
  ('prog-single-binaerbaum-inorder', 'In der Reihenfolge des Einfügens', false, 1),
  ('prog-single-binaerbaum-inorder', 'Ebene für Ebene von oben nach unten', false, 2),
  ('prog-single-binaerbaum-inorder', 'Beginnend mit der Wurzel, dann links, dann rechts', false, 3),
  -- prog-single-komposition-statt-vererbung
  ('prog-single-komposition-statt-vererbung', 'Die Kopplung bleibt geringer und das genutzte Verhalten ist zur Laufzeit austauschbar', true, 0),
  ('prog-single-komposition-statt-vererbung', 'Komposition benötigt weniger Arbeitsspeicher als Vererbung', false, 1),
  ('prog-single-komposition-statt-vererbung', 'Nur mit Komposition lassen sich Methoden wiederverwenden', false, 2),
  ('prog-single-komposition-statt-vererbung', 'Komposition macht Schnittstellen überflüssig', false, 3),
  -- prog-single-liskov
  ('prog-single-liskov', 'Objekte einer Unterklasse müssen anstelle der Oberklasse verwendbar sein, ohne das Verhalten zu brechen', true, 0),
  ('prog-single-liskov', 'Jede Klasse darf nur eine einzige öffentliche Methode besitzen', false, 1),
  ('prog-single-liskov', 'Eine Klasse muss für Erweiterung offen und für Änderung geschlossen sein', false, 2),
  ('prog-single-liskov', 'Module sollen von Abstraktionen abhängen, nicht von konkreten Klassen', false, 3),
  -- prog-single-observer-pattern
  ('prog-single-observer-pattern', 'Mehrere Objekte werden über Zustandsänderungen einer Quelle informiert, ohne dass diese sie konkret kennt', true, 0),
  ('prog-single-observer-pattern', 'Von einer Klasse existiert zur Laufzeit garantiert nur eine Instanz', false, 1),
  ('prog-single-observer-pattern', 'Eine bestehende Schnittstelle wird an eine erwartete Schnittstelle angepasst', false, 2),
  ('prog-single-observer-pattern', 'Ein Algorithmus wird in austauschbare Varianten gekapselt', false, 3),
  -- prog-single-factory-pattern
  ('prog-single-factory-pattern', 'Die Objekterzeugung wird gekapselt, damit der Aufrufer die konkrete Klasse nicht kennen muss', true, 0),
  ('prog-single-factory-pattern', 'Bereits erzeugte Objekte werden zwischengespeichert und wiederverwendet', false, 1),
  ('prog-single-factory-pattern', 'Ein Objektbaum wird einheitlich über eine gemeinsame Schnittstelle durchlaufen', false, 2),
  ('prog-single-factory-pattern', 'Zugriffe auf ein Objekt werden über einen Stellvertreter geleitet', false, 3),
  -- prog-single-refactoring-definition
  ('prog-single-refactoring-definition', 'Die Struktur des Codes wird verbessert, das nach außen sichtbare Verhalten bleibt gleich', true, 0),
  ('prog-single-refactoring-definition', 'Bestehende Fehler werden systematisch gesucht und behoben', false, 1),
  ('prog-single-refactoring-definition', 'Die Anwendung wird auf eine neue Programmiersprache portiert', false, 2),
  ('prog-single-refactoring-definition', 'Neue Funktionen werden möglichst schnell ergänzt', false, 3),
  -- prog-single-git-merge-konflikt
  ('prog-single-git-merge-konflikt', 'Wenn beide Zweige dieselben Zeilen einer Datei unterschiedlich geändert haben', true, 0),
  ('prog-single-git-merge-konflikt', 'Sobald in beiden Zweigen überhaupt Commits vorhanden sind', false, 1),
  ('prog-single-git-merge-konflikt', 'Wenn in einem Zweig eine neue Datei angelegt wurde', false, 2),
  ('prog-single-git-merge-konflikt', 'Wenn die Commit-Nachrichten beider Zweige identisch sind', false, 3),
  -- prog-single-git-revert
  ('prog-single-git-revert', 'revert erzeugt einen zusätzlichen Commit und erhält die Historie, reset --hard verwirft Commits', true, 0),
  ('prog-single-git-revert', 'Beide Befehle bewirken dasselbe, revert ist lediglich der neuere Name', false, 1),
  ('prog-single-git-revert', 'revert wirkt nur auf einzelne Dateien, reset --hard immer auf das gesamte Repository', false, 2),
  ('prog-single-git-revert', 'revert löscht den Branch, reset --hard benennt ihn nur um', false, 3),
  -- prog-single-scrum-product-owner
  ('prog-single-scrum-product-owner', 'Für das Pflegen und Priorisieren des Product Backlogs', true, 0),
  ('prog-single-scrum-product-owner', 'Für die technische Architektur der Lösung', false, 1),
  ('prog-single-scrum-product-owner', 'Für die Einhaltung der Scrum-Regeln im Team', false, 2),
  ('prog-single-scrum-product-owner', 'Für die Zuweisung der Aufgaben an einzelne Entwickler', false, 3),
  -- prog-single-wasserfall-nachteil
  ('prog-single-wasserfall-nachteil', 'Anforderungen werden früh festgeschrieben, spätere Änderungen sind nur mit hohem Aufwand möglich', true, 0),
  ('prog-single-wasserfall-nachteil', 'Es entsteht keinerlei Dokumentation der Phasen', false, 1),
  ('prog-single-wasserfall-nachteil', 'Die Phasen laufen parallel und lassen sich nicht koordinieren', false, 2),
  ('prog-single-wasserfall-nachteil', 'Tests sind im Modell überhaupt nicht vorgesehen', false, 3),
  -- prog-single-uml-vererbung-notation
  ('prog-single-uml-vererbung-notation', 'Durchgezogene Linie mit geschlossener, nicht ausgefüllter Dreiecksspitze zur Oberklasse', true, 0),
  ('prog-single-uml-vererbung-notation', 'Gestrichelte Linie mit offener Pfeilspitze zur Oberklasse', false, 1),
  ('prog-single-uml-vererbung-notation', 'Durchgezogene Linie mit ausgefüllter Raute an der Unterklasse', false, 2),
  ('prog-single-uml-vererbung-notation', 'Doppelte Linie ohne Pfeilspitze zwischen beiden Klassen', false, 3),
  -- prog-single-rest-put-post
  ('prog-single-rest-put-post', 'PUT legt eine Ressource unter einer bekannten URI an oder ersetzt sie vollständig, POST erzeugt über eine Sammlung eine neue Ressource', true, 0),
  ('prog-single-rest-put-post', 'PUT liest Daten, POST schreibt Daten', false, 1),
  ('prog-single-rest-put-post', 'PUT überträgt Daten verschlüsselt, POST unverschlüsselt', false, 2),
  ('prog-single-rest-put-post', 'PUT darf nur von authentifizierten Clients genutzt werden, POST von allen', false, 3),
  -- prog-single-xss
  ('prog-single-xss', 'Eingeschleuster Skriptcode wird ungeprüft ausgeliefert und im Browser anderer Nutzer ausgeführt', true, 0),
  ('prog-single-xss', 'Der Angreifer erzeugt so viele Anfragen, dass der Server nicht mehr erreichbar ist', false, 1),
  ('prog-single-xss', 'Über ein Eingabefeld werden zusätzliche Datenbankbefehle ausgeführt', false, 2),
  ('prog-single-xss', 'Der Datenverkehr zwischen Client und Server wird unbemerkt mitgelesen', false, 3),
  -- prog-single-integer-overflow
  ('prog-single-integer-overflow', 'Das Ergebnis springt auf den kleinsten negativen int-Wert um, ohne dass ein Fehler gemeldet wird', true, 0),
  ('prog-single-integer-overflow', 'Es wird zur Laufzeit eine ArithmeticException geworfen', false, 1),
  ('prog-single-integer-overflow', 'Der Wert wird automatisch in einen long umgewandelt', false, 2),
  ('prog-single-integer-overflow', 'Der Wert bleibt beim Maximum stehen und ändert sich nicht mehr', false, 3),
  -- prog-single-float-vergleich
  ('prog-single-float-vergleich', 'Viele Dezimalbrüche sind binär nicht exakt darstellbar, dadurch entstehen Rundungsfehler', true, 0),
  ('prog-single-float-vergleich', 'Der Operator == ist für Gleitkommatypen syntaktisch nicht erlaubt', false, 1),
  ('prog-single-float-vergleich', 'Gleitkommazahlen werden beim Vergleich immer auf ganze Zahlen gerundet', false, 2),
  ('prog-single-float-vergleich', 'Der Vergleich prüft bei Gleitkommazahlen nur die Referenz, nicht den Wert', false, 3),
  -- prog-single-shortcircuit
  ('prog-single-shortcircuit', 'Ist der linke Operand false, wird der rechte gar nicht mehr ausgewertet', true, 0),
  ('prog-single-shortcircuit', 'Beide Operanden werden ausgewertet, aber nur der linke bestimmt das Ergebnis', false, 1),
  ('prog-single-shortcircuit', 'Die Operanden werden von rechts nach links ausgewertet', false, 2),
  ('prog-single-shortcircuit', 'Das Ergebnis wird zwischengespeichert und bei erneutem Aufruf wiederverwendet', false, 3),
  -- prog-single-do-while
  ('prog-single-do-while', 'Der Schleifenrumpf wird mindestens einmal ausgeführt, weil erst danach geprüft wird', true, 0),
  ('prog-single-do-while', 'Sie kann ausschließlich mit einer festen Anzahl an Durchläufen arbeiten', false, 1),
  ('prog-single-do-while', 'Sie lässt sich nicht vorzeitig mit break verlassen', false, 2),
  ('prog-single-do-while', 'Sie prüft die Bedingung sowohl vor als auch nach jedem Durchlauf', false, 3),
  -- prog-single-struktogramm
  ('prog-single-struktogramm', 'Es stellt den Ablauf eines Algorithmus sprachunabhängig aus verschachtelten Blöcken dar', true, 0),
  ('prog-single-struktogramm', 'Es zeigt die Beziehungen zwischen den Tabellen einer Datenbank', false, 1),
  ('prog-single-struktogramm', 'Es dokumentiert die Verkabelung eines Netzwerks', false, 2),
  ('prog-single-struktogramm', 'Es beschreibt die Klassen einer Anwendung mit ihren Attributen', false, 3),
  -- prog-single-mock-objekt
  ('prog-single-mock-objekt', 'Es ersetzt eine echte Abhängigkeit durch ein steuerbares Ersatzobjekt', true, 0),
  ('prog-single-mock-objekt', 'Es misst die Laufzeit einzelner Methoden während des Tests', false, 1),
  ('prog-single-mock-objekt', 'Es erzeugt automatisch Testfälle aus dem Quellcode', false, 2),
  ('prog-single-mock-objekt', 'Es protokolliert die Testergebnisse für den Abschlussbericht', false, 3),
  -- prog-single-linear-search
  ('prog-single-linear-search', 'O(n)', true, 0),
  ('prog-single-linear-search', 'O(1)', false, 1),
  ('prog-single-linear-search', 'O(log n)', false, 2),
  ('prog-single-linear-search', 'O(n²)', false, 3),
  -- prog-single-konstruktor
  ('prog-single-konstruktor', 'Er wird beim Erzeugen eines Objekts aufgerufen und initialisiert dessen Attribute', true, 0),
  ('prog-single-konstruktor', 'Er gibt beim Beenden des Programms den Speicher des Objekts frei', false, 1),
  ('prog-single-konstruktor', 'Er legt fest, von welcher Klasse geerbt wird', false, 2),
  ('prog-single-konstruktor', 'Er stellt sicher, dass von der Klasse nur ein Objekt existiert', false, 3),
  -- prog-single-checked-exception
  ('prog-single-checked-exception', 'Sie muss gefangen oder mit throws in der Signatur deklariert werden', true, 0),
  ('prog-single-checked-exception', 'Sie kann grundsätzlich nicht in einem catch-Block behandelt werden', false, 1),
  ('prog-single-checked-exception', 'Sie beendet das Programm sofort, ohne den finally-Block auszuführen', false, 2),
  ('prog-single-checked-exception', 'Sie tritt ausschließlich beim Kompilieren auf, nie zur Laufzeit', false, 3)
) as v(source_key, text, is_correct, sort_order)
on v.source_key = q.source_key;
