-- Industriekaufmann/-frau: 75 selbst formulierte Fragen zur Wirtschafts- &
-- Sozialkunde (30 x multiple, 45 x single). Diese Prüfungsdisziplin ist im
-- IHK-System weitgehend berufsübergreifend, die Fragen wurden deshalb bewusst
-- aus einem anderen Blickwinkel als der bereits vorhandene fiae-ae-Pool
-- formuliert (andere Beispiele, andere Schwerpunktsetzung, keine Übernahme
-- von Wortlaut oder Aufbau) und decken zusätzlich die für Industriekaufleute
-- typischen Themenfelder ab: Ausbildung, Arbeitsrecht, Tarifrecht und
-- Mitbestimmung, Sozialversicherung, Steuern, Wirtschaftsordnung, Unter-
-- nehmensformen, Kaufvertrag und Verbraucherschutz, Zahlungsverkehr, Europa
-- und Globalisierung, Datenschutz sowie Umwelt und Nachhaltigkeit. Die
-- Personalwirtschaft-spezifische HR-Prozessperspektive (Einstellung,
-- Personalbeschaffung, Kündigungsprozess im Betrieb) wird hier bewusst
-- ausgespart, da sie im gleichnamigen Schwesterthema behandelt wird; hier
-- steht die volkswirtschaftlich-rechtliche Systemsicht im Vordergrund.
-- source_key-Präfix: ik-wiso-

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'industriekaufmann'
join (values
  -- ===================== Ausbildung / BBiG =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-berufsausbildungsvertrag-inhalt',
   'Welche Angabe muss ein Berufsausbildungsvertrag nach dem Berufsbildungsgesetz zwingend enthalten?',
   'Zu den gesetzlich vorgeschriebenen Mindestangaben zählt unter anderem die Dauer der Probezeit. Der Vertrag ist kein formfreies Gespräch, sondern muss schriftlich niedergelegt werden, damit Ausbildungsziel, Zeiten und Vergütung eindeutig festgehalten sind.',
   1, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-ausbildungsordnung-bestandteile',
   'Welche Elemente legt eine Ausbildungsordnung für einen anerkannten Ausbildungsberuf verbindlich fest?',
   'Eine Ausbildungsordnung bestimmt bundeseinheitlich die Bezeichnung des Berufs, die Dauer der Ausbildung, ein Berufsbild sowie einen zeitlich gegliederten Ausbildungsrahmenplan. Die Höhe der Ausbildungsvergütung wird dagegen nicht in ihr geregelt, sondern folgt aus Tarifverträgen oder betrieblicher Praxis.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-ihk-pruefungsausschuss-besetzung',
   'Wie ist ein Prüfungsausschuss der IHK für Abschlussprüfungen grundsätzlich zusammengesetzt?',
   'Er besteht paritätisch aus Beauftragten der Arbeitgeber, Beauftragten der Arbeitnehmer und mindestens einer Lehrkraft einer berufsbildenden Schule, damit unterschiedliche Perspektiven auf die Prüfungsleistung einfließen.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-jugendarbeitsschutz-verbote',
   'Welche Beschäftigungsformen sind für Jugendliche nach dem Jugendarbeitsschutzgesetz grundsätzlich untersagt?',
   'Akkordarbeit mit vorgegebenem Arbeitstempo und Arbeiten mit erheblicher Gefährdung, etwa im Umgang mit gefährlichen Stoffen ohne Aufsicht, sind für Jugendliche grundsätzlich verboten, weil sie die körperliche und geistige Entwicklung gefährden können. Leichte Botengänge im Betrieb fallen nicht darunter.',
   3, 'multiple'),
  -- ===================== Arbeitsrecht =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-arbeitsvertrag-willenserklaerungen',
   'Wodurch kommt ein Arbeitsvertrag rechtlich zustande?',
   'Wie jeder Vertrag entsteht auch der Arbeitsvertrag durch zwei übereinstimmende Willenserklärungen, ein Angebot und dessen Annahme. Eine besondere Form ist dafür grundsätzlich nicht vorgeschrieben, wird in der Praxis aber aus Beweisgründen gewählt.',
   1, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-kuendigungsarten-uebersicht',
   'Welche der folgenden Begriffe bezeichnen im deutschen Arbeitsrecht anerkannte Kündigungsarten?',
   'Ordentliche und außerordentliche Kündigung sind die beiden gesetzlich verankerten Grundformen, daneben tritt in der Praxis die Änderungskündigung, mit der eine Vertragsänderung durchgesetzt werden soll. Eine "stille Kündigung" ist kein Rechtsbegriff, sondern beschreibt nur ein Verhaltensmuster im Arbeitsalltag.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-ausserordentliche-kuendigung-voraussetzung',
   'Welche Voraussetzung muss für eine außerordentliche fristlose Kündigung nach dem BGB vorliegen?',
   'Es muss ein wichtiger Grund gegeben sein, der es der kündigenden Seite unter Abwägung aller Umstände unzumutbar macht, das Arbeitsverhältnis auch nur bis zum Ablauf der ordentlichen Frist fortzusetzen.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-kuendigungsgruende-kschg',
   'Welche Kündigungsgründe erkennt das Kündigungsschutzgesetz für eine ordentliche Kündigung durch den Arbeitgeber grundsätzlich an?',
   'Das Gesetz lässt eine Kündigung nur zu, wenn sie sozial gerechtfertigt ist: personenbedingt, etwa durch dauerhafte Krankheit, verhaltensbedingt bei Pflichtverletzungen, oder betriebsbedingt bei Wegfall des Arbeitsplatzes. Ein bloßer Wunsch nach jüngerem Personal ist keiner dieser anerkannten Gründe.',
   4, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-abmahnung-funktion',
   'Welche Funktion hat eine Abmahnung im Arbeitsverhältnis?',
   'Sie rügt ein konkretes Fehlverhalten, fordert künftig vertragsgemäßes Verhalten und weist auf mögliche Folgen bei Wiederholung hin. Erst nach einer erfolglosen Abmahnung ist bei wiederkehrenden Pflichtverstößen regelmäßig eine verhaltensbedingte Kündigung tragfähig.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-elternzeit-anspruch',
   'Welche Aussagen zur Elternzeit treffen zu?',
   'Der Anspruch besteht grundsätzlich bis zur Vollendung des dritten Lebensjahres des Kindes. Ein Anteil davon kann mit Zustimmung des Arbeitgebers auf einen späteren Zeitraum übertragen werden, und während der Elternzeit besteht ein besonderer Kündigungsschutz. Beide Elternteile müssen die Elternzeit dabei nicht gleichzeitig nehmen.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-arbeitszeugnis-wohlwollend',
   'Welchem Grundsatz muss ein qualifiziertes Arbeitszeugnis nach der Rechtsprechung entsprechen?',
   'Es muss wahr und zugleich wohlwollend formuliert sein, also den beruflichen Weg nicht unnötig erschweren. Beide Anforderungen stehen in einem Spannungsverhältnis, das durch eine wertneutrale, aber verständliche Zeugnissprache aufgelöst wird.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-urlaub-grundsaetze',
   'Welche Aussagen zum gesetzlichen Erholungsurlaub treffen zu?',
   'Urlaub dient der Erholung und darf deshalb grundsätzlich nicht durch eine Geldzahlung ersetzt werden, solange das Arbeitsverhältnis fortbesteht. Nur bei Beendigung des Arbeitsverhältnisses wird nicht genommener Urlaub abgegolten. Der Anspruch entsteht unabhängig von einer bestimmten Betriebsgröße.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-nachtarbeit-zuschlag',
   'Worauf haben Arbeitnehmer bei geleisteter Nachtarbeit nach dem Arbeitszeitgesetz grundsätzlich Anspruch?',
   'Sie haben Anspruch auf einen angemessenen Ausgleich, entweder durch bezahlte freie Tage oder durch einen angemessenen Zuschlag auf das Bruttoentgelt, sofern kein Tarifvertrag eine abweichende Regelung trifft.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-befristung-sachgrundlos',
   'Welche Aussagen zur sachgrundlosen Befristung eines Arbeitsverhältnisses nach dem Teilzeit- und Befristungsgesetz treffen zu?',
   'Eine sachgrundlose Befristung ist bis zu einer Gesamtdauer von zwei Jahren zulässig, innerhalb derer eine Verlängerung höchstens dreimal möglich ist. Voraussetzung ist außerdem, dass zuvor kein Arbeitsverhältnis mit demselben Arbeitgeber bestand. Eine beliebig oft wiederholbare Verlängerung um jeweils zwei weitere Jahre sieht das Gesetz nicht vor.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-teilzeitanspruch-voraussetzung',
   'Welche Voraussetzungen müssen erfüllt sein, damit ein Arbeitnehmer grundsätzlich einen gesetzlichen Anspruch auf Verringerung seiner Arbeitszeit nach dem Teilzeit- und Befristungsgesetz hat?',
   'Der Betrieb muss in der Regel mehr als 15 Arbeitnehmer beschäftigen, das Arbeitsverhältnis muss bereits länger als sechs Monate bestehen, und der Antrag muss rechtzeitig vor dem gewünschten Beginn gestellt werden. Eine bestimmte Mindestbetriebszugehörigkeit von zehn Jahren verlangt das Gesetz dagegen nicht.',
   3, 'multiple'),
  -- ===================== Tarifrecht und Mitbestimmung =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-tarifautonomie-begriff',
   'Was versteht man unter dem Grundsatz der Tarifautonomie?',
   'Tarifautonomie bedeutet, dass Arbeitgeber beziehungsweise Arbeitgeberverbände und Gewerkschaften Löhne und Arbeitsbedingungen eigenständig und ohne staatliche Einmischung in Tarifverträgen aushandeln, geschützt durch die im Grundgesetz verankerte Koalitionsfreiheit.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-tarifvertrag-wirkung',
   'Welche Aussagen zur Wirkung eines Tarifvertrags treffen zu?',
   'Ein Tarifvertrag entfaltet unmittelbare und zwingende Wirkung für tarifgebundene Arbeitgeber und gewerkschaftlich organisierte Arbeitnehmer. Er kann durch eine Allgemeinverbindlicherklärung auf nicht organisierte Betriebe der Branche erstreckt werden. Einzelvertraglich darf zugunsten des Arbeitnehmers davon abgewichen werden, zu seinen Ungunsten grundsätzlich nicht.',
   4, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-jav-aufgabe',
   'Welche Aufgabe hat die Jugend- und Auszubildendenvertretung (JAV) in einem Betrieb?',
   'Die JAV vertritt die besonderen Interessen der jugendlichen und der in Ausbildung befindlichen Beschäftigten gegenüber dem Betriebsrat und dem Arbeitgeber, kann aber selbst keine Betriebsvereinbarungen abschließen.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-betriebsrat-wahlvoraussetzung',
   'Unter welchen Voraussetzungen kann in einem Betrieb ein Betriebsrat gewählt werden?',
   'Voraussetzung ist ein Betrieb mit in der Regel mindestens fünf ständig wahlberechtigten Arbeitnehmern, von denen mindestens drei wählbar sein müssen. Eine bestimmte Rechtsform des Unternehmens ist dagegen nicht vorgeschrieben, ein Betriebsrat kann ebenso in einer GmbH wie in einem Einzelunternehmen entstehen.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-streikrecht-traeger',
   'Wer ist in Deutschland Träger des Streikrechts?',
   'Träger des Streikrechts sind die Gewerkschaften, nicht der einzelne Arbeitnehmer und nicht der Betriebsrat. Ein von einer Gewerkschaft nicht getragener sogenannter wilder Streik ist rechtlich nicht abgesichert.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-friedenspflicht-tarif',
   'Was besagt die relative Friedenspflicht während der Laufzeit eines Tarifvertrags?',
   'Solange der Tarifvertrag läuft, dürfen die darin bereits geregelten Punkte nicht durch Arbeitskampf neu erstritten werden. Themen, die der Tarifvertrag nicht regelt, bleiben davon unberührt und können weiterhin Gegenstand eines Arbeitskampfes sein.',
   4, 'single'),
  -- ===================== Sozialversicherung =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-solidaritaetsprinzip',
   'Was kennzeichnet das Solidaritätsprinzip in der gesetzlichen Sozialversicherung?',
   'Beiträge richten sich nach der wirtschaftlichen Leistungsfähigkeit der Versicherten, während Leistungen sich am individuellen Bedarf orientieren. Wer mehr verdient, zahlt tendenziell mehr ein, ohne dafür automatisch mehr Leistung zu erhalten, wodurch ein Ausgleich zwischen den Mitgliedern entsteht.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-pflichtversicherung-zweige',
   'In welchen Zweigen der Sozialversicherung sind Arbeitnehmer in einem regulären Beschäftigungsverhältnis grundsätzlich pflichtversichert?',
   'Kranken-, Renten-, Pflege- und Arbeitslosenversicherung setzen üblicherweise eine eigene Beitragsleistung der Arbeitnehmer voraus. Die Unfallversicherung besteht ebenfalls, wird jedoch vollständig vom Arbeitgeber finanziert und zählt trotzdem zu den fünf Pflichtzweigen.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-versicherungsprinzip-abgrenzung',
   'Welche Aussagen zum Versicherungsprinzip in der Sozialversicherung treffen zu?',
   'Beim Versicherungsprinzip hängt die Höhe mancher Leistungen, etwa der Rente, von der Höhe der eingezahlten Beiträge ab. Es steht damit im Gegensatz zum Solidaritätsprinzip, das einen Ausgleich unabhängig von der individuellen Beitragshöhe vorsieht, wobei beide Prinzipien in der gesetzlichen Rentenversicherung nebeneinander wirken.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-pflegeversicherung-einfuehrung',
   'Welchem Zweck dient die gesetzliche Pflegeversicherung als jüngster Zweig der Sozialversicherung?',
   'Sie soll das finanzielle Risiko der Pflegebedürftigkeit auffangen und die Kosten für Pflegeleistungen im Alter oder bei Krankheit teilweise absichern, ohne die Pflegekosten dabei vollständig zu übernehmen.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-familienversicherung-kv',
   'Welche Aussagen zur Familienversicherung in der gesetzlichen Krankenversicherung treffen zu?',
   'Ehepartner und Kinder ohne oder mit nur geringem eigenem Einkommen können beitragsfrei über das versicherte Mitglied mitversichert werden. Die Mitversicherung ist an bestimmte Einkommensgrenzen der Angehörigen geknüpft und entlastet Familien, weil für die mitversicherten Angehörigen kein eigener Beitrag anfällt.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-arbeitslosengeld-grundlage',
   'Welche Voraussetzungen müssen grundsätzlich erfüllt sein, damit ein Anspruch auf Arbeitslosengeld I entsteht?',
   'Es muss innerhalb der Rahmenfrist eine Mindestzeit an sozialversicherungspflichtiger Beschäftigung, die sogenannte Anwartschaftszeit, zurückgelegt worden sein; zusätzlich muss sich die Person persönlich arbeitslos gemeldet haben und der Arbeitsvermittlung zur Verfügung stehen. Ein bestimmtes Mindestalter oder ein Studienabschluss sind dagegen keine Voraussetzung.',
   3, 'multiple'),
  -- ===================== Steuern =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-einkommensteuer-progression',
   'Was bedeutet die Progression im deutschen Einkommensteuertarif?',
   'Mit steigendem zu versteuerndem Einkommen steigt nicht nur die absolute Steuerlast, sondern auch der prozentuale Grenzsteuersatz an, sodass höhere Einkommen anteilig stärker belastet werden.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-direkte-vs-indirekte-steuern-beispiele',
   'Welche der folgenden Steuern zählen zu den direkten Steuern?',
   'Bei direkten Steuern fallen Steuerschuldner und wirtschaftlich Belasteter zusammen, wie bei der Einkommen- und der Körperschaftsteuer. Die Umsatzsteuer dagegen wird vom Unternehmen abgeführt, aber wirtschaftlich vom Endverbraucher getragen, und zählt deshalb zu den indirekten Steuern.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-lohnsteuerklassen-zweck',
   'Wozu dienen die unterschiedlichen Lohnsteuerklassen in Deutschland?',
   'Sie steuern die Höhe des monatlichen Lohnsteuerabzugs vom Arbeitsentgelt in Abhängigkeit vom Familienstand, um die endgültige Steuerschuld möglichst treffend vorwegzunehmen; die tatsächliche Jahressteuerschuld wird abschließend über die Einkommensteuererklärung ermittelt.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-gewerbesteuer-empfaenger',
   'Welcher Gebietskörperschaft steht das Aufkommen der Gewerbesteuer überwiegend zu?',
   'Die Gewerbesteuer ist die zentrale eigene Einnahmequelle der Gemeinden und wird von Unternehmen abhängig vom Gewerbeertrag erhoben, wobei der jeweilige Hebesatz von der Gemeinde selbst festgelegt wird.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-vorsteuerabzug-zweck',
   'Welchen Zweck erfüllt der Vorsteuerabzug für ein umsatzsteuerpflichtiges Unternehmen?',
   'Er sorgt dafür, dass die beim Einkauf gezahlte Umsatzsteuer mit der beim Verkauf vereinnahmten Umsatzsteuer verrechnet werden kann, sodass Unternehmen im Ergebnis nicht mit der Steuer belastet bleiben und nur der Endverbraucher sie wirtschaftlich trägt.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-freibetrag-vs-freigrenze',
   'Worin unterscheidet sich ein Freibetrag von einer Freigrenze im Steuerrecht?',
   'Bei einem Freibetrag bleibt nur der über den Betrag hinausgehende Teil steuerpflichtig, während bei einer Freigrenze bei Überschreiten der gesamte Betrag steuerpflichtig wird, nicht nur der übersteigende Teil.',
   4, 'single'),
  -- ===================== Wirtschaftsordnung und Wirtschaftskreislauf =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-soziale-marktwirtschaft-idee',
   'Welcher Grundgedanke kennzeichnet die soziale Marktwirtschaft als Wirtschaftsordnung Deutschlands?',
   'Sie verbindet die Freiheit des Marktes bei Preisbildung und Wettbewerb mit einem sozialen Ausgleich durch den Staat, etwa über Sozialversicherung und Umverteilung, um die Härten eines rein freien Marktes abzufedern.',
   1, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-marktwirtschaft-planwirtschaft-merkmale',
   'Welche Merkmale sind für eine freie Marktwirtschaft im Unterschied zu einer zentralen Planwirtschaft typisch?',
   'Preise entstehen dezentral über Angebot und Nachfrage, und Produktionsmittel befinden sich überwiegend in privatem Eigentum. In einer Planwirtschaft legt dagegen eine zentrale staatliche Stelle Produktionsmengen und Preise verbindlich fest.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-nachfrageverschiebung-einkommen',
   'Wie wirkt sich ein Anstieg des verfügbaren Einkommens der Haushalte typischerweise auf die Nachfragekurve eines normalen Gutes aus?',
   'Die Nachfragekurve verschiebt sich bei gleichbleibendem Preis nach rechts, weil Haushalte bei mehr verfügbarem Einkommen bei jedem Preis eine größere Menge des Gutes nachfragen als zuvor.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-substitutionsgueter-beispiel',
   'Was versteht man unter Substitutionsgütern im wirtschaftlichen Sinn?',
   'Substitutionsgüter können sich in ihrem Verwendungszweck gegenseitig ersetzen, sodass ein Preisanstieg beim einen Gut die Nachfrage nach dem anderen erhöht, weil Verbraucher auf die günstigere Alternative ausweichen.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-wirtschaftskreislauf-akteure',
   'Welche zwei Grundakteure stehen im einfachen Wirtschaftskreislaufmodell einander gegenüber?',
   'Im einfachen Modell tauschen private Haushalte und Unternehmen Güter, Produktionsfaktoren und Geld gegeneinander aus: Haushalte stellen Arbeitskraft bereit und erhalten Einkommen, Unternehmen produzieren Güter und erhalten dafür Entgelt.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-konjunkturindikatoren',
   'Welche Größen dienen typischerweise als Indikatoren zur Beobachtung der konjunkturellen Lage einer Volkswirtschaft?',
   'Auftragseingänge der Industrie und die Arbeitslosenquote gelten als aussagekräftige Frühindikatoren beziehungsweise Spätindikatoren der Konjunktur. Die Anzahl der Feiertage in einem Kalenderjahr hat dagegen keinen wirtschaftlichen Aussagewert für den Konjunkturverlauf.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-inflation-messung',
   'Womit wird die Inflationsrate einer Volkswirtschaft in Deutschland üblicherweise gemessen?',
   'Grundlage ist der Verbraucherpreisindex, der die Preisentwicklung eines repräsentativen Warenkorbs typischer Konsumgüter und Dienstleistungen im Zeitverlauf abbildet.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-deflation-risiko',
   'Welches Risiko ist mit einer anhaltenden Deflation für eine Volkswirtschaft typischerweise verbunden?',
   'Verbraucher verschieben Käufe in Erwartung weiter fallender Preise, wodurch die Nachfrage sinkt, Unternehmen Investitionen zurückstellen und im ungünstigen Fall eine Abwärtsspirale aus sinkender Produktion und steigender Arbeitslosigkeit entstehen kann.',
   4, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-zieldreieck-erweitert',
   'Um welches Ziel wurde das ursprüngliche Zieldreieck der Wirtschaftspolitik zum sogenannten magischen Viereck erweitert?',
   'Zu Preisniveaustabilität, Vollbeschäftigung und außenwirtschaftlichem Gleichgewicht trat als viertes Ziel ein stetiges und angemessenes Wirtschaftswachstum hinzu, wodurch die vier Ziele nur schwer gleichzeitig vollständig erreichbar sind.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-monopol-merkmal',
   'Was kennzeichnet ein Angebotsmonopol auf einem Markt?',
   'Einem einzigen Anbieter steht eine Vielzahl von Nachfragern gegenüber, wodurch der Anbieter mangels Konkurrenz erheblichen Einfluss auf die Preisgestaltung erhält, den er in einem Wettbewerbsmarkt so nicht hätte.',
   2, 'single'),
  -- ===================== Unternehmensformen =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-einzelunternehmen-merkmal',
   'Welches Merkmal ist für ein Einzelunternehmen charakteristisch?',
   'Der Inhaber trägt die alleinige unternehmerische Verantwortung, trifft Entscheidungen allein und haftet dafür unbeschränkt mit seinem gesamten Privatvermögen, ohne dass ein Mindestkapital vorgeschrieben ist.',
   1, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-gmbh-merkmale',
   'Welche Aussagen zur Gesellschaft mit beschränkter Haftung (GmbH) treffen zu?',
   'Die Haftung ist grundsätzlich auf das Gesellschaftsvermögen beschränkt, ihre Gründung erfordert ein Stammkapital sowie einen notariell beurkundeten Gesellschaftsvertrag. Eine natürliche Person als alleiniger Gesellschafter ist zulässig, eine GmbH kann also auch von nur einer Person gegründet werden.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-ug-haftungsbeschraenkt-zweck',
   'Welchem Zweck dient die Unternehmergesellschaft (haftungsbeschränkt) als Variante der GmbH?',
   'Sie erlaubt Gründungen mit beschränkter Haftung bereits bei geringem Startkapital ab einem Euro und verpflichtet im Gegenzug zu einer schrittweisen Rücklagenbildung, bis das für die reguläre GmbH vorgeschriebene Stammkapital erreicht ist.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-genossenschaft-prinzip',
   'Welches Grundprinzip verfolgt eine eingetragene Genossenschaft als Unternehmensform?',
   'Sie bezweckt in erster Linie die Förderung ihrer Mitglieder durch gemeinschaftlichen Geschäftsbetrieb, etwa durch günstigeren Einkauf oder gemeinsame Vermarktung, und nicht vorrangig die Erzielung eines möglichst hohen Gewinns für externe Kapitalgeber.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-aktiengesellschaft-organe',
   'Welches Organ einer Aktiengesellschaft überwacht die Geschäftsführung des Vorstands?',
   'Der Aufsichtsrat bestellt den Vorstand, überwacht dessen Geschäftsführung und muss über wesentliche Vorgänge informiert werden, greift jedoch nicht selbst in das laufende operative Tagesgeschäft ein.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-gbr-ohg-abgrenzung',
   'Wodurch unterscheidet sich eine offene Handelsgesellschaft (OHG) von einer Gesellschaft bürgerlichen Rechts (GbR)?',
   'Die OHG ist stets auf den Betrieb eines Handelsgewerbes unter gemeinsamer Firma ausgerichtet und wird ins Handelsregister eingetragen, während die GbR jeden erlaubten gemeinsamen Zweck verfolgen kann. Bei der Haftung unterscheiden sich beide Formen dagegen kaum, in beiden haften die Gesellschafter grundsätzlich persönlich.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-handelsregister-publizitaet',
   'Welche Aussagen zur Publizitätswirkung des Handelsregisters treffen zu?',
   'Wer im Rechtsverkehr auf eingetragene und bekannt gemachte Angaben, etwa zur Vertretungsbefugnis, vertraut, wird grundsätzlich geschützt. Das Handelsregister ist für jedermann öffentlich einsehbar, und Änderungen wie ein Geschäftsführerwechsel müssen zur Eintragung angemeldet werden. Eine automatische Löschung eingetragener Daten nach wenigen Jahren gibt es dagegen nicht.',
   4, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-kapitalgesellschaft-vorteil',
   'Welchen zentralen Vorteil bietet die Rechtsform einer Kapitalgesellschaft gegenüber einem Einzelunternehmen typischerweise für die Gründer?',
   'Das persönliche Haftungsrisiko der Gesellschafter wird auf das eingebrachte Kapital der Gesellschaft begrenzt, sodass im Regelfall das private Vermögen der Gründer bei Geschäftsmisserfolgen nicht unmittelbar herangezogen wird.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-prokura-erteilung',
   'Wer kann einem Mitarbeiter im Unternehmen Prokura erteilen?',
   'Prokura kann nur der Inhaber des Handelsgeschäfts selbst oder sein gesetzlicher Vertreter erteilen, nicht ein anderer Prokurist, und die Erteilung muss ins Handelsregister eingetragen werden.',
   3, 'single'),
  -- ===================== Kaufvertrag und Verbraucherschutz =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-vertragsfreiheit-grenzen',
   'Wodurch wird der Grundsatz der Vertragsfreiheit im deutschen Recht begrenzt?',
   'Zwingende gesetzliche Vorschriften, etwa zum Verbraucherschutz oder Verbote sittenwidriger Geschäfte, setzen der freien Vertragsgestaltung Grenzen, damit die Freiheit nicht zulasten der schwächeren Vertragspartei missbraucht wird.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-willenserklaerung-merkmale',
   'Welche Aussagen zur Willenserklärung als Grundbaustein eines Vertrags treffen zu?',
   'Sie richtet sich auf die Herbeiführung einer bestimmten Rechtsfolge und kann ausdrücklich, etwa mündlich oder schriftlich, aber auch durch schlüssiges Verhalten abgegeben werden. Reines Schweigen gilt dagegen im Regelfall gerade nicht als Zustimmung.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-verzug-rechtsfolge-schaden',
   'Welche Rechtsfolge kann ein Verkäufer geltend machen, wenn der Käufer mit der Kaufpreiszahlung in Verzug gerät?',
   'Der Verkäufer kann neben der weiterhin geschuldeten Zahlung Verzugszinsen sowie den Ersatz eines durch den Verzug entstandenen weiteren Schadens verlangen, sofern dieser nachgewiesen wird.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-widerrufsausnahmen',
   'Bei welchen Vertragsarten ist das gesetzliche Widerrufsrecht für Fernabsatzverträge typischerweise ausgeschlossen?',
   'Individuell nach Kundenwunsch angefertigte Waren und schnell verderbliche Waren sind vom Widerrufsrecht ausgenommen, weil eine Rückabwicklung wirtschaftlich nicht sinnvoll wäre. Der Kauf eines standardmäßig vorrätigen Fernsehgeräts im Onlineshop unterliegt dagegen dem regulären Widerrufsrecht.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-garantie-gewaehrleistung-unterschied',
   'Welche Aussagen zum Unterschied zwischen gesetzlicher Gewährleistung und einer Herstellergarantie treffen zu?',
   'Die Gewährleistung ist gesetzlich vorgeschrieben und trifft den Verkäufer, während die Garantie eine freiwillige Zusatzzusage meist des Herstellers ist, deren Inhalt er frei festlegen kann. Beide Ansprüche können nebeneinander bestehen. Eine Garantie ersetzt die gesetzliche Gewährleistung damit gerade nicht vollständig.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-agb-einbeziehung',
   'Welche Aussagen dazu, wann Allgemeine Geschäftsbedingungen wirksam Vertragsbestandteil werden, treffen zu?',
   'Der Verwender muss bei Vertragsschluss ausdrücklich auf die AGB hinweisen und der anderen Vertragspartei die Möglichkeit verschaffen, in zumutbarer Weise von ihrem Inhalt Kenntnis zu nehmen. Ein einmaliger Aushang vor Jahren reicht dafür nicht für alle künftigen Verträge, und überraschende Klauseln werden trotz Einbeziehung der AGB nicht automatisch wirksam.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-mangel-begriff',
   'Welche Aussagen dazu, wann nach dem Kaufrecht ein Sachmangel vorliegt, treffen zu?',
   'Ein Sachmangel liegt vor, wenn die Kaufsache bei Gefahrübergang nicht der vereinbarten Beschaffenheit entspricht, sich nicht für die gewöhnliche Verwendung eignet oder nicht für eine vertraglich vorausgesetzte besondere Verwendung taugt. Bloße Unzufriedenheit mit dem Preis oder eine verspätete Lieferung sind dagegen keine Sachmängel.',
   2, 'multiple'),
  -- ===================== Geld- und Zahlungsverkehr =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-sepa-ueberweisung-frist',
   'Innerhalb welcher regulären Frist muss eine SEPA-Überweisung dem Konto des Zahlungsempfängers gutgeschrieben werden?',
   'Eine SEPA-Standardüberweisung muss spätestens am nächsten Bankgeschäftstag nach Auftragserteilung beim Zahlungsempfänger gutgeschrieben sein, sofern der Auftrag rechtzeitig vor der bankinternen Annahmeschlusszeit eingereicht wurde.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-iban-funktion',
   'Wozu dient die IBAN im europäischen Zahlungsverkehr?',
   'Die IBAN identifiziert ein Bankkonto eindeutig über Ländergrenzen hinweg und ersetzt die früher getrennte Angabe von Kontonummer und Bankleitzahl durch ein einheitliches, international standardisiertes Format.',
   1, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-bargeldloser-zahlungsverkehr-formen',
   'Welche der folgenden Zahlungsformen zählen zum unbaren Zahlungsverkehr?',
   'Überweisung und Lastschrift wickeln Zahlungen ohne Bargeldübergabe über Bankkonten ab. Die Barzahlung an der Kasse gehört dagegen begrifflich zum Bargeldverkehr, auch wenn sie im Betrieb ebenfalls häufig vorkommt.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-skonto-berechnung',
   'Was bewirkt ein vereinbarter Skontoabzug bei einer Rechnung mit dem Vermerk "2 % Skonto bei Zahlung innerhalb von 10 Tagen"?',
   'Zahlt der Kunde innerhalb der genannten Frist, darf er zwei Prozent des Rechnungsbetrags abziehen; Skonto ist damit ein Preisnachlass für besonders schnelle Zahlung und unterscheidet sich vom Rabatt, der unabhängig von der Zahlungsgeschwindigkeit gewährt wird.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-akkreditiv-funktion',
   'Welche Funktion erfüllt ein Dokumentenakkreditiv im Außenhandel?',
   'Eine Bank verpflichtet sich gegenüber dem Exporteur zur Zahlung, sobald bestimmte vereinbarte Dokumente fristgerecht vorgelegt werden, wodurch sowohl das Zahlungsrisiko des Verkäufers als auch das Lieferrisiko des Käufers abgesichert werden.',
   4, 'single'),
  -- ===================== Europa und Globalisierung =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-eu-binnenmarkt-grundfreiheiten',
   'Welche vier Grundfreiheiten kennzeichnen den EU-Binnenmarkt?',
   'Der Binnenmarkt beruht auf dem freien Verkehr von Waren, Dienstleistungen, Personen und Kapital zwischen den Mitgliedstaaten, wodurch Handelshemmnisse innerhalb der EU weitgehend abgebaut werden.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-globalisierung-chancen-risiken',
   'Welche Auswirkungen der Globalisierung auf einen exportorientierten Industriebetrieb sind zutreffend?',
   'Neue Absatzmärkte im Ausland eröffnen zusätzliche Umsatzchancen, gleichzeitig steigt der Wettbewerbsdruck durch ausländische Anbieter und Lieferketten werden anfälliger für internationale Störungen. Der Wettbewerb um Fachkräfte wird dadurch nicht automatisch geringer, sondern eher intensiver.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-euro-vorteil-binnenhandel',
   'Welchen Vorteil bietet die gemeinsame Währung Euro für Unternehmen im Handel innerhalb der Eurozone?',
   'Da Umrechnungs- und Wechselkursrisiken innerhalb der Eurozone entfallen, werden Preise unmittelbar vergleichbar und die Kalkulation grenzüberschreitender Geschäfte wird einfacher und planbarer.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-freihandelsabkommen-zweck',
   'Welchem Zweck dient ein Freihandelsabkommen zwischen zwei Wirtschaftsräumen typischerweise?',
   'Es soll Zölle und andere Handelshemmnisse zwischen den beteiligten Staaten abbauen oder ganz beseitigen, um den gegenseitigen Warenaustausch zu erleichtern und zu verbilligen.',
   1, 'single'),
  -- ===================== Datenschutz =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-dsgvo-rechtsgrundlage',
   'Welche der folgenden Umstände können nach der DSGVO eine zulässige Rechtsgrundlage für die Verarbeitung personenbezogener Daten eines Kunden darstellen?',
   'Eine ausdrückliche Einwilligung, die Erforderlichkeit zur Vertragserfüllung sowie eine gesetzliche Verpflichtung des Unternehmens sind anerkannte Rechtsgrundlagen. Ein bloßes wirtschaftliches Interesse ohne benannten Zweck oder eine formlose Zusage ohne dokumentierten Zweck reichen dagegen nicht aus.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-datenschutzbeauftragter-pflicht',
   'Ab wann ist ein Unternehmen nach deutschem Recht in der Regel verpflichtet, einen betrieblichen Datenschutzbeauftragten zu bestellen?',
   'Die Pflicht greift regelmäßig, sobald in der Regel mindestens 20 Personen ständig mit der automatisierten Verarbeitung personenbezogener Daten beschäftigt sind, unabhängig von der Größe des Unternehmens insgesamt.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-datenminimierung-grundsatz',
   'Was fordert der Grundsatz der Datenminimierung im betrieblichen Datenschutz?',
   'Es dürfen nur so viele personenbezogene Daten erhoben und verarbeitet werden, wie für den konkreten Zweck tatsächlich erforderlich sind, ein Vorrat an Daten auf Vorrat ist damit unzulässig.',
   2, 'single'),
  -- ===================== Umwelt und Nachhaltigkeit =====================
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-nachhaltigkeit-drei-saeulen',
   'Welche Dimensionen umfasst das gängige Leitbild der Nachhaltigkeit im unternehmerischen Kontext?',
   'Nachhaltigkeit wird üblicherweise über die ökologische, die ökonomische und die soziale Dimension definiert, die gleichrangig berücksichtigt werden sollen, damit wirtschaftlicher Erfolg nicht zulasten von Umwelt und Gesellschaft geht. Eine eigenständige rein rechtliche oder rein politische vierte Säule gehört nicht zu diesem Leitbild.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-m-betriebliche-umweltmassnahmen',
   'Welche Maßnahmen tragen in einem Industriebetrieb unmittelbar zur Senkung des betrieblichen Ressourcenverbrauchs bei?',
   'Die Rückgewinnung von Abwärme aus Produktionsprozessen und ein konsequentes Recycling von Produktionsabfällen senken den Verbrauch an Energie beziehungsweise Rohstoffen direkt. Eine höhere Beleuchtungsstärke über den betrieblichen Bedarf hinaus erhöht den Verbrauch dagegen eher, statt ihn zu senken.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-emissionshandel-prinzip',
   'Nach welchem Grundprinzip funktioniert der europäische Emissionshandel für Treibhausgase?',
   'Unternehmen benötigen für jede ausgestoßene Tonne CO2 ein Emissionszertifikat; da die Gesamtmenge der Zertifikate begrenzt ist, entsteht ein wirtschaftlicher Anreiz, Emissionen zu senken, weil überschüssige Zertifikate gehandelt werden können.',
   4, 'single'),
  ('Wirtschafts- & Sozialkunde', 'ik-wiso-s-erweiterte-produzentenverantwortung',
   'Was bedeutet die erweiterte Herstellerverantwortung im Rahmen der Kreislaufwirtschaft?',
   'Hersteller werden über den reinen Verkauf hinaus für die spätere Entsorgung oder Verwertung ihrer Produkte mitverantwortlich gemacht, etwa durch Beteiligung an Rücknahme- und Recyclingsystemen, um Anreize für langlebigere Produkte zu setzen.',
   3, 'single')
) as v(topic_name, source_key, q, expl, difficulty, question_type)
on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- ik-wiso-s-berufsausbildungsvertrag-inhalt
  ('ik-wiso-s-berufsausbildungsvertrag-inhalt', 'Die Dauer der Probezeit', true, 0),
  ('ik-wiso-s-berufsausbildungsvertrag-inhalt', 'Die spätere Übernahmezusage nach der Ausbildung', false, 1),
  ('ik-wiso-s-berufsausbildungsvertrag-inhalt', 'Der Name der zuständigen Berufsschullehrkraft', false, 2),
  ('ik-wiso-s-berufsausbildungsvertrag-inhalt', 'Die geplante spätere Abteilung nach der Übernahme', false, 3),
  -- ik-wiso-m-ausbildungsordnung-bestandteile
  ('ik-wiso-m-ausbildungsordnung-bestandteile', 'Bezeichnung des Ausbildungsberufs', true, 0),
  ('ik-wiso-m-ausbildungsordnung-bestandteile', 'Dauer der Ausbildung', true, 1),
  ('ik-wiso-m-ausbildungsordnung-bestandteile', 'Zeitlich gegliederter Ausbildungsrahmenplan', true, 2),
  ('ik-wiso-m-ausbildungsordnung-bestandteile', 'Konkrete Höhe der Ausbildungsvergütung', false, 3),
  -- ik-wiso-s-ihk-pruefungsausschuss-besetzung
  ('ik-wiso-s-ihk-pruefungsausschuss-besetzung', 'Paritätisch aus Arbeitgeber- und Arbeitnehmerseite sowie mindestens einer Lehrkraft', true, 0),
  ('ik-wiso-s-ihk-pruefungsausschuss-besetzung', 'Ausschließlich aus Vertretern des Ausbildungsbetriebs', false, 1),
  ('ik-wiso-s-ihk-pruefungsausschuss-besetzung', 'Ausschließlich aus hauptamtlichen IHK-Mitarbeitern', false, 2),
  ('ik-wiso-s-ihk-pruefungsausschuss-besetzung', 'Ausschließlich aus Lehrkräften der Berufsschule', false, 3),
  -- ik-wiso-m-jugendarbeitsschutz-verbote
  ('ik-wiso-m-jugendarbeitsschutz-verbote', 'Akkordarbeit mit vorgegebenem Arbeitstempo', true, 0),
  ('ik-wiso-m-jugendarbeitsschutz-verbote', 'Arbeiten mit erheblicher Gefährdung ohne Aufsicht durch Fachkräfte', true, 1),
  ('ik-wiso-m-jugendarbeitsschutz-verbote', 'Leichte Botengänge innerhalb des Betriebs', false, 2),
  ('ik-wiso-m-jugendarbeitsschutz-verbote', 'Teilnahme am regulären Berufsschulunterricht', false, 3),
  -- ik-wiso-s-arbeitsvertrag-willenserklaerungen
  ('ik-wiso-s-arbeitsvertrag-willenserklaerungen', 'Durch Angebot und Annahme, also zwei übereinstimmende Willenserklärungen', true, 0),
  ('ik-wiso-s-arbeitsvertrag-willenserklaerungen', 'Nur durch die notarielle Beurkundung', false, 1),
  ('ik-wiso-s-arbeitsvertrag-willenserklaerungen', 'Erst mit Eintragung ins Handelsregister', false, 2),
  ('ik-wiso-s-arbeitsvertrag-willenserklaerungen', 'Erst mit dem ersten tatsächlichen Arbeitstag', false, 3),
  -- ik-wiso-m-kuendigungsarten-uebersicht
  ('ik-wiso-m-kuendigungsarten-uebersicht', 'Ordentliche Kündigung', true, 0),
  ('ik-wiso-m-kuendigungsarten-uebersicht', 'Außerordentliche Kündigung', true, 1),
  ('ik-wiso-m-kuendigungsarten-uebersicht', 'Änderungskündigung', true, 2),
  ('ik-wiso-m-kuendigungsarten-uebersicht', 'Stille Kündigung', false, 3),
  -- ik-wiso-s-ausserordentliche-kuendigung-voraussetzung
  ('ik-wiso-s-ausserordentliche-kuendigung-voraussetzung', 'Ein wichtiger Grund, der die Fortsetzung bis zum Fristablauf unzumutbar macht', true, 0),
  ('ik-wiso-s-ausserordentliche-kuendigung-voraussetzung', 'Eine vorherige schriftliche Zustimmung des Betriebsrats in jedem Fall', false, 1),
  ('ik-wiso-s-ausserordentliche-kuendigung-voraussetzung', 'Ausschließlich eine wiederholte Verspätung um wenige Minuten', false, 2),
  ('ik-wiso-s-ausserordentliche-kuendigung-voraussetzung', 'Der bloße Ablauf der vereinbarten Probezeit', false, 3),
  -- ik-wiso-m-kuendigungsgruende-kschg
  ('ik-wiso-m-kuendigungsgruende-kschg', 'Personenbedingte Gründe, etwa dauerhafte Krankheit', true, 0),
  ('ik-wiso-m-kuendigungsgruende-kschg', 'Verhaltensbedingte Gründe, etwa wiederholte Pflichtverletzungen', true, 1),
  ('ik-wiso-m-kuendigungsgruende-kschg', 'Betriebsbedingte Gründe, etwa Wegfall des Arbeitsplatzes', true, 2),
  ('ik-wiso-m-kuendigungsgruende-kschg', 'Der bloße Wunsch nach jüngerem Personal', false, 3),
  -- ik-wiso-s-abmahnung-funktion
  ('ik-wiso-s-abmahnung-funktion', 'Rüge eines Fehlverhaltens mit Aufforderung zu künftig vertragsgemäßem Verhalten', true, 0),
  ('ik-wiso-s-abmahnung-funktion', 'Sofortige Beendigung des Arbeitsverhältnisses', false, 1),
  ('ik-wiso-s-abmahnung-funktion', 'Automatische Kürzung des Gehalts im Folgemonat', false, 2),
  ('ik-wiso-s-abmahnung-funktion', 'Verlängerung der vereinbarten Kündigungsfrist', false, 3),
  -- ik-wiso-m-elternzeit-anspruch
  ('ik-wiso-m-elternzeit-anspruch', 'Der Anspruch besteht grundsätzlich bis zur Vollendung des dritten Lebensjahres des Kindes', true, 0),
  ('ik-wiso-m-elternzeit-anspruch', 'Ein Anteil kann mit Zustimmung des Arbeitgebers auf einen späteren Zeitraum übertragen werden', true, 1),
  ('ik-wiso-m-elternzeit-anspruch', 'Während der Elternzeit besteht ein besonderer Kündigungsschutz', true, 2),
  ('ik-wiso-m-elternzeit-anspruch', 'Beide Elternteile müssen die Elternzeit stets gleichzeitig nehmen', false, 3),
  ('ik-wiso-m-elternzeit-anspruch', 'Elternzeit darf nur an einem Stück und nicht in Teilabschnitten genommen werden', false, 4),
  -- ik-wiso-s-arbeitszeugnis-wohlwollend
  ('ik-wiso-s-arbeitszeugnis-wohlwollend', 'Es muss wahr und zugleich wohlwollend formuliert sein', true, 0),
  ('ik-wiso-s-arbeitszeugnis-wohlwollend', 'Es darf ausschließlich positive Aussagen enthalten', false, 1),
  ('ik-wiso-s-arbeitszeugnis-wohlwollend', 'Es muss jede Fehlzeit einzeln auflisten', false, 2),
  ('ik-wiso-s-arbeitszeugnis-wohlwollend', 'Es ist rechtlich unverbindlich und ohne Wahrheitspflicht', false, 3),
  -- ik-wiso-m-urlaub-grundsaetze
  ('ik-wiso-m-urlaub-grundsaetze', 'Urlaub darf während des laufenden Arbeitsverhältnisses grundsätzlich nicht durch Geld ersetzt werden', true, 0),
  ('ik-wiso-m-urlaub-grundsaetze', 'Nicht genommener Urlaub wird bei Beendigung des Arbeitsverhältnisses abgegolten', true, 1),
  ('ik-wiso-m-urlaub-grundsaetze', 'Der gesetzliche Urlaubsanspruch besteht unabhängig von der Betriebsgröße', true, 2),
  ('ik-wiso-m-urlaub-grundsaetze', 'Urlaub kann beliebig in das übernächste Kalenderjahr verschoben werden', false, 3),
  -- ik-wiso-s-nachtarbeit-zuschlag
  ('ik-wiso-s-nachtarbeit-zuschlag', 'Angemessener Ausgleich durch bezahlte Freizeit oder einen Zuschlag', true, 0),
  ('ik-wiso-s-nachtarbeit-zuschlag', 'Verdopplung der regulären Wochenarbeitszeit', false, 1),
  ('ik-wiso-s-nachtarbeit-zuschlag', 'Automatische Umwandlung in ein unbefristetes Arbeitsverhältnis', false, 2),
  ('ik-wiso-s-nachtarbeit-zuschlag', 'Ein zusätzlicher gesetzlicher Jahresurlaubstag pro Monat Nachtarbeit', false, 3),
  -- ik-wiso-m-befristung-sachgrundlos
  ('ik-wiso-m-befristung-sachgrundlos', 'Sie ist bis zu einer Gesamtdauer von zwei Jahren zulässig', true, 0),
  ('ik-wiso-m-befristung-sachgrundlos', 'Eine Verlängerung ist innerhalb dieser Zeit höchstens dreimal möglich', true, 1),
  ('ik-wiso-m-befristung-sachgrundlos', 'Voraussetzung ist, dass zuvor kein Arbeitsverhältnis mit demselben Arbeitgeber bestand', true, 2),
  ('ik-wiso-m-befristung-sachgrundlos', 'Sie kann beliebig oft um jeweils zwei weitere Jahre verlängert werden', false, 3),
  ('ik-wiso-m-befristung-sachgrundlos', 'Sie erfordert stets die Zustimmung des Betriebsrats im Einzelfall', false, 4),
  -- ik-wiso-m-teilzeitanspruch-voraussetzung
  ('ik-wiso-m-teilzeitanspruch-voraussetzung', 'Der Betrieb beschäftigt in der Regel mehr als 15 Arbeitnehmer', true, 0),
  ('ik-wiso-m-teilzeitanspruch-voraussetzung', 'Das Arbeitsverhältnis besteht bereits länger als sechs Monate', true, 1),
  ('ik-wiso-m-teilzeitanspruch-voraussetzung', 'Der Antrag wird rechtzeitig vor dem gewünschten Beginn gestellt', true, 2),
  ('ik-wiso-m-teilzeitanspruch-voraussetzung', 'Der Arbeitnehmer ist seit mindestens zehn Jahren im Betrieb beschäftigt', false, 3),
  ('ik-wiso-m-teilzeitanspruch-voraussetzung', 'Der Arbeitgeber muss der Verringerung unabhängig von betrieblichen Gründen stets zustimmen', false, 4),
  -- ik-wiso-s-tarifautonomie-begriff
  ('ik-wiso-s-tarifautonomie-begriff', 'Eigenständiges Aushandeln von Löhnen und Arbeitsbedingungen ohne staatliche Einmischung', true, 0),
  ('ik-wiso-s-tarifautonomie-begriff', 'Die Festlegung von Löhnen ausschließlich durch den Gesetzgeber', false, 1),
  ('ik-wiso-s-tarifautonomie-begriff', 'Das Recht jedes einzelnen Arbeitnehmers, seinen eigenen Tarifvertrag zu schließen', false, 2),
  ('ik-wiso-s-tarifautonomie-begriff', 'Die verpflichtende Genehmigung von Tarifverträgen durch die Bundesregierung', false, 3),
  -- ik-wiso-m-tarifvertrag-wirkung
  ('ik-wiso-m-tarifvertrag-wirkung', 'Unmittelbare und zwingende Wirkung für tarifgebundene Parteien', true, 0),
  ('ik-wiso-m-tarifvertrag-wirkung', 'Mögliche Erstreckung auf nicht organisierte Betriebe durch Allgemeinverbindlicherklärung', true, 1),
  ('ik-wiso-m-tarifvertrag-wirkung', 'Abweichung zugunsten des Arbeitnehmers ist einzelvertraglich zulässig', true, 2),
  ('ik-wiso-m-tarifvertrag-wirkung', 'Abweichung zulasten des Arbeitnehmers ist einzelvertraglich ohne Weiteres zulässig', false, 3),
  -- ik-wiso-s-jav-aufgabe
  ('ik-wiso-s-jav-aufgabe', 'Vertretung der Interessen jugendlicher und auszubildender Beschäftigter gegenüber Betriebsrat und Arbeitgeber', true, 0),
  ('ik-wiso-s-jav-aufgabe', 'Eigenständiger Abschluss von Betriebsvereinbarungen', false, 1),
  ('ik-wiso-s-jav-aufgabe', 'Festsetzung der Ausbildungsvergütung im Betrieb', false, 2),
  ('ik-wiso-s-jav-aufgabe', 'Durchführung der IHK-Abschlussprüfungen', false, 3),
  -- ik-wiso-m-betriebsrat-wahlvoraussetzung
  ('ik-wiso-m-betriebsrat-wahlvoraussetzung', 'In der Regel mindestens fünf wahlberechtigte Arbeitnehmer im Betrieb', true, 0),
  ('ik-wiso-m-betriebsrat-wahlvoraussetzung', 'Mindestens drei davon müssen wählbar sein', true, 1),
  ('ik-wiso-m-betriebsrat-wahlvoraussetzung', 'Eine bestimmte Rechtsform des Unternehmens ist nicht vorgeschrieben', true, 2),
  ('ik-wiso-m-betriebsrat-wahlvoraussetzung', 'Der Betrieb muss börsennotiert sein', false, 3),
  -- ik-wiso-s-streikrecht-traeger
  ('ik-wiso-s-streikrecht-traeger', 'Die Gewerkschaften', true, 0),
  ('ik-wiso-s-streikrecht-traeger', 'Der einzelne Arbeitnehmer allein', false, 1),
  ('ik-wiso-s-streikrecht-traeger', 'Der Betriebsrat', false, 2),
  ('ik-wiso-s-streikrecht-traeger', 'Die zuständige Industrie- und Handelskammer', false, 3),
  -- ik-wiso-s-friedenspflicht-tarif
  ('ik-wiso-s-friedenspflicht-tarif', 'Bereits tariflich geregelte Punkte dürfen während der Laufzeit nicht bestreikt werden', true, 0),
  ('ik-wiso-s-friedenspflicht-tarif', 'Während der Laufzeit ist jeder Streik im Betrieb ausnahmslos verboten', false, 1),
  ('ik-wiso-s-friedenspflicht-tarif', 'Sie verbietet dem Arbeitgeber jede betriebsbedingte Kündigung', false, 2),
  ('ik-wiso-s-friedenspflicht-tarif', 'Sie gilt nur für Gewerkschaftsmitglieder, nicht für den Arbeitgeber', false, 3),
  -- ik-wiso-s-solidaritaetsprinzip
  ('ik-wiso-s-solidaritaetsprinzip', 'Beiträge nach Leistungsfähigkeit, Leistungen nach individuellem Bedarf', true, 0),
  ('ik-wiso-s-solidaritaetsprinzip', 'Beiträge und Leistungen sind stets exakt gleich hoch', false, 1),
  ('ik-wiso-s-solidaritaetsprinzip', 'Nur wer einzahlt, erhält später überhaupt eine Leistung', false, 2),
  ('ik-wiso-s-solidaritaetsprinzip', 'Der Staat übernimmt sämtliche Beiträge aus Steuermitteln', false, 3),
  -- ik-wiso-m-pflichtversicherung-zweige
  ('ik-wiso-m-pflichtversicherung-zweige', 'Krankenversicherung', true, 0),
  ('ik-wiso-m-pflichtversicherung-zweige', 'Rentenversicherung', true, 1),
  ('ik-wiso-m-pflichtversicherung-zweige', 'Unfallversicherung', true, 2),
  ('ik-wiso-m-pflichtversicherung-zweige', 'Private Haftpflichtversicherung', false, 3),
  -- ik-wiso-m-versicherungsprinzip-abgrenzung
  ('ik-wiso-m-versicherungsprinzip-abgrenzung', 'Die Höhe mancher Leistungen, etwa der Rente, hängt von der Höhe der eingezahlten Beiträge ab', true, 0),
  ('ik-wiso-m-versicherungsprinzip-abgrenzung', 'Es steht im Gegensatz zum Solidaritätsprinzip, das unabhängig von der Beitragshöhe ausgleicht', true, 1),
  ('ik-wiso-m-versicherungsprinzip-abgrenzung', 'Beide Prinzipien wirken in der gesetzlichen Rentenversicherung nebeneinander', true, 2),
  ('ik-wiso-m-versicherungsprinzip-abgrenzung', 'Alle Versicherten erhalten nach dem Versicherungsprinzip unabhängig von ihren Beiträgen dieselbe Leistung', false, 3),
  ('ik-wiso-m-versicherungsprinzip-abgrenzung', 'Das Versicherungsprinzip gilt ausschließlich in der privaten Krankenversicherung', false, 4),
  -- ik-wiso-s-pflegeversicherung-einfuehrung
  ('ik-wiso-s-pflegeversicherung-einfuehrung', 'Teilweise Absicherung des finanziellen Risikos der Pflegebedürftigkeit', true, 0),
  ('ik-wiso-s-pflegeversicherung-einfuehrung', 'Vollständige Übernahme sämtlicher Pflegekosten', false, 1),
  ('ik-wiso-s-pflegeversicherung-einfuehrung', 'Absicherung ausschließlich für Beschäftigte über 60 Jahre', false, 2),
  ('ik-wiso-s-pflegeversicherung-einfuehrung', 'Ersatz der gesetzlichen Krankenversicherung', false, 3),
  -- ik-wiso-m-familienversicherung-kv
  ('ik-wiso-m-familienversicherung-kv', 'Ehepartner und Kinder ohne oder mit geringem eigenem Einkommen können beitragsfrei mitversichert werden', true, 0),
  ('ik-wiso-m-familienversicherung-kv', 'Die Mitversicherung ist an bestimmte Einkommensgrenzen der Angehörigen geknüpft', true, 1),
  ('ik-wiso-m-familienversicherung-kv', 'Sie entlastet Familien, weil für mitversicherte Angehörige kein eigener Beitrag anfällt', true, 2),
  ('ik-wiso-m-familienversicherung-kv', 'Jedes Familienmitglied muss unabhängig vom Einkommen einen eigenen Beitrag zahlen', false, 3),
  ('ik-wiso-m-familienversicherung-kv', 'Die Familienversicherung gilt nur für minderjährige Kinder, niemals für Ehepartner', false, 4),
  -- ik-wiso-m-arbeitslosengeld-grundlage
  ('ik-wiso-m-arbeitslosengeld-grundlage', 'Erfüllung der Anwartschaftszeit durch sozialversicherungspflichtige Beschäftigung', true, 0),
  ('ik-wiso-m-arbeitslosengeld-grundlage', 'Persönliche Arbeitslosmeldung bei der Agentur für Arbeit', true, 1),
  ('ik-wiso-m-arbeitslosengeld-grundlage', 'Verfügbarkeit für die Arbeitsvermittlung', true, 2),
  ('ik-wiso-m-arbeitslosengeld-grundlage', 'Ein Mindestalter von 50 Jahren', false, 3),
  ('ik-wiso-m-arbeitslosengeld-grundlage', 'Der Nachweis eines Universitätsabschlusses', false, 4),
  -- ik-wiso-s-einkommensteuer-progression
  ('ik-wiso-s-einkommensteuer-progression', 'Der Grenzsteuersatz steigt mit zunehmendem zu versteuerndem Einkommen', true, 0),
  ('ik-wiso-s-einkommensteuer-progression', 'Alle Einkommen werden unabhängig von der Höhe mit demselben Satz besteuert', false, 1),
  ('ik-wiso-s-einkommensteuer-progression', 'Der Steuersatz sinkt mit steigendem Einkommen', false, 2),
  ('ik-wiso-s-einkommensteuer-progression', 'Sie betrifft ausschließlich Kapitalerträge', false, 3),
  -- ik-wiso-m-direkte-vs-indirekte-steuern-beispiele
  ('ik-wiso-m-direkte-vs-indirekte-steuern-beispiele', 'Einkommensteuer', true, 0),
  ('ik-wiso-m-direkte-vs-indirekte-steuern-beispiele', 'Körperschaftsteuer', true, 1),
  ('ik-wiso-m-direkte-vs-indirekte-steuern-beispiele', 'Umsatzsteuer', false, 2),
  ('ik-wiso-m-direkte-vs-indirekte-steuern-beispiele', 'Energiesteuer', false, 3),
  -- ik-wiso-s-lohnsteuerklassen-zweck
  ('ik-wiso-s-lohnsteuerklassen-zweck', 'Steuerung der Höhe des monatlichen Lohnsteuerabzugs je nach Familienstand', true, 0),
  ('ik-wiso-s-lohnsteuerklassen-zweck', 'Endgültige und abschließende Festlegung der Jahressteuerschuld', false, 1),
  ('ik-wiso-s-lohnsteuerklassen-zweck', 'Bestimmung der Höhe der Sozialversicherungsbeiträge', false, 2),
  ('ik-wiso-s-lohnsteuerklassen-zweck', 'Einordnung der Berufsgruppe für die Rentenberechnung', false, 3),
  -- ik-wiso-s-gewerbesteuer-empfaenger
  ('ik-wiso-s-gewerbesteuer-empfaenger', 'Den Gemeinden', true, 0),
  ('ik-wiso-s-gewerbesteuer-empfaenger', 'Dem Bund', false, 1),
  ('ik-wiso-s-gewerbesteuer-empfaenger', 'Der Bundesagentur für Arbeit', false, 2),
  ('ik-wiso-s-gewerbesteuer-empfaenger', 'Ausschließlich der jeweiligen IHK', false, 3),
  -- ik-wiso-s-vorsteuerabzug-zweck
  ('ik-wiso-s-vorsteuerabzug-zweck', 'Verrechnung gezahlter und vereinnahmter Umsatzsteuer, damit Unternehmen nicht selbst belastet bleiben', true, 0),
  ('ik-wiso-s-vorsteuerabzug-zweck', 'Vollständige Befreiung von der Einkommensteuer', false, 1),
  ('ik-wiso-s-vorsteuerabzug-zweck', 'Automatische Reduzierung der Gewerbesteuer', false, 2),
  ('ik-wiso-s-vorsteuerabzug-zweck', 'Erstattung der Lohnsteuer der Beschäftigten', false, 3),
  -- ik-wiso-s-freibetrag-vs-freigrenze
  ('ik-wiso-s-freibetrag-vs-freigrenze', 'Beim Freibetrag bleibt nur der übersteigende Teil steuerpflichtig, bei der Freigrenze bei Überschreitung der gesamte Betrag', true, 0),
  ('ik-wiso-s-freibetrag-vs-freigrenze', 'Beide Begriffe bezeichnen exakt denselben Mechanismus', false, 1),
  ('ik-wiso-s-freibetrag-vs-freigrenze', 'Ein Freibetrag gilt nur für Unternehmen, eine Freigrenze nur für Privatpersonen', false, 2),
  ('ik-wiso-s-freibetrag-vs-freigrenze', 'Eine Freigrenze lässt stets den übersteigenden Teil steuerfrei', false, 3),
  -- ik-wiso-s-soziale-marktwirtschaft-idee
  ('ik-wiso-s-soziale-marktwirtschaft-idee', 'Freier Wettbewerb kombiniert mit staatlichem sozialem Ausgleich', true, 0),
  ('ik-wiso-s-soziale-marktwirtschaft-idee', 'Vollständige zentrale Steuerung von Preisen und Produktion durch den Staat', false, 1),
  ('ik-wiso-s-soziale-marktwirtschaft-idee', 'Ein Markt vollständig ohne jede staatliche Regulierung', false, 2),
  ('ik-wiso-s-soziale-marktwirtschaft-idee', 'Verstaatlichung aller Schlüsselindustrien', false, 3),
  -- ik-wiso-m-marktwirtschaft-planwirtschaft-merkmale
  ('ik-wiso-m-marktwirtschaft-planwirtschaft-merkmale', 'Preise entstehen dezentral über Angebot und Nachfrage', true, 0),
  ('ik-wiso-m-marktwirtschaft-planwirtschaft-merkmale', 'Produktionsmittel befinden sich überwiegend in privatem Eigentum', true, 1),
  ('ik-wiso-m-marktwirtschaft-planwirtschaft-merkmale', 'Eine zentrale Stelle legt Produktionsmengen und Preise verbindlich fest', false, 2),
  ('ik-wiso-m-marktwirtschaft-planwirtschaft-merkmale', 'Unternehmensgründungen sind grundsätzlich genehmigungspflichtig durch den Staat', false, 3),
  -- ik-wiso-s-nachfrageverschiebung-einkommen
  ('ik-wiso-s-nachfrageverschiebung-einkommen', 'Die Nachfragekurve verschiebt sich bei gleichem Preis nach rechts', true, 0),
  ('ik-wiso-s-nachfrageverschiebung-einkommen', 'Die Nachfragekurve verschiebt sich bei gleichem Preis nach links', false, 1),
  ('ik-wiso-s-nachfrageverschiebung-einkommen', 'Der Preis des Gutes sinkt automatisch auf null', false, 2),
  ('ik-wiso-s-nachfrageverschiebung-einkommen', 'Angebot und Nachfrage bleiben in jedem Fall unverändert', false, 3),
  -- ik-wiso-s-substitutionsgueter-beispiel
  ('ik-wiso-s-substitutionsgueter-beispiel', 'Güter, die sich gegenseitig ersetzen können, sodass ein Preisanstieg beim einen die Nachfrage nach dem anderen erhöht', true, 0),
  ('ik-wiso-s-substitutionsgueter-beispiel', 'Güter, die nur gemeinsam sinnvoll genutzt werden können', false, 1),
  ('ik-wiso-s-substitutionsgueter-beispiel', 'Güter, deren Preis staatlich festgelegt wird', false, 2),
  ('ik-wiso-s-substitutionsgueter-beispiel', 'Güter, die nur im Außenhandel gehandelt werden dürfen', false, 3),
  -- ik-wiso-s-wirtschaftskreislauf-akteure
  ('ik-wiso-s-wirtschaftskreislauf-akteure', 'Private Haushalte und Unternehmen', true, 0),
  ('ik-wiso-s-wirtschaftskreislauf-akteure', 'Staat und Ausland', false, 1),
  ('ik-wiso-s-wirtschaftskreislauf-akteure', 'Banken und Versicherungen', false, 2),
  ('ik-wiso-s-wirtschaftskreislauf-akteure', 'Gewerkschaften und Arbeitgeberverbände', false, 3),
  -- ik-wiso-m-konjunkturindikatoren
  ('ik-wiso-m-konjunkturindikatoren', 'Auftragseingänge der Industrie', true, 0),
  ('ik-wiso-m-konjunkturindikatoren', 'Arbeitslosenquote', true, 1),
  ('ik-wiso-m-konjunkturindikatoren', 'Bruttoinlandsprodukt', true, 2),
  ('ik-wiso-m-konjunkturindikatoren', 'Anzahl der gesetzlichen Feiertage im Jahr', false, 3),
  -- ik-wiso-s-inflation-messung
  ('ik-wiso-s-inflation-messung', 'Mit dem Verbraucherpreisindex auf Basis eines repräsentativen Warenkorbs', true, 0),
  ('ik-wiso-s-inflation-messung', 'Mit der Summe aller im Land gezahlten Löhne', false, 1),
  ('ik-wiso-s-inflation-messung', 'Mit dem aktuellen Leitzins der Zentralbank', false, 2),
  ('ik-wiso-s-inflation-messung', 'Mit der Zahl der Unternehmensinsolvenzen', false, 3),
  -- ik-wiso-s-deflation-risiko
  ('ik-wiso-s-deflation-risiko', 'Aufgeschobene Käufe und rückläufige Investitionen mit möglicher Abwärtsspirale', true, 0),
  ('ik-wiso-s-deflation-risiko', 'Eine automatische Erhöhung der Reallöhne ohne weitere Folgen', false, 1),
  ('ik-wiso-s-deflation-risiko', 'Ein sofortiger Anstieg der Exportquote ohne Nachteile', false, 2),
  ('ik-wiso-s-deflation-risiko', 'Eine garantierte Vollbeschäftigung', false, 3),
  -- ik-wiso-s-zieldreieck-erweitert
  ('ik-wiso-s-zieldreieck-erweitert', 'Stetiges und angemessenes Wirtschaftswachstum', true, 0),
  ('ik-wiso-s-zieldreieck-erweitert', 'Vollständige Abschaffung der Staatsverschuldung', false, 1),
  ('ik-wiso-s-zieldreieck-erweitert', 'Gerechte Einkommensverteilung als viertes eigenständiges Ziel', false, 2),
  ('ik-wiso-s-zieldreieck-erweitert', 'Freihandel mit allen Staaten der Welt', false, 3),
  -- ik-wiso-s-monopol-merkmal
  ('ik-wiso-s-monopol-merkmal', 'Ein einziger Anbieter steht vielen Nachfragern gegenüber', true, 0),
  ('ik-wiso-s-monopol-merkmal', 'Viele Anbieter stehen einem einzigen Nachfrager gegenüber', false, 1),
  ('ik-wiso-s-monopol-merkmal', 'Zwei etwa gleich große Anbieter teilen sich den Markt', false, 2),
  ('ik-wiso-s-monopol-merkmal', 'Der Staat legt den Preis unabhängig vom Anbieter fest', false, 3),
  -- ik-wiso-s-einzelunternehmen-merkmal
  ('ik-wiso-s-einzelunternehmen-merkmal', 'Alleinige Entscheidungsgewalt und unbeschränkte persönliche Haftung des Inhabers', true, 0),
  ('ik-wiso-s-einzelunternehmen-merkmal', 'Beschränkung der Haftung auf das eingebrachte Kapital', false, 1),
  ('ik-wiso-s-einzelunternehmen-merkmal', 'Verpflichtendes Mindestkapital von 25.000 Euro', false, 2),
  ('ik-wiso-s-einzelunternehmen-merkmal', 'Verpflichtende Bestellung eines Aufsichtsrats', false, 3),
  -- ik-wiso-m-gmbh-merkmale
  ('ik-wiso-m-gmbh-merkmale', 'Die Haftung ist grundsätzlich auf das Gesellschaftsvermögen beschränkt', true, 0),
  ('ik-wiso-m-gmbh-merkmale', 'Die Gründung erfordert ein Stammkapital und einen notariell beurkundeten Vertrag', true, 1),
  ('ik-wiso-m-gmbh-merkmale', 'Eine Gründung durch nur eine Person ist zulässig', true, 2),
  ('ik-wiso-m-gmbh-merkmale', 'Alle Gesellschafter haften stets zusätzlich mit ihrem Privatvermögen', false, 3),
  -- ik-wiso-s-ug-haftungsbeschraenkt-zweck
  ('ik-wiso-s-ug-haftungsbeschraenkt-zweck', 'Gründung mit beschränkter Haftung schon bei geringem Startkapital, mit Pflicht zur Rücklagenbildung', true, 0),
  ('ik-wiso-s-ug-haftungsbeschraenkt-zweck', 'Vollständige Befreiung von jeder Kapitalpflicht dauerhaft', false, 1),
  ('ik-wiso-s-ug-haftungsbeschraenkt-zweck', 'Unbeschränkte persönliche Haftung aller Gesellschafter', false, 2),
  ('ik-wiso-s-ug-haftungsbeschraenkt-zweck', 'Verpflichtender Börsengang innerhalb von zwei Jahren', false, 3),
  -- ik-wiso-s-genossenschaft-prinzip
  ('ik-wiso-s-genossenschaft-prinzip', 'Förderung der Mitglieder durch gemeinschaftlichen Geschäftsbetrieb', true, 0),
  ('ik-wiso-s-genossenschaft-prinzip', 'Maximierung der Gewinnausschüttung an externe Kapitalgeber', false, 1),
  ('ik-wiso-s-genossenschaft-prinzip', 'Vollständige staatliche Kontrolle der Geschäftsführung', false, 2),
  ('ik-wiso-s-genossenschaft-prinzip', 'Verpflichtende Börsennotierung', false, 3),
  -- ik-wiso-s-aktiengesellschaft-organe
  ('ik-wiso-s-aktiengesellschaft-organe', 'Der Aufsichtsrat', true, 0),
  ('ik-wiso-s-aktiengesellschaft-organe', 'Die Hauptversammlung allein im Tagesgeschäft', false, 1),
  ('ik-wiso-s-aktiengesellschaft-organe', 'Der Betriebsrat', false, 2),
  ('ik-wiso-s-aktiengesellschaft-organe', 'Die zuständige IHK', false, 3),
  -- ik-wiso-m-gbr-ohg-abgrenzung
  ('ik-wiso-m-gbr-ohg-abgrenzung', 'Die OHG betreibt stets ein Handelsgewerbe unter gemeinsamer Firma', true, 0),
  ('ik-wiso-m-gbr-ohg-abgrenzung', 'Die OHG wird ins Handelsregister eingetragen, die GbR grundsätzlich nicht', true, 1),
  ('ik-wiso-m-gbr-ohg-abgrenzung', 'In beiden Formen haften die Gesellschafter grundsätzlich persönlich', true, 2),
  ('ik-wiso-m-gbr-ohg-abgrenzung', 'Nur die GbR kann ein Handelsgewerbe betreiben, die OHG nicht', false, 3),
  -- ik-wiso-m-handelsregister-publizitaet
  ('ik-wiso-m-handelsregister-publizitaet', 'Wer auf eingetragene und bekannt gemachte Angaben vertraut, wird grundsätzlich geschützt', true, 0),
  ('ik-wiso-m-handelsregister-publizitaet', 'Das Handelsregister ist für jedermann öffentlich einsehbar', true, 1),
  ('ik-wiso-m-handelsregister-publizitaet', 'Änderungen wie ein Geschäftsführerwechsel müssen zur Eintragung angemeldet werden', true, 2),
  ('ik-wiso-m-handelsregister-publizitaet', 'Eingetragene Daten werden nach zwei Jahren automatisch gelöscht', false, 3),
  ('ik-wiso-m-handelsregister-publizitaet', 'Nur Behörden dürfen Einsicht in das Handelsregister nehmen', false, 4),
  -- ik-wiso-s-kapitalgesellschaft-vorteil
  ('ik-wiso-s-kapitalgesellschaft-vorteil', 'Begrenzung des persönlichen Haftungsrisikos der Gesellschafter auf das Kapital der Gesellschaft', true, 0),
  ('ik-wiso-s-kapitalgesellschaft-vorteil', 'Vollständiger Wegfall jeder Buchführungspflicht', false, 1),
  ('ik-wiso-s-kapitalgesellschaft-vorteil', 'Automatische Befreiung von der Gewerbesteuer', false, 2),
  ('ik-wiso-s-kapitalgesellschaft-vorteil', 'Kein Mindestkapital in jedem Fall notwendig', false, 3),
  -- ik-wiso-s-prokura-erteilung
  ('ik-wiso-s-prokura-erteilung', 'Nur der Geschäftsinhaber oder sein gesetzlicher Vertreter', true, 0),
  ('ik-wiso-s-prokura-erteilung', 'Jeder bereits bestellte Prokurist an weitere Mitarbeiter', false, 1),
  ('ik-wiso-s-prokura-erteilung', 'Der Betriebsrat des Unternehmens', false, 2),
  ('ik-wiso-s-prokura-erteilung', 'Die zuständige Industrie- und Handelskammer', false, 3),
  -- ik-wiso-s-vertragsfreiheit-grenzen
  ('ik-wiso-s-vertragsfreiheit-grenzen', 'Zwingende gesetzliche Vorschriften, etwa zum Verbraucherschutz', true, 0),
  ('ik-wiso-s-vertragsfreiheit-grenzen', 'Sie kennt in Deutschland keinerlei rechtliche Grenzen', false, 1),
  ('ik-wiso-s-vertragsfreiheit-grenzen', 'Nur mündliche Absprachen dürfen begrenzt werden', false, 2),
  ('ik-wiso-s-vertragsfreiheit-grenzen', 'Sie gilt ausschließlich für Verträge zwischen Unternehmen', false, 3),
  -- ik-wiso-m-willenserklaerung-merkmale
  ('ik-wiso-m-willenserklaerung-merkmale', 'Sie zielt auf die Herbeiführung einer bestimmten Rechtsfolge', true, 0),
  ('ik-wiso-m-willenserklaerung-merkmale', 'Sie kann auch durch schlüssiges Verhalten abgegeben werden', true, 1),
  ('ik-wiso-m-willenserklaerung-merkmale', 'Bloßes Schweigen gilt im Regelfall nicht als Zustimmung', true, 2),
  ('ik-wiso-m-willenserklaerung-merkmale', 'Sie ist immer nur in notarieller Form wirksam', false, 3),
  -- ik-wiso-s-verzug-rechtsfolge-schaden
  ('ik-wiso-s-verzug-rechtsfolge-schaden', 'Verzugszinsen und Ersatz eines nachgewiesenen weiteren Verzugsschadens', true, 0),
  ('ik-wiso-s-verzug-rechtsfolge-schaden', 'Automatische Auflösung des Kaufvertrags ohne weiteres Zutun', false, 1),
  ('ik-wiso-s-verzug-rechtsfolge-schaden', 'Sofortige strafrechtliche Anzeige gegen den Käufer', false, 2),
  ('ik-wiso-s-verzug-rechtsfolge-schaden', 'Der Anspruch auf den Kaufpreis erlischt vollständig', false, 3),
  -- ik-wiso-m-widerrufsausnahmen
  ('ik-wiso-m-widerrufsausnahmen', 'Nach Kundenwunsch individuell angefertigte Waren', true, 0),
  ('ik-wiso-m-widerrufsausnahmen', 'Schnell verderbliche Waren', true, 1),
  ('ik-wiso-m-widerrufsausnahmen', 'Der Kauf eines standardmäßig vorrätigen Fernsehgeräts im Onlineshop', false, 2),
  ('ik-wiso-m-widerrufsausnahmen', 'Der Kauf eines vorrätigen Werkzeugsets im Onlineshop', false, 3),
  -- ik-wiso-m-garantie-gewaehrleistung-unterschied
  ('ik-wiso-m-garantie-gewaehrleistung-unterschied', 'Die Gewährleistung ist gesetzlich vorgeschrieben und trifft den Verkäufer', true, 0),
  ('ik-wiso-m-garantie-gewaehrleistung-unterschied', 'Die Garantie ist eine freiwillige Zusatzzusage, deren Inhalt der Garantiegeber frei festlegen kann', true, 1),
  ('ik-wiso-m-garantie-gewaehrleistung-unterschied', 'Beide Ansprüche können nebeneinander bestehen und schließen sich nicht gegenseitig aus', true, 2),
  ('ik-wiso-m-garantie-gewaehrleistung-unterschied', 'Eine Garantie ersetzt in jedem Fall die gesetzliche Gewährleistung vollständig', false, 3),
  ('ik-wiso-m-garantie-gewaehrleistung-unterschied', 'Die Gewährleistungsfrist kann vom Verkäufer bei neuer Ware beliebig verkürzt werden', false, 4),
  -- ik-wiso-m-agb-einbeziehung
  ('ik-wiso-m-agb-einbeziehung', 'Der Verwender muss bei Vertragsschluss ausdrücklich auf die AGB hinweisen', true, 0),
  ('ik-wiso-m-agb-einbeziehung', 'Die andere Vertragspartei muss in zumutbarer Weise Kenntnis vom Inhalt nehmen können', true, 1),
  ('ik-wiso-m-agb-einbeziehung', 'Überraschende Klauseln werden trotz Einbeziehung der AGB automatisch wirksam', false, 2),
  ('ik-wiso-m-agb-einbeziehung', 'Ein einmaliger Aushang im Betrieb vor Jahren genügt für alle künftigen Verträge', false, 3),
  -- ik-wiso-m-mangel-begriff
  ('ik-wiso-m-mangel-begriff', 'Die Kaufsache weicht bei Gefahrübergang von der vereinbarten Beschaffenheit ab', true, 0),
  ('ik-wiso-m-mangel-begriff', 'Die Kaufsache eignet sich nicht für die gewöhnliche Verwendung', true, 1),
  ('ik-wiso-m-mangel-begriff', 'Der Käufer ist mit dem vereinbarten Kaufpreis schlicht unzufrieden', false, 2),
  ('ik-wiso-m-mangel-begriff', 'Die Ware trifft verspätet beim Käufer ein', false, 3),
  -- ik-wiso-s-sepa-ueberweisung-frist
  ('ik-wiso-s-sepa-ueberweisung-frist', 'Spätestens am nächsten Bankgeschäftstag nach Auftragserteilung', true, 0),
  ('ik-wiso-s-sepa-ueberweisung-frist', 'Innerhalb von zwei Wochen nach Auftragserteilung', false, 1),
  ('ik-wiso-s-sepa-ueberweisung-frist', 'Nur am letzten Werktag des jeweiligen Monats', false, 2),
  ('ik-wiso-s-sepa-ueberweisung-frist', 'Es gibt dafür keine gesetzliche Frist', false, 3),
  -- ik-wiso-s-iban-funktion
  ('ik-wiso-s-iban-funktion', 'Eindeutige länderübergreifende Identifikation eines Bankkontos', true, 0),
  ('ik-wiso-s-iban-funktion', 'Verschlüsselung des Zahlungsverkehrs zwischen zwei Banken', false, 1),
  ('ik-wiso-s-iban-funktion', 'Festlegung des jeweils gültigen Wechselkurses', false, 2),
  ('ik-wiso-s-iban-funktion', 'Nachweis der Bonität des Kontoinhabers', false, 3),
  -- ik-wiso-m-bargeldloser-zahlungsverkehr-formen
  ('ik-wiso-m-bargeldloser-zahlungsverkehr-formen', 'Überweisung', true, 0),
  ('ik-wiso-m-bargeldloser-zahlungsverkehr-formen', 'Lastschrift', true, 1),
  ('ik-wiso-m-bargeldloser-zahlungsverkehr-formen', 'Barzahlung an der Kasse', false, 2),
  ('ik-wiso-m-bargeldloser-zahlungsverkehr-formen', 'Bareinzahlung am Schalter', false, 3),
  -- ik-wiso-s-skonto-berechnung
  ('ik-wiso-s-skonto-berechnung', 'Ein Preisnachlass für besonders schnelle Zahlung innerhalb der genannten Frist', true, 0),
  ('ik-wiso-s-skonto-berechnung', 'Ein fester Rabatt unabhängig vom Zahlungszeitpunkt', false, 1),
  ('ik-wiso-s-skonto-berechnung', 'Ein zusätzlicher Aufschlag bei später Zahlung', false, 2),
  ('ik-wiso-s-skonto-berechnung', 'Eine gesetzlich vorgeschriebene Mahngebühr', false, 3),
  -- ik-wiso-s-akkreditiv-funktion
  ('ik-wiso-s-akkreditiv-funktion', 'Bankzahlungszusage gegen Vorlage vereinbarter Dokumente zur Absicherung beider Handelspartner', true, 0),
  ('ik-wiso-s-akkreditiv-funktion', 'Ein zinsloses Darlehen der Hausbank an den Importeur', false, 1),
  ('ik-wiso-s-akkreditiv-funktion', 'Eine staatliche Exportförderung ohne Bankbeteiligung', false, 2),
  ('ik-wiso-s-akkreditiv-funktion', 'Eine Versicherung gegen Produktionsausfall', false, 3),
  -- ik-wiso-s-eu-binnenmarkt-grundfreiheiten
  ('ik-wiso-s-eu-binnenmarkt-grundfreiheiten', 'Freier Verkehr von Waren, Dienstleistungen, Personen und Kapital', true, 0),
  ('ik-wiso-s-eu-binnenmarkt-grundfreiheiten', 'Freier Verkehr nur für Waren, alles andere bleibt reguliert', false, 1),
  ('ik-wiso-s-eu-binnenmarkt-grundfreiheiten', 'Einheitliche Steuersätze in allen Mitgliedstaaten', false, 2),
  ('ik-wiso-s-eu-binnenmarkt-grundfreiheiten', 'Gemeinsame Außenzölle ohne freien Binnenverkehr', false, 3),
  -- ik-wiso-m-globalisierung-chancen-risiken
  ('ik-wiso-m-globalisierung-chancen-risiken', 'Neue Absatzmärkte im Ausland eröffnen zusätzliche Umsatzchancen', true, 0),
  ('ik-wiso-m-globalisierung-chancen-risiken', 'Der Wettbewerbsdruck durch ausländische Anbieter steigt', true, 1),
  ('ik-wiso-m-globalisierung-chancen-risiken', 'Lieferketten werden anfälliger für internationale Störungen', true, 2),
  ('ik-wiso-m-globalisierung-chancen-risiken', 'Der Wettbewerb um Fachkräfte wird dadurch automatisch geringer', false, 3),
  -- ik-wiso-s-euro-vorteil-binnenhandel
  ('ik-wiso-s-euro-vorteil-binnenhandel', 'Wegfall von Umrechnungs- und Wechselkursrisiken innerhalb der Eurozone', true, 0),
  ('ik-wiso-s-euro-vorteil-binnenhandel', 'Automatische Befreiung von der Umsatzsteuer', false, 1),
  ('ik-wiso-s-euro-vorteil-binnenhandel', 'Vollständiger Wegfall von Zöllen mit Nicht-EU-Staaten', false, 2),
  ('ik-wiso-s-euro-vorteil-binnenhandel', 'Garantierte einheitliche Löhne in allen Mitgliedstaaten', false, 3),
  -- ik-wiso-s-freihandelsabkommen-zweck
  ('ik-wiso-s-freihandelsabkommen-zweck', 'Abbau von Zöllen und anderen Handelshemmnissen zwischen den beteiligten Staaten', true, 0),
  ('ik-wiso-s-freihandelsabkommen-zweck', 'Einführung einheitlicher Steuersätze weltweit', false, 1),
  ('ik-wiso-s-freihandelsabkommen-zweck', 'Vollständige Abschaffung nationaler Währungen', false, 2),
  ('ik-wiso-s-freihandelsabkommen-zweck', 'Verpflichtende gemeinsame Sozialversicherung der beteiligten Staaten', false, 3),
  -- ik-wiso-m-dsgvo-rechtsgrundlage
  ('ik-wiso-m-dsgvo-rechtsgrundlage', 'Eine ausdrückliche Einwilligung der betroffenen Person', true, 0),
  ('ik-wiso-m-dsgvo-rechtsgrundlage', 'Die Erforderlichkeit zur Erfüllung eines Vertrags mit der betroffenen Person', true, 1),
  ('ik-wiso-m-dsgvo-rechtsgrundlage', 'Eine gesetzliche Verpflichtung des Unternehmens zur Verarbeitung', true, 2),
  ('ik-wiso-m-dsgvo-rechtsgrundlage', 'Das bloße wirtschaftliche Interesse, ohne dass ein Zweck benannt wird', false, 3),
  ('ik-wiso-m-dsgvo-rechtsgrundlage', 'Eine formlose mündliche Zusage ohne dokumentierten Zweck', false, 4),
  -- ik-wiso-s-datenschutzbeauftragter-pflicht
  ('ik-wiso-s-datenschutzbeauftragter-pflicht', 'Ab in der Regel mindestens 20 Personen in der automatisierten Datenverarbeitung', true, 0),
  ('ik-wiso-s-datenschutzbeauftragter-pflicht', 'Ab dem ersten Mitarbeiter des Unternehmens', false, 1),
  ('ik-wiso-s-datenschutzbeauftragter-pflicht', 'Erst ab 500 Mitarbeitern im gesamten Unternehmen', false, 2),
  ('ik-wiso-s-datenschutzbeauftragter-pflicht', 'Nur bei Unternehmen mit Sitz im Ausland', false, 3),
  -- ik-wiso-s-datenminimierung-grundsatz
  ('ik-wiso-s-datenminimierung-grundsatz', 'Nur für den Zweck tatsächlich erforderliche Daten dürfen erhoben werden', true, 0),
  ('ik-wiso-s-datenminimierung-grundsatz', 'Es dürfen möglichst viele Daten auf Vorrat gesammelt werden', false, 1),
  ('ik-wiso-s-datenminimierung-grundsatz', 'Er betrifft nur Daten von Minderjährigen', false, 2),
  ('ik-wiso-s-datenminimierung-grundsatz', 'Er verlangt die Löschung aller Daten nach 24 Stunden', false, 3),
  -- ik-wiso-m-nachhaltigkeit-drei-saeulen
  ('ik-wiso-m-nachhaltigkeit-drei-saeulen', 'Ökologische Dimension', true, 0),
  ('ik-wiso-m-nachhaltigkeit-drei-saeulen', 'Ökonomische Dimension', true, 1),
  ('ik-wiso-m-nachhaltigkeit-drei-saeulen', 'Soziale Dimension', true, 2),
  ('ik-wiso-m-nachhaltigkeit-drei-saeulen', 'Eine eigenständige rein rechtliche vierte Säule', false, 3),
  ('ik-wiso-m-nachhaltigkeit-drei-saeulen', 'Eine eigenständige rein politische vierte Säule', false, 4),
  -- ik-wiso-m-betriebliche-umweltmassnahmen
  ('ik-wiso-m-betriebliche-umweltmassnahmen', 'Rückgewinnung von Abwärme aus Produktionsprozessen', true, 0),
  ('ik-wiso-m-betriebliche-umweltmassnahmen', 'Konsequentes Recycling von Produktionsabfällen', true, 1),
  ('ik-wiso-m-betriebliche-umweltmassnahmen', 'Höhere Beleuchtungsstärke über den betrieblichen Bedarf hinaus', false, 2),
  ('ik-wiso-m-betriebliche-umweltmassnahmen', 'Verlängerung aller Transportwege ohne betrieblichen Grund', false, 3),
  -- ik-wiso-s-emissionshandel-prinzip
  ('ik-wiso-s-emissionshandel-prinzip', 'Handelbare, mengenmäßig begrenzte Zertifikate schaffen einen Anreiz zur Emissionssenkung', true, 0),
  ('ik-wiso-s-emissionshandel-prinzip', 'Jedes Unternehmen zahlt einen festen, für alle gleichen Betrag pro Jahr', false, 1),
  ('ik-wiso-s-emissionshandel-prinzip', 'Emissionen werden durch ein absolutes gesetzliches Verbot ab sofort verhindert', false, 2),
  ('ik-wiso-s-emissionshandel-prinzip', 'Zertifikate werden nur an staatliche Betriebe ausgegeben', false, 3),
  -- ik-wiso-s-erweiterte-produzentenverantwortung
  ('ik-wiso-s-erweiterte-produzentenverantwortung', 'Hersteller werden auch für Entsorgung und Verwertung ihrer Produkte mitverantwortlich gemacht', true, 0),
  ('ik-wiso-s-erweiterte-produzentenverantwortung', 'Sie überträgt die gesamte Entsorgungsverantwortung allein auf die Kommunen', false, 1),
  ('ik-wiso-s-erweiterte-produzentenverantwortung', 'Sie betrifft nur den Verkaufsprozess, nicht die spätere Entsorgung', false, 2),
  ('ik-wiso-s-erweiterte-produzentenverantwortung', 'Sie gilt ausschließlich für Lebensmittelhersteller', false, 3)
) as v(source_key, text, is_correct, sort_order)
on v.source_key = q.source_key;
