-- Kaufmännische Steuerung & Kontrolle: 75 neue, selbst geschriebene Fragen
-- für den Themenbereich der Prüfung Industriekaufmann/-frau (Exam-Slug
-- 'industriekaufmann'). 30 Fragen im Format 'multiple', 45 im Format
-- 'single'. Neue Exam-Reihe, daher keine Bestandsprüfung nötig, aber alle
-- source_keys sind innerhalb dieser Datei eindeutig geplant.
-- Abgedeckte Bereiche: Buchführung, Kosten- und Leistungsrechnung,
-- Controlling, Finanzierung, statische Investitionsrechnung, Steuern im
-- Betrieb, Jahresabschlussanalyse. 25 Fragen enthalten eine eigenständige
-- Berechnung, alle Zahlen wurden von Hand nachgerechnet.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'industriekaufmann'
join (values
  -- Mehrfachauswahl
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-inventur-arten',
   'Welche Aussagen zur Inventur treffen zu?',
   'Bei der körperlichen Inventur werden Bestände gezählt, gewogen oder gemessen, bei der Buchinventur werden Bestände aus Aufzeichnungen abgeleitet, etwa bei Forderungen. Die permanente Inventur erlaubt eine Bestandsaufnahme während des Jahres, wenn eine fortgeschriebene Lagerbuchführung existiert. Eine Inventur ist gesetzlich vorgeschrieben, nicht freiwillig.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-bilanz-aufbau',
   'Welche Aussagen zum Aufbau der Bilanz treffen zu?',
   'Die Aktivseite zeigt die Mittelverwendung, gegliedert nach Anlage- und Umlaufvermögen, die Passivseite die Mittelherkunft aus Eigen- und Fremdkapital. Beide Seiten sind stets gleich groß, weil jede Vermögensposition irgendwie finanziert sein muss. Das Anlagevermögen steht dabei vor dem Umlaufvermögen.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-guv-aufwand-ertrag',
   'Welche Aussagen zur Gewinn- und Verlustrechnung treffen zu?',
   'Die GuV stellt Erträge und Aufwendungen einer Periode gegenüber und ermittelt daraus den Periodenerfolg. Übersteigen die Erträge die Aufwendungen, entsteht ein Gewinn. Anders als die Bilanz zeigt sie keinen Bestand zu einem Stichtag, sondern eine Stromgröße über den Zeitraum.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-bestandskonten',
   'Welche Aussagen zu Bestandskonten treffen zu?',
   'Aktivkonten beginnen im Soll mit dem Anfangsbestand und mehren sich im Soll, Passivkonten beginnen im Haben und mehren sich im Haben. Der Schlussbestand steht jeweils auf der Seite, auf der sonst die Minderungen gebucht werden, damit beide Seiten ausgeglichen sind.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-erfolgskonten',
   'Welche Aussagen zu Erfolgskonten treffen zu?',
   'Aufwandskonten werden im Soll, Ertragskonten im Haben gebucht. Am Periodenende werden alle Erfolgskonten über das Gewinn- und Verlustkonto abgeschlossen, nicht direkt gegeneinander. Ein Aufwandskonto weist bei einem Habenüberschuss keinen sinnvollen Saldo aus, da Aufwand grundsätzlich im Soll steht.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-rueckstellungen',
   'Welche Aussagen zu Rückstellungen treffen zu?',
   'Rückstellungen werden gebildet, wenn eine Verpflichtung dem Grunde nach wahrscheinlich, aber hinsichtlich Höhe oder Fälligkeit noch ungewiss ist, etwa bei drohenden Prozesskosten. Sie werden als Fremdkapital passiviert und mindern über den Aufwand den Gewinn der Periode, in der sie gebildet werden.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-kostenarten',
   'Welche Aussagen zur Kostenartenrechnung treffen zu?',
   'Die Kostenartenrechnung beantwortet die Frage, welche Kosten in welcher Höhe angefallen sind, und unterscheidet unter anderem Personal-, Material- und Kapitalkosten. Einzelkosten lassen sich einem Kostenträger direkt zurechnen, Gemeinkosten nur über Schlüssel. Sie ist die erste Stufe vor Kostenstellen- und Kostenträgerrechnung.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-bab-prinzip',
   'Welche Aussagen zum Betriebsabrechnungsbogen (BAB) treffen zu?',
   'Der BAB verteilt Gemeinkosten mittels Verteilungsschlüsseln auf Kostenstellen und ermittelt daraus Zuschlagssätze für die Kalkulation. Einzelkosten werden im BAB nicht verteilt, weil sie bereits direkt zurechenbar sind. Er trennt üblicherweise Vorkostenstellen von Hauptkostenstellen.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-kostentraeger',
   'Welche Aussagen zur Kostenträgerrechnung treffen zu?',
   'Die Kostenträgerrechnung fragt, wofür Kosten angefallen sind, also für welches Produkt oder welche Leistung. Die Kostenträgerstückrechnung ist die Kalkulation eines einzelnen Erzeugnisses, die Kostenträgerzeitrechnung stellt Kosten und Leistungen einer Periode gegenüber. Sie baut auf den Ergebnissen von Kostenarten- und Kostenstellenrechnung auf.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-fixe-variable-kosten',
   'Welche Aussagen zu fixen und variablen Kosten treffen zu?',
   'Fixe Kosten fallen unabhängig von der Beschäftigung in gleicher Höhe an, etwa die Miete für die Fertigungshalle. Variable Kosten steigen mit der Ausbringungsmenge, müssen dabei aber nicht proportional verlaufen. Die Fixkosten je Stück sinken mit steigender Ausbringungsmenge, weil sie sich auf mehr Einheiten verteilen.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-deckungsbeitrag-konzept',
   'Welche Aussagen zur Deckungsbeitragsrechnung treffen zu?',
   'Der Deckungsbeitrag ergibt sich aus dem Verkaufspreis abzüglich der variablen Kosten je Stück. Er dient dazu, zunächst die Fixkosten zu decken, ein darüber hinausgehender Betrag ist Gewinn. Ein positiver Deckungsbeitrag bedeutet für sich genommen noch nicht, dass das Produkt insgesamt profitabel ist, solange die Fixkosten nicht gedeckt sind.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-zuschlagskalkulation-aufbau',
   'Welche Aussagen zur Zuschlagskalkulation treffen zu?',
   'Materialgemeinkosten werden auf die Materialeinzelkosten, Fertigungsgemeinkosten auf die Fertigungseinzelkosten aufgeschlagen. Verwaltungs- und Vertriebsgemeinkostenzuschläge beziehen sich auf die Herstellkosten. Der Zuschlagssatz wird zuvor im BAB ermittelt, nicht frei geschätzt.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-soll-ist-vergleich',
   'Welche Aussagen zum Soll-Ist-Vergleich im Controlling treffen zu?',
   'Der Soll-Ist-Vergleich stellt geplante und tatsächlich erreichte Werte gegenüber und macht Abweichungen sichtbar. Eine Abweichung allein sagt noch nicht, wodurch sie verursacht wurde, dafür ist eine Abweichungsanalyse nötig. Er dient auch dazu, künftige Planungen realistischer zu gestalten.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-kennzahlen-rentabilitaet',
   'Welche Aussagen zu Rentabilitätskennzahlen treffen zu?',
   'Die Eigenkapitalrentabilität setzt den Gewinn ins Verhältnis zum eingesetzten Eigenkapital. Die Umsatzrentabilität setzt den Gewinn ins Verhältnis zum Umsatz. Beide Kennzahlen werden meist in Prozent angegeben und eignen sich für einen Vergleich über mehrere Jahre oder mit Wettbewerbern.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-kennzahlen-liquiditaet',
   'Welche Aussagen zu Liquiditätskennzahlen treffen zu?',
   'Die Liquiditätsgrade setzen kurzfristig verfügbare Vermögenswerte ins Verhältnis zu den kurzfristigen Verbindlichkeiten. Je höher die Stufe, desto mehr Vermögenswerte fließen mit ein, von den flüssigen Mitteln über Forderungen bis zu den Vorräten. Eine Liquidität 1. Grades von deutlich unter 100 Prozent ist für sich genommen noch kein Zahlungsunfähigkeitsbeweis, da laufend neue Mittel zufließen.',
   4, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-budgetierung',
   'Welche Aussagen zur Budgetierung treffen zu?',
   'Ein Budget legt für einen künftigen Zeitraum geplante Kosten oder Erlöse fest und dient als Vorgabe für die operative Steuerung. Die Top-down-Budgetierung gibt Vorgaben von der Leitung an die Bereiche vor, die Bottom-up-Budgetierung sammelt Planzahlen aus den Bereichen ein. Budgets werden regelmäßig mit den Ist-Werten verglichen.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-eigenfinanzierung',
   'Welche Aussagen zur Eigenfinanzierung treffen zu?',
   'Eigenfinanzierung liegt vor, wenn Kapital von den Eigentümern oder aus einbehaltenen Gewinnen stammt. Eine Kapitalerhöhung durch Ausgabe neuer Aktien zählt ebenso dazu wie die Selbstfinanzierung aus thesaurierten Gewinnen. Eigenkapital haftet im Insolvenzfall, anders als die meisten Fremdkapitalpositionen, nachrangig.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-fremdfinanzierung',
   'Welche Aussagen zur Fremdfinanzierung treffen zu?',
   'Fremdkapital wird von außenstehenden Gläubigern zur Verfügung gestellt und muss unabhängig vom Geschäftserfolg zurückgezahlt und verzinst werden. Ein Bankdarlehen und ein Lieferantenkredit zählen beide dazu. Fremdkapitalgeber haben im Regelfall kein Mitspracherecht in der Geschäftsführung, anders als Eigenkapitalgeber.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-kreditarten',
   'Welche Aussagen zu Kreditarten treffen zu?',
   'Der Kontokorrentkredit dient der kurzfristigen Überbrückung von Liquiditätsengpässen und ist meist teurer als ein langfristiges Darlehen. Ein Investitionskredit ist auf die Finanzierung einer bestimmten Anschaffung ausgerichtet und läuft über deren Nutzungsdauer. Der Lieferantenkredit entsteht durch ein eingeräumtes Zahlungsziel.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-leasing-vs-kauf',
   'Welche Aussagen zum Vergleich von Leasing und Kauf treffen zu?',
   'Leasing schont die Liquidität, weil keine hohe Einmalzahlung anfällt, dafür fallen laufende Leasingraten an. Beim Kauf steht der Gegenstand meist im Anlagevermögen des Käufers und wird von ihm abgeschrieben, beim Operating-Leasing bleibt er in der Regel beim Leasinggeber. Über die gesamte Laufzeit ist Leasing nicht grundsätzlich günstiger als ein Kauf.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-liquiditaetsgrade-konzept',
   'Welche Aussagen zu den drei Liquiditätsgraden treffen zu?',
   'Die Liquidität 1. Grades berücksichtigt nur die flüssigen Mittel, die Liquidität 2. Grades zusätzlich die kurzfristigen Forderungen, die Liquidität 3. Grades zusätzlich die Vorräte. Mit jeder Stufe steigt der Kennzahlenwert normalerweise an, weil der Zähler um weitere Positionen ergänzt wird.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-investitionsrechnung-statisch-ueberblick',
   'Welche Aussagen zu den statischen Verfahren der Investitionsrechnung treffen zu?',
   'Kostenvergleichs-, Gewinnvergleichs-, Rentabilitäts- und Amortisationsrechnung arbeiten mit Durchschnittswerten einer Periode und berücksichtigen den Zeitpunkt einzelner Zahlungen nicht. Sie sind einfacher anzuwenden als dynamische Verfahren wie die Kapitalwertmethode, dafür ungenauer bei ungleichmäßigen Zahlungsströmen. Kalkulatorische Zinsen werden dennoch in mehreren dieser Verfahren berücksichtigt.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-amortisationsrechnung-konzept',
   'Welche Aussagen zur statischen Amortisationsrechnung treffen zu?',
   'Sie ermittelt, nach welcher Zeit die Anschaffungsauszahlung durch die jährlichen Rückflüsse wieder hereingeholt ist. Als Rückfluss gelten dabei Gewinn und Abschreibung zusammen, weil die Abschreibung keine Auszahlung darstellt. Eine kürzere Amortisationszeit gilt bei sonst gleichen Bedingungen als vorteilhafter, weil das gebundene Kapital schneller wieder verfügbar ist.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-umsatzsteuer-vorsteuer',
   'Welche Aussagen zu Umsatzsteuer und Vorsteuer treffen zu?',
   'Die Umsatzsteuer wird auf eigene Ausgangsleistungen erhoben und an das Finanzamt abgeführt. Die Vorsteuer aus Eingangsrechnungen kann ein vorsteuerabzugsberechtigtes Unternehmen gegenrechnen. Für das Unternehmen selbst ist die Umsatzsteuer wirtschaftlich neutral, sie wird letztlich vom Endverbraucher getragen.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-gewerbesteuer',
   'Welche Aussagen zur Gewerbesteuer treffen zu?',
   'Die Gewerbesteuer wird von den Gemeinden erhoben und knüpft an den Gewerbeertrag an. Ihre Höhe hängt vom individuellen Hebesatz der jeweiligen Gemeinde ab, weshalb sie sich örtlich unterscheidet. Sie betrifft grundsätzlich alle Gewerbebetriebe, nicht nur Kapitalgesellschaften.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-koerperschaftsteuer',
   'Welche Aussagen zur Körperschaftsteuer treffen zu?',
   'Die Körperschaftsteuer wird auf das Einkommen von Kapitalgesellschaften wie der GmbH oder AG erhoben. Personengesellschaften unterliegen ihr grundsätzlich nicht, deren Gewinnanteile werden stattdessen bei den Gesellschaftern mit Einkommensteuer erfasst. Zusätzlich zur Körperschaftsteuer wird der Solidaritätszuschlag erhoben.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-eigenkapitalquote-konzept',
   'Welche Aussagen zur Eigenkapitalquote treffen zu?',
   'Die Eigenkapitalquote setzt das Eigenkapital ins Verhältnis zur Bilanzsumme und zeigt den Anteil der Finanzierung aus eigenen Mitteln. Eine höhere Quote gilt allgemein als Zeichen geringerer Verschuldung und höherer Stabilität. Sie sagt allein aber noch nichts über die Rentabilität eines Unternehmens aus.',
   2, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-abschreibung-methoden',
   'Welche Aussagen zu Abschreibungsmethoden treffen zu?',
   'Bei der linearen Abschreibung ist der jährliche Abschreibungsbetrag über die gesamte Nutzungsdauer gleich hoch. Bei der degressiven Abschreibung mit festem Prozentsatz wird jeweils vom aktuellen Restbuchwert abgeschrieben, wodurch die Beträge von Jahr zu Jahr sinken. In den ersten Jahren führt die degressive Methode zu einem höheren Aufwand als die lineare.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-break-even-konzept',
   'Welche Aussagen zur Break-even-Analyse treffen zu?',
   'Am Break-even-Punkt deckt der gesamte Deckungsbeitrag genau die Fixkosten, der Gewinn ist an dieser Stelle null. Unterhalb der Break-even-Menge entsteht ein Verlust, oberhalb ein Gewinn. Eine Senkung der Fixkosten senkt bei sonst gleichen Bedingungen auch die Break-even-Menge.',
   3, 'multiple'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-mc-anlagendeckungsgrad',
   'Welche Aussagen zum Anlagendeckungsgrad treffen zu?',
   'Der Anlagendeckungsgrad setzt langfristig verfügbares Kapital ins Verhältnis zum Anlagevermögen und prüft, ob die goldene Bilanzregel eingehalten ist. Wird das Anlagevermögen vollständig durch Eigenkapital gedeckt, spricht man vom Anlagendeckungsgrad 1. Ein Wert deutlich unter 100 Prozent bei der einfachen Betrachtung mit nur Eigenkapital ist in der Praxis üblich, solange zusätzlich langfristiges Fremdkapital einbezogen wird.',
   4, 'multiple'),
  -- Einfachauswahl
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-inventar-definition',
   'Was ist das Inventar im Sinne des Rechnungswesens?',
   'Das Inventar ist das detaillierte, durch die Inventur ermittelte Verzeichnis aller Vermögensgegenstände und Schulden nach Art, Menge und Wert. Aus ihm wird verdichtet die Bilanz abgeleitet.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-bilanz-definition',
   'Was zeigt die Bilanz eines Unternehmens?',
   'Die Bilanz stellt zu einem bestimmten Stichtag das Vermögen und dessen Finanzierung gegenüber. Sie ist eine Zeitpunktbetrachtung, im Gegensatz zur GuV, die eine Periode abbildet.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-guv-zweck',
   'Welchem Zweck dient die Gewinn- und Verlustrechnung in erster Linie?',
   'Sie ermittelt durch Gegenüberstellung von Erträgen und Aufwendungen den Erfolg einer Periode und zeigt damit, wie sich der Gewinn oder Verlust zusammensetzt.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-buchungssatz-warenverkauf',
   'Ein Unternehmen verkauft Waren auf Ziel für netto 10.000 Euro zzgl. 19 Prozent Umsatzsteuer. Wie lautet der Buchungssatz?',
   'Die Umsatzsteuer beträgt 10.000 Euro mal 19 Prozent, also 1.900 Euro, der Bruttobetrag damit 11.900 Euro. Die Forderung entsteht in voller Bruttohöhe, während der Umsatzerlös nur netto gebucht wird: Forderungen aus Lieferungen und Leistungen 11.900 Euro an Umsatzerlöse 10.000 Euro an Umsatzsteuer 1.900 Euro.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-buchungssatz-wareneinkauf',
   'Ein Unternehmen kauft Waren auf Ziel für netto 5.000 Euro zzgl. 19 Prozent Vorsteuer ein. Wie lautet der Buchungssatz?',
   'Die Vorsteuer beträgt 5.000 Euro mal 19 Prozent, also 950 Euro, der Bruttobetrag damit 5.950 Euro. Gebucht wird: Wareneingang 5.000 Euro, Vorsteuer 950 Euro an Verbindlichkeiten aus Lieferungen und Leistungen 5.950 Euro.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-aktivkonto-mehrung',
   'Auf welcher Seite wird ein Aktivkonto gemehrt?',
   'Aktivkonten beginnen im Soll mit dem Anfangsbestand und werden auch im Soll gemehrt, Minderungen stehen im Haben.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-passivkonto-mehrung',
   'Auf welcher Seite wird ein Passivkonto gemehrt?',
   'Passivkonten beginnen im Haben mit dem Anfangsbestand und werden im Haben gemehrt, Minderungen stehen im Soll.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-abschreibung-linear',
   'Eine Maschine kostet 40.000 Euro Anschaffungskosten, die Nutzungsdauer beträgt 8 Jahre, der Restwert wird mit 0 Euro angesetzt. Wie hoch ist die jährliche lineare Abschreibung?',
   'Bei linearer Abschreibung gilt: Abschreibungsbetrag gleich Anschaffungskosten geteilt durch Nutzungsdauer. 40.000 Euro geteilt durch 8 Jahre ergibt 5.000 Euro pro Jahr.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-abschreibung-degressiv-jahr1',
   'Eine Anlage mit Anschaffungskosten von 40.000 Euro wird degressiv mit einem festen Satz von 25 Prozent abgeschrieben. Wie hoch ist die Abschreibung im ersten Jahr?',
   'Im ersten Jahr wird vom vollen Anschaffungswert abgeschrieben: 40.000 Euro mal 25 Prozent ergibt 10.000 Euro. Der Restbuchwert am Jahresende beträgt damit 30.000 Euro.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-abschreibung-degressiv-jahr2',
   'Für dieselbe Anlage aus der vorherigen Aufgabe (Anschaffungskosten 40.000 Euro, degressiver Satz 25 Prozent, Restbuchwert nach Jahr 1 von 30.000 Euro): Wie hoch ist die Abschreibung im zweiten Jahr?',
   'Bei der degressiven Abschreibung bezieht sich der Prozentsatz jedes Jahr auf den aktuellen Restbuchwert, nicht auf die ursprünglichen Anschaffungskosten. 30.000 Euro mal 25 Prozent ergibt 7.500 Euro für das zweite Jahr.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-rueckstellung-definition',
   'Wodurch unterscheidet sich eine Rückstellung von einer Verbindlichkeit?',
   'Bei einer Verbindlichkeit stehen Grund, Höhe und Fälligkeit fest. Bei einer Rückstellung ist die Verpflichtung dem Grunde nach wahrscheinlich, Höhe oder Zeitpunkt sind aber noch ungewiss und müssen geschätzt werden.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-kostenartenrechnung-frage',
   'Welche Grundfrage beantwortet die Kostenartenrechnung?',
   'Sie beantwortet die Frage, welche Kosten in welcher Höhe in einer Periode angefallen sind, unabhängig davon, wo oder wofür sie entstanden sind.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-einzelkosten-definition',
   'Was kennzeichnet Einzelkosten?',
   'Einzelkosten lassen sich einem einzelnen Kostenträger, also einem bestimmten Produkt oder Auftrag, unmittelbar und ohne Schlüsselung zurechnen, etwa das für ein Werkstück verbrauchte Material.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-gemeinkosten-definition',
   'Was kennzeichnet Gemeinkosten?',
   'Gemeinkosten können keinem einzelnen Kostenträger direkt zugeordnet werden und müssen über Verteilungsschlüssel, etwa im Betriebsabrechnungsbogen, auf die Kostenträger verrechnet werden, zum Beispiel die Hallenmiete.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-bab-zweck',
   'Wozu dient der Betriebsabrechnungsbogen vor allem?',
   'Er verteilt die Gemeinkosten auf die Kostenstellen und ermittelt daraus die Zuschlagssätze, die anschließend in der Kalkulation der einzelnen Kostenträger verwendet werden.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-kostentraegerrechnung-zweck',
   'Welche Frage beantwortet die Kostenträgerrechnung?',
   'Sie beantwortet die Frage, wofür, also für welches Produkt oder welche Leistung, die Kosten angefallen sind.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-materialkosten-calc',
   'Die Materialeinzelkosten eines Auftrags betragen 300 Euro, der Materialgemeinkostenzuschlag beträgt 20 Prozent. Wie hoch sind die Materialkosten insgesamt?',
   'Materialgemeinkosten = 300 Euro mal 20 Prozent = 60 Euro. Materialkosten = Materialeinzelkosten plus Materialgemeinkosten = 300 Euro plus 60 Euro = 360 Euro.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-herstellkosten-calc',
   'Für denselben Auftrag betragen die Materialkosten 360 Euro. Die Fertigungseinzelkosten (Löhne) liegen bei 200 Euro, der Fertigungsgemeinkostenzuschlag bei 150 Prozent. Wie hoch sind die Herstellkosten?',
   'Fertigungsgemeinkosten = 200 Euro mal 150 Prozent = 300 Euro. Fertigungskosten = 200 Euro plus 300 Euro = 500 Euro. Herstellkosten = Materialkosten plus Fertigungskosten = 360 Euro plus 500 Euro = 860 Euro.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-selbstkosten-calc',
   'Die Herstellkosten desselben Auftrags betragen 860 Euro. Der Verwaltungsgemeinkostenzuschlag beträgt 10 Prozent, der Vertriebsgemeinkostenzuschlag 15 Prozent, jeweils bezogen auf die Herstellkosten. Wie hoch sind die Selbstkosten?',
   'Verwaltungsgemeinkosten = 860 Euro mal 10 Prozent = 86 Euro. Vertriebsgemeinkosten = 860 Euro mal 15 Prozent = 129 Euro. Selbstkosten = 860 Euro plus 86 Euro plus 129 Euro = 1.075 Euro.',
   4, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-barverkaufspreis-calc',
   'Die Selbstkosten desselben Auftrags betragen 1.075 Euro. Auf die Selbstkosten wird ein Gewinnzuschlag von 10 Prozent aufgeschlagen. Wie hoch ist der Barverkaufspreis?',
   'Gewinn = 1.075 Euro mal 10 Prozent = 107,50 Euro. Barverkaufspreis = Selbstkosten plus Gewinn = 1.075 Euro plus 107,50 Euro = 1.182,50 Euro.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-fixkosten-definition',
   'Was sind fixe Kosten?',
   'Fixe Kosten sind innerhalb eines bestimmten Zeitraums unabhängig von der Beschäftigung, sie fallen also auch bei einem Produktionsstillstand in gleicher Höhe an, etwa die Miete für das Werksgelände.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-variable-kosten-definition',
   'Was sind variable Kosten?',
   'Variable Kosten verändern sich mit der Ausbringungsmenge, etwa der Materialverbrauch je produzierter Einheit.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-break-even-menge-calc',
   'Ein Unternehmen hat Fixkosten von 60.000 Euro pro Jahr. Der Verkaufspreis je Stück beträgt 50 Euro, die variablen Kosten je Stück 30 Euro. Wie hoch ist die Break-even-Menge?',
   'Deckungsbeitrag je Stück = Verkaufspreis minus variable Kosten = 50 Euro minus 30 Euro = 20 Euro. Break-even-Menge = Fixkosten geteilt durch Deckungsbeitrag je Stück = 60.000 Euro geteilt durch 20 Euro = 3.000 Stück.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-break-even-umsatz-calc',
   'Ein Unternehmen hat Fixkosten von 40.000 Euro. Der Verkaufspreis je Stück beträgt 100 Euro, die variablen Kosten je Stück 60 Euro. Wie hoch ist der Break-even-Umsatz?',
   'Deckungsbeitrag je Stück = 100 Euro minus 60 Euro = 40 Euro. Deckungsbeitragsquote = 40 Euro geteilt durch 100 Euro = 0,4. Break-even-Umsatz = Fixkosten geteilt durch Deckungsbeitragsquote = 40.000 Euro geteilt durch 0,4 = 100.000 Euro. Zur Probe: Break-even-Menge = 40.000 Euro geteilt durch 40 Euro = 1.000 Stück, mal 100 Euro Preis ergibt ebenfalls 100.000 Euro.',
   4, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-break-even-zielgewinn-calc',
   'Ein Unternehmen hat Fixkosten von 50.000 Euro und einen Deckungsbeitrag von 25 Euro je Stück. Es soll ein Zielgewinn von 10.000 Euro erreicht werden. Wie viele Stück müssen dafür verkauft werden?',
   'Um zusätzlich zu den Fixkosten den Zielgewinn zu erwirtschaften, muss der gesamte Deckungsbeitrag Fixkosten plus Zielgewinn decken: (50.000 Euro plus 10.000 Euro) geteilt durch 25 Euro = 60.000 Euro geteilt durch 25 Euro = 2.400 Stück.',
   4, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-deckungsbeitrag-stueck-calc',
   'Ein Produkt wird für 45 Euro verkauft, die variablen Kosten je Stück betragen 27 Euro. Bei 500 verkauften Stück: Wie hoch ist der gesamte Deckungsbeitrag?',
   'Deckungsbeitrag je Stück = 45 Euro minus 27 Euro = 18 Euro. Gesamter Deckungsbeitrag = 18 Euro mal 500 Stück = 9.000 Euro.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-deckungsbeitrag-gesamt-calc',
   'Ein Unternehmen erzielt einen Umsatz von 200.000 Euro, die variablen Kosten betragen 140.000 Euro, die Fixkosten 50.000 Euro. Wie hoch ist das Betriebsergebnis?',
   'Gesamter Deckungsbeitrag = Umsatz minus variable Kosten = 200.000 Euro minus 140.000 Euro = 60.000 Euro. Betriebsergebnis = Deckungsbeitrag minus Fixkosten = 60.000 Euro minus 50.000 Euro = 10.000 Euro Gewinn.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-deckungsbeitrag-mehrprodukt-calc',
   'Ein Unternehmen fertigt zwei Produkte. Produkt A erzielt einen Deckungsbeitrag von 10 Euro je Stück bei 1.000 verkauften Stück, Produkt B einen Deckungsbeitrag von 15 Euro je Stück bei 800 verkauften Stück. Die Fixkosten des Unternehmens betragen 18.000 Euro. Wie hoch ist der Gewinn?',
   'Deckungsbeitrag A = 10 Euro mal 1.000 = 10.000 Euro. Deckungsbeitrag B = 15 Euro mal 800 = 12.000 Euro. Gesamter Deckungsbeitrag = 10.000 Euro plus 12.000 Euro = 22.000 Euro. Gewinn = 22.000 Euro minus 18.000 Euro Fixkosten = 4.000 Euro.',
   4, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-soll-ist-abweichung',
   'Der Plan sieht Materialkosten von 80.000 Euro vor, tatsächlich fallen 92.000 Euro an. Wie wird diese Abweichung im Soll-Ist-Vergleich bezeichnet?',
   'Da die tatsächlichen Kosten die geplanten übersteigen, handelt es sich um eine negative Abweichung beziehungsweise Kostenüberschreitung von 12.000 Euro, die im Controlling weiter analysiert werden sollte.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-budgetierung-zweck',
   'Welchem Zweck dient ein Budget im betrieblichen Controlling in erster Linie?',
   'Ein Budget legt für eine kommende Periode Vorgaben für Kosten, Erlöse oder Investitionen fest und dient damit als Maßstab, an dem sich die spätere Ist-Entwicklung messen lässt.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-eigenfinanzierung-beispiel',
   'Welches der folgenden Beispiele stellt Eigenfinanzierung dar?',
   'Eine Kapitalerhöhung durch Ausgabe neuer Aktien bringt dem Unternehmen zusätzliches Eigenkapital von den Anteilseignern und zählt damit zur Eigenfinanzierung.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-fremdfinanzierung-beispiel',
   'Welches der folgenden Beispiele stellt Fremdfinanzierung dar?',
   'Ein von der Hausbank gewährtes Darlehen ist Kapital eines außenstehenden Gläubigers, das zurückgezahlt und verzinst werden muss, und zählt damit zur Fremdfinanzierung.',
   1, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-kontokorrentkredit',
   'Wofür wird ein Kontokorrentkredit typischerweise genutzt?',
   'Er dient der kurzfristigen Überbrückung von Liquiditätsengpässen im laufenden Geschäftsbetrieb, etwa wenn Zahlungseingänge und Zahlungsausgänge zeitlich auseinanderfallen.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-darlehen-vs-kontokorrent',
   'Warum ist ein Kontokorrentkredit im Regelfall teurer als ein langfristiges Darlehen?',
   'Der Kontokorrentkredit bietet der Bank flexible, kurzfristige und ungesicherte Kreditlinien, wofür ein höherer Zinssatz verlangt wird. Ein Darlehen ist meist besser besichert und langfristig kalkulierbar, was zu niedrigeren Zinsen führt.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-leasing-vorteil',
   'Welchen wesentlichen Vorteil bietet Leasing gegenüber dem Kauf einer Anlage?',
   'Leasing erfordert keine hohe Einmalzahlung, dadurch bleibt Liquidität für andere Zwecke im Unternehmen erhalten, während die Kosten über laufende Raten verteilt werden.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-liquiditaet-1-grades-calc',
   'Ein Unternehmen hat flüssige Mittel von 20.000 Euro und kurzfristige Verbindlichkeiten von 100.000 Euro. Wie hoch ist die Liquidität 1. Grades?',
   'Liquidität 1. Grades = flüssige Mittel geteilt durch kurzfristige Verbindlichkeiten mal 100 = 20.000 Euro geteilt durch 100.000 Euro mal 100 = 20 Prozent.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-liquiditaet-3-grades-calc',
   'Dasselbe Unternehmen hat zusätzlich kurzfristige Forderungen von 30.000 Euro und Vorräte von 50.000 Euro, bei weiterhin 100.000 Euro kurzfristigen Verbindlichkeiten. Wie hoch ist die Liquidität 3. Grades?',
   'Liquidität 3. Grades = (flüssige Mittel plus Forderungen plus Vorräte) geteilt durch kurzfristige Verbindlichkeiten mal 100 = (20.000 Euro plus 30.000 Euro plus 50.000 Euro) geteilt durch 100.000 Euro mal 100 = 100.000 Euro geteilt durch 100.000 Euro mal 100 = 100 Prozent.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-kostenvergleichsrechnung-calc',
   'Eine Investition kostet 100.000 Euro Anschaffungskosten, die Nutzungsdauer beträgt 5 Jahre, der Restwert 0 Euro, der kalkulatorische Zinssatz 8 Prozent. Die laufenden Kosten (ohne Abschreibung und Zinsen) betragen 50.000 Euro pro Jahr. Wie hoch sind die gesamten jährlichen Kosten laut Kostenvergleichsrechnung?',
   'Abschreibung = 100.000 Euro geteilt durch 5 Jahre = 20.000 Euro. Kalkulatorische Zinsen = (Anschaffungskosten plus Restwert) geteilt durch 2 mal Zinssatz = (100.000 Euro plus 0 Euro) geteilt durch 2 mal 8 Prozent = 50.000 Euro mal 8 Prozent = 4.000 Euro. Gesamtkosten = laufende Kosten plus Abschreibung plus kalkulatorische Zinsen = 50.000 Euro plus 20.000 Euro plus 4.000 Euro = 74.000 Euro.',
   4, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-gewinnvergleichsrechnung-calc',
   'Für dieselbe Investition (Gesamtkosten 74.000 Euro pro Jahr) werden jährliche Erlöse von 80.000 Euro erwartet. Wie hoch ist der Gewinn laut Gewinnvergleichsrechnung?',
   'Gewinn = Erlöse minus Gesamtkosten = 80.000 Euro minus 74.000 Euro = 6.000 Euro pro Jahr.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-rentabilitaetsrechnung-calc',
   'Für dieselbe Investition (Anschaffungskosten 100.000 Euro, Restwert 0 Euro, Gewinn 6.000 Euro pro Jahr): Wie hoch ist die Rentabilität laut Rentabilitätsrechnung?',
   'Durchschnittlich gebundenes Kapital = (Anschaffungskosten plus Restwert) geteilt durch 2 = (100.000 Euro plus 0 Euro) geteilt durch 2 = 50.000 Euro. Rentabilität = Gewinn geteilt durch durchschnittlich gebundenes Kapital mal 100 = 6.000 Euro geteilt durch 50.000 Euro mal 100 = 12 Prozent.',
   4, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-amortisationsrechnung-calc',
   'Für dieselbe Investition (Anschaffungskosten 100.000 Euro, jährlicher Gewinn 6.000 Euro, jährliche Abschreibung 20.000 Euro): Wie viele Jahre dauert die Amortisation nach der Durchschnittsmethode?',
   'Jährlicher Kapitalrückfluss = Gewinn plus Abschreibung = 6.000 Euro plus 20.000 Euro = 26.000 Euro. Amortisationszeit = Anschaffungskosten geteilt durch jährlichen Rückfluss = 100.000 Euro geteilt durch 26.000 Euro, das ergibt rund 3,85 Jahre.',
   4, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-umsatzsteuer-berechnung',
   'Eine Rechnung weist einen Nettobetrag von 8.000 Euro aus, der Umsatzsteuersatz beträgt 19 Prozent. Wie hoch ist der Bruttobetrag der Rechnung?',
   'Umsatzsteuer = 8.000 Euro mal 19 Prozent = 1.520 Euro. Bruttobetrag = Nettobetrag plus Umsatzsteuer = 8.000 Euro plus 1.520 Euro = 9.520 Euro.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-eigenkapitalquote-calc',
   'Ein Unternehmen hat eine Bilanzsumme von 500.000 Euro und ein Eigenkapital von 150.000 Euro. Wie hoch ist die Eigenkapitalquote?',
   'Eigenkapitalquote = Eigenkapital geteilt durch Bilanzsumme mal 100 = 150.000 Euro geteilt durch 500.000 Euro mal 100 = 30 Prozent.',
   2, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-eigenkapitalrentabilitaet-calc',
   'Ein Unternehmen erzielt einen Jahresgewinn von 30.000 Euro bei einem Eigenkapital von 150.000 Euro und einem Umsatz von 600.000 Euro. Wie hoch ist die Eigenkapitalrentabilität?',
   'Eigenkapitalrentabilität = Gewinn geteilt durch Eigenkapital mal 100 = 30.000 Euro geteilt durch 150.000 Euro mal 100 = 20 Prozent. Zum Vergleich: Die Umsatzrentabilität läge bei 30.000 Euro geteilt durch 600.000 Euro mal 100, also 5 Prozent, das ist hier aber nicht gefragt.',
   3, 'single'),
  ('Kaufmännische Steuerung & Kontrolle', 'steuerung-sg-skontosatz-effektivzins-calc',
   'Ein Lieferant räumt ein Zahlungsziel von 30 Tagen netto ein, gewährt aber 2 Prozent Skonto bei Zahlung innerhalb von 10 Tagen. Wie hoch ist der effektive Jahreszinssatz, den man durch Verzicht auf den Skontoabzug faktisch in Kauf nimmt (Formel: Skontosatz geteilt durch (100 minus Skontosatz), mal 360 geteilt durch die Differenz der Zahlungsfristen)?',
   'Skontosatz-Faktor = 2 geteilt durch (100 minus 2) = 2 geteilt durch 98 = 0,0204. Kreditzeitraum = 30 Tage minus 10 Tage = 20 Tage. Zeitfaktor = 360 geteilt durch 20 = 18. Effektivzins = 0,0204 mal 18 = 0,3673, also rund 36,7 Prozent pro Jahr. Da das deutlich über üblichen Bankzinsen liegt, lohnt sich das Ausnutzen des Skontos fast immer.',
   4, 'single')
) as v(topic_name, source_key, q, expl, difficulty, question_type)
on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- steuerung-mc-inventur-arten
  ('steuerung-mc-inventur-arten', 'Bei der körperlichen Inventur werden Bestände gezählt, gewogen oder gemessen', true, 0),
  ('steuerung-mc-inventur-arten', 'Bei der Buchinventur werden Bestände aus Aufzeichnungen abgeleitet', true, 1),
  ('steuerung-mc-inventur-arten', 'Die permanente Inventur ermöglicht eine Bestandsaufnahme während des Jahres bei fortgeschriebener Lagerbuchführung', true, 2),
  ('steuerung-mc-inventur-arten', 'Die Inventur ist gesetzlich nicht vorgeschrieben und rein freiwillig', false, 3),
  -- steuerung-mc-bilanz-aufbau
  ('steuerung-mc-bilanz-aufbau', 'Die Aktivseite zeigt die Mittelverwendung', true, 0),
  ('steuerung-mc-bilanz-aufbau', 'Die Passivseite zeigt die Mittelherkunft', true, 1),
  ('steuerung-mc-bilanz-aufbau', 'Aktiv- und Passivseite sind stets gleich groß', true, 2),
  ('steuerung-mc-bilanz-aufbau', 'Das Umlaufvermögen steht in der Bilanz grundsätzlich vor dem Anlagevermögen', false, 3),
  -- steuerung-mc-guv-aufwand-ertrag
  ('steuerung-mc-guv-aufwand-ertrag', 'Die GuV stellt Erträge und Aufwendungen einer Periode gegenüber', true, 0),
  ('steuerung-mc-guv-aufwand-ertrag', 'Übersteigen die Erträge die Aufwendungen, entsteht ein Gewinn', true, 1),
  ('steuerung-mc-guv-aufwand-ertrag', 'Die GuV ist wie die Bilanz eine Stichtagsbetrachtung', false, 2),
  ('steuerung-mc-guv-aufwand-ertrag', 'Die GuV zeigt eine Stromgröße über einen Zeitraum', true, 3),
  -- steuerung-mc-bestandskonten
  ('steuerung-mc-bestandskonten', 'Aktivkonten beginnen im Soll mit dem Anfangsbestand', true, 0),
  ('steuerung-mc-bestandskonten', 'Aktivkonten mehren sich im Soll', true, 1),
  ('steuerung-mc-bestandskonten', 'Passivkonten beginnen im Haben mit dem Anfangsbestand und mehren sich im Haben', true, 2),
  ('steuerung-mc-bestandskonten', 'Der Schlussbestand steht immer auf derselben Seite wie der Anfangsbestand', false, 3),
  -- steuerung-mc-erfolgskonten
  ('steuerung-mc-erfolgskonten', 'Aufwandskonten werden im Soll gebucht', true, 0),
  ('steuerung-mc-erfolgskonten', 'Ertragskonten werden im Haben gebucht', true, 1),
  ('steuerung-mc-erfolgskonten', 'Erfolgskonten werden am Periodenende über das Gewinn- und Verlustkonto abgeschlossen', true, 2),
  ('steuerung-mc-erfolgskonten', 'Aufwands- und Ertragskonten werden direkt gegeneinander abgeschlossen, ohne GuV-Konto', false, 3),
  -- steuerung-mc-rueckstellungen
  ('steuerung-mc-rueckstellungen', 'Rückstellungen werden gebildet, wenn eine Verpflichtung dem Grunde nach wahrscheinlich, aber unsicher in Höhe oder Fälligkeit ist', true, 0),
  ('steuerung-mc-rueckstellungen', 'Rückstellungen werden als Fremdkapital passiviert', true, 1),
  ('steuerung-mc-rueckstellungen', 'Rückstellungen mindern den Gewinn der Periode ihrer Bildung', true, 2),
  ('steuerung-mc-rueckstellungen', 'Rückstellungen dürfen nur für bereits vollständig feststehende Verbindlichkeiten gebildet werden', false, 3),
  -- steuerung-mc-kostenarten
  ('steuerung-mc-kostenarten', 'Die Kostenartenrechnung beantwortet, welche Kosten in welcher Höhe angefallen sind', true, 0),
  ('steuerung-mc-kostenarten', 'Einzelkosten lassen sich einem Kostenträger direkt zurechnen', true, 1),
  ('steuerung-mc-kostenarten', 'Gemeinkosten lassen sich nur über Schlüssel zurechnen', true, 2),
  ('steuerung-mc-kostenarten', 'Die Kostenartenrechnung folgt zeitlich auf die Kostenträgerrechnung', false, 3),
  -- steuerung-mc-bab-prinzip
  ('steuerung-mc-bab-prinzip', 'Der BAB verteilt Gemeinkosten über Schlüssel auf Kostenstellen', true, 0),
  ('steuerung-mc-bab-prinzip', 'Der BAB ermittelt Zuschlagssätze für die Kalkulation', true, 1),
  ('steuerung-mc-bab-prinzip', 'Einzelkosten werden im BAB nicht verteilt', true, 2),
  ('steuerung-mc-bab-prinzip', 'Der BAB unterscheidet nicht zwischen Vor- und Hauptkostenstellen', false, 3),
  -- steuerung-mc-kostentraeger
  ('steuerung-mc-kostentraeger', 'Die Kostenträgerrechnung fragt, wofür Kosten angefallen sind', true, 0),
  ('steuerung-mc-kostentraeger', 'Die Kostenträgerstückrechnung kalkuliert ein einzelnes Erzeugnis', true, 1),
  ('steuerung-mc-kostentraeger', 'Die Kostenträgerzeitrechnung stellt Kosten und Leistungen einer Periode gegenüber', true, 2),
  ('steuerung-mc-kostentraeger', 'Die Kostenträgerrechnung wird vor der Kostenartenrechnung durchgeführt', false, 3),
  -- steuerung-mc-fixe-variable-kosten
  ('steuerung-mc-fixe-variable-kosten', 'Fixe Kosten fallen unabhängig von der Beschäftigung in gleicher Höhe an', true, 0),
  ('steuerung-mc-fixe-variable-kosten', 'Variable Kosten steigen mit der Ausbringungsmenge', true, 1),
  ('steuerung-mc-fixe-variable-kosten', 'Variable Kosten müssen nicht proportional zur Menge verlaufen', true, 2),
  ('steuerung-mc-fixe-variable-kosten', 'Die Fixkosten je Stück steigen mit zunehmender Ausbringungsmenge', false, 3),
  -- steuerung-mc-deckungsbeitrag-konzept
  ('steuerung-mc-deckungsbeitrag-konzept', 'Der Deckungsbeitrag ergibt sich aus Verkaufspreis minus variablen Kosten je Stück', true, 0),
  ('steuerung-mc-deckungsbeitrag-konzept', 'Der Deckungsbeitrag dient zunächst der Deckung der Fixkosten', true, 1),
  ('steuerung-mc-deckungsbeitrag-konzept', 'Ein positiver Deckungsbeitrag bedeutet für sich genommen bereits Gesamtgewinn', false, 2),
  ('steuerung-mc-deckungsbeitrag-konzept', 'Ein Betrag über die Fixkostendeckung hinaus ist Gewinn', true, 3),
  -- steuerung-mc-zuschlagskalkulation-aufbau
  ('steuerung-mc-zuschlagskalkulation-aufbau', 'Materialgemeinkosten werden auf die Materialeinzelkosten aufgeschlagen', true, 0),
  ('steuerung-mc-zuschlagskalkulation-aufbau', 'Fertigungsgemeinkosten werden auf die Fertigungseinzelkosten aufgeschlagen', true, 1),
  ('steuerung-mc-zuschlagskalkulation-aufbau', 'Verwaltungs- und Vertriebsgemeinkostenzuschläge beziehen sich auf die Herstellkosten', true, 2),
  ('steuerung-mc-zuschlagskalkulation-aufbau', 'Der Zuschlagssatz wird frei geschätzt, ohne Bezug zum BAB', false, 3),
  -- steuerung-mc-soll-ist-vergleich
  ('steuerung-mc-soll-ist-vergleich', 'Der Soll-Ist-Vergleich stellt geplante und tatsächliche Werte gegenüber', true, 0),
  ('steuerung-mc-soll-ist-vergleich', 'Eine Abweichung allein zeigt noch nicht ihre Ursache', true, 1),
  ('steuerung-mc-soll-ist-vergleich', 'Er hilft, künftige Planungen realistischer zu gestalten', true, 2),
  ('steuerung-mc-soll-ist-vergleich', 'Er wird ausschließlich am Ende der gesamten Unternehmenslaufzeit durchgeführt', false, 3),
  -- steuerung-mc-kennzahlen-rentabilitaet
  ('steuerung-mc-kennzahlen-rentabilitaet', 'Die Eigenkapitalrentabilität setzt Gewinn ins Verhältnis zum Eigenkapital', true, 0),
  ('steuerung-mc-kennzahlen-rentabilitaet', 'Die Umsatzrentabilität setzt Gewinn ins Verhältnis zum Umsatz', true, 1),
  ('steuerung-mc-kennzahlen-rentabilitaet', 'Beide Kennzahlen werden meist in Prozent angegeben', true, 2),
  ('steuerung-mc-kennzahlen-rentabilitaet', 'Rentabilitätskennzahlen eignen sich nicht für einen Vergleich zwischen Unternehmen', false, 3),
  -- steuerung-mc-kennzahlen-liquiditaet
  ('steuerung-mc-kennzahlen-liquiditaet', 'Liquiditätsgrade setzen kurzfristig verfügbare Vermögenswerte ins Verhältnis zu kurzfristigen Verbindlichkeiten', true, 0),
  ('steuerung-mc-kennzahlen-liquiditaet', 'Mit steigender Stufe fließen mehr Vermögenswerte in den Zähler ein', true, 1),
  ('steuerung-mc-kennzahlen-liquiditaet', 'Eine Liquidität 1. Grades unter 100 Prozent bedeutet zwingend sofortige Zahlungsunfähigkeit', false, 2),
  ('steuerung-mc-kennzahlen-liquiditaet', 'Liquiditätskennzahlen werden meist in Prozent angegeben', true, 3),
  -- steuerung-mc-budgetierung
  ('steuerung-mc-budgetierung', 'Ein Budget legt geplante Kosten oder Erlöse für eine künftige Periode fest', true, 0),
  ('steuerung-mc-budgetierung', 'Top-down-Budgetierung gibt Vorgaben von der Leitung an die Bereiche vor', true, 1),
  ('steuerung-mc-budgetierung', 'Bottom-up-Budgetierung sammelt Planzahlen aus den Bereichen ein', true, 2),
  ('steuerung-mc-budgetierung', 'Budgets werden nach ihrer Verabschiedung nicht mehr mit Ist-Werten verglichen', false, 3),
  -- steuerung-mc-eigenfinanzierung
  ('steuerung-mc-eigenfinanzierung', 'Eigenfinanzierung liegt vor, wenn Kapital von Eigentümern oder aus Gewinnen stammt', true, 0),
  ('steuerung-mc-eigenfinanzierung', 'Eine Kapitalerhöhung durch neue Aktien zählt zur Eigenfinanzierung', true, 1),
  ('steuerung-mc-eigenfinanzierung', 'Selbstfinanzierung aus thesaurierten Gewinnen zählt zur Eigenfinanzierung', true, 2),
  ('steuerung-mc-eigenfinanzierung', 'Eigenkapital haftet im Insolvenzfall vorrangig vor dem Fremdkapital', false, 3),
  -- steuerung-mc-fremdfinanzierung
  ('steuerung-mc-fremdfinanzierung', 'Fremdkapital wird von außenstehenden Gläubigern zur Verfügung gestellt', true, 0),
  ('steuerung-mc-fremdfinanzierung', 'Fremdkapital muss unabhängig vom Geschäftserfolg zurückgezahlt und verzinst werden', true, 1),
  ('steuerung-mc-fremdfinanzierung', 'Ein Lieferantenkredit zählt zur Fremdfinanzierung', true, 2),
  ('steuerung-mc-fremdfinanzierung', 'Fremdkapitalgeber haben im Regelfall dasselbe Mitspracherecht wie Eigenkapitalgeber', false, 3),
  -- steuerung-mc-kreditarten
  ('steuerung-mc-kreditarten', 'Der Kontokorrentkredit dient der kurzfristigen Überbrückung von Liquiditätsengpässen', true, 0),
  ('steuerung-mc-kreditarten', 'Der Kontokorrentkredit ist meist günstiger als ein langfristiges Darlehen', false, 1),
  ('steuerung-mc-kreditarten', 'Ein Investitionskredit ist auf eine bestimmte Anschaffung ausgerichtet', true, 2),
  ('steuerung-mc-kreditarten', 'Ein Lieferantenkredit entsteht durch ein eingeräumtes Zahlungsziel', true, 3),
  ('steuerung-mc-kreditarten', 'Ein Investitionskredit läuft grundsätzlich kürzer als ein Kontokorrentkredit', false, 4),
  -- steuerung-mc-leasing-vs-kauf
  ('steuerung-mc-leasing-vs-kauf', 'Leasing schont die Liquidität, weil keine hohe Einmalzahlung anfällt', true, 0),
  ('steuerung-mc-leasing-vs-kauf', 'Beim Kauf steht der Gegenstand meist im Anlagevermögen des Käufers', true, 1),
  ('steuerung-mc-leasing-vs-kauf', 'Beim Operating-Leasing bleibt der Gegenstand in der Regel beim Leasinggeber', true, 2),
  ('steuerung-mc-leasing-vs-kauf', 'Leasing ist über die gesamte Laufzeit grundsätzlich günstiger als ein Kauf', false, 3),
  -- steuerung-mc-liquiditaetsgrade-konzept
  ('steuerung-mc-liquiditaetsgrade-konzept', 'Die Liquidität 1. Grades berücksichtigt nur die flüssigen Mittel', true, 0),
  ('steuerung-mc-liquiditaetsgrade-konzept', 'Die Liquidität 2. Grades berücksichtigt zusätzlich die kurzfristigen Forderungen', true, 1),
  ('steuerung-mc-liquiditaetsgrade-konzept', 'Die Liquidität 3. Grades berücksichtigt zusätzlich die Vorräte', true, 2),
  ('steuerung-mc-liquiditaetsgrade-konzept', 'Der Wert sinkt normalerweise mit jeder weiteren Stufe', false, 3),
  -- steuerung-mc-investitionsrechnung-statisch-ueberblick
  ('steuerung-mc-investitionsrechnung-statisch-ueberblick', 'Statische Verfahren arbeiten mit Durchschnittswerten einer Periode', true, 0),
  ('steuerung-mc-investitionsrechnung-statisch-ueberblick', 'Statische Verfahren berücksichtigen den Zeitpunkt einzelner Zahlungen nicht', true, 1),
  ('steuerung-mc-investitionsrechnung-statisch-ueberblick', 'Statische Verfahren sind einfacher anzuwenden als dynamische Verfahren', true, 2),
  ('steuerung-mc-investitionsrechnung-statisch-ueberblick', 'Kalkulatorische Zinsen spielen in statischen Verfahren keine Rolle', false, 3),
  -- steuerung-mc-amortisationsrechnung-konzept
  ('steuerung-mc-amortisationsrechnung-konzept', 'Sie ermittelt, nach welcher Zeit die Anschaffungsauszahlung durch Rückflüsse hereingeholt ist', true, 0),
  ('steuerung-mc-amortisationsrechnung-konzept', 'Als Rückfluss gelten Gewinn und Abschreibung zusammen', true, 1),
  ('steuerung-mc-amortisationsrechnung-konzept', 'Eine kürzere Amortisationszeit gilt bei sonst gleichen Bedingungen als vorteilhafter', true, 2),
  ('steuerung-mc-amortisationsrechnung-konzept', 'Die Abschreibung wird bei der Ermittlung des Rückflusses abgezogen, nicht addiert', false, 3),
  -- steuerung-mc-umsatzsteuer-vorsteuer
  ('steuerung-mc-umsatzsteuer-vorsteuer', 'Die Umsatzsteuer wird auf eigene Ausgangsleistungen erhoben', true, 0),
  ('steuerung-mc-umsatzsteuer-vorsteuer', 'Die Vorsteuer aus Eingangsrechnungen kann gegengerechnet werden', true, 1),
  ('steuerung-mc-umsatzsteuer-vorsteuer', 'Die Umsatzsteuer ist für das Unternehmen wirtschaftlich neutral', true, 2),
  ('steuerung-mc-umsatzsteuer-vorsteuer', 'Die Umsatzsteuer wird wirtschaftlich letztlich vom Unternehmen selbst getragen', false, 3),
  -- steuerung-mc-gewerbesteuer
  ('steuerung-mc-gewerbesteuer', 'Die Gewerbesteuer wird von den Gemeinden erhoben', true, 0),
  ('steuerung-mc-gewerbesteuer', 'Sie knüpft an den Gewerbeertrag an', true, 1),
  ('steuerung-mc-gewerbesteuer', 'Ihre Höhe hängt vom Hebesatz der Gemeinde ab', true, 2),
  ('steuerung-mc-gewerbesteuer', 'Sie betrifft ausschließlich Kapitalgesellschaften', false, 3),
  -- steuerung-mc-koerperschaftsteuer
  ('steuerung-mc-koerperschaftsteuer', 'Sie wird auf das Einkommen von Kapitalgesellschaften erhoben', true, 0),
  ('steuerung-mc-koerperschaftsteuer', 'Personengesellschaften unterliegen ihr grundsätzlich nicht', true, 1),
  ('steuerung-mc-koerperschaftsteuer', 'Zusätzlich wird der Solidaritätszuschlag erhoben', true, 2),
  ('steuerung-mc-koerperschaftsteuer', 'Gewinnanteile von Personengesellschaftern werden gar nicht besteuert', false, 3),
  -- steuerung-mc-eigenkapitalquote-konzept
  ('steuerung-mc-eigenkapitalquote-konzept', 'Die Eigenkapitalquote setzt Eigenkapital ins Verhältnis zur Bilanzsumme', true, 0),
  ('steuerung-mc-eigenkapitalquote-konzept', 'Eine höhere Quote gilt als Zeichen geringerer Verschuldung', true, 1),
  ('steuerung-mc-eigenkapitalquote-konzept', 'Sie sagt allein noch nichts über die Rentabilität aus', true, 2),
  ('steuerung-mc-eigenkapitalquote-konzept', 'Sie wird aus dem Verhältnis von Umsatz zu Gewinn berechnet', false, 3),
  -- steuerung-mc-abschreibung-methoden
  ('steuerung-mc-abschreibung-methoden', 'Bei linearer Abschreibung ist der Jahresbetrag über die Nutzungsdauer gleich hoch', true, 0),
  ('steuerung-mc-abschreibung-methoden', 'Bei degressiver Abschreibung wird jeweils vom aktuellen Restbuchwert abgeschrieben', true, 1),
  ('steuerung-mc-abschreibung-methoden', 'Die degressiven Beträge sinken von Jahr zu Jahr', true, 2),
  ('steuerung-mc-abschreibung-methoden', 'In den ersten Jahren führt die degressive Methode zu einem niedrigeren Aufwand als die lineare', false, 3),
  -- steuerung-mc-break-even-konzept
  ('steuerung-mc-break-even-konzept', 'Am Break-even-Punkt deckt der Deckungsbeitrag genau die Fixkosten', true, 0),
  ('steuerung-mc-break-even-konzept', 'Unterhalb der Break-even-Menge entsteht ein Verlust', true, 1),
  ('steuerung-mc-break-even-konzept', 'Oberhalb der Break-even-Menge entsteht ein Gewinn', true, 2),
  ('steuerung-mc-break-even-konzept', 'Eine Senkung der Fixkosten erhöht bei sonst gleichen Bedingungen die Break-even-Menge', false, 3),
  -- steuerung-mc-anlagendeckungsgrad
  ('steuerung-mc-anlagendeckungsgrad', 'Der Anlagendeckungsgrad setzt langfristiges Kapital ins Verhältnis zum Anlagevermögen', true, 0),
  ('steuerung-mc-anlagendeckungsgrad', 'Er prüft die Einhaltung der goldenen Bilanzregel', true, 1),
  ('steuerung-mc-anlagendeckungsgrad', 'Beim Anlagendeckungsgrad 1 wird das Anlagevermögen vollständig durch Eigenkapital gedeckt', true, 2),
  ('steuerung-mc-anlagendeckungsgrad', 'Der Anlagendeckungsgrad setzt das Umlaufvermögen ins Verhältnis zu den kurzfristigen Verbindlichkeiten', false, 3),
  -- Einfachauswahl
  ('steuerung-sg-inventar-definition', 'Ein detailliertes Verzeichnis aller Vermögensgegenstände und Schulden nach Art, Menge und Wert', true, 0),
  ('steuerung-sg-inventar-definition', 'Eine stark verdichtete tabellarische Übersicht wie die Bilanz', false, 1),
  ('steuerung-sg-inventar-definition', 'Eine Aufstellung nur der offenen Forderungen', false, 2),
  ('steuerung-sg-inventar-definition', 'Der Jahresabschlussbericht an die Gesellschafter', false, 3),
  ('steuerung-sg-bilanz-definition', 'Vermögen und Finanzierung zu einem bestimmten Stichtag', true, 0),
  ('steuerung-sg-bilanz-definition', 'Erträge und Aufwendungen einer Periode', false, 1),
  ('steuerung-sg-bilanz-definition', 'Nur die liquiden Mittel eines Unternehmens', false, 2),
  ('steuerung-sg-bilanz-definition', 'Ausschließlich die geplanten Zahlen des Folgejahres', false, 3),
  ('steuerung-sg-guv-zweck', 'Ermittlung des Periodenerfolgs durch Gegenüberstellung von Erträgen und Aufwendungen', true, 0),
  ('steuerung-sg-guv-zweck', 'Feststellung des Vermögens zu einem Stichtag', false, 1),
  ('steuerung-sg-guv-zweck', 'Dokumentation der Inventurergebnisse', false, 2),
  ('steuerung-sg-guv-zweck', 'Berechnung der Liquiditätsgrade', false, 3),
  ('steuerung-sg-buchungssatz-warenverkauf', 'Forderungen 11.900 Euro an Umsatzerlöse 10.000 Euro an Umsatzsteuer 1.900 Euro', true, 0),
  ('steuerung-sg-buchungssatz-warenverkauf', 'Forderungen 10.000 Euro an Umsatzerlöse 10.000 Euro', false, 1),
  ('steuerung-sg-buchungssatz-warenverkauf', 'Umsatzerlöse 11.900 Euro an Forderungen 11.900 Euro', false, 2),
  ('steuerung-sg-buchungssatz-warenverkauf', 'Forderungen 11.900 Euro an Umsatzerlöse 11.900 Euro', false, 3),
  ('steuerung-sg-buchungssatz-wareneinkauf', 'Wareneingang 5.000 Euro, Vorsteuer 950 Euro an Verbindlichkeiten 5.950 Euro', true, 0),
  ('steuerung-sg-buchungssatz-wareneinkauf', 'Wareneingang 5.950 Euro an Verbindlichkeiten 5.950 Euro', false, 1),
  ('steuerung-sg-buchungssatz-wareneinkauf', 'Verbindlichkeiten 5.950 Euro an Wareneingang 5.000 Euro an Vorsteuer 950 Euro', false, 2),
  ('steuerung-sg-buchungssatz-wareneinkauf', 'Wareneingang 5.000 Euro an Verbindlichkeiten 5.000 Euro', false, 3),
  ('steuerung-sg-aktivkonto-mehrung', 'Im Soll', true, 0),
  ('steuerung-sg-aktivkonto-mehrung', 'Im Haben', false, 1),
  ('steuerung-sg-aktivkonto-mehrung', 'Je zur Hälfte auf beiden Seiten', false, 2),
  ('steuerung-sg-aktivkonto-mehrung', 'Das hängt von der jeweiligen Kontenart ab', false, 3),
  ('steuerung-sg-passivkonto-mehrung', 'Im Haben', true, 0),
  ('steuerung-sg-passivkonto-mehrung', 'Im Soll', false, 1),
  ('steuerung-sg-passivkonto-mehrung', 'Je zur Hälfte auf beiden Seiten', false, 2),
  ('steuerung-sg-passivkonto-mehrung', 'Nur am Jahresende', false, 3),
  ('steuerung-sg-abschreibung-linear', '5.000 Euro', true, 0),
  ('steuerung-sg-abschreibung-linear', '4.000 Euro', false, 1),
  ('steuerung-sg-abschreibung-linear', '8.000 Euro', false, 2),
  ('steuerung-sg-abschreibung-linear', '320.000 Euro', false, 3),
  ('steuerung-sg-abschreibung-degressiv-jahr1', '10.000 Euro', true, 0),
  ('steuerung-sg-abschreibung-degressiv-jahr1', '5.000 Euro', false, 1),
  ('steuerung-sg-abschreibung-degressiv-jahr1', '8.000 Euro', false, 2),
  ('steuerung-sg-abschreibung-degressiv-jahr1', '40.000 Euro', false, 3),
  ('steuerung-sg-abschreibung-degressiv-jahr2', '7.500 Euro', true, 0),
  ('steuerung-sg-abschreibung-degressiv-jahr2', '10.000 Euro', false, 1),
  ('steuerung-sg-abschreibung-degressiv-jahr2', '5.625 Euro', false, 2),
  ('steuerung-sg-abschreibung-degressiv-jahr2', '6.000 Euro', false, 3),
  ('steuerung-sg-rueckstellung-definition', 'Bei einer Rückstellung sind Höhe oder Zeitpunkt der wahrscheinlichen Verpflichtung noch ungewiss', true, 0),
  ('steuerung-sg-rueckstellung-definition', 'Eine Rückstellung ist stets exakt in Höhe und Fälligkeit bekannt', false, 1),
  ('steuerung-sg-rueckstellung-definition', 'Eine Verbindlichkeit wird nur geschätzt, eine Rückstellung ist immer belegt', false, 2),
  ('steuerung-sg-rueckstellung-definition', 'Rückstellungen zählen zum Eigenkapital', false, 3),
  ('steuerung-sg-kostenartenrechnung-frage', 'Welche Kosten in welcher Höhe angefallen sind', true, 0),
  ('steuerung-sg-kostenartenrechnung-frage', 'Wo die Kosten entstanden sind', false, 1),
  ('steuerung-sg-kostenartenrechnung-frage', 'Wofür die Kosten angefallen sind', false, 2),
  ('steuerung-sg-kostenartenrechnung-frage', 'Wie hoch der Marktpreis eines Produkts ist', false, 3),
  ('steuerung-sg-einzelkosten-definition', 'Kosten, die einem Kostenträger direkt und ohne Schlüsselung zurechenbar sind', true, 0),
  ('steuerung-sg-einzelkosten-definition', 'Kosten, die nur über Verteilungsschlüssel zurechenbar sind', false, 1),
  ('steuerung-sg-einzelkosten-definition', 'Kosten, die unabhängig von der Beschäftigung anfallen', false, 2),
  ('steuerung-sg-einzelkosten-definition', 'Kosten, die ausschließlich in der Verwaltung entstehen', false, 3),
  ('steuerung-sg-gemeinkosten-definition', 'Kosten, die keinem Kostenträger direkt zugeordnet werden können', true, 0),
  ('steuerung-sg-gemeinkosten-definition', 'Kosten, die einem einzelnen Auftrag direkt zurechenbar sind', false, 1),
  ('steuerung-sg-gemeinkosten-definition', 'Kosten, die ausschließlich variabel sind', false, 2),
  ('steuerung-sg-gemeinkosten-definition', 'Kosten, die nur im Vertrieb anfallen', false, 3),
  ('steuerung-sg-bab-zweck', 'Verteilung der Gemeinkosten auf Kostenstellen und Ermittlung von Zuschlagssätzen', true, 0),
  ('steuerung-sg-bab-zweck', 'Erfassung der Einzelkosten je Auftrag', false, 1),
  ('steuerung-sg-bab-zweck', 'Ermittlung der Liquiditätsgrade', false, 2),
  ('steuerung-sg-bab-zweck', 'Buchung der laufenden Geschäftsvorfälle', false, 3),
  ('steuerung-sg-kostentraegerrechnung-zweck', 'Wofür die Kosten angefallen sind', true, 0),
  ('steuerung-sg-kostentraegerrechnung-zweck', 'Welche Kosten in welcher Höhe angefallen sind', false, 1),
  ('steuerung-sg-kostentraegerrechnung-zweck', 'Wo im Betrieb die Kosten entstanden sind', false, 2),
  ('steuerung-sg-kostentraegerrechnung-zweck', 'Wie die Kosten künftig sinken können', false, 3),
  ('steuerung-sg-materialkosten-calc', '360 Euro', true, 0),
  ('steuerung-sg-materialkosten-calc', '320 Euro', false, 1),
  ('steuerung-sg-materialkosten-calc', '300 Euro', false, 2),
  ('steuerung-sg-materialkosten-calc', '420 Euro', false, 3),
  ('steuerung-sg-herstellkosten-calc', '860 Euro', true, 0),
  ('steuerung-sg-herstellkosten-calc', '660 Euro', false, 1),
  ('steuerung-sg-herstellkosten-calc', '560 Euro', false, 2),
  ('steuerung-sg-herstellkosten-calc', '760 Euro', false, 3),
  ('steuerung-sg-selbstkosten-calc', '1.075 Euro', true, 0),
  ('steuerung-sg-selbstkosten-calc', '946 Euro', false, 1),
  ('steuerung-sg-selbstkosten-calc', '1.020 Euro', false, 2),
  ('steuerung-sg-selbstkosten-calc', '946,50 Euro', false, 3),
  ('steuerung-sg-barverkaufspreis-calc', '1.182,50 Euro', true, 0),
  ('steuerung-sg-barverkaufspreis-calc', '1.075 Euro', false, 1),
  ('steuerung-sg-barverkaufspreis-calc', '1.161,25 Euro', false, 2),
  ('steuerung-sg-barverkaufspreis-calc', '1.290 Euro', false, 3),
  ('steuerung-sg-fixkosten-definition', 'Kosten, die unabhängig von der Beschäftigung in gleicher Höhe anfallen', true, 0),
  ('steuerung-sg-fixkosten-definition', 'Kosten, die proportional zur Ausbringungsmenge steigen', false, 1),
  ('steuerung-sg-fixkosten-definition', 'Kosten, die nur bei Vollauslastung entstehen', false, 2),
  ('steuerung-sg-fixkosten-definition', 'Kosten, die ausschließlich im Einkauf anfallen', false, 3),
  ('steuerung-sg-variable-kosten-definition', 'Kosten, die sich mit der Ausbringungsmenge verändern', true, 0),
  ('steuerung-sg-variable-kosten-definition', 'Kosten, die unabhängig von der Menge konstant bleiben', false, 1),
  ('steuerung-sg-variable-kosten-definition', 'Kosten, die nur einmalig bei der Anschaffung anfallen', false, 2),
  ('steuerung-sg-variable-kosten-definition', 'Kosten, die ausschließlich der Verwaltung zuzurechnen sind', false, 3),
  ('steuerung-sg-break-even-menge-calc', '3.000 Stück', true, 0),
  ('steuerung-sg-break-even-menge-calc', '2.000 Stück', false, 1),
  ('steuerung-sg-break-even-menge-calc', '1.200 Stück', false, 2),
  ('steuerung-sg-break-even-menge-calc', '3.750 Stück', false, 3),
  ('steuerung-sg-break-even-umsatz-calc', '100.000 Euro', true, 0),
  ('steuerung-sg-break-even-umsatz-calc', '40.000 Euro', false, 1),
  ('steuerung-sg-break-even-umsatz-calc', '66.667 Euro', false, 2),
  ('steuerung-sg-break-even-umsatz-calc', '160.000 Euro', false, 3),
  ('steuerung-sg-break-even-zielgewinn-calc', '2.400 Stück', true, 0),
  ('steuerung-sg-break-even-zielgewinn-calc', '2.000 Stück', false, 1),
  ('steuerung-sg-break-even-zielgewinn-calc', '2.800 Stück', false, 2),
  ('steuerung-sg-break-even-zielgewinn-calc', '400 Stück', false, 3),
  ('steuerung-sg-deckungsbeitrag-stueck-calc', '9.000 Euro', true, 0),
  ('steuerung-sg-deckungsbeitrag-stueck-calc', '13.500 Euro', false, 1),
  ('steuerung-sg-deckungsbeitrag-stueck-calc', '22.500 Euro', false, 2),
  ('steuerung-sg-deckungsbeitrag-stueck-calc', '18 Euro', false, 3),
  ('steuerung-sg-deckungsbeitrag-gesamt-calc', '10.000 Euro Gewinn', true, 0),
  ('steuerung-sg-deckungsbeitrag-gesamt-calc', '60.000 Euro Gewinn', false, 1),
  ('steuerung-sg-deckungsbeitrag-gesamt-calc', '10.000 Euro Verlust', false, 2),
  ('steuerung-sg-deckungsbeitrag-gesamt-calc', '150.000 Euro Gewinn', false, 3),
  ('steuerung-sg-deckungsbeitrag-mehrprodukt-calc', '4.000 Euro', true, 0),
  ('steuerung-sg-deckungsbeitrag-mehrprodukt-calc', '22.000 Euro', false, 1),
  ('steuerung-sg-deckungsbeitrag-mehrprodukt-calc', '18.000 Euro', false, 2),
  ('steuerung-sg-deckungsbeitrag-mehrprodukt-calc', '2.000 Euro', false, 3),
  ('steuerung-sg-soll-ist-abweichung', 'Negative Abweichung von 12.000 Euro (Kostenüberschreitung)', true, 0),
  ('steuerung-sg-soll-ist-abweichung', 'Positive Abweichung von 12.000 Euro', false, 1),
  ('steuerung-sg-soll-ist-abweichung', 'Keine Abweichung, da beide Werte im Rahmen der Planung liegen', false, 2),
  ('steuerung-sg-soll-ist-abweichung', 'Negative Abweichung von 8.000 Euro', false, 3),
  ('steuerung-sg-budgetierung-zweck', 'Vorgabe von Kosten- oder Erlöswerten als Maßstab für die spätere Ist-Entwicklung', true, 0),
  ('steuerung-sg-budgetierung-zweck', 'Nachträgliche Dokumentation bereits abgeschlossener Geschäftsjahre', false, 1),
  ('steuerung-sg-budgetierung-zweck', 'Ersatz für die Buchführung', false, 2),
  ('steuerung-sg-budgetierung-zweck', 'Berechnung der Umsatzsteuerschuld', false, 3),
  ('steuerung-sg-eigenfinanzierung-beispiel', 'Kapitalerhöhung durch Ausgabe neuer Aktien', true, 0),
  ('steuerung-sg-eigenfinanzierung-beispiel', 'Aufnahme eines Bankdarlehens', false, 1),
  ('steuerung-sg-eigenfinanzierung-beispiel', 'Ausnutzung eines Lieferantenkredits', false, 2),
  ('steuerung-sg-eigenfinanzierung-beispiel', 'Ausgabe einer Unternehmensanleihe', false, 3),
  ('steuerung-sg-fremdfinanzierung-beispiel', 'Ein von der Hausbank gewährtes Darlehen', true, 0),
  ('steuerung-sg-fremdfinanzierung-beispiel', 'Eine Kapitalerhöhung durch neue Gesellschafter', false, 1),
  ('steuerung-sg-fremdfinanzierung-beispiel', 'Einbehaltene Gewinne aus Vorjahren', false, 2),
  ('steuerung-sg-fremdfinanzierung-beispiel', 'Die Einlage eines neuen Gesellschafters', false, 3),
  ('steuerung-sg-kontokorrentkredit', 'Zur kurzfristigen Überbrückung von Liquiditätsengpässen', true, 0),
  ('steuerung-sg-kontokorrentkredit', 'Zur langfristigen Finanzierung von Maschinen', false, 1),
  ('steuerung-sg-kontokorrentkredit', 'Ausschließlich zur Finanzierung von Grundstücken', false, 2),
  ('steuerung-sg-kontokorrentkredit', 'Zur Ablösung von Eigenkapital', false, 3),
  ('steuerung-sg-darlehen-vs-kontokorrent', 'Weil Kontokorrentkredite flexibel, kurzfristig und meist ungesichert sind', true, 0),
  ('steuerung-sg-darlehen-vs-kontokorrent', 'Weil Darlehen grundsätzlich keine Zinsen kosten', false, 1),
  ('steuerung-sg-darlehen-vs-kontokorrent', 'Weil Kontokorrentkredite immer besser besichert sind als Darlehen', false, 2),
  ('steuerung-sg-darlehen-vs-kontokorrent', 'Weil für Darlehen keine Bonitätsprüfung nötig ist', false, 3),
  ('steuerung-sg-leasing-vorteil', 'Keine hohe Einmalzahlung, dadurch bleibt Liquidität erhalten', true, 0),
  ('steuerung-sg-leasing-vorteil', 'Der Leasinggegenstand geht sofort in das Eigentum des Leasingnehmers über', false, 1),
  ('steuerung-sg-leasing-vorteil', 'Leasing verursacht grundsätzlich keinerlei laufende Kosten', false, 2),
  ('steuerung-sg-leasing-vorteil', 'Leasingraten müssen nicht in der Buchführung erfasst werden', false, 3),
  ('steuerung-sg-liquiditaet-1-grades-calc', '20 Prozent', true, 0),
  ('steuerung-sg-liquiditaet-1-grades-calc', '50 Prozent', false, 1),
  ('steuerung-sg-liquiditaet-1-grades-calc', '80 Prozent', false, 2),
  ('steuerung-sg-liquiditaet-1-grades-calc', '5 Prozent', false, 3),
  ('steuerung-sg-liquiditaet-3-grades-calc', '100 Prozent', true, 0),
  ('steuerung-sg-liquiditaet-3-grades-calc', '80 Prozent', false, 1),
  ('steuerung-sg-liquiditaet-3-grades-calc', '50 Prozent', false, 2),
  ('steuerung-sg-liquiditaet-3-grades-calc', '120 Prozent', false, 3),
  ('steuerung-sg-kostenvergleichsrechnung-calc', '74.000 Euro', true, 0),
  ('steuerung-sg-kostenvergleichsrechnung-calc', '70.000 Euro', false, 1),
  ('steuerung-sg-kostenvergleichsrechnung-calc', '78.000 Euro', false, 2),
  ('steuerung-sg-kostenvergleichsrechnung-calc', '58.000 Euro', false, 3),
  ('steuerung-sg-gewinnvergleichsrechnung-calc', '6.000 Euro', true, 0),
  ('steuerung-sg-gewinnvergleichsrechnung-calc', '30.000 Euro', false, 1),
  ('steuerung-sg-gewinnvergleichsrechnung-calc', '80.000 Euro', false, 2),
  ('steuerung-sg-gewinnvergleichsrechnung-calc', '4.000 Euro', false, 3),
  ('steuerung-sg-rentabilitaetsrechnung-calc', '12 Prozent', true, 0),
  ('steuerung-sg-rentabilitaetsrechnung-calc', '6 Prozent', false, 1),
  ('steuerung-sg-rentabilitaetsrechnung-calc', '7,5 Prozent', false, 2),
  ('steuerung-sg-rentabilitaetsrechnung-calc', '8 Prozent', false, 3),
  ('steuerung-sg-amortisationsrechnung-calc', 'rund 3,85 Jahre', true, 0),
  ('steuerung-sg-amortisationsrechnung-calc', 'rund 5 Jahre', false, 1),
  ('steuerung-sg-amortisationsrechnung-calc', 'rund 16,7 Jahre', false, 2),
  ('steuerung-sg-amortisationsrechnung-calc', 'rund 3 Jahre', false, 3),
  ('steuerung-sg-umsatzsteuer-berechnung', '9.520 Euro', true, 0),
  ('steuerung-sg-umsatzsteuer-berechnung', '9.500 Euro', false, 1),
  ('steuerung-sg-umsatzsteuer-berechnung', '8.152 Euro', false, 2),
  ('steuerung-sg-umsatzsteuer-berechnung', '10.520 Euro', false, 3),
  ('steuerung-sg-eigenkapitalquote-calc', '30 Prozent', true, 0),
  ('steuerung-sg-eigenkapitalquote-calc', '35 Prozent', false, 1),
  ('steuerung-sg-eigenkapitalquote-calc', '15 Prozent', false, 2),
  ('steuerung-sg-eigenkapitalquote-calc', '333 Prozent', false, 3),
  ('steuerung-sg-eigenkapitalrentabilitaet-calc', '20 Prozent', true, 0),
  ('steuerung-sg-eigenkapitalrentabilitaet-calc', '5 Prozent', false, 1),
  ('steuerung-sg-eigenkapitalrentabilitaet-calc', '50 Prozent', false, 2),
  ('steuerung-sg-eigenkapitalrentabilitaet-calc', '18 Prozent', false, 3),
  ('steuerung-sg-skontosatz-effektivzins-calc', 'rund 36,7 Prozent', true, 0),
  ('steuerung-sg-skontosatz-effektivzins-calc', 'rund 24 Prozent', false, 1),
  ('steuerung-sg-skontosatz-effektivzins-calc', 'rund 2 Prozent', false, 2),
  ('steuerung-sg-skontosatz-effektivzins-calc', 'rund 18 Prozent', false, 3)
) as v(source_key, text, is_correct, sort_order)
on v.source_key = q.source_key;
