-- Industriekaufmann/-frau, Topic Geschaeftsprozesse: 75 selbst geschriebene
-- Fragen (30 multiple, 45 single), Praefix geschaeftsprozesse-. Deckt
-- Beschaffung, Lagerhaltung/Logistik, Produktion, Absatz/Marketing,
-- Auftragsabwicklung, Zahlungsverkehr, Projektmanagement, Prozessmanagement
-- und Digitalisierung ab, inklusive 10 durchgerechneten Kalkulationsaufgaben.
-- Keine Uebernahme aus realen IHK-Pruefungen.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'industriekaufmann'
join (values
  -- Beschaffung
  ('Geschäftsprozesse', 'geschaeftsprozesse-bedarfsermittlung-arten',
   'Wie wird der Bedarf an Rohstoffen und Bauteilen bezeichnet, der sich rechnerisch aus dem Bedarf an Fertigerzeugnissen ableitet?',
   'Der Primärbedarf betrifft die verkaufsfähigen Enderzeugnisse. Der davon abgeleitete Bedarf an Rohstoffen, Teilen und Baugruppen heißt Sekundärbedarf.',
   1, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-bestellmengenplanung-optimale',
   'Was beschreibt die optimale Bestellmenge in der Beschaffung?',
   'Die optimale Bestellmenge ist die Menge, bei der die Summe aus bestellfixen Kosten und Lagerhaltungskosten je Periode am geringsten ist. Größere Bestellmengen senken die Bestellkosten je Stück, erhöhen aber die Lagerkosten.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-bestellmenge',
   'Ein Betrieb hat einen Jahresbedarf von 2.400 Stück eines Normteils und bestellt gleichmäßig verteilt viermal im Jahr. Wie groß ist eine Bestellmenge?',
   'Der Jahresbedarf wird durch die Anzahl der Bestellungen geteilt: 2.400 Stück geteilt durch 4 ergibt 600 Stück je Bestellung.',
   1, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-angebotsvergleich-kriterien',
   'Welche Kriterien fließen typischerweise in den quantitativen Angebotsvergleich ein?',
   'Zum quantitativen Vergleich zählen rechenbare Größen wie Bezugspreis, Zahlungsbedingungen und Lieferzeit. Weiche Faktoren wie der persönliche Eindruck vom Verkäufer gehören zum qualitativen Vergleich.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-bezugspreis-1',
   'Ein Lieferant stellt für eine Bestellung einen Listeneinkaufspreis von 12.000 Euro in Rechnung. Der Käufer erhält 10 Prozent Liefererrabatt und bei fristgerechter Zahlung 2 Prozent Liefererskonto, außerdem fallen 300 Euro Bezugskosten an. Wie hoch ist der Bezugspreis?',
   'Zieleinkaufspreis: 12.000 Euro minus 10 Prozent Rabatt = 10.800 Euro. Bareinkaufspreis: 10.800 Euro minus 2 Prozent Skonto = 10.584 Euro. Bezugspreis: 10.584 Euro plus 300 Euro Bezugskosten = 10.884 Euro.',
   3, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-lieferantenauswahl-kriterien',
   'Welche Aspekte fließen üblicherweise in eine systematische Lieferantenbewertung ein?',
   'Bei der Lieferantenbewertung zählen unter anderem Liefertreue, Produktqualität und Preisniveau. Rein zufällige oder unternehmensfremde Merkmale spielen dagegen keine Rolle.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-rahmenvertrag-merkmale',
   'Welche Aussagen zu einem Rahmenvertrag in der Beschaffung treffen zu?',
   'Ein Rahmenvertrag legt Gesamtmenge, Zeitraum und wesentliche Konditionen wie den Preis vorab fest. Die konkrete Liefermenge wird später über einzelne Abrufe bestimmt, es muss also nicht jede Bestellung neu ausgehandelt werden.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-lieferverzug-rechte',
   'Welche Rechte stehen einem Käufer bei Lieferverzug des Verkäufers grundsätzlich zu?',
   'Bei Lieferverzug kann der Käufer in der Regel eine angemessene Nachfrist setzen und nach deren Ablauf vom Vertrag zurücktreten, außerdem kann er Schadensersatz verlangen. Eine sofortige Vertragsauflösung ohne jede Fristsetzung ist nur in Ausnahmefällen wie beim Fixgeschäft möglich.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-maengelruege-frist',
   'Wann muss ein Kaufmann eine gelieferte Ware im Handelskauf gemäß § 377 HGB auf Mängel untersuchen und rügen?',
   'Nach § 377 HGB muss die Ware unverzüglich, das heißt ohne schuldhaftes Zögern, nach Erhalt untersucht und ein erkennbarer Mangel unverzüglich gerügt werden. Andernfalls gilt die Ware als genehmigt.',
   3, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-gewaehrleistung-frist',
   'Wie lang ist die gesetzliche Gewährleistungsfrist beim Kauf einer neuen beweglichen Sache in der Regel?',
   'Die gesetzliche Gewährleistungsfrist für bewegliche Sachen beträgt grundsätzlich zwei Jahre ab Übergabe der Ware.',
   1, 'single'),
  -- Lagerhaltung und Logistik
  ('Geschäftsprozesse', 'geschaeftsprozesse-abc-analyse-zweck',
   'Wozu dient die ABC-Analyse im Lager- und Beschaffungswesen?',
   'Die ABC-Analyse klassifiziert Materialien nach ihrem Wertanteil am Gesamtbeschaffungsvolumen, damit sich Beschaffungs- und Kontrollaufwand auf die wertmäßig wichtigsten Artikel konzentrieren lässt.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-abc-analyse-merkmale',
   'Welche Aussagen zur ABC-Analyse treffen zu?',
   'A-Güter machen mengenmäßig meist einen kleinen Anteil, aber einen hohen Wertanteil aus, C-Güter verhalten sich umgekehrt. Die Analyse orientiert sich häufig am Pareto-Prinzip. Eine Gleichbehandlung aller Artikel widerspricht gerade dem Grundgedanken der Methode.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-just-in-time-merkmal',
   'Was ist ein zentrales Merkmal des Just-in-Time-Prinzips in der Beschaffung?',
   'Bei Just-in-Time werden Materialien in kleinen Mengen möglichst genau zum tatsächlichen Bedarfszeitpunkt angeliefert, wodurch die eigenen Lagerbestände deutlich gesenkt werden können.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-just-in-time-risiken',
   'Welche Risiken sind mit einer konsequenten Just-in-Time-Beschaffung verbunden?',
   'Just-in-Time erhöht die Abhängigkeit von der Zuverlässigkeit der Lieferanten, macht die Produktion störanfälliger bei Lieferengpässen und führt durch häufigere kleine Lieferungen oft zu höheren Transportkosten.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-inventur-pflicht',
   'Wer ist nach dem Handelsgesetzbuch grundsätzlich zur Durchführung einer Inventur verpflichtet?',
   'Nach dem HGB sind Kaufleute verpflichtet, zu Beginn ihrer Geschäftstätigkeit und zum Ende jedes Geschäftsjahres eine Inventur durchzuführen.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-inventurarten',
   'Welche Inventurverfahren sind nach den gesetzlichen Vereinfachungsregeln zulässig?',
   'Zulässig sind unter anderem die Stichtagsinventur, die permanente Inventur und die Stichprobeninventur. Eine Inventur ist keine einmalige Angelegenheit, sondern muss regelmäßig wiederholt werden.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-bestandsarten',
   'Welche Aussagen zu den verschiedenen Bestandsarten im Lager treffen zu?',
   'Der Meldebestand löst bei Unterschreitung eine neue Bestellung aus, der Höchstbestand soll aus Kapazitäts- und Kostengründen nicht überschritten werden, und der Sicherheitsbestand federt Nachfrage- und Lieferschwankungen ab. Der Meldebestand ist dabei fast nie null, sondern liegt deutlich darüber.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-lagerbestand-durchschnitt',
   'Ein Lager weist zu Jahresbeginn einen Bestand von 8.000 Euro und zum Jahresende einen Bestand von 12.000 Euro auf. Wie hoch ist der durchschnittliche Lagerbestand nach der vereinfachten Formel?',
   'Der durchschnittliche Lagerbestand ergibt sich aus (Anfangsbestand plus Endbestand) geteilt durch 2: (8.000 Euro plus 12.000 Euro) geteilt durch 2 gleich 10.000 Euro.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-lagerumschlag',
   'In einer Periode beträgt der Wareneinsatz 240.000 Euro, der durchschnittliche Lagerbestand liegt bei 40.000 Euro. Wie hoch ist die Lagerumschlagshäufigkeit?',
   'Die Lagerumschlagshäufigkeit ergibt sich aus Wareneinsatz geteilt durch durchschnittlichen Lagerbestand: 240.000 Euro geteilt durch 40.000 Euro gleich 6. Das Lager wird also sechsmal im Jahr umgeschlagen.',
   3, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-lagerdauer',
   'Die Lagerumschlagshäufigkeit eines Artikels beträgt 6. Wie hoch ist die durchschnittliche Lagerdauer in Tagen, wenn mit einem Geschäftsjahr von 360 Tagen gerechnet wird?',
   'Die durchschnittliche Lagerdauer ergibt sich aus 360 Tagen geteilt durch die Umschlagshäufigkeit: 360 geteilt durch 6 gleich 60 Tage.',
   3, 'single'),
  -- Produktion und Leistungserstellung
  ('Geschäftsprozesse', 'geschaeftsprozesse-fertigungsverfahren-einzelfertigung',
   'Was ist kennzeichnend für die Einzelfertigung?',
   'Bei der Einzelfertigung wird ein individuelles Produkt in geringer Stückzahl, häufig genau nach den Vorgaben eines Kunden, hergestellt, etwa im Sondermaschinenbau.',
   1, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-fertigungsverfahren-vergleich',
   'Welche Aussagen zu den Fertigungsverfahren nach der Wiederholhäufigkeit treffen zu?',
   'Bei der Massenfertigung wird über lange Zeit eine sehr große Stückzahl desselben Produkts hergestellt. Die Sortenfertigung stellt ähnliche Varianten eines Grundtyps her, die Serienfertigung produziert begrenzte Losgrößen. Die Einzelfertigung ist wegen fehlender Skaleneffekte meist nicht die Variante mit den günstigsten Stückkosten.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-produktionsplanung-ziel',
   'Was ist das zentrale Ziel der Produktionsplanung?',
   'Die Produktionsplanung soll Termine, Mengen und Kapazitäten so aufeinander abstimmen, dass Kundenaufträge wirtschaftlich, termingerecht und in der geforderten Qualität erfüllt werden können.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-qualitaetsmanagement-iso',
   'Wofür steht im Kern die Normenreihe ISO 9000?',
   'Die ISO-9000-Normenreihe beschreibt Anforderungen an ein systematisches Qualitätsmanagementsystem in Unternehmen.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-qualitaetsmanagement-instrumente',
   'Welche Instrumente werden im betrieblichen Qualitätsmanagement eingesetzt?',
   'Zu den gängigen Instrumenten zählen die Fehlersammelkarte zur Erfassung von Fehlerarten, das Ursache-Wirkungs-Diagramm zur Fehleranalyse sowie die statistische Prozesskontrolle zur laufenden Überwachung von Fertigungsprozessen.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-kapazitaetsplanung-engpass',
   'Wie wird der Produktionsfaktor bezeichnet, der die maximal mögliche Ausbringungsmenge eines Betriebs begrenzt?',
   'Dieser begrenzende Faktor wird als Engpass bezeichnet. Die Kapazitätsplanung richtet sich vor allem an diesem Engpass aus.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-kapazitaetsauslastung-massnahmen',
   'Welche Maßnahmen können bei einem kurzfristigen Kapazitätsengpass in der Produktion ergriffen werden?',
   'Möglich sind zum Beispiel Überstunden, die zeitweise Fremdvergabe einzelner Arbeitsschritte an Zulieferer sowie das Einrichten einer zusätzlichen Schicht. Termine einfach zu ignorieren ist keine geeignete Maßnahme.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-null-fehler-prinzip',
   'Was besagt das Null-Fehler-Prinzip im Qualitätsmanagement?',
   'Das Null-Fehler-Prinzip zielt darauf ab, Fehler möglichst direkt an ihrer Entstehungsquelle zu vermeiden, statt sie erst am Ende der Produktion durch Nacharbeit oder Ausschuss zu beheben.',
   2, 'single'),
  -- Absatz und Marketing
  ('Geschäftsprozesse', 'geschaeftsprozesse-marktforschung-primaer-sekundaer',
   'Worin unterscheidet sich die Primärforschung von der Sekundärforschung?',
   'Die Primärforschung erhebt eigens für die konkrete Fragestellung neue Daten, zum Beispiel durch Befragungen. Die Sekundärforschung greift dagegen auf bereits vorhandenes Material wie Statistiken oder Studien zurück.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-marktforschung-methoden',
   'Welche Methoden zählen zur Primärforschung im Rahmen der Marktforschung?',
   'Zur Primärforschung zählen die Befragung, die Beobachtung und das Experiment, da hierbei neue Daten erhoben werden. Die Auswertung bereits vorliegender amtlicher Statistiken ist dagegen Sekundärforschung.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-marketing-mix-4p',
   'Wie viele Instrumentalbereiche umfasst der klassische Marketing-Mix nach dem 4P-Modell?',
   'Der klassische Marketing-Mix umfasst vier Bereiche: Produktpolitik, Preispolitik, Distributionspolitik und Kommunikationspolitik.',
   1, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-marketing-mix-zuordnung',
   'Welche Maßnahmen gehören zur Kontrahierungs- beziehungsweise Preispolitik im Marketing-Mix?',
   'Zur Preispolitik zählen unter anderem Rabattstaffeln, Zahlungsbedingungen und Preisdifferenzierung. Die Wahl des Vertriebswegs gehört dagegen zur Distributionspolitik, nicht zur Preispolitik.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-vertriebswege-direkt-indirekt',
   'Was ist ein Merkmal des direkten Vertriebs?',
   'Beim direkten Vertrieb verkauft der Hersteller seine Produkte ohne zwischengeschaltete Absatzmittler unmittelbar an den Endkunden.',
   1, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-vertriebswege-eigenschaften',
   'Welche Aussagen zu Vertriebswegen treffen zu?',
   'Der indirekte Vertrieb nutzt Absatzmittler wie Großhandel oder Einzelhandel. Direkter Vertrieb ermöglicht in der Regel einen engeren Kundenkontakt, und der Online-Verkauf über den eigenen Shop ist eine Form des Direktvertriebs. Beim indirekten Vertrieb übernehmen die Absatzmittler einen Teil des Absatzrisikos, es liegt also nicht vollständig beim Hersteller.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-crm-zweck',
   'Welches Ziel verfolgt Customer-Relationship-Management in einem Industriebetrieb?',
   'CRM zielt darauf ab, langfristige und profitable Kundenbeziehungen aufzubauen und zu pflegen, gestützt auf systematisch erfasste und ausgewertete Kundendaten.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-verkaufsfoerderung-massnahmen',
   'Welche Maßnahmen zählen typischerweise zur Verkaufsförderung am Point of Sale?',
   'Zur Verkaufsförderung zählen etwa Produktproben, Verkaufswettbewerbe für den Handel und eine gezielte Warenpräsentation am Verkaufsort. Langfristig angelegte Imagewerbung im Fernsehen ist dagegen klassische Werbung und keine kurzfristige Verkaufsförderungsmaßnahme.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-marktsegmentierung-kriterium',
   'Was versteht man unter Marktsegmentierung?',
   'Marktsegmentierung bedeutet, den Gesamtmarkt in intern möglichst homogene und untereinander unterscheidbare Käufergruppen aufzuteilen, um sie gezielt anzusprechen.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-produktlebenszyklus-phasen',
   'In welcher Phase des Produktlebenszyklus sind Umsatz und Gewinn eines Produkts typischerweise am höchsten?',
   'In der Reifephase erreicht das Produkt üblicherweise seinen höchsten Umsatz und den höchsten Gewinn, bevor in der anschließenden Sättigungsphase die Wachstumsraten abflachen.',
   2, 'single'),
  -- Auftragsabwicklung
  ('Geschäftsprozesse', 'geschaeftsprozesse-auftragsabwicklung-reihenfolge',
   'Welches Dokument stellt der Verkäufer typischerweise unmittelbar nach der Bestellung des Kunden aus?',
   'Nach Eingang der Bestellung sendet der Verkäufer üblicherweise eine Auftragsbestätigung, mit der er den Auftrag zu den genannten Konditionen annimmt.',
   1, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-kaufvertrag-bestandteile',
   'Welche Angaben sind wesentliche Bestandteile eines wirksamen Kaufvertrags?',
   'Ein Kaufvertrag setzt eine Einigung über die zu liefernde Ware oder Leistung und den zu zahlenden Preis voraus, also übereinstimmende Willenserklärungen von Angebot und Annahme. Das Werbebudget des Verkäufers hat mit dem Vertragsinhalt nichts zu tun.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-angebot-bindungsfrist',
   'Welche Aussagen zur Bindung an ein Angebot treffen zu?',
   'Ein befristetes Angebot bindet den Anbieter bis zum Ablauf der genannten Frist. Ein unbefristetes Angebot kann innerhalb einer angemessenen Frist angenommen werden, und ein als freibleibend gekennzeichnetes Angebot begründet keine Bindung. Es trifft nicht zu, dass jedes Angebot grundsätzlich unbefristet gilt.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-reklamation-vorgehen',
   'Welche Schritte gehören zu einem professionellen Reklamationsmanagement?',
   'Dazu zählen die zeitnahe Bearbeitung eingehender Reklamationen, die saubere Dokumentation der Mängel sowie eine klare Rückmeldung an den Kunden über die geplante Lösung. Reklamationen grundsätzlich zu ignorieren gefährdet die Kundenbeziehung erheblich.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-bezugspreis-2',
   'Ein Betrieb bezieht Waren mit einem Listeneinkaufspreis von 8.000 Euro, erhält 5 Prozent Liefererrabatt und bei fristgerechter Zahlung 3 Prozent Liefererskonto. Zusätzlich fallen 200 Euro Bezugskosten an. Wie hoch ist der Bezugspreis?',
   'Zieleinkaufspreis: 8.000 Euro minus 5 Prozent Rabatt = 7.600 Euro. Bareinkaufspreis: 7.600 Euro minus 3 Prozent Skonto = 7.372 Euro. Bezugspreis: 7.372 Euro plus 200 Euro Bezugskosten = 7.572 Euro.',
   3, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-verkaufskalkulation-vorwaerts',
   'Ein Artikel hat einen Bezugspreis von 800 Euro. Der Handlungskostenzuschlag beträgt 25 Prozent, der Gewinnzuschlag 20 Prozent, das Kundenskonto 4 Prozent und der Kundenrabatt 20 Prozent. Wie hoch ist der Listenverkaufspreis?',
   'Selbstkosten: 800 Euro plus 25 Prozent Handlungskosten = 1.000 Euro. Barverkaufspreis: 1.000 Euro plus 20 Prozent Gewinn = 1.200 Euro. Da der Barverkaufspreis dem um 4 Prozent Skonto geminderten Zielverkaufspreis entspricht, ergibt sich der Zielverkaufspreis aus 1.200 Euro geteilt durch 0,96 gleich 1.250 Euro. Da dieser wiederum dem um 20 Prozent Rabatt geminderten Listenverkaufspreis entspricht, folgt der Listenverkaufspreis aus 1.250 Euro geteilt durch 0,8 gleich 1.562,50 Euro.',
   4, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-verkaufskalkulation-rueckwaerts',
   'Ein Produkt wird mit einem Listenverkaufspreis von 1.200 Euro angeboten. Der Kunde erhält 10 Prozent Rabatt und bei schneller Zahlung 2 Prozent Skonto. Kalkuliert wurde mit 20 Prozent Gewinnzuschlag und 25 Prozent Handlungskostenzuschlag. Wie hoch war der ursprüngliche Bezugspreis?',
   'Zielverkaufspreis: 1.200 Euro minus 10 Prozent Rabatt = 1.080 Euro. Barverkaufspreis: 1.080 Euro minus 2 Prozent Skonto = 1.058,40 Euro. Selbstkosten: 1.058,40 Euro geteilt durch 1,2 (Gewinnzuschlag 20 Prozent) = 882 Euro. Bezugspreis: 882 Euro geteilt durch 1,25 (Handlungskostenzuschlag 25 Prozent) = 705,60 Euro.',
   4, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-versandarten-inco',
   'Was regeln Incoterms im Rahmen der internationalen Auftragsabwicklung?',
   'Incoterms legen einheitlich fest, an welchem Punkt Transportkosten und Transportrisiko zwischen Käufer und Verkäufer übergehen und wer bestimmte Transport- und Versicherungsleistungen organisiert.',
   3, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-rechnungsangaben',
   'Welche Angaben muss eine ordnungsgemäße Rechnung nach dem Umsatzsteuerrecht grundsätzlich enthalten?',
   'Pflichtangaben sind unter anderem vollständiger Name und Anschrift von leistendem Unternehmen und Empfänger, die Steuernummer oder Umsatzsteuer-Identifikationsnummer, eine fortlaufende Rechnungsnummer sowie Steuersatz und Steuerbetrag. Die Bankverbindung ist dagegen keine zwingende gesetzliche Pflichtangabe.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-kalkulationsschema-aufbau',
   'Wie wird im Kalkulationsschema der Aufschlag bezeichnet, der aus dem Bezugspreis die Selbstkosten ergibt?',
   'Dieser Aufschlag wird als Handlungskostenzuschlag bezeichnet. Er deckt die im Betrieb anfallenden Kosten wie Verwaltung und Vertrieb, die zusätzlich zum Bezugspreis anfallen.',
   2, 'single'),
  -- Zahlungsverkehr
  ('Geschäftsprozesse', 'geschaeftsprozesse-zahlungsarten-vergleich',
   'Welche Aussagen zu gängigen Zahlungsarten im Geschäftsverkehr treffen zu?',
   'Vorkasse minimiert das Zahlungsausfallrisiko für den Verkäufer, da die Ware erst nach Zahlungseingang versendet wird. Eine Lastschrift setzt ein gültiges SEPA-Lastschriftmandat voraus. Für den Käufer ist der Kauf auf Rechnung am risikoärmsten, da er erst nach Erhalt der Ware zahlt. Nachnahme ist nicht dasselbe wie Vorkasse, da hier bei Zustellung gezahlt wird.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-skonto-definition',
   'Was versteht man unter Skonto?',
   'Skonto ist ein Preisnachlass, den der Verkäufer gewährt, wenn der Käufer innerhalb einer festgelegten kurzen Frist zahlt, statt das volle Zahlungsziel auszuschöpfen.',
   1, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-skonto-1',
   'Eine Rechnung über 5.000 Euro sieht 2 Prozent Skonto bei Zahlung innerhalb von 10 Tagen vor, ansonsten gilt ein Zahlungsziel von 30 Tagen netto. Wie hoch ist der Zahlbetrag bei Nutzung des Skontos?',
   'Der Skontobetrag beträgt 2 Prozent von 5.000 Euro, also 100 Euro. Der Zahlbetrag ergibt sich aus 5.000 Euro minus 100 Euro gleich 4.900 Euro.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-calc-skonto-2',
   'Ein Kunde erhält eine Rechnung über 15.000 Euro mit 2 Prozent Skonto bei Zahlung innerhalb von 14 Tagen. Er überweist den Betrag bereits am 10. Tag. Wie hoch ist der Zahlbetrag?',
   'Der Skontobetrag beträgt 2 Prozent von 15.000 Euro, also 300 Euro. Da fristgerecht gezahlt wurde, ergibt sich der Zahlbetrag aus 15.000 Euro minus 300 Euro gleich 14.700 Euro.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-mahnverfahren-stufen',
   'Welche Aussagen zum außergerichtlichen Mahnverfahren treffen zu?',
   'In der Praxis ist ein mehrstufiges Vorgehen mit Zahlungserinnerung sowie erster und zweiter Mahnung üblich. Bei Verzug können Verzugszinsen verlangt werden. Ist eine Zahlungsfrist kalendermäßig eindeutig bestimmt, gerät der Schuldner nach § 286 BGB auch ohne vorherige Mahnung in Verzug, eine Mahnung ist also nicht in jedem Fall zwingende Voraussetzung.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-inkasso-zweck',
   'Wozu beauftragen Unternehmen häufig ein Inkassounternehmen?',
   'Ein Inkassounternehmen wird beauftragt, um überfällige, unbezahlt gebliebene Forderungen gegenüber säumigen Schuldnern professionell durchzusetzen.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-mahnbescheid-gericht',
   'Wo wird der Antrag auf Erlass eines gerichtlichen Mahnbescheids gestellt?',
   'Der Antrag auf einen Mahnbescheid wird beim zuständigen Mahngericht gestellt, das ist regelmäßig ein bestimmtes Amtsgericht.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-zahlungsziel-bedeutung',
   'Welche Aussagen zum Zahlungsziel treffen zu?',
   'Das Zahlungsziel legt die Frist fest, bis zu der eine Rechnung spätestens zu begleichen ist. Es kann mit einem Skontoabzug bei früherer Zahlung kombiniert werden, und nach Ablauf ohne Zahlung gerät der Schuldner in Verzug. Ein Zahlungsziel schließt Skonto nicht aus, beides wird in der Praxis häufig gemeinsam vereinbart.',
   2, 'multiple'),
  -- Projektmanagement
  ('Geschäftsprozesse', 'geschaeftsprozesse-projektmanagement-merkmal',
   'Was kennzeichnet ein Projekt im Sinne der klassischen Projektmanagement-Definition?',
   'Ein Projekt ist ein zeitlich befristetes, einmaliges Vorhaben mit einem klar abgegrenzten Ziel und begrenzten Ressourcen, das sich von der wiederkehrenden Routinetätigkeit unterscheidet.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-projektphasen-reihenfolge',
   'Welche Phase folgt in einem klassischen Projektablauf typischerweise unmittelbar auf die Planungsphase?',
   'Nach der Planungsphase folgt die Durchführungsphase, in der die geplanten Maßnahmen tatsächlich umgesetzt werden.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-netzplan-zweck',
   'Wozu dient ein Netzplan im Projektmanagement?',
   'Ein Netzplan stellt die zeitlichen und logischen Abhängigkeiten zwischen den einzelnen Vorgängen eines Projekts dar und ermöglicht so unter anderem die Ermittlung des kritischen Pfads.',
   3, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-meilenstein-definition',
   'Was versteht man in einem Projekt unter einem Meilenstein?',
   'Ein Meilenstein ist ein Ereignis von besonderer Bedeutung mit der Dauer null, das genutzt wird, um den Fortschritt eines Projekts zu einem bestimmten Zeitpunkt zu überprüfen.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-projektphasen-aufgaben',
   'Welche Aufgaben fallen typischerweise in die Planungsphase eines Projekts?',
   'In der Planungsphase werden unter anderem die Terminplanung, die Ressourcenplanung und die Kostenplanung durchgeführt. Der Abschlussbericht wird dagegen erst in der Abschlussphase erstellt.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-kritischer-pfad-merkmale',
   'Welche Aussagen zum kritischen Pfad in einem Netzplan treffen zu?',
   'Der kritische Pfad ist die längste Kette zusammenhängender Vorgänge im Netzplan. Verzögerungen auf ihm verzögern unmittelbar den gesamten Projektendtermin, und die Vorgänge auf ihm besitzen keinen zeitlichen Puffer. Er ist damit gerade nicht der kürzeste, sondern der längste Weg durch den Netzplan.',
   3, 'multiple'),
  -- Prozessmanagement
  ('Geschäftsprozesse', 'geschaeftsprozesse-wertschoepfungskette-begriff',
   'Was beschreibt die Wertschöpfungskette nach dem Modell von Michael Porter?',
   'Die Wertschöpfungskette bildet die Abfolge der Aktivitäten eines Unternehmens ab, die gemeinsam zur Wertschöpfung eines Produkts oder einer Dienstleistung beitragen.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-wertschoepfungskette-aktivitaeten',
   'Welche Bereiche zählen zu den primären Aktivitäten der Wertschöpfungskette?',
   'Zu den primären Aktivitäten zählen unter anderem Eingangslogistik, Produktion sowie Marketing und Vertrieb, da sie unmittelbar zur Wertschöpfung beitragen. Die Personalwirtschaft ist dagegen eine unterstützende Aktivität.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-prozessoptimierung-ziel',
   'Was ist das Hauptziel der Prozessoptimierung in einem Unternehmen?',
   'Prozessoptimierung soll Durchlaufzeiten verkürzen und Kosten senken, ohne dabei die Qualität der Leistung zu verschlechtern, im Idealfall wird sie sogar verbessert.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-prozessoptimierung-methoden',
   'Welche Methoden werden zur Optimierung betrieblicher Prozesse eingesetzt?',
   'Eingesetzt werden unter anderem der kontinuierliche Verbesserungsprozess nach dem Kaizen-Gedanken, die Visualisierung von Abläufen in Ablaufdiagrammen sowie das Benchmarking mit anderen Unternehmen. Ein bewusstes Ignorieren von Schnittstellenproblemen trägt dagegen nicht zur Verbesserung bei.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-schnittstellen-abteilungen',
   'Was versteht man unter einer Schnittstelle zwischen zwei Abteilungen eines Unternehmens?',
   'Eine Schnittstelle ist der Übergabepunkt, an dem Informationen, Materialien oder Aufgaben von einer Organisationseinheit an eine andere weitergegeben werden.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-schnittstellenprobleme',
   'Welche Folgen können schlecht abgestimmte Schnittstellen zwischen Abteilungen haben?',
   'Mangelhaft abgestimmte Schnittstellen führen häufig zu Informationsverlusten, verlängerten Durchlaufzeiten und doppelter Datenerfassung in verschiedenen Systemen. Eine automatische Verbesserung der Prozessqualität ergibt sich daraus keinesfalls.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-prozesskette-kunde',
   'Wie wird ein Geschäftsprozess bezeichnet, der beim Bedarf eines Kunden beginnt und mit der Erfüllung dieses Bedarfs endet?',
   'Ein solcher kundenorientierter Ablauf wird als Kernprozess bezeichnet, da er unmittelbar auf die Wertschöpfung für den externen Kunden ausgerichtet ist.',
   2, 'single'),
  -- Digitalisierung im Geschäftsprozess
  ('Geschäftsprozesse', 'geschaeftsprozesse-erp-grundfunktion',
   'Was ist die zentrale Funktion eines ERP-Systems in einem Industriebetrieb?',
   'Ein ERP-System integriert und steuert die wichtigsten betrieblichen Ressourcen und Prozesse, etwa Einkauf, Produktion und Finanzen, auf einer gemeinsamen Datenbasis.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-erp-module',
   'Welche Bereiche werden typischerweise durch Module eines ERP-Systems abgedeckt?',
   'Typische Module decken unter anderem Materialwirtschaft und Einkauf, Produktion sowie Finanzbuchhaltung ab. Die private Social-Media-Nutzung von Mitarbeitern ist kein betrieblicher ERP-Bereich.',
   2, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-edi-definition',
   'Was bedeutet EDI im Zusammenhang mit Geschäftsprozessen?',
   'EDI steht für Electronic Data Interchange und bezeichnet den elektronischen Austausch strukturierter Geschäftsdaten, etwa Bestellungen oder Rechnungen, direkt zwischen den IT-Systemen unterschiedlicher Unternehmen.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-edi-vorteile',
   'Welche Vorteile bietet der Einsatz von EDI im Datenaustausch mit Geschäftspartnern?',
   'EDI beschleunigt die Auftragsabwicklung, reduziert manuelle Erfassungsfehler durch den Wegfall von Doppelerfassungen und senkt den Papieraufwand deutlich. Ein vollständiger Verzicht auf jegliche Datenformatstandards ist dagegen gerade nicht der Fall, EDI setzt vielmehr auf standardisierte Formate.',
   3, 'multiple'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-digitalisierung-schnittstelle-vorteil',
   'Welchen Vorteil bietet die digitale Anbindung von Lieferanten über standardisierte Schnittstellen?',
   'Eine standardisierte digitale Anbindung ermöglicht einen automatisierten und schnellen Datenaustausch, wodurch manuelle Übertragungsfehler reduziert und Bestellprozesse spürbar beschleunigt werden.',
   2, 'single'),
  ('Geschäftsprozesse', 'geschaeftsprozesse-digitalisierung-risiken',
   'Welche Risiken sind mit einer zunehmenden Digitalisierung von Geschäftsprozessen verbunden?',
   'Mit der Digitalisierung steigen die Anforderungen an die IT-Sicherheit, es entsteht eine stärkere Abhängigkeit von einer funktionierenden IT-Infrastruktur, und die Anforderungen an den Datenschutz nehmen zu. Digitalisierung beseitigt unternehmerisches Risiko keineswegs vollständig.',
   3, 'multiple')
) as v(topic_name, source_key, q, expl, difficulty, question_type) on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  ('geschaeftsprozesse-bedarfsermittlung-arten', 'Sekundärbedarf', true, 0),
  ('geschaeftsprozesse-bedarfsermittlung-arten', 'Primärbedarf', false, 1),
  ('geschaeftsprozesse-bedarfsermittlung-arten', 'Tertiärbedarf', false, 2),
  ('geschaeftsprozesse-bedarfsermittlung-arten', 'Nettobedarf', false, 3),

  ('geschaeftsprozesse-bestellmengenplanung-optimale', 'Die Menge, bei der Bestellkosten und Lagerhaltungskosten in Summe am geringsten sind', true, 0),
  ('geschaeftsprozesse-bestellmengenplanung-optimale', 'Die größtmögliche Menge, die der Lieferant liefern kann', false, 1),
  ('geschaeftsprozesse-bestellmengenplanung-optimale', 'Die Menge, die exakt dem Jahresbedarf entspricht', false, 2),
  ('geschaeftsprozesse-bestellmengenplanung-optimale', 'Die kleinstmögliche Bestellmenge, die der Lieferant akzeptiert', false, 3),

  ('geschaeftsprozesse-calc-bestellmenge', '600 Stück', true, 0),
  ('geschaeftsprozesse-calc-bestellmenge', '400 Stück', false, 1),
  ('geschaeftsprozesse-calc-bestellmenge', '2.400 Stück', false, 2),
  ('geschaeftsprozesse-calc-bestellmenge', '800 Stück', false, 3),

  ('geschaeftsprozesse-angebotsvergleich-kriterien', 'Bezugspreis', true, 0),
  ('geschaeftsprozesse-angebotsvergleich-kriterien', 'Zahlungsbedingungen', true, 1),
  ('geschaeftsprozesse-angebotsvergleich-kriterien', 'Lieferzeit', true, 2),
  ('geschaeftsprozesse-angebotsvergleich-kriterien', 'Persönliche Sympathie zum Verkäufer', false, 3),

  ('geschaeftsprozesse-calc-bezugspreis-1', '10.884,00 Euro', true, 0),
  ('geschaeftsprozesse-calc-bezugspreis-1', '10.800,00 Euro', false, 1),
  ('geschaeftsprozesse-calc-bezugspreis-1', '11.184,00 Euro', false, 2),
  ('geschaeftsprozesse-calc-bezugspreis-1', '10.584,00 Euro', false, 3),

  ('geschaeftsprozesse-lieferantenauswahl-kriterien', 'Liefertreue', true, 0),
  ('geschaeftsprozesse-lieferantenauswahl-kriterien', 'Produktqualität', true, 1),
  ('geschaeftsprozesse-lieferantenauswahl-kriterien', 'Preisniveau', true, 2),
  ('geschaeftsprozesse-lieferantenauswahl-kriterien', 'Schriftart auf der Rechnung', false, 3),

  ('geschaeftsprozesse-rahmenvertrag-merkmale', 'Gesamtmenge und Zeitraum sind vorab festgelegt', true, 0),
  ('geschaeftsprozesse-rahmenvertrag-merkmale', 'Die genaue Liefermenge wird über spätere Einzelabrufe bestimmt', true, 1),
  ('geschaeftsprozesse-rahmenvertrag-merkmale', 'Wesentliche Konditionen wie der Preis sind bereits fixiert', true, 2),
  ('geschaeftsprozesse-rahmenvertrag-merkmale', 'Jede einzelne Bestellung muss komplett neu verhandelt werden', false, 3),

  ('geschaeftsprozesse-lieferverzug-rechte', 'Nachfrist setzen und danach vom Vertrag zurücktreten', true, 0),
  ('geschaeftsprozesse-lieferverzug-rechte', 'Schadensersatz verlangen', true, 1),
  ('geschaeftsprozesse-lieferverzug-rechte', 'Gegebenenfalls einen Deckungskauf vornehmen', true, 2),
  ('geschaeftsprozesse-lieferverzug-rechte', 'Den Vertrag immer sofort ohne jede Fristsetzung auflösen', false, 3),

  ('geschaeftsprozesse-maengelruege-frist', 'Unverzüglich, also ohne schuldhaftes Zögern', true, 0),
  ('geschaeftsprozesse-maengelruege-frist', 'Erst nach Ablauf von sechs Monaten', false, 1),
  ('geschaeftsprozesse-maengelruege-frist', 'Nur bei ausdrücklicher Aufforderung durch den Lieferanten', false, 2),
  ('geschaeftsprozesse-maengelruege-frist', 'Es gibt keine gesetzliche Untersuchungspflicht unter Kaufleuten', false, 3),

  ('geschaeftsprozesse-gewaehrleistung-frist', 'Zwei Jahre', true, 0),
  ('geschaeftsprozesse-gewaehrleistung-frist', 'Sechs Monate', false, 1),
  ('geschaeftsprozesse-gewaehrleistung-frist', 'Fünf Jahre', false, 2),
  ('geschaeftsprozesse-gewaehrleistung-frist', 'Ein Jahr', false, 3),

  ('geschaeftsprozesse-abc-analyse-zweck', 'Klassifizierung der Materialien nach ihrem Wertanteil zur Priorisierung', true, 0),
  ('geschaeftsprozesse-abc-analyse-zweck', 'Ermittlung des optimalen Lagerstandorts', false, 1),
  ('geschaeftsprozesse-abc-analyse-zweck', 'Berechnung der Lohnkosten im Lager', false, 2),
  ('geschaeftsprozesse-abc-analyse-zweck', 'Festlegung der Urlaubsplanung des Lagerpersonals', false, 3),

  ('geschaeftsprozesse-abc-analyse-merkmale', 'A-Güter haben meist einen geringen Mengenanteil, aber hohen Wertanteil', true, 0),
  ('geschaeftsprozesse-abc-analyse-merkmale', 'C-Güter haben meist einen hohen Mengenanteil, aber geringen Wertanteil', true, 1),
  ('geschaeftsprozesse-abc-analyse-merkmale', 'Die Analyse orientiert sich häufig am Pareto-Prinzip', true, 2),
  ('geschaeftsprozesse-abc-analyse-merkmale', 'Alle Materialien werden im Ergebnis gleich behandelt', false, 3),

  ('geschaeftsprozesse-just-in-time-merkmal', 'Anlieferung in kleinen Mengen genau zum Bedarfszeitpunkt', true, 0),
  ('geschaeftsprozesse-just-in-time-merkmal', 'Aufbau möglichst hoher Sicherheitsbestände', false, 1),
  ('geschaeftsprozesse-just-in-time-merkmal', 'Einmalige Jahresbestellung der gesamten Menge', false, 2),
  ('geschaeftsprozesse-just-in-time-merkmal', 'Verzicht auf jegliche Lieferantenanbindung', false, 3),

  ('geschaeftsprozesse-just-in-time-risiken', 'Hohe Abhängigkeit von der Zuverlässigkeit der Lieferanten', true, 0),
  ('geschaeftsprozesse-just-in-time-risiken', 'Störanfälligkeit der Produktion bei Lieferengpässen', true, 1),
  ('geschaeftsprozesse-just-in-time-risiken', 'Häufig höhere Transportkosten durch kleinteilige Lieferungen', true, 2),
  ('geschaeftsprozesse-just-in-time-risiken', 'Sinkende Abhängigkeit von den Zulieferern', false, 3),

  ('geschaeftsprozesse-inventur-pflicht', 'Kaufleute nach den Vorschriften des HGB', true, 0),
  ('geschaeftsprozesse-inventur-pflicht', 'Nur börsennotierte Aktiengesellschaften', false, 1),
  ('geschaeftsprozesse-inventur-pflicht', 'Ausschließlich Betriebe mit eigenem Lager über 1.000 Quadratmeter', false, 2),
  ('geschaeftsprozesse-inventur-pflicht', 'Nur Unternehmen mit mehr als 500 Beschäftigten', false, 3),

  ('geschaeftsprozesse-inventurarten', 'Stichtagsinventur', true, 0),
  ('geschaeftsprozesse-inventurarten', 'Permanente Inventur', true, 1),
  ('geschaeftsprozesse-inventurarten', 'Stichprobeninventur', true, 2),
  ('geschaeftsprozesse-inventurarten', 'Eine einmalige Inventur bei Firmengründung reicht für die gesamte Unternehmensdauer', false, 3),

  ('geschaeftsprozesse-bestandsarten', 'Der Meldebestand löst bei Unterschreitung eine neue Bestellung aus', true, 0),
  ('geschaeftsprozesse-bestandsarten', 'Der Höchstbestand soll aus Kosten- und Kapazitätsgründen nicht überschritten werden', true, 1),
  ('geschaeftsprozesse-bestandsarten', 'Der Sicherheitsbestand federt Nachfrage- und Lieferschwankungen ab', true, 2),
  ('geschaeftsprozesse-bestandsarten', 'Der Meldebestand ist grundsätzlich gleich null', false, 3),

  ('geschaeftsprozesse-calc-lagerbestand-durchschnitt', '10.000 Euro', true, 0),
  ('geschaeftsprozesse-calc-lagerbestand-durchschnitt', '20.000 Euro', false, 1),
  ('geschaeftsprozesse-calc-lagerbestand-durchschnitt', '8.000 Euro', false, 2),
  ('geschaeftsprozesse-calc-lagerbestand-durchschnitt', '12.000 Euro', false, 3),

  ('geschaeftsprozesse-calc-lagerumschlag', '6', true, 0),
  ('geschaeftsprozesse-calc-lagerumschlag', '4', false, 1),
  ('geschaeftsprozesse-calc-lagerumschlag', '8', false, 2),
  ('geschaeftsprozesse-calc-lagerumschlag', '60', false, 3),

  ('geschaeftsprozesse-calc-lagerdauer', '60 Tage', true, 0),
  ('geschaeftsprozesse-calc-lagerdauer', '6 Tage', false, 1),
  ('geschaeftsprozesse-calc-lagerdauer', '30 Tage', false, 2),
  ('geschaeftsprozesse-calc-lagerdauer', '360 Tage', false, 3),

  ('geschaeftsprozesse-fertigungsverfahren-einzelfertigung', 'Herstellung eines individuellen Produkts in geringer Stückzahl nach Kundenvorgabe', true, 0),
  ('geschaeftsprozesse-fertigungsverfahren-einzelfertigung', 'Dauerhafte Herstellung sehr großer Stückzahlen desselben Produkts', false, 1),
  ('geschaeftsprozesse-fertigungsverfahren-einzelfertigung', 'Herstellung mehrerer Varianten eines Grundmodells in großer Zahl', false, 2),
  ('geschaeftsprozesse-fertigungsverfahren-einzelfertigung', 'Fertigung ausschließlich in vollautomatisierten Werken', false, 3),

  ('geschaeftsprozesse-fertigungsverfahren-vergleich', 'Bei der Massenfertigung wird über lange Zeit eine sehr große Stückzahl desselben Produkts hergestellt', true, 0),
  ('geschaeftsprozesse-fertigungsverfahren-vergleich', 'Die Sortenfertigung stellt ähnliche Varianten eines Grundtyps her', true, 1),
  ('geschaeftsprozesse-fertigungsverfahren-vergleich', 'Die Serienfertigung produziert in begrenzten Losgrößen', true, 2),
  ('geschaeftsprozesse-fertigungsverfahren-vergleich', 'Die Einzelfertigung hat wegen der hohen Stückzahl stets die günstigsten Stückkosten', false, 3),

  ('geschaeftsprozesse-produktionsplanung-ziel', 'Termine, Mengen und Kapazitäten so abzustimmen, dass Aufträge wirtschaftlich erfüllt werden', true, 0),
  ('geschaeftsprozesse-produktionsplanung-ziel', 'Ausschließlich die Personalkosten zu minimieren', false, 1),
  ('geschaeftsprozesse-produktionsplanung-ziel', 'Den Absatzmarkt für neue Produkte zu erschließen', false, 2),
  ('geschaeftsprozesse-produktionsplanung-ziel', 'Die Gestaltung der Firmenwerbung zu koordinieren', false, 3),

  ('geschaeftsprozesse-qualitaetsmanagement-iso', 'Anforderungen an ein Qualitätsmanagementsystem', true, 0),
  ('geschaeftsprozesse-qualitaetsmanagement-iso', 'Vorschriften zum Arbeitsschutz', false, 1),
  ('geschaeftsprozesse-qualitaetsmanagement-iso', 'Regeln zur Finanzbuchhaltung', false, 2),
  ('geschaeftsprozesse-qualitaetsmanagement-iso', 'Normen für die Verpackungsgestaltung', false, 3),

  ('geschaeftsprozesse-qualitaetsmanagement-instrumente', 'Fehlersammelkarte', true, 0),
  ('geschaeftsprozesse-qualitaetsmanagement-instrumente', 'Ursache-Wirkungs-Diagramm', true, 1),
  ('geschaeftsprozesse-qualitaetsmanagement-instrumente', 'Statistische Prozesskontrolle', true, 2),
  ('geschaeftsprozesse-qualitaetsmanagement-instrumente', 'Bilanzanalyse', false, 3),

  ('geschaeftsprozesse-kapazitaetsplanung-engpass', 'Engpass', true, 0),
  ('geschaeftsprozesse-kapazitaetsplanung-engpass', 'Sicherheitsbestand', false, 1),
  ('geschaeftsprozesse-kapazitaetsplanung-engpass', 'Deckungsbeitrag', false, 2),
  ('geschaeftsprozesse-kapazitaetsplanung-engpass', 'Meilenstein', false, 3),

  ('geschaeftsprozesse-kapazitaetsauslastung-massnahmen', 'Überstunden anordnen', true, 0),
  ('geschaeftsprozesse-kapazitaetsauslastung-massnahmen', 'Einzelne Arbeitsschritte zeitweise an Zulieferer vergeben', true, 1),
  ('geschaeftsprozesse-kapazitaetsauslastung-massnahmen', 'Eine zusätzliche Schicht einrichten', true, 2),
  ('geschaeftsprozesse-kapazitaetsauslastung-massnahmen', 'Liefertermine ohne Prüfung beliebig verschieben', false, 3),

  ('geschaeftsprozesse-null-fehler-prinzip', 'Fehler sollen bereits an der Entstehungsquelle vermieden werden', true, 0),
  ('geschaeftsprozesse-null-fehler-prinzip', 'Fehler werden erst am Ende der Produktion aussortiert', false, 1),
  ('geschaeftsprozesse-null-fehler-prinzip', 'Fehlerhafte Ware wird grundsätzlich weiterverkauft', false, 2),
  ('geschaeftsprozesse-null-fehler-prinzip', 'Qualitätskontrollen werden vollständig abgeschafft', false, 3),

  ('geschaeftsprozesse-marktforschung-primaer-sekundaer', 'Primärforschung erhebt neue Daten, Sekundärforschung nutzt vorhandenes Material', true, 0),
  ('geschaeftsprozesse-marktforschung-primaer-sekundaer', 'Beide Begriffe bezeichnen dasselbe Verfahren', false, 1),
  ('geschaeftsprozesse-marktforschung-primaer-sekundaer', 'Sekundärforschung findet immer vor der Primärforschung statt und ist verpflichtend', false, 2),
  ('geschaeftsprozesse-marktforschung-primaer-sekundaer', 'Primärforschung nutzt ausschließlich amtliche Statistiken', false, 3),

  ('geschaeftsprozesse-marktforschung-methoden', 'Befragung', true, 0),
  ('geschaeftsprozesse-marktforschung-methoden', 'Beobachtung', true, 1),
  ('geschaeftsprozesse-marktforschung-methoden', 'Experiment', true, 2),
  ('geschaeftsprozesse-marktforschung-methoden', 'Auswertung amtlicher Statistiken', false, 3),

  ('geschaeftsprozesse-marketing-mix-4p', 'Vier', true, 0),
  ('geschaeftsprozesse-marketing-mix-4p', 'Drei', false, 1),
  ('geschaeftsprozesse-marketing-mix-4p', 'Fünf', false, 2),
  ('geschaeftsprozesse-marketing-mix-4p', 'Sechs', false, 3),

  ('geschaeftsprozesse-marketing-mix-zuordnung', 'Rabattstaffel', true, 0),
  ('geschaeftsprozesse-marketing-mix-zuordnung', 'Zahlungsbedingungen', true, 1),
  ('geschaeftsprozesse-marketing-mix-zuordnung', 'Preisdifferenzierung', true, 2),
  ('geschaeftsprozesse-marketing-mix-zuordnung', 'Wahl des Vertriebswegs', false, 3),

  ('geschaeftsprozesse-vertriebswege-direkt-indirekt', 'Verkauf ohne zwischengeschaltete Absatzmittler direkt an den Endkunden', true, 0),
  ('geschaeftsprozesse-vertriebswege-direkt-indirekt', 'Verkauf ausschließlich über den Großhandel', false, 1),
  ('geschaeftsprozesse-vertriebswege-direkt-indirekt', 'Verkauf ausschließlich über Handelsvertreter', false, 2),
  ('geschaeftsprozesse-vertriebswege-direkt-indirekt', 'Verkauf, bei dem der Hersteller den Endkunden nie kennt', false, 3),

  ('geschaeftsprozesse-vertriebswege-eigenschaften', 'Der indirekte Vertrieb nutzt Absatzmittler wie Großhandel oder Einzelhandel', true, 0),
  ('geschaeftsprozesse-vertriebswege-eigenschaften', 'Direkter Vertrieb ermöglicht in der Regel einen engeren Kundenkontakt', true, 1),
  ('geschaeftsprozesse-vertriebswege-eigenschaften', 'Der Online-Verkauf über den eigenen Shop ist eine Form des Direktvertriebs', true, 2),
  ('geschaeftsprozesse-vertriebswege-eigenschaften', 'Beim indirekten Vertrieb trägt stets der Hersteller allein das gesamte Absatzrisiko', false, 3),

  ('geschaeftsprozesse-crm-zweck', 'Aufbau und Pflege langfristiger Kundenbeziehungen anhand systematisch erfasster Daten', true, 0),
  ('geschaeftsprozesse-crm-zweck', 'Reine Verwaltung der Lieferantenrechnungen', false, 1),
  ('geschaeftsprozesse-crm-zweck', 'Planung der internen Lagerlogistik', false, 2),
  ('geschaeftsprozesse-crm-zweck', 'Steuerung der Produktionskapazitäten', false, 3),

  ('geschaeftsprozesse-verkaufsfoerderung-massnahmen', 'Produktproben', true, 0),
  ('geschaeftsprozesse-verkaufsfoerderung-massnahmen', 'Verkaufswettbewerbe für den Handel', true, 1),
  ('geschaeftsprozesse-verkaufsfoerderung-massnahmen', 'Warenpräsentation am Verkaufsort', true, 2),
  ('geschaeftsprozesse-verkaufsfoerderung-massnahmen', 'Langfristig angelegte Imagewerbung im Fernsehen', false, 3),

  ('geschaeftsprozesse-marktsegmentierung-kriterium', 'Aufteilung des Gesamtmarkts in homogene Käufergruppen', true, 0),
  ('geschaeftsprozesse-marktsegmentierung-kriterium', 'Zusammenfassung aller Konkurrenten zu einer Gruppe', false, 1),
  ('geschaeftsprozesse-marktsegmentierung-kriterium', 'Festlegung eines einheitlichen Preises für alle Kunden', false, 2),
  ('geschaeftsprozesse-marktsegmentierung-kriterium', 'Reduzierung des Sortiments auf ein einziges Produkt', false, 3),

  ('geschaeftsprozesse-produktlebenszyklus-phasen', 'Reifephase', true, 0),
  ('geschaeftsprozesse-produktlebenszyklus-phasen', 'Einführungsphase', false, 1),
  ('geschaeftsprozesse-produktlebenszyklus-phasen', 'Rückgangsphase', false, 2),
  ('geschaeftsprozesse-produktlebenszyklus-phasen', 'Entwicklungsphase', false, 3),

  ('geschaeftsprozesse-auftragsabwicklung-reihenfolge', 'Auftragsbestätigung', true, 0),
  ('geschaeftsprozesse-auftragsabwicklung-reihenfolge', 'Angebot', false, 1),
  ('geschaeftsprozesse-auftragsabwicklung-reihenfolge', 'Anfrage', false, 2),
  ('geschaeftsprozesse-auftragsabwicklung-reihenfolge', 'Mahnung', false, 3),

  ('geschaeftsprozesse-kaufvertrag-bestandteile', 'Einigung über die zu liefernde Ware oder Leistung', true, 0),
  ('geschaeftsprozesse-kaufvertrag-bestandteile', 'Einigung über den zu zahlenden Preis', true, 1),
  ('geschaeftsprozesse-kaufvertrag-bestandteile', 'Übereinstimmende Willenserklärungen von Angebot und Annahme', true, 2),
  ('geschaeftsprozesse-kaufvertrag-bestandteile', 'Das Werbebudget des Verkäufers', false, 3),

  ('geschaeftsprozesse-angebot-bindungsfrist', 'Ein befristetes Angebot bindet den Anbieter bis zum Fristablauf', true, 0),
  ('geschaeftsprozesse-angebot-bindungsfrist', 'Ein unbefristetes Angebot kann innerhalb angemessener Frist angenommen werden', true, 1),
  ('geschaeftsprozesse-angebot-bindungsfrist', 'Ein als freibleibend gekennzeichnetes Angebot begründet keine Bindung', true, 2),
  ('geschaeftsprozesse-angebot-bindungsfrist', 'Jedes Angebot ist grundsätzlich unbefristet gültig', false, 3),

  ('geschaeftsprozesse-reklamation-vorgehen', 'Reklamationen zeitnah bearbeiten', true, 0),
  ('geschaeftsprozesse-reklamation-vorgehen', 'Mängel sauber dokumentieren', true, 1),
  ('geschaeftsprozesse-reklamation-vorgehen', 'Kunden klar über die geplante Lösung informieren', true, 2),
  ('geschaeftsprozesse-reklamation-vorgehen', 'Reklamationen grundsätzlich ignorieren, bis der Kunde erneut schreibt', false, 3),

  ('geschaeftsprozesse-calc-bezugspreis-2', '7.572,00 Euro', true, 0),
  ('geschaeftsprozesse-calc-bezugspreis-2', '7.372,00 Euro', false, 1),
  ('geschaeftsprozesse-calc-bezugspreis-2', '7.600,00 Euro', false, 2),
  ('geschaeftsprozesse-calc-bezugspreis-2', '7.800,00 Euro', false, 3),

  ('geschaeftsprozesse-calc-verkaufskalkulation-vorwaerts', '1.562,50 Euro', true, 0),
  ('geschaeftsprozesse-calc-verkaufskalkulation-vorwaerts', '1.250,00 Euro', false, 1),
  ('geschaeftsprozesse-calc-verkaufskalkulation-vorwaerts', '1.200,00 Euro', false, 2),
  ('geschaeftsprozesse-calc-verkaufskalkulation-vorwaerts', '1.440,00 Euro', false, 3),

  ('geschaeftsprozesse-calc-verkaufskalkulation-rueckwaerts', '705,60 Euro', true, 0),
  ('geschaeftsprozesse-calc-verkaufskalkulation-rueckwaerts', '882,00 Euro', false, 1),
  ('geschaeftsprozesse-calc-verkaufskalkulation-rueckwaerts', '1.058,40 Euro', false, 2),
  ('geschaeftsprozesse-calc-verkaufskalkulation-rueckwaerts', '750,00 Euro', false, 3),

  ('geschaeftsprozesse-versandarten-inco', 'Übergang von Transportkosten und Transportrisiko zwischen Käufer und Verkäufer', true, 0),
  ('geschaeftsprozesse-versandarten-inco', 'Die Höhe der Umsatzsteuer bei Auslandslieferungen', false, 1),
  ('geschaeftsprozesse-versandarten-inco', 'Die Gewährleistungsfrist für die gelieferte Ware', false, 2),
  ('geschaeftsprozesse-versandarten-inco', 'Die Kündigungsfristen von Lieferverträgen', false, 3),

  ('geschaeftsprozesse-rechnungsangaben', 'Vollständiger Name und Anschrift von leistendem Unternehmen und Empfänger', true, 0),
  ('geschaeftsprozesse-rechnungsangaben', 'Steuernummer oder Umsatzsteuer-Identifikationsnummer', true, 1),
  ('geschaeftsprozesse-rechnungsangaben', 'Fortlaufende Rechnungsnummer sowie Steuersatz und Steuerbetrag', true, 2),
  ('geschaeftsprozesse-rechnungsangaben', 'Bankverbindung als zwingende gesetzliche Pflichtangabe', false, 3),

  ('geschaeftsprozesse-kalkulationsschema-aufbau', 'Handlungskostenzuschlag', true, 0),
  ('geschaeftsprozesse-kalkulationsschema-aufbau', 'Gewinnzuschlag', false, 1),
  ('geschaeftsprozesse-kalkulationsschema-aufbau', 'Liefererrabatt', false, 2),
  ('geschaeftsprozesse-kalkulationsschema-aufbau', 'Kundenskonto', false, 3),

  ('geschaeftsprozesse-zahlungsarten-vergleich', 'Vorkasse minimiert das Zahlungsausfallrisiko für den Verkäufer', true, 0),
  ('geschaeftsprozesse-zahlungsarten-vergleich', 'Eine Lastschrift setzt ein gültiges SEPA-Mandat voraus', true, 1),
  ('geschaeftsprozesse-zahlungsarten-vergleich', 'Kauf auf Rechnung ist für den Käufer am risikoärmsten', true, 2),
  ('geschaeftsprozesse-zahlungsarten-vergleich', 'Nachnahme ist identisch mit Vorkasse', false, 3),

  ('geschaeftsprozesse-skonto-definition', 'Ein Preisnachlass für Zahlung innerhalb einer kurzen festgelegten Frist', true, 0),
  ('geschaeftsprozesse-skonto-definition', 'Ein Aufschlag für verspätete Zahlung', false, 1),
  ('geschaeftsprozesse-skonto-definition', 'Ein fester Bestandteil jeder Umsatzsteuer', false, 2),
  ('geschaeftsprozesse-skonto-definition', 'Ein Zuschlag für besonders schnelle Lieferung', false, 3),

  ('geschaeftsprozesse-calc-skonto-1', '4.900 Euro', true, 0),
  ('geschaeftsprozesse-calc-skonto-1', '5.000 Euro', false, 1),
  ('geschaeftsprozesse-calc-skonto-1', '4.800 Euro', false, 2),
  ('geschaeftsprozesse-calc-skonto-1', '4.950 Euro', false, 3),

  ('geschaeftsprozesse-calc-skonto-2', '14.700 Euro', true, 0),
  ('geschaeftsprozesse-calc-skonto-2', '15.000 Euro', false, 1),
  ('geschaeftsprozesse-calc-skonto-2', '14.400 Euro', false, 2),
  ('geschaeftsprozesse-calc-skonto-2', '14.850 Euro', false, 3),

  ('geschaeftsprozesse-mahnverfahren-stufen', 'Üblich ist ein mehrstufiges Vorgehen mit Zahlungserinnerung und Mahnungen', true, 0),
  ('geschaeftsprozesse-mahnverfahren-stufen', 'Bei Verzug können Verzugszinsen verlangt werden', true, 1),
  ('geschaeftsprozesse-mahnverfahren-stufen', 'Bei kalendermäßig bestimmter Frist tritt Verzug auch ohne Mahnung ein', true, 2),
  ('geschaeftsprozesse-mahnverfahren-stufen', 'Eine Mahnung ist in jedem Fall zwingende Voraussetzung für Verzug', false, 3),

  ('geschaeftsprozesse-inkasso-zweck', 'Durchsetzung überfälliger Forderungen gegenüber säumigen Schuldnern', true, 0),
  ('geschaeftsprozesse-inkasso-zweck', 'Erstellung der Jahresbilanz eines Unternehmens', false, 1),
  ('geschaeftsprozesse-inkasso-zweck', 'Prüfung von Angeboten neuer Lieferanten', false, 2),
  ('geschaeftsprozesse-inkasso-zweck', 'Planung der Marketingkampagnen', false, 3),

  ('geschaeftsprozesse-mahnbescheid-gericht', 'Beim zuständigen Mahngericht, in der Regel einem Amtsgericht', true, 0),
  ('geschaeftsprozesse-mahnbescheid-gericht', 'Beim zuständigen Finanzamt', false, 1),
  ('geschaeftsprozesse-mahnbescheid-gericht', 'Bei der Industrie- und Handelskammer', false, 2),
  ('geschaeftsprozesse-mahnbescheid-gericht', 'Beim Handelsregister', false, 3),

  ('geschaeftsprozesse-zahlungsziel-bedeutung', 'Es legt die Frist bis zur Fälligkeit der Rechnung fest', true, 0),
  ('geschaeftsprozesse-zahlungsziel-bedeutung', 'Es kann mit einem Skontoabzug bei früherer Zahlung kombiniert werden', true, 1),
  ('geschaeftsprozesse-zahlungsziel-bedeutung', 'Nach Ablauf ohne Zahlung gerät der Schuldner in Verzug', true, 2),
  ('geschaeftsprozesse-zahlungsziel-bedeutung', 'Ein Zahlungsziel schließt Skonto grundsätzlich aus', false, 3),

  ('geschaeftsprozesse-projektmanagement-merkmal', 'Zeitlich befristetes, einmaliges Vorhaben mit klar abgegrenztem Ziel', true, 0),
  ('geschaeftsprozesse-projektmanagement-merkmal', 'Eine dauerhaft wiederkehrende Routinetätigkeit', false, 1),
  ('geschaeftsprozesse-projektmanagement-merkmal', 'Eine Tätigkeit ohne definierten Zeitrahmen', false, 2),
  ('geschaeftsprozesse-projektmanagement-merkmal', 'Eine Aufgabe ohne festgelegtes Ziel', false, 3),

  ('geschaeftsprozesse-projektphasen-reihenfolge', 'Durchführungsphase', true, 0),
  ('geschaeftsprozesse-projektphasen-reihenfolge', 'Initiierungsphase', false, 1),
  ('geschaeftsprozesse-projektphasen-reihenfolge', 'Abschlussphase', false, 2),
  ('geschaeftsprozesse-projektphasen-reihenfolge', 'Definitionsphase', false, 3),

  ('geschaeftsprozesse-netzplan-zweck', 'Darstellung der Abhängigkeiten und Ermittlung des kritischen Pfads', true, 0),
  ('geschaeftsprozesse-netzplan-zweck', 'Berechnung der Materialkosten eines Projekts', false, 1),
  ('geschaeftsprozesse-netzplan-zweck', 'Erstellung der Rechnung an den Kunden', false, 2),
  ('geschaeftsprozesse-netzplan-zweck', 'Verwaltung der Personalakten der Projektmitarbeiter', false, 3),

  ('geschaeftsprozesse-meilenstein-definition', 'Ereignis von besonderer Bedeutung mit der Dauer null', true, 0),
  ('geschaeftsprozesse-meilenstein-definition', 'Ein Vorgang mit besonders langer Dauer', false, 1),
  ('geschaeftsprozesse-meilenstein-definition', 'Die letzte Aufgabe eines Projekts', false, 2),
  ('geschaeftsprozesse-meilenstein-definition', 'Ein finanzieller Puffer im Projektbudget', false, 3),

  ('geschaeftsprozesse-projektphasen-aufgaben', 'Terminplanung', true, 0),
  ('geschaeftsprozesse-projektphasen-aufgaben', 'Ressourcenplanung', true, 1),
  ('geschaeftsprozesse-projektphasen-aufgaben', 'Kostenplanung', true, 2),
  ('geschaeftsprozesse-projektphasen-aufgaben', 'Verfassen des Projektabschlussberichts', false, 3),

  ('geschaeftsprozesse-kritischer-pfad-merkmale', 'Er ist die längste Kette von Vorgängen im Netzplan', true, 0),
  ('geschaeftsprozesse-kritischer-pfad-merkmale', 'Verzögerungen auf ihm verzögern das Gesamtprojekt direkt', true, 1),
  ('geschaeftsprozesse-kritischer-pfad-merkmale', 'Vorgänge auf ihm haben keinen zeitlichen Puffer', true, 2),
  ('geschaeftsprozesse-kritischer-pfad-merkmale', 'Der kritische Pfad ist immer der kürzeste Weg durch den Netzplan', false, 3),

  ('geschaeftsprozesse-wertschoepfungskette-begriff', 'Die Abfolge der Aktivitäten, die zur Wertschöpfung eines Produkts beitragen', true, 0),
  ('geschaeftsprozesse-wertschoepfungskette-begriff', 'Die Liste aller Lieferanten eines Unternehmens', false, 1),
  ('geschaeftsprozesse-wertschoepfungskette-begriff', 'Die Aufstellung aller Konkurrenten in einer Branche', false, 2),
  ('geschaeftsprozesse-wertschoepfungskette-begriff', 'Die Reihenfolge der Buchungssätze in der Finanzbuchhaltung', false, 3),

  ('geschaeftsprozesse-wertschoepfungskette-aktivitaeten', 'Eingangslogistik', true, 0),
  ('geschaeftsprozesse-wertschoepfungskette-aktivitaeten', 'Produktion', true, 1),
  ('geschaeftsprozesse-wertschoepfungskette-aktivitaeten', 'Marketing und Vertrieb', true, 2),
  ('geschaeftsprozesse-wertschoepfungskette-aktivitaeten', 'Personalwirtschaft', false, 3),

  ('geschaeftsprozesse-prozessoptimierung-ziel', 'Durchlaufzeiten verkürzen und Kosten senken bei gleichbleibender oder besserer Qualität', true, 0),
  ('geschaeftsprozesse-prozessoptimierung-ziel', 'Ausschließlich die Anzahl der Mitarbeiter erhöhen', false, 1),
  ('geschaeftsprozesse-prozessoptimierung-ziel', 'Neue Produkte unabhängig von Kosten entwickeln', false, 2),
  ('geschaeftsprozesse-prozessoptimierung-ziel', 'Die Anzahl der Standorte vergrößern', false, 3),

  ('geschaeftsprozesse-prozessoptimierung-methoden', 'Kontinuierlicher Verbesserungsprozess nach Kaizen', true, 0),
  ('geschaeftsprozesse-prozessoptimierung-methoden', 'Prozessvisualisierung mittels Ablaufdiagramm', true, 1),
  ('geschaeftsprozesse-prozessoptimierung-methoden', 'Benchmarking mit anderen Unternehmen', true, 2),
  ('geschaeftsprozesse-prozessoptimierung-methoden', 'Bewusstes Ignorieren von Schnittstellenproblemen', false, 3),

  ('geschaeftsprozesse-schnittstellen-abteilungen', 'Übergabepunkt für Informationen, Materialien oder Aufgaben zwischen Organisationseinheiten', true, 0),
  ('geschaeftsprozesse-schnittstellen-abteilungen', 'Ein technisches Bauteil in der Produktionsmaschine', false, 1),
  ('geschaeftsprozesse-schnittstellen-abteilungen', 'Der Name der Buchhaltungssoftware', false, 2),
  ('geschaeftsprozesse-schnittstellen-abteilungen', 'Ein Synonym für den Unternehmenssitz', false, 3),

  ('geschaeftsprozesse-schnittstellenprobleme', 'Informationsverluste', true, 0),
  ('geschaeftsprozesse-schnittstellenprobleme', 'Verlängerte Durchlaufzeiten', true, 1),
  ('geschaeftsprozesse-schnittstellenprobleme', 'Doppelte Datenerfassung', true, 2),
  ('geschaeftsprozesse-schnittstellenprobleme', 'Automatische Verbesserung der Prozessqualität', false, 3),

  ('geschaeftsprozesse-prozesskette-kunde', 'Kernprozess', true, 0),
  ('geschaeftsprozesse-prozesskette-kunde', 'Unterstützungsprozess', false, 1),
  ('geschaeftsprozesse-prozesskette-kunde', 'Führungsprozess', false, 2),
  ('geschaeftsprozesse-prozesskette-kunde', 'Nebenprozess', false, 3),

  ('geschaeftsprozesse-erp-grundfunktion', 'Integration und Steuerung der wichtigsten betrieblichen Ressourcen auf einer gemeinsamen Datenbasis', true, 0),
  ('geschaeftsprozesse-erp-grundfunktion', 'Ausschließlich die Verwaltung von E-Mail-Postfächern', false, 1),
  ('geschaeftsprozesse-erp-grundfunktion', 'Die Gestaltung der Unternehmenswebsite', false, 2),
  ('geschaeftsprozesse-erp-grundfunktion', 'Reine Textverarbeitung für Verträge', false, 3),

  ('geschaeftsprozesse-erp-module', 'Materialwirtschaft und Einkauf', true, 0),
  ('geschaeftsprozesse-erp-module', 'Produktion', true, 1),
  ('geschaeftsprozesse-erp-module', 'Finanzbuchhaltung', true, 2),
  ('geschaeftsprozesse-erp-module', 'Private Social-Media-Nutzung der Mitarbeiter', false, 3),

  ('geschaeftsprozesse-edi-definition', 'Elektronischer Austausch strukturierter Geschäftsdaten zwischen IT-Systemen', true, 0),
  ('geschaeftsprozesse-edi-definition', 'Ein Verfahren zur manuellen Dateneingabe per Fax', false, 1),
  ('geschaeftsprozesse-edi-definition', 'Ein Standard für die Gestaltung von Firmenlogos', false, 2),
  ('geschaeftsprozesse-edi-definition', 'Eine Methode zur Berechnung von Verzugszinsen', false, 3),

  ('geschaeftsprozesse-edi-vorteile', 'Schnellere Auftragsabwicklung', true, 0),
  ('geschaeftsprozesse-edi-vorteile', 'Weniger manuelle Erfassungsfehler', true, 1),
  ('geschaeftsprozesse-edi-vorteile', 'Geringerer Papieraufwand', true, 2),
  ('geschaeftsprozesse-edi-vorteile', 'Vollständiger Verzicht auf jegliche Datenformatstandards', false, 3),

  ('geschaeftsprozesse-digitalisierung-schnittstelle-vorteil', 'Automatisierter, schneller Datenaustausch mit weniger Übertragungsfehlern', true, 0),
  ('geschaeftsprozesse-digitalisierung-schnittstelle-vorteil', 'Vollständiger Wegfall jeglicher IT-Kosten', false, 1),
  ('geschaeftsprozesse-digitalisierung-schnittstelle-vorteil', 'Automatische Erhöhung der Gewinnmarge', false, 2),
  ('geschaeftsprozesse-digitalisierung-schnittstelle-vorteil', 'Verzicht auf jede Form der Datenprüfung', false, 3),

  ('geschaeftsprozesse-digitalisierung-risiken', 'Höhere Anforderungen an die IT-Sicherheit', true, 0),
  ('geschaeftsprozesse-digitalisierung-risiken', 'Stärkere Abhängigkeit von funktionierender IT-Infrastruktur', true, 1),
  ('geschaeftsprozesse-digitalisierung-risiken', 'Steigende Anforderungen an den Datenschutz', true, 2),
  ('geschaeftsprozesse-digitalisierung-risiken', 'Digitalisierung beseitigt jegliches unternehmerisches Risiko vollständig', false, 3)
) as v(source_key, text, is_correct, sort_order) on v.source_key = q.source_key;
