-- Netzwerke-Erweiterung für fiae-ae: 40 neue, selbst geschriebene Fragen
-- (16 multiple, 24 single). Alle source_keys tragen das Präfix net2- und
-- wurden gegen den bestehenden Fragenpool geprüft. Inhaltlich bewusst in
-- Lücken gelegt: Subnetting mit Rechenaufgaben, Routing, Switching, VLAN-
-- Technik, Ports, TLS, WLAN, Verkabelung, Diagnosewerkzeuge und Cloud.
-- Keine Übernahme aus realen IHK-Prüfungen.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'fiae-ae'
join (values
  -- Subnetting und Adressierung (Rechenaufgaben)
  ('Netzwerke', 'net2-calc-hosts-27',
   'Wie viele nutzbare Hostadressen stehen in einem IPv4-Netz mit der Präfixlänge /27 zur Verfügung?',
   'Bei /27 bleiben 32-27 = 5 Hostbits, das ergibt 2^5 = 32 Adressen. Netzadresse und Broadcast-Adresse sind nicht an Hosts vergebbar, es bleiben also 30.',
   2, 'single'),
  ('Netzwerke', 'net2-calc-network-address',
   'Ein Rechner hat die Adresse 192.168.20.130 mit der Präfixlänge /26. Wie lautet die Netzadresse seines Subnetzes?',
   'Ein /26-Netz hat eine Blockgröße von 64. Die Subnetze beginnen bei .0, .64, .128 und .192. Die 130 liegt im Block 128 bis 191, die Netzadresse ist damit 192.168.20.128.',
   3, 'single'),
  ('Netzwerke', 'net2-calc-broadcast-28',
   'Wie lautet die Broadcast-Adresse des Subnetzes, in dem sich die Adresse 10.0.5.37/28 befindet?',
   'Bei /28 beträgt die Blockgröße 16. Der Host liegt im Bereich 10.0.5.32 bis 10.0.5.47. Die höchste Adresse dieses Bereichs ist die Broadcast-Adresse 10.0.5.47.',
   3, 'single'),
  ('Netzwerke', 'net2-calc-mask-cidr',
   'Welcher Präfixlänge in CIDR-Schreibweise entspricht die Subnetzmaske 255.255.255.240?',
   'Die ersten drei Oktette liefern 24 Einsen. Das letzte Oktett 240 entspricht binär 11110000 und steuert vier weitere Einsen bei. Zusammen ergibt das /28.',
   2, 'single'),
  ('Netzwerke', 'net2-calc-subnets-split',
   'Ein Netz 192.168.10.0/24 soll in gleich große Subnetze aufgeteilt werden, in denen jeweils mindestens 25 Hosts adressierbar sind. Welche Präfixlänge ist die passende und wie viele Subnetze entstehen dabei?',
   'Bei /27 bleiben 30 nutzbare Adressen, das reicht für 25 Hosts; /28 böte nur 14 und wäre zu klein. Aus einem /24 lassen sich 256 / 32 = 8 Subnetze der Größe /27 bilden.',
   4, 'single'),
  ('Netzwerke', 'net2-calc-vlsm-60hosts',
   'Eine Abteilung benötigt Adressen für 60 Endgeräte. Welche Präfixlänge ist die kleinste, die dafür ausreicht?',
   'Ein /26-Netz enthält 64 Adressen, abzüglich Netz- und Broadcast-Adresse bleiben 62 nutzbare. Ein /27 mit nur 30 nutzbaren Adressen wäre zu klein, ein /25 würde unnötig viele Adressen verschwenden.',
   3, 'single'),
  ('Netzwerke', 'net2-calc-same-subnet',
   'Zwei Rechner haben die Adressen 192.168.1.100 und 192.168.1.160, beide mit der Maske 255.255.255.192. Können sie ohne Router direkt miteinander kommunizieren?',
   'Die Maske entspricht /26 mit der Blockgröße 64. Die .100 liegt im Bereich 64 bis 127, die .160 im Bereich 128 bis 191. Beide liegen also in verschiedenen Subnetzen und benötigen einen Router.',
   3, 'single'),
  ('Netzwerke', 'net2-multi-subnet-172',
   'Gegeben ist das Netz 172.16.8.0/22. Welche Aussagen dazu treffen zu?',
   'Bei /22 stehen im dritten Oktett zwei Netzbits weniger zur Verfügung, die Maske lautet 255.255.252.0 und der Adressbereich reicht von 172.16.8.0 bis 172.16.11.255. Es bleiben 2^10 - 2 = 1022 nutzbare Hostadressen.',
   4, 'multiple'),
  -- Modelle, Routing, Switching
  ('Netzwerke', 'net2-tcpip-schichten',
   'Welche OSI-Schichten fasst die Anwendungsschicht des TCP/IP-Referenzmodells zusammen?',
   'Das TCP/IP-Modell kennt nur vier Schichten. Seine Anwendungsschicht deckt ab, was im OSI-Modell auf Sitzungs-, Darstellungs- und Anwendungsschicht verteilt ist, also die Schichten 5 bis 7.',
   3, 'single'),
  ('Netzwerke', 'net2-multi-routing',
   'Welche Aussagen über das Routing in IP-Netzen treffen zu?',
   'Statische Routen sind manuell gepflegte Einträge ohne automatische Anpassung. Bei mehreren passenden Einträgen entscheidet die längste Präfixübereinstimmung, und die Standardroute 0.0.0.0/0 greift, wenn kein spezifischerer Eintrag passt. OSPF ist ein Link-State-Protokoll, kein Distanzvektorprotokoll.',
   4, 'multiple'),
  ('Netzwerke', 'net2-multi-switch-vs-hub',
   'Welche Aussagen über die Arbeitsweise eines Switches treffen zu?',
   'Ein Switch schaltet jeden Port als eigene Kollisionsdomäne und lernt die MAC-Adressen aus den Quelladressen der eingehenden Frames. Ist ein Ziel noch unbekannt, flutet er den Frame auf alle übrigen Ports. Die Broadcast-Domäne bleibt dabei ungeteilt, dafür wären VLANs oder ein Router nötig.',
   3, 'multiple'),
  ('Netzwerke', 'net2-stp-zweck',
   'Wozu dient das Spanning Tree Protocol in einem Switch-Netzwerk?',
   'Redundante Verbindungen zwischen Switches erzeugen Schleifen, in denen Broadcasts endlos kreisen und das Netz lahmlegen. STP berechnet eine schleifenfreie Baumstruktur und setzt überzählige Ports in den Blocking-Zustand, hält sie aber als Reserve bereit.',
   3, 'single'),
  ('Netzwerke', 'net2-multi-vlan-technik',
   'Welche Aussagen zur technischen Umsetzung von VLANs treffen zu?',
   'IEEE 802.1Q ergänzt den Ethernet-Frame um ein Tag mit der VLAN-ID. Über einen Trunk-Port laufen mehrere VLANs auf einer Leitung, während ein Access-Port genau einem VLAN zugeordnet ist. Da VLANs getrennte Broadcast-Domänen bilden, braucht der Verkehr zwischen ihnen eine Instanz auf Schicht 3.',
   4, 'multiple'),
  ('Netzwerke', 'net2-multi-nat-pat',
   'Welche Aussagen zu NAT und PAT treffen zu?',
   'PAT bildet viele interne Verbindungen auf eine öffentliche Adresse ab und unterscheidet sie anhand der Quellports. Von außen initiierte Verbindungen finden ohne Portweiterleitung kein Ziel. Der Adressmangel bei IPv4 ist der eigentliche Grund für den NAT-Einsatz, eine Verschlüsselung leistet NAT nicht.',
   3, 'multiple'),
  -- Protokolle und Ports
  ('Netzwerke', 'net2-port-ssh',
   'Welchen Standardport verwendet SSH?',
   'SSH ist auf Port 22 registriert. Port 23 gehört zum unverschlüsselten Telnet, das SSH abgelöst hat, Port 21 zum Steuerkanal von FTP.',
   1, 'single'),
  ('Netzwerke', 'net2-port-dns',
   'Über welchen Port beantwortet ein DNS-Server gewöhnliche Namensanfragen?',
   'DNS nutzt Port 53, für kurze Anfragen üblicherweise über UDP und für größere Antworten oder Zonentransfers über TCP.',
   1, 'single'),
  ('Netzwerke', 'net2-port-ntp',
   'Welcher Dienst arbeitet standardmäßig auf Port 123?',
   'Port 123 gehört zum Network Time Protocol, das Systemuhren im Netz synchronisiert. SNMP nutzt 161, LDAP 389 und RDP 3389.',
   2, 'single'),
  ('Netzwerke', 'net2-snmp-zweck',
   'Wofür wird SNMP in der Netzwerkadministration eingesetzt?',
   'SNMP fragt Statuswerte wie Auslastung, Fehlerzähler oder Portzustände von Routern, Switches und Servern ab und erlaubt es den Geräten, per Trap selbst auf Störungen hinzuweisen.',
   2, 'single'),
  ('Netzwerke', 'net2-imap-vs-pop3',
   'Worin unterscheidet sich IMAP grundlegend von POP3?',
   'POP3 lädt Nachrichten herunter und entfernt sie typischerweise vom Server, IMAP verwaltet sie serverseitig samt Ordnerstruktur. Deshalb sehen mehrere Geräte bei IMAP denselben, synchronen Postfachzustand.',
   2, 'single'),
  ('Netzwerke', 'net2-multi-ports-mail',
   'Welche der folgenden Portnummern gehören zu klassischen E-Mail-Protokollen?',
   'Port 25 dient dem Nachrichtentransport per SMTP, Port 110 dem Abruf per POP3 und Port 143 dem Zugriff per IMAP. Port 53 gehört zu DNS, Port 3389 zum Remote Desktop Protocol.',
   2, 'multiple'),
  ('Netzwerke', 'net2-multi-udp-dienste',
   'Welche der folgenden Dienste setzen typischerweise auf UDP als Transportprotokoll?',
   'Kurze DNS-Anfragen, die Adressvergabe per DHCP und die Zeitsynchronisation per NTP kommen mit einzelnen kleinen Datagrammen aus, ein Verbindungsaufbau würde hier nur bremsen. SSH und die Datenübertragung per FTP brauchen dagegen die gesicherte Reihenfolge von TCP.',
   3, 'multiple'),
  ('Netzwerke', 'net2-multi-dns-records',
   'Welche Beschreibungen von DNS-Recordtypen sind korrekt?',
   'Der MX-Record benennt den für eine Domain zuständigen Mailserver, CNAME legt einen Alias auf einen anderen Namen an und AAAA verweist auf eine IPv6-Adresse. PTR dient der Rückwärtsauflösung von IP-Adresse zu Name, TXT enthält frei definierbare Textangaben wie SPF-Einträge.',
   2, 'multiple'),
  ('Netzwerke', 'net2-dhcp-dora',
   'In welcher Reihenfolge tauschen Client und Server die vier Nachrichten einer DHCP-Adressvergabe aus?',
   'Der Client sucht per Broadcast einen Server (Discover), der Server bietet eine Adresse an (Offer), der Client fordert genau dieses Angebot an (Request) und der Server bestätigt die Zuweisung (Acknowledge).',
   3, 'single'),
  ('Netzwerke', 'net2-apipa',
   'Welche Adresse konfiguriert ein Client selbst, wenn beim Start kein DHCP-Server antwortet?',
   'Ohne DHCP-Antwort weist sich der Client eine Adresse aus dem Bereich 169.254.0.0/16 zu. Damit ist nur Kommunikation im selben Segment möglich, ein Gateway oder DNS-Server fehlt. Eine solche Adresse ist deshalb ein klarer Hinweis auf ein DHCP-Problem.',
   3, 'single'),
  -- Diagnose und Leistungsgrößen
  ('Netzwerke', 'net2-traceroute-ttl',
   'Worauf beruht die Funktionsweise von traceroute beziehungsweise tracert?',
   'Das Werkzeug sendet Pakete mit schrittweise erhöhter TTL. Jeder Router, bei dem die TTL auf null fällt, verwirft das Paket und meldet dies per ICMP zurück. Aus diesen Meldungen entsteht die Liste der Zwischenstationen.',
   4, 'single'),
  ('Netzwerke', 'net2-multi-troubleshooting-tools',
   'Welche Aussagen über gängige Diagnosewerkzeuge treffen zu?',
   'tracert zeigt den Pfad zum Ziel, nslookup fragt gezielt einen Nameserver ab und netstat listet die Verbindungen und lauschenden Ports des lokalen Systems. ping prüft nur Erreichbarkeit und Antwortzeit, nicht die Bandbreite, und ipconfig wirkt ausschließlich lokal.',
   2, 'multiple'),
  ('Netzwerke', 'net2-mtu-fragmentierung',
   'Was gibt die MTU einer Netzwerkverbindung an?',
   'Die MTU ist die größte Nutzlast, die in einem einzelnen Paket übertragen werden kann, im Ethernet üblicherweise 1500 Byte. Größere Datenmengen müssen fragmentiert werden, was zusätzlichen Overhead verursacht.',
   3, 'single'),
  ('Netzwerke', 'net2-qos',
   'Welchen Zweck verfolgt Quality of Service in einem Netzwerk?',
   'QoS ordnet Datenströme in Klassen ein und bevorzugt zeitkritischen Verkehr wie Sprache oder Video, wenn die Leitung ausgelastet ist. Die verfügbare Bandbreite wächst dadurch nicht, sie wird nur anders verteilt.',
   2, 'single'),
  -- Sicherheit, TLS, VPN
  ('Netzwerke', 'net2-multi-tls-zertifikat',
   'Welche Aussagen über TLS-Serverzertifikate treffen zu?',
   'Ein Zertifikat verknüpft einen öffentlichen Schlüssel mit einem Namen und wird durch die Signatur einer Zertifizierungsstelle überprüfbar. Der private Schlüssel bleibt beim Server und wird nie mitgeliefert. Läuft die Gültigkeit ab, kann der Client die Bindung nicht mehr bestätigen und warnt.',
   3, 'multiple'),
  ('Netzwerke', 'net2-tls-handshake-schluessel',
   'Welche Rolle spielt das asymmetrische Verfahren im TLS-Handshake?',
   'Asymmetrische Kryptografie ist rechenaufwendig und wird deshalb nur zur Authentifizierung des Servers und zum sicheren Aushandeln eines gemeinsamen Sitzungsschlüssels genutzt. Die eigentlichen Nutzdaten verschlüsselt anschließend ein schnelles symmetrisches Verfahren.',
   4, 'single'),
  ('Netzwerke', 'net2-multi-firewall-typen',
   'Welche Aussagen über Firewalls und Netzwerksegmentierung treffen zu?',
   'Ein einfacher Paketfilter bewertet jedes Paket isoliert anhand von Adressen, Ports und Protokoll. Eine Stateful-Inspection-Firewall führt zusätzlich eine Verbindungstabelle und erkennt so Antwortpakete als zugehörig. In einer DMZ stehen von außen erreichbare Dienste, damit ein kompromittierter Server nicht direkt im internen Netz steht.',
   3, 'multiple'),
  ('Netzwerke', 'net2-multi-angriffe',
   'Welche Aussagen über Angriffe und Schutzsysteme im Netzwerk treffen zu?',
   'Beim ARP-Spoofing beantwortet der Angreifer ARP-Anfragen mit der eigenen MAC-Adresse und lenkt den Verkehr über sich. Ein DDoS-Angriff erschöpft Ressourcen aus vielen Quellen gleichzeitig, und ein Portscan dient der Erkundung offener Dienste. Ein IDS erkennt und meldet nur, erst ein IPS greift aktiv ein.',
   3, 'multiple'),
  ('Netzwerke', 'net2-vpn-site-to-site',
   'Was kennzeichnet ein Site-to-Site-VPN im Unterschied zu einem Client-to-Site-VPN?',
   'Beim Site-to-Site-VPN bauen die Gateways zweier Standorte einen dauerhaften Tunnel auf. Die Endgeräte in beiden Netzen brauchen keine eigene VPN-Software, für sie wirkt die Verbindung wie eine normale Route ins andere Netz.',
   3, 'single'),
  ('Netzwerke', 'net2-proxy-reverse',
   'Worin unterscheidet sich ein Reverse Proxy von einem klassischen Forward Proxy?',
   'Ein Forward Proxy steht auf der Clientseite und leitet ausgehende Anfragen weiter. Ein Reverse Proxy steht vor den eigenen Servern, nimmt die Anfragen aus dem Internet entgegen und verteilt sie intern, häufig verbunden mit TLS-Terminierung und Lastverteilung.',
   3, 'single'),
  -- WLAN, Verkabelung, Virtualisierung
  ('Netzwerke', 'net2-multi-wpa3',
   'Welche Aussagen zur Absicherung eines WLANs treffen zu?',
   'WPA3 ersetzt den angreifbaren PSK-Handshake durch SAE und schützt so auch schwache Passwörter besser gegen Offline-Angriffe. WEP ist seit Langem gebrochen. WPA2-Enterprise verlagert die Authentifizierung auf einen RADIUS-Server, sodass jeder Nutzer eigene Zugangsdaten hat. Versteckte SSIDs und MAC-Filter sind mit einfachen Mitteln zu umgehen.',
   3, 'multiple'),
  ('Netzwerke', 'net2-wlan-5ghz',
   'Welchen Vorteil bietet das 5-GHz-Band gegenüber dem 2,4-GHz-Band?',
   'Im 5-GHz-Band stehen deutlich mehr überlappungsfreie Kanäle und breitere Kanalbandbreiten zur Verfügung, was höhere Datenraten erlaubt. Dafür ist die Reichweite geringer, weil hohe Frequenzen Wände und Decken schlechter durchdringen.',
   2, 'single'),
  ('Netzwerke', 'net2-multi-kabel-medien',
   'Welche Aussagen über Übertragungsmedien treffen zu?',
   'Im Ethernet gilt für Twisted-Pair-Kupferstrecken die Grenze von 100 m je Segment, danach steigt die Dämpfung zu stark. Lichtwellenleiter übertragen optisch und sind deshalb gegen elektromagnetische Einstreuung unempfindlich. Die Verdrillung der Adernpaare hebt eingestreute Störungen weitgehend auf. Singlemode-Fasern sind gerade für lange Strecken gedacht.',
   2, 'multiple'),
  ('Netzwerke', 'net2-poe',
   'Was ermöglicht Power over Ethernet?',
   'Bei PoE liefert der Switch die Betriebsspannung über dieselbe Twisted-Pair-Leitung, über die auch die Daten laufen. Access Points, IP-Kameras oder Telefone brauchen dadurch keine eigene Steckdose am Montageort.',
   1, 'single'),
  ('Netzwerke', 'net2-multi-cloud-netz',
   'Welche Aussagen über Netzwerke in virtualisierten und Cloud-Umgebungen treffen zu?',
   'Der Hypervisor stellt einen virtuellen Switch bereit, über den die VMs untereinander und nach außen kommunizieren. Ein Load Balancer verteilt eingehende Anfragen auf mehrere Backend-Instanzen. Sicherheitsgruppen wirken als Paketfilter direkt an der einzelnen Instanz. Container teilen sich in der Regel die Adresse des Hosts und werden über Portmapping erreichbar.',
   4, 'multiple'),
  ('Netzwerke', 'net2-multi-ipv6-eigenschaften',
   'Welche Aussagen über IPv6-Adressen treffen zu?',
   'Eine IPv6-Adresse ist 128 Bit lang und wird hexadezimal in acht Blöcken notiert. Die Kurzschreibweise :: darf zusammenhängende Nullblöcke ersetzen, aber nur einmal pro Adresse, sonst wäre sie nicht mehr eindeutig auflösbar. Adressen mit dem Präfix fe80:: gelten nur im lokalen Link.',
   3, 'multiple')
) as v(topic_name, source_key, q, expl, difficulty, question_type)
on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- net2-calc-hosts-27
  ('net2-calc-hosts-27', '30', true, 0),
  ('net2-calc-hosts-27', '32', false, 1),
  ('net2-calc-hosts-27', '14', false, 2),
  ('net2-calc-hosts-27', '62', false, 3),
  -- net2-calc-network-address
  ('net2-calc-network-address', '192.168.20.128', true, 0),
  ('net2-calc-network-address', '192.168.20.64', false, 1),
  ('net2-calc-network-address', '192.168.20.129', false, 2),
  ('net2-calc-network-address', '192.168.20.192', false, 3),
  -- net2-calc-broadcast-28
  ('net2-calc-broadcast-28', '10.0.5.47', true, 0),
  ('net2-calc-broadcast-28', '10.0.5.48', false, 1),
  ('net2-calc-broadcast-28', '10.0.5.46', false, 2),
  ('net2-calc-broadcast-28', '10.0.5.63', false, 3),
  -- net2-calc-mask-cidr
  ('net2-calc-mask-cidr', '/28', true, 0),
  ('net2-calc-mask-cidr', '/27', false, 1),
  ('net2-calc-mask-cidr', '/29', false, 2),
  ('net2-calc-mask-cidr', '/26', false, 3),
  -- net2-calc-subnets-split
  ('net2-calc-subnets-split', '/27, daraus entstehen 8 Subnetze', true, 0),
  ('net2-calc-subnets-split', '/26, daraus entstehen 4 Subnetze', false, 1),
  ('net2-calc-subnets-split', '/28, daraus entstehen 16 Subnetze', false, 2),
  ('net2-calc-subnets-split', '/27, daraus entstehen 6 Subnetze', false, 3),
  -- net2-calc-vlsm-60hosts
  ('net2-calc-vlsm-60hosts', '/26', true, 0),
  ('net2-calc-vlsm-60hosts', '/27', false, 1),
  ('net2-calc-vlsm-60hosts', '/25', false, 2),
  ('net2-calc-vlsm-60hosts', '/24', false, 3),
  -- net2-calc-same-subnet
  ('net2-calc-same-subnet', 'Nein, die .100 liegt im Block 64 bis 127 und die .160 im Block 128 bis 191', true, 0),
  ('net2-calc-same-subnet', 'Ja, beide gehören zum Netz 192.168.1.0/26', false, 1),
  ('net2-calc-same-subnet', 'Ja, weil die ersten drei Oktette übereinstimmen', false, 2),
  ('net2-calc-same-subnet', 'Nein, weil 192.168.1.160 die Broadcast-Adresse ihres Subnetzes ist', false, 3),
  -- net2-multi-subnet-172
  ('net2-multi-subnet-172', 'Die zugehörige Subnetzmaske lautet 255.255.252.0', true, 0),
  ('net2-multi-subnet-172', 'Die Broadcast-Adresse ist 172.16.11.255', true, 1),
  ('net2-multi-subnet-172', 'Es sind 1022 Hostadressen nutzbar', true, 2),
  ('net2-multi-subnet-172', 'Die Adresse 172.16.12.5 gehört noch zu diesem Netz', false, 3),
  ('net2-multi-subnet-172', 'Die zugehörige Subnetzmaske lautet 255.255.254.0', false, 4),
  -- net2-tcpip-schichten
  ('net2-tcpip-schichten', 'Die OSI-Schichten 5 bis 7', true, 0),
  ('net2-tcpip-schichten', 'Die OSI-Schichten 4 bis 7', false, 1),
  ('net2-tcpip-schichten', 'Nur die OSI-Schichten 6 und 7', false, 2),
  ('net2-tcpip-schichten', 'Die OSI-Schichten 1 und 2', false, 3),
  -- net2-multi-routing
  ('net2-multi-routing', 'Statische Routen müssen manuell gepflegt werden', true, 0),
  ('net2-multi-routing', 'Passen mehrere Einträge, gewinnt der mit der längsten Präfixübereinstimmung', true, 1),
  ('net2-multi-routing', 'Die Standardroute wird als 0.0.0.0/0 notiert', true, 2),
  ('net2-multi-routing', 'OSPF ist ein Distanzvektorprotokoll', false, 3),
  ('net2-multi-routing', 'Ein Router puffert Pakete ohne passende Route, bis eine Route entsteht', false, 4),
  -- net2-multi-switch-vs-hub
  ('net2-multi-switch-vs-hub', 'Jeder Port bildet eine eigene Kollisionsdomäne', true, 0),
  ('net2-multi-switch-vs-hub', 'Der Switch lernt MAC-Adressen aus den Quelladressen eingehender Frames', true, 1),
  ('net2-multi-switch-vs-hub', 'Ist die Ziel-MAC-Adresse unbekannt, wird der Frame auf alle anderen Ports geflutet', true, 2),
  ('net2-multi-switch-vs-hub', 'Ein Switch teilt standardmäßig auch die Broadcast-Domäne auf', false, 3),
  ('net2-multi-switch-vs-hub', 'Jeder Port benötigt eine eigene IP-Adresse', false, 4),
  -- net2-stp-zweck
  ('net2-stp-zweck', 'Es verhindert Schleifen in redundant verkabelten Netzen, indem es überzählige Ports blockiert', true, 0),
  ('net2-stp-zweck', 'Es verteilt den Verkehr gleichmäßig auf alle vorhandenen Leitungen', false, 1),
  ('net2-stp-zweck', 'Es vergibt automatisch VLAN-IDs an die angeschlossenen Ports', false, 2),
  ('net2-stp-zweck', 'Es verschlüsselt Frames zwischen benachbarten Switches', false, 3),
  -- net2-multi-vlan-technik
  ('net2-multi-vlan-technik', 'IEEE 802.1Q fügt dem Ethernet-Frame ein Tag mit der VLAN-ID hinzu', true, 0),
  ('net2-multi-vlan-technik', 'Ein Trunk-Port überträgt Frames mehrerer VLANs über eine Leitung', true, 1),
  ('net2-multi-vlan-technik', 'Für Verkehr zwischen zwei VLANs wird ein Router oder Layer-3-Switch benötigt', true, 2),
  ('net2-multi-vlan-technik', 'Ein Access-Port gehört gleichzeitig zu allen konfigurierten VLANs', false, 3),
  ('net2-multi-vlan-technik', 'VLANs verschlüsseln den Verkehr zwischen den Segmenten', false, 4),
  -- net2-multi-nat-pat
  ('net2-multi-nat-pat', 'Bei PAT unterscheidet der Router die Verbindungen zusätzlich anhand der Portnummern', true, 0),
  ('net2-multi-nat-pat', 'Für eingehende Verbindungen auf einen internen Server ist eine Portweiterleitung nötig', true, 1),
  ('net2-multi-nat-pat', 'NAT senkt den Bedarf an öffentlichen IPv4-Adressen', true, 2),
  ('net2-multi-nat-pat', 'NAT verschlüsselt die übersetzten Pakete', false, 3),
  ('net2-multi-nat-pat', 'In IPv6-Netzen ist NAT zwingend vorgeschrieben', false, 4),
  -- net2-port-ssh
  ('net2-port-ssh', '22', true, 0),
  ('net2-port-ssh', '23', false, 1),
  ('net2-port-ssh', '21', false, 2),
  ('net2-port-ssh', '25', false, 3),
  -- net2-port-dns
  ('net2-port-dns', '53', true, 0),
  ('net2-port-dns', '67', false, 1),
  ('net2-port-dns', '43', false, 2),
  ('net2-port-dns', '123', false, 3),
  -- net2-port-ntp
  ('net2-port-ntp', 'NTP', true, 0),
  ('net2-port-ntp', 'SNMP', false, 1),
  ('net2-port-ntp', 'LDAP', false, 2),
  ('net2-port-ntp', 'RDP', false, 3),
  -- net2-snmp-zweck
  ('net2-snmp-zweck', 'Zur Überwachung und Verwaltung von Netzwerkgeräten', true, 0),
  ('net2-snmp-zweck', 'Zur Synchronisation der Systemzeit im Netz', false, 1),
  ('net2-snmp-zweck', 'Zum Transport von E-Mails zwischen Mailservern', false, 2),
  ('net2-snmp-zweck', 'Zur Auflösung von Namen in IP-Adressen', false, 3),
  -- net2-imap-vs-pop3
  ('net2-imap-vs-pop3', 'IMAP verwaltet Nachrichten und Ordner auf dem Server, sodass mehrere Geräte denselben Stand sehen', true, 0),
  ('net2-imap-vs-pop3', 'IMAP dient dem Versand von Nachrichten, POP3 nur dem Empfang', false, 1),
  ('net2-imap-vs-pop3', 'IMAP ist grundsätzlich verschlüsselt, POP3 grundsätzlich nicht', false, 2),
  ('net2-imap-vs-pop3', 'IMAP arbeitet über UDP, POP3 über TCP', false, 3),
  -- net2-multi-ports-mail
  ('net2-multi-ports-mail', '25', true, 0),
  ('net2-multi-ports-mail', '110', true, 1),
  ('net2-multi-ports-mail', '143', true, 2),
  ('net2-multi-ports-mail', '53', false, 3),
  ('net2-multi-ports-mail', '3389', false, 4),
  -- net2-multi-udp-dienste
  ('net2-multi-udp-dienste', 'Kurze DNS-Anfragen', true, 0),
  ('net2-multi-udp-dienste', 'DHCP', true, 1),
  ('net2-multi-udp-dienste', 'NTP', true, 2),
  ('net2-multi-udp-dienste', 'Eine interaktive SSH-Sitzung', false, 3),
  ('net2-multi-udp-dienste', 'Die Datenübertragung per FTP', false, 4),
  -- net2-multi-dns-records
  ('net2-multi-dns-records', 'MX verweist auf den für die Domain zuständigen Mailserver', true, 0),
  ('net2-multi-dns-records', 'CNAME legt einen Alias auf einen anderen Namen an', true, 1),
  ('net2-multi-dns-records', 'AAAA ordnet einem Namen eine IPv6-Adresse zu', true, 2),
  ('net2-multi-dns-records', 'PTR ordnet einem Namen eine MAC-Adresse zu', false, 3),
  ('net2-multi-dns-records', 'TXT legt die Gültigkeitsdauer der Zone fest', false, 4),
  -- net2-dhcp-dora
  ('net2-dhcp-dora', 'Discover, Offer, Request, Acknowledge', true, 0),
  ('net2-dhcp-dora', 'Discover, Request, Offer, Acknowledge', false, 1),
  ('net2-dhcp-dora', 'Request, Offer, Discover, Acknowledge', false, 2),
  ('net2-dhcp-dora', 'Offer, Discover, Acknowledge, Request', false, 3),
  -- net2-apipa
  ('net2-apipa', 'Eine Adresse aus 169.254.0.0/16', true, 0),
  ('net2-apipa', '127.0.0.1', false, 1),
  ('net2-apipa', 'Eine Adresse aus 192.168.0.0/24', false, 2),
  ('net2-apipa', '0.0.0.0', false, 3),
  -- net2-traceroute-ttl
  ('net2-traceroute-ttl', 'Es sendet Pakete mit schrittweise erhöhter TTL und wertet die ICMP-Meldungen der Router aus', true, 0),
  ('net2-traceroute-ttl', 'Es fragt beim zuständigen DNS-Server die Route zum Ziel ab', false, 1),
  ('net2-traceroute-ttl', 'Es liest die Routingtabelle des Zielsystems aus', false, 2),
  ('net2-traceroute-ttl', 'Es sendet gleichzeitig Testpakete an alle bekannten Router im Internet', false, 3),
  -- net2-multi-troubleshooting-tools
  ('net2-multi-troubleshooting-tools', 'tracert zeigt die Zwischenstationen auf dem Weg zum Ziel', true, 0),
  ('net2-multi-troubleshooting-tools', 'nslookup fragt gezielt einen Nameserver ab', true, 1),
  ('net2-multi-troubleshooting-tools', 'netstat zeigt Verbindungen und lauschende Ports des lokalen Systems', true, 2),
  ('net2-multi-troubleshooting-tools', 'ping misst die verfügbare Bandbreite einer Leitung', false, 3),
  ('net2-multi-troubleshooting-tools', 'ipconfig ändert Routen auf entfernten Routern', false, 4),
  -- net2-mtu-fragmentierung
  ('net2-mtu-fragmentierung', 'Die maximale Nutzlast, die in einem einzelnen Paket übertragen werden kann', true, 0),
  ('net2-mtu-fragmentierung', 'Die maximale Übertragungsrate in Mbit/s', false, 1),
  ('net2-mtu-fragmentierung', 'Die maximale zulässige Kabellänge eines Segments', false, 2),
  ('net2-mtu-fragmentierung', 'Die maximale Anzahl gleichzeitiger Verbindungen', false, 3),
  -- net2-qos
  ('net2-qos', 'Zeitkritische Datenströme werden bei Auslastung bevorzugt behandelt', true, 0),
  ('net2-qos', 'Die physikalisch verfügbare Bandbreite wird erhöht', false, 1),
  ('net2-qos', 'Der gesamte Verkehr wird verschlüsselt übertragen', false, 2),
  ('net2-qos', 'Paketverluste werden vollständig ausgeschlossen', false, 3),
  -- net2-multi-tls-zertifikat
  ('net2-multi-tls-zertifikat', 'Es bindet einen öffentlichen Schlüssel an einen Namen', true, 0),
  ('net2-multi-tls-zertifikat', 'Die Signatur einer Zertifizierungsstelle macht es überprüfbar', true, 1),
  ('net2-multi-tls-zertifikat', 'Nach Ablauf der Gültigkeit warnt der Browser vor der Verbindung', true, 2),
  ('net2-multi-tls-zertifikat', 'Es enthält den privaten Schlüssel des Servers', false, 3),
  ('net2-multi-tls-zertifikat', 'Ein selbstsigniertes Zertifikat kann die Verbindung nicht verschlüsseln', false, 4),
  -- net2-tls-handshake-schluessel
  ('net2-tls-handshake-schluessel', 'Es dient der Authentifizierung und dem Aushandeln eines symmetrischen Sitzungsschlüssels', true, 0),
  ('net2-tls-handshake-schluessel', 'Die gesamten Nutzdaten werden dauerhaft asymmetrisch verschlüsselt', false, 1),
  ('net2-tls-handshake-schluessel', 'Es komprimiert die Daten vor der Übertragung', false, 2),
  ('net2-tls-handshake-schluessel', 'Es ersetzt die Prüfung des Serverzertifikats', false, 3),
  -- net2-multi-firewall-typen
  ('net2-multi-firewall-typen', 'Ein Paketfilter entscheidet anhand von IP-Adressen, Ports und Protokoll', true, 0),
  ('net2-multi-firewall-typen', 'Eine Stateful-Inspection-Firewall verfolgt den Zustand bestehender Verbindungen', true, 1),
  ('net2-multi-firewall-typen', 'In einer DMZ stehen Dienste, die aus dem Internet erreichbar sein müssen', true, 2),
  ('net2-multi-firewall-typen', 'Eine Firewall erkennt Schadsoftware auch im verschlüsselten Datenstrom zuverlässig', false, 3),
  ('net2-multi-firewall-typen', 'Eine Personal Firewall auf jedem Client ersetzt die Netzwerksegmentierung', false, 4),
  -- net2-multi-angriffe
  ('net2-multi-angriffe', 'Beim ARP-Spoofing gibt sich ein Angreifer im LAN als anderer Host oder als Gateway aus', true, 0),
  ('net2-multi-angriffe', 'Ein DDoS-Angriff überlastet einen Dienst mit Anfragen aus vielen Quellen', true, 1),
  ('net2-multi-angriffe', 'Ein Portscan dient dem Auffinden offener Dienste auf einem Zielsystem', true, 2),
  ('net2-multi-angriffe', 'Ein Man-in-the-Middle-Angriff setzt physischen Zugriff auf den Zielserver voraus', false, 3),
  ('net2-multi-angriffe', 'Ein IDS blockiert erkannte Angriffe automatisch, bevor sie das Ziel erreichen', false, 4),
  -- net2-vpn-site-to-site
  ('net2-vpn-site-to-site', 'Zwei Gateways verbinden ganze Standortnetze dauerhaft, ohne Software auf den Endgeräten', true, 0),
  ('net2-vpn-site-to-site', 'Ein einzelner Client baut aus dem Homeoffice einen Tunnel ins Firmennetz auf', false, 1),
  ('net2-vpn-site-to-site', 'Der Zugriff erfolgt über einen Proxy im Browser statt über einen Tunnel', false, 2),
  ('net2-vpn-site-to-site', 'Es ersetzt die öffentliche IP-Adresse des Standorts durch eine private', false, 3),
  -- net2-proxy-reverse
  ('net2-proxy-reverse', 'Er steht vor den eigenen Servern und nimmt Anfragen aus dem Internet stellvertretend entgegen', true, 0),
  ('net2-proxy-reverse', 'Er arbeitet auf der Sicherungsschicht und wertet MAC-Adressen aus', false, 1),
  ('net2-proxy-reverse', 'Er muss in jedem Client als Verbindungsziel eingetragen werden', false, 2),
  ('net2-proxy-reverse', 'Er verschlüsselt ausschließlich DNS-Anfragen der Clients', false, 3),
  -- net2-multi-wpa3
  ('net2-multi-wpa3', 'WPA3 ersetzt das PSK-Handshake-Verfahren durch SAE', true, 0),
  ('net2-multi-wpa3', 'WEP gilt als gebrochen und sollte nicht mehr eingesetzt werden', true, 1),
  ('net2-multi-wpa3', 'WPA2-Enterprise authentifiziert Nutzer über einen RADIUS-Server', true, 2),
  ('net2-multi-wpa3', 'Eine verborgene SSID bietet wirksamen Schutz gegen Angreifer', false, 3),
  ('net2-multi-wpa3', 'Ein MAC-Filter verhindert unbefugten Zugriff zuverlässig', false, 4),
  -- net2-wlan-5ghz
  ('net2-wlan-5ghz', 'Mehr überlappungsfreie Kanäle und höhere Datenraten bei geringerer Reichweite', true, 0),
  ('net2-wlan-5ghz', 'Höhere Reichweite bei gleicher Sendeleistung', false, 1),
  ('net2-wlan-5ghz', 'Eine Verschlüsselung ist in diesem Band nicht mehr nötig', false, 2),
  ('net2-wlan-5ghz', 'Wände und Decken dämpfen das Signal in diesem Band kaum noch', false, 3),
  -- net2-multi-kabel-medien
  ('net2-multi-kabel-medien', 'Für Twisted-Pair-Segmente im Ethernet gilt die Grenze von 100 m', true, 0),
  ('net2-multi-kabel-medien', 'Lichtwellenleiter sind unempfindlich gegen elektromagnetische Störungen', true, 1),
  ('net2-multi-kabel-medien', 'Die Verdrillung der Adernpaare verringert das Übersprechen', true, 2),
  ('net2-multi-kabel-medien', 'Singlemode-Fasern eignen sich nur für kurze Strecken innerhalb eines Gebäudes', false, 3),
  ('net2-multi-kabel-medien', 'Koaxialkabel ist der aktuelle Standard für strukturierte Gebäudeverkabelung', false, 4),
  -- net2-poe
  ('net2-poe', 'Die Stromversorgung des Endgeräts läuft über dasselbe Netzwerkkabel wie die Daten', true, 0),
  ('net2-poe', 'Die maximale Segmentlänge steigt deutlich über 100 m', false, 1),
  ('net2-poe', 'Die Datenrate der Leitung verdoppelt sich', false, 2),
  ('net2-poe', 'Der übertragene Verkehr wird automatisch verschlüsselt', false, 3),
  -- net2-multi-cloud-netz
  ('net2-multi-cloud-netz', 'Virtuelle Maschinen werden über einen virtuellen Switch im Hypervisor angebunden', true, 0),
  ('net2-multi-cloud-netz', 'Ein Load Balancer verteilt eingehende Anfragen auf mehrere Backend-Instanzen', true, 1),
  ('net2-multi-cloud-netz', 'Sicherheitsgruppen wirken wie ein Paketfilter direkt an der einzelnen Instanz', true, 2),
  ('net2-multi-cloud-netz', 'Container auf demselben Host benötigen je eine eigene öffentliche IP-Adresse', false, 3),
  ('net2-multi-cloud-netz', 'In einer VPC vergibt der Anbieter ausschließlich öffentliche Adressbereiche', false, 4),
  -- net2-multi-ipv6-eigenschaften
  ('net2-multi-ipv6-eigenschaften', 'Eine IPv6-Adresse ist 128 Bit lang', true, 0),
  ('net2-multi-ipv6-eigenschaften', 'Zusammenhängende Nullblöcke dürfen einmal pro Adresse durch :: ersetzt werden', true, 1),
  ('net2-multi-ipv6-eigenschaften', 'Adressen mit dem Präfix fe80:: sind nur im lokalen Link gültig', true, 2),
  ('net2-multi-ipv6-eigenschaften', 'IPv6-Adressen werden dezimal in vier Oktetten notiert', false, 3),
  ('net2-multi-ipv6-eigenschaften', 'Ohne NAT ist mit IPv6 kein Internetzugang möglich', false, 4)
) as v(source_key, text, is_correct, sort_order)
on v.source_key = q.source_key;
