-- Datenbanken-Erweiterung: 39 neue, selbst geschriebene Fragen für fiae-ae.
-- 16 Fragen im Format 'multiple', 23 im Format 'single'.
-- Alle source_keys wurden gegen den bestehenden Bestand geprüft.
-- Inhaltlich decken die Fragen Lücken ab: Isolationsstufen und Sperren,
-- Indexstrategie und Ausführungspläne, NULL-Semantik, Unterabfragen,
-- DDL/DCL, Rechtevergabe, Denormalisierung, OLTP/OLAP, Replikation,
-- BCNF, funktionale Abhängigkeiten und Anomalietypen.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'fiae-ae'
join (values
  -- Mehrfachauswahl
  ('Datenbanken', 'db-mc-ddl-befehle',
   'Welche SQL-Anweisungen gehören zur Data Definition Language (DDL)?',
   'Die DDL beschreibt die Struktur der Datenbank. CREATE, ALTER und DROP verändern Schemaobjekte. SELECT ist Abfragesprache (DQL), UPDATE verändert Daten und zählt zur DML.',
   2, 'multiple'),
  ('Datenbanken', 'db-mc-isolationsprobleme',
   'Welche Phänomene können auftreten, wenn die Isolationsstufe einer Transaktion zu niedrig gewählt wird?',
   'Zu schwache Isolation lässt Transaktionen die Zwischenstände anderer sehen: Dirty Read liest ungesicherte Daten, beim Non-Repeatable Read ändert sich ein bereits gelesener Satz, beim Phantom Read tauchen zusätzliche Zeilen auf. Ein Deadlock ist dagegen ein Sperrkonflikt und tritt gerade bei strenger Isolation häufiger auf.',
   4, 'multiple'),
  ('Datenbanken', 'db-mc-index-sinnvoll',
   'In welchen Situationen ist das Anlegen eines Index auf einer Spalte fachlich sinnvoll?',
   'Ein Index zahlt sich aus, wenn die Spalte häufig zum Filtern, Verknüpfen oder Sortieren dient und die Tabelle überwiegend gelesen wird. Bei sehr schreiblastigen Tabellen oder bei Spalten mit nur wenigen verschiedenen Werten überwiegt oft der Pflegeaufwand.',
   3, 'multiple'),
  ('Datenbanken', 'db-mc-unique-constraint',
   'Welche Aussagen über den UNIQUE-Constraint treffen zu?',
   'UNIQUE sichert Eindeutigkeit, ist aber nicht der Primärschlüssel: eine Tabelle darf mehrere UNIQUE-Constraints haben, viele Systeme erlauben in einer UNIQUE-Spalte einen NULL-Wert, und intern wird zur Prüfung meist ein Index angelegt.',
   3, 'multiple'),
  ('Datenbanken', 'db-mc-grant-revoke',
   'Welche Aussagen über GRANT und REVOKE treffen zu?',
   'GRANT und REVOKE sind die Kernbefehle der Data Control Language. Sie steuern, welcher Benutzer welche Operation auf welchem Objekt ausführen darf, greifen aber nicht in die Tabellenstruktur oder in den Dateninhalt ein.',
   2, 'multiple'),
  ('Datenbanken', 'db-mc-null-semantik',
   'Welche Aussagen über den Umgang mit NULL-Werten in SQL treffen zu?',
   'NULL bedeutet "Wert unbekannt", nicht "leer" und nicht "null". Vergleiche mit NULL liefern deshalb weder wahr noch falsch, sondern unbekannt, weshalb IS NULL nötig ist. COUNT über eine konkrete Spalte überspringt NULL-Werte, COUNT(*) nicht.',
   4, 'multiple'),
  ('Datenbanken', 'db-mc-denormalisierung',
   'Welche Aussagen über Denormalisierung treffen zu?',
   'Denormalisierung ist eine bewusste Entscheidung gegen ein Stück Normalisierung, um Lesezugriffe ohne teure Joins zu bedienen. Der Preis ist zusätzliche Redundanz und damit ein höheres Risiko für inkonsistente Daten bei Änderungen.',
   3, 'multiple'),
  ('Datenbanken', 'db-mc-mn-aufloesung',
   'Welche Aussagen über die Umsetzung einer m:n-Beziehung im relationalen Modell treffen zu?',
   'Das relationale Modell kennt keine direkte m:n-Verknüpfung. Sie wird über eine Zwischentabelle abgebildet, die Fremdschlüssel auf beide Seiten hält. Deren Kombination eignet sich in der Regel als zusammengesetzter Primärschlüssel.',
   2, 'multiple'),
  ('Datenbanken', 'db-mc-view-eigenschaften',
   'Welche Aussagen über Views treffen zu?',
   'Eine View ist eine gespeicherte Abfrage ohne eigenen Datenbestand. Sie eignet sich gut, um Benutzern nur bestimmte Spalten oder Zeilen zugänglich zu machen. Schreibende Zugriffe sind nur möglich, wenn sich jede Ergebniszeile eindeutig einer Basiszeile zuordnen lässt.',
   3, 'multiple'),
  ('Datenbanken', 'db-mc-sicherungsstrategie',
   'Welche Aussagen über eine tragfähige Datenbank-Sicherungsstrategie treffen zu?',
   'Ein differenzielles Backup bezieht sich immer auf das letzte Vollbackup, dadurch reichen zum Zurückspielen zwei Sicherungen. Das Transaktionslog erlaubt die Wiederherstellung bis zu einem gewählten Zeitpunkt. RAID schützt gegen Plattenausfall, nicht gegen versehentliches Löschen, ersetzt also kein Backup.',
   3, 'multiple'),
  ('Datenbanken', 'db-mc-oltp-olap',
   'Welche Aussagen über den Unterschied zwischen OLTP- und OLAP-Systemen treffen zu?',
   'OLTP-Systeme bedienen das Tagesgeschäft mit vielen kurzen, schreibenden Transaktionen und sind stark normalisiert. OLAP-Systeme werten große Datenmengen lesend aus und nehmen dafür bewusst Redundanz in Kauf, etwa in einem Sternschema.',
   3, 'multiple'),
  ('Datenbanken', 'db-mc-on-delete-set-null',
   'Welche Aussagen über die Fremdschlüssel-Option ON DELETE SET NULL treffen zu?',
   'Beim Löschen des übergeordneten Datensatzes bleibt die Kindzeile bestehen, nur der Verweis wird geleert. Das setzt zwingend voraus, dass die Fremdschlüsselspalte NULL zulässt, sonst weist die Datenbank die Definition oder das Löschen zurück.',
   4, 'multiple'),
  ('Datenbanken', 'db-mc-unterabfragen',
   'Welche Aussagen über Unterabfragen (Subqueries) treffen zu?',
   'Eine korrelierte Unterabfrage greift auf eine Spalte der äußeren Abfrage zu und wird deshalb je Zeile ausgewertet. EXISTS interessiert sich nur dafür, ob überhaupt eine Zeile zurückkommt, nicht für deren Inhalt. Eine abgeleitete Tabelle im FROM-Teil verlangt in den meisten Systemen einen Alias.',
   4, 'multiple'),
  ('Datenbanken', 'db-mc-db-sicherheit',
   'Welche Maßnahmen erhöhen die Sicherheit einer produktiv genutzten Datenbank?',
   'Sicherheit entsteht durch das Zusammenspiel von minimalen Rechten für das Anwendungskonto, strikter Trennung von Code und Eingabe über Prepared Statements und einer verschlüsselten Verbindung. Ein Administratorkonto in der Anwendung und detaillierte SQL-Fehlermeldungen an den Endnutzer helfen dagegen dem Angreifer.',
   2, 'multiple'),
  ('Datenbanken', 'db-mc-aggregatfunktionen',
   'Welche Aussagen über Aggregatfunktionen in SQL treffen zu?',
   'COUNT(*) zählt Zeilen unabhängig vom Inhalt, während AVG, SUM und COUNT über eine Spalte NULL-Werte auslassen. MIN und MAX arbeiten auch auf Datums- und Zeichenspalten über deren Sortierordnung. In der WHERE-Klausel sind Aggregate nicht erlaubt, weil dort noch keine Gruppen gebildet sind.',
   3, 'multiple'),
  ('Datenbanken', 'db-mc-sperrmechanismen',
   'Welche Aussagen über Sperren (Locks) in einer relationalen Datenbank treffen zu?',
   'Ein Shared Lock erlaubt weitere Lesesperren auf demselben Objekt, ein Exclusive Lock schließt jede andere Sperre aus. Je feiner die Sperrgranularität, desto mehr Transaktionen laufen parallel, allerdings steigt der Verwaltungsaufwand. Sperren werden am Transaktionsende freigegeben, nicht erst beim Neustart.',
   4, 'multiple'),
  -- Einfachauswahl
  ('Datenbanken', 'db-sg-bcnf',
   'Was fordert die Boyce-Codd-Normalform zusätzlich zur 3. Normalform?',
   'In der BCNF muss jede Determinante, also jedes Attribut oder jede Attributkombination, von der etwas funktional abhängt, ein Schlüsselkandidat sein. Damit werden auch Abhängigkeiten von Teilen überlappender Schlüsselkandidaten beseitigt, die die 3NF noch zulässt.',
   4, 'single'),
  ('Datenbanken', 'db-sg-isolation-serializable',
   'Welche Isolationsstufe schließt als einzige auch Phantom-Reads aus?',
   'SERIALIZABLE lässt das Ergebnis nebenläufiger Transaktionen so aussehen, als wären sie nacheinander gelaufen. REPEATABLE READ hält bereits gelesene Zeilen stabil, verhindert aber nicht, dass eine andere Transaktion neue passende Zeilen einfügt.',
   4, 'single'),
  ('Datenbanken', 'db-sg-dirty-read',
   'Was versteht man unter einem Dirty Read?',
   'Beim Dirty Read liest eine Transaktion Daten, die eine andere Transaktion geändert, aber noch nicht bestätigt hat. Wird diese anschließend zurückgerollt, hat die lesende Transaktion mit einem Wert gearbeitet, den es nie offiziell gab.',
   2, 'single'),
  ('Datenbanken', 'db-sg-savepoint',
   'Wozu dient ein SAVEPOINT innerhalb einer Transaktion?',
   'Ein SAVEPOINT markiert eine Zwischenstelle, auf die gezielt zurückgesetzt werden kann. Der bis dahin erledigte Teil der Transaktion bleibt erhalten, die Transaktion selbst läuft weiter und muss noch bestätigt oder verworfen werden.',
   3, 'single'),
  ('Datenbanken', 'db-sg-durability',
   'Was sagt die ACID-Eigenschaft Dauerhaftigkeit (Durability) über eine bestätigte Transaktion aus?',
   'Nach einem erfolgreichen COMMIT sind die Änderungen dauerhaft festgeschrieben. Die Datenbank stellt sie über das Transaktionslog auch nach einem Absturz oder Stromausfall wieder her, selbst wenn sie noch nicht in die Datendateien geschrieben waren.',
   2, 'single'),
  ('Datenbanken', 'db-sg-surrogatschluessel',
   'Was kennzeichnet einen Surrogatschlüssel?',
   'Ein Surrogatschlüssel ist ein künstlich erzeugter Wert ohne fachliche Bedeutung, meist eine fortlaufende Nummer. Er bleibt auch dann stabil, wenn sich fachliche Merkmale wie Kundennummer oder Name ändern.',
   2, 'single'),
  ('Datenbanken', 'db-sg-not-in-null',
   'Warum liefert eine Bedingung der Form "spalte NOT IN (unterabfrage)" kein Ergebnis, wenn die Unterabfrage einen NULL-Wert enthält?',
   'NOT IN wird intern zu einer Kette von Ungleichheitsvergleichen. Der Vergleich mit NULL ergibt "unbekannt", und weil alle Teilbedingungen wahr sein müssen, wird die Gesamtbedingung nie wahr. Mit NOT EXISTS oder einem Filter auf NOT NULL lässt sich das umgehen.',
   4, 'single'),
  ('Datenbanken', 'db-sg-cross-join',
   'Was liefert ein CROSS JOIN zweier Tabellen?',
   'Der CROSS JOIN bildet das kartesische Produkt, verbindet also jede Zeile der ersten Tabelle mit jeder Zeile der zweiten. Bei 100 und 50 Zeilen entstehen 5000 Ergebniszeilen, weshalb er meist ungewollt durch eine vergessene Verknüpfungsbedingung entsteht.',
   2, 'single'),
  ('Datenbanken', 'db-sg-full-outer-join',
   'Welches Ergebnis liefert ein FULL OUTER JOIN?',
   'Der FULL OUTER JOIN behält alle Zeilen beider Tabellen. Findet sich auf der jeweils anderen Seite kein passender Datensatz, werden dessen Spalten mit NULL gefüllt. Damit lassen sich Datensätze finden, die nur auf einer Seite existieren.',
   2, 'single'),
  ('Datenbanken', 'db-sg-alter-table-add',
   'Mit welcher Anweisung ergänzt man eine bestehende Tabelle um eine weitere Spalte?',
   'ALTER TABLE ändert die Struktur einer vorhandenen Tabelle. CREATE TABLE würde eine neue Tabelle anlegen, UPDATE ändert nur Daten, und INSERT fügt Zeilen ein, keine Spalten.',
   1, 'single'),
  ('Datenbanken', 'db-sg-drop-vs-truncate',
   'Was unterscheidet DROP TABLE von TRUNCATE TABLE?',
   'TRUNCATE leert eine Tabelle, lässt aber Struktur, Spalten und Rechte bestehen. DROP entfernt zusätzlich die Tabellendefinition selbst, sodass sie vor einer erneuten Nutzung neu angelegt werden muss.',
   2, 'single'),
  ('Datenbanken', 'db-sg-ausfuehrungsplan',
   'Wozu dient der Ausführungsplan, den man sich etwa über EXPLAIN anzeigen lässt?',
   'Der Ausführungsplan zeigt, wie der Optimierer eine Abfrage abarbeiten will, also welche Zugriffspfade, Verknüpfungsverfahren und Reihenfolgen er wählt. Damit lässt sich erkennen, ob ein vorhandener Index genutzt wird oder warum eine Abfrage langsam ist.',
   4, 'single'),
  ('Datenbanken', 'db-sg-full-table-scan',
   'Was bedeutet es, wenn der Ausführungsplan einer Abfrage einen Full Table Scan ausweist?',
   'Die Datenbank liest alle Zeilen der Tabelle und prüft jede einzeln gegen die Bedingung. Bei kleinen Tabellen ist das unproblematisch, bei großen ein deutlicher Hinweis auf einen fehlenden oder durch die Formulierung der Bedingung unbrauchbaren Index.',
   3, 'single'),
  ('Datenbanken', 'db-sg-composite-index-reihenfolge',
   'Warum ist bei einem zusammengesetzten Index über die Spalten (nachname, vorname) die Reihenfolge der Spalten entscheidend?',
   'Ein zusammengesetzter Index ist nach der ersten Spalte sortiert, innerhalb gleicher Werte nach der zweiten. Eine Abfrage nur nach vorname kann ihn daher nicht sinnvoll nutzen, eine Abfrage nur nach nachname dagegen schon.',
   4, 'single'),
  ('Datenbanken', 'db-sg-clustered-index',
   'Was kennzeichnet einen Clustered Index?',
   'Beim Clustered Index bestimmt der Index die physische Speicherreihenfolge der Zeilen. Deshalb kann es je Tabelle nur einen geben, und Bereichsabfragen über die Indexspalte sind besonders schnell, weil die Sätze zusammenhängend liegen.',
   4, 'single'),
  ('Datenbanken', 'db-sg-materialized-view',
   'Was unterscheidet eine Materialized View von einer gewöhnlichen View?',
   'Eine Materialized View speichert das Abfrageergebnis physisch ab. Lesezugriffe sind dadurch schnell, dafür sind die Daten nur so aktuell wie die letzte Aktualisierung. Eine gewöhnliche View wertet die hinterlegte Abfrage bei jedem Zugriff neu aus.',
   3, 'single'),
  ('Datenbanken', 'db-sg-default-wert',
   'Was bewirkt die Angabe DEFAULT bei einer Spaltendefinition?',
   'Der DEFAULT-Wert wird eingesetzt, wenn beim INSERT für diese Spalte kein Wert angegeben wird. Wird ausdrücklich NULL eingefügt, greift der Vorgabewert nicht, sofern die Spalte NULL zulässt.',
   1, 'single'),
  ('Datenbanken', 'db-sg-like-praefix',
   'Mit welchem Muster findet "WHERE nachname LIKE ..." alle Namen, die mit "Mü" beginnen?',
   'Das Prozentzeichen steht für beliebig viele Zeichen, der Unterstrich für genau eines. "Mü%" trifft also jeden Namen mit diesem Anfang, unabhängig von der restlichen Länge.',
   2, 'single'),
  ('Datenbanken', 'db-sg-top-n-abfrage',
   'Wie ermittelt man aus einer Tabelle artikel die zehn teuersten Artikel?',
   'Erst muss absteigend nach Preis sortiert werden, danach begrenzt LIMIT (in anderen Systemen TOP oder FETCH FIRST) die Ausgabe. Ohne ORDER BY ist die Reihenfolge der Zeilen nicht garantiert, die Begrenzung liefert dann eine beliebige Auswahl.',
   2, 'single'),
  ('Datenbanken', 'db-sg-loeschanomalie',
   'Was versteht man unter einer Löschanomalie?',
   'Eine Löschanomalie liegt vor, wenn mit dem Entfernen eines Datensatzes ungewollt auch Informationen verschwinden, die eigentlich unabhängig davon sind. Wird etwa der letzte Kurs eines Dozenten gelöscht, gehen in einer unnormalisierten Tabelle auch dessen Stammdaten verloren.',
   3, 'single'),
  ('Datenbanken', 'db-sg-funktionale-abhaengigkeit',
   'Was bedeutet die Aussage, dass Attribut B funktional von Attribut A abhängt?',
   'Zu jedem Wert von A gehört genau ein Wert von B. Aus der Artikelnummer folgt zum Beispiel eindeutig die Artikelbezeichnung. Umgekehrt muss das nicht gelten, weil mehrere Artikel dieselbe Bezeichnung tragen können.',
   3, 'single'),
  ('Datenbanken', 'db-sg-replikation',
   'Welchen Zweck verfolgt die Replikation einer Datenbank?',
   'Bei der Replikation wird der Datenbestand auf weitere Server gespiegelt. Das erhöht die Ausfallsicherheit und erlaubt es, lesende Zugriffe auf Replikate zu verteilen. Ein Backup ersetzt sie nicht, weil fehlerhafte Änderungen sofort mitrepliziert werden.',
   2, 'single'),
  ('Datenbanken', 'db-sg-generalisierung',
   'Was beschreibt eine Generalisierung im erweiterten ER-Modell?',
   'Gemeinsame Attribute mehrerer Entitätstypen werden zu einem übergeordneten Typ zusammengefasst, von dem die spezielleren Typen erben. Kunde und Lieferant lassen sich so etwa unter Geschäftspartner bündeln.',
   3, 'single')
) as v(topic_name, source_key, q, expl, difficulty, question_type)
on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- db-mc-ddl-befehle
  ('db-mc-ddl-befehle', 'CREATE TABLE', true, 0),
  ('db-mc-ddl-befehle', 'ALTER TABLE', true, 1),
  ('db-mc-ddl-befehle', 'DROP TABLE', true, 2),
  ('db-mc-ddl-befehle', 'UPDATE', false, 3),
  ('db-mc-ddl-befehle', 'SELECT', false, 4),
  -- db-mc-isolationsprobleme
  ('db-mc-isolationsprobleme', 'Dirty Read', true, 0),
  ('db-mc-isolationsprobleme', 'Non-Repeatable Read', true, 1),
  ('db-mc-isolationsprobleme', 'Phantom Read', true, 2),
  ('db-mc-isolationsprobleme', 'Deadlock', false, 3),
  ('db-mc-isolationsprobleme', 'Verlust bereits bestätigter Daten nach einem Serverneustart', false, 4),
  -- db-mc-index-sinnvoll
  ('db-mc-index-sinnvoll', 'Die Spalte wird häufig in WHERE-Bedingungen gefiltert', true, 0),
  ('db-mc-index-sinnvoll', 'Die Spalte dient regelmäßig als Verknüpfungsbedingung in Joins', true, 1),
  ('db-mc-index-sinnvoll', 'Nach der Spalte wird häufig sortiert', true, 2),
  ('db-mc-index-sinnvoll', 'Die Tabelle wird im Sekundentakt beschrieben und nur selten gelesen', false, 3),
  ('db-mc-index-sinnvoll', 'Die Spalte enthält bei 200 Zeilen nur die Werte "ja" und "nein"', false, 4),
  -- db-mc-unique-constraint
  ('db-mc-unique-constraint', 'Eine Tabelle darf mehrere UNIQUE-Constraints besitzen', true, 0),
  ('db-mc-unique-constraint', 'Die meisten Systeme lassen in einer UNIQUE-Spalte einen NULL-Wert zu', true, 1),
  ('db-mc-unique-constraint', 'Zur Prüfung legt das DBMS in der Regel automatisch einen Index an', true, 2),
  ('db-mc-unique-constraint', 'UNIQUE macht einen Primärschlüssel in der Tabelle überflüssig', false, 3),
  ('db-mc-unique-constraint', 'UNIQUE erlaubt beliebig viele gleiche Werte, solange sie nicht NULL sind', false, 4),
  -- db-mc-grant-revoke
  ('db-mc-grant-revoke', 'GRANT vergibt einem Benutzer oder einer Rolle bestimmte Rechte', true, 0),
  ('db-mc-grant-revoke', 'REVOKE entzieht zuvor vergebene Rechte wieder', true, 1),
  ('db-mc-grant-revoke', 'Beide Anweisungen gehören zur Data Control Language', true, 2),
  ('db-mc-grant-revoke', 'Beide Anweisungen verändern die Spaltendefinition der betroffenen Tabelle', false, 3),
  -- db-mc-null-semantik
  ('db-mc-null-semantik', 'Der Vergleich "spalte = NULL" liefert weder wahr noch falsch', true, 0),
  ('db-mc-null-semantik', 'Zum Prüfen auf einen fehlenden Wert wird IS NULL benötigt', true, 1),
  ('db-mc-null-semantik', 'COUNT(spalte) zählt Zeilen mit NULL in dieser Spalte nicht mit', true, 2),
  ('db-mc-null-semantik', 'NULL ist gleichbedeutend mit der leeren Zeichenkette', false, 3),
  ('db-mc-null-semantik', 'In numerischen Spalten entspricht NULL dem Wert 0', false, 4),
  -- db-mc-denormalisierung
  ('db-mc-denormalisierung', 'Sie nimmt Redundanz bewusst in Kauf, um Lesezugriffe zu beschleunigen', true, 0),
  ('db-mc-denormalisierung', 'Sie erhöht das Risiko von Änderungsanomalien', true, 1),
  ('db-mc-denormalisierung', 'Sie wird vor allem in auswertenden Systemen eingesetzt', true, 2),
  ('db-mc-denormalisierung', 'Sie ist grundsätzlich ein Modellierungsfehler', false, 3),
  ('db-mc-denormalisierung', 'Sie senkt in aller Regel den Speicherbedarf', false, 4),
  -- db-mc-mn-aufloesung
  ('db-mc-mn-aufloesung', 'Es wird eine zusätzliche Zwischentabelle benötigt', true, 0),
  ('db-mc-mn-aufloesung', 'Die Zwischentabelle enthält Fremdschlüssel auf beide beteiligten Tabellen', true, 1),
  ('db-mc-mn-aufloesung', 'Die beiden Fremdschlüssel bilden zusammen häufig den Primärschlüssel', true, 2),
  ('db-mc-mn-aufloesung', 'Eine m:n-Beziehung lässt sich direkt zwischen zwei Tabellen abbilden', false, 3),
  -- db-mc-view-eigenschaften
  ('db-mc-view-eigenschaften', 'Eine View kann den Zugriff auf einzelne Spalten oder Zeilen einschränken', true, 0),
  ('db-mc-view-eigenschaften', 'Eine View hält in der Regel keine eigenen Daten vor', true, 1),
  ('db-mc-view-eigenschaften', 'Unter bestimmten Bedingungen ist auch schreibender Zugriff über eine View möglich', true, 2),
  ('db-mc-view-eigenschaften', 'Eine View beschleunigt Abfragen, weil ihr Ergebnis dauerhaft gespeichert wird', false, 3),
  ('db-mc-view-eigenschaften', 'Für jede View muss ein eigener Index angelegt werden', false, 4),
  -- db-mc-sicherungsstrategie
  ('db-mc-sicherungsstrategie', 'Ein differenzielles Backup sichert alle Änderungen seit dem letzten Vollbackup', true, 0),
  ('db-mc-sicherungsstrategie', 'Mit dem Transaktionslog ist eine Wiederherstellung auf einen bestimmten Zeitpunkt möglich', true, 1),
  ('db-mc-sicherungsstrategie', 'Sicherungen sollten regelmäßig testweise zurückgespielt werden', true, 2),
  ('db-mc-sicherungsstrategie', 'Ein RAID-Verbund macht Backups überflüssig', false, 3),
  -- db-mc-oltp-olap
  ('db-mc-oltp-olap', 'OLTP-Systeme verarbeiten viele kurze, überwiegend schreibende Transaktionen', true, 0),
  ('db-mc-oltp-olap', 'OLAP-Systeme werten große Datenbestände überwiegend lesend aus', true, 1),
  ('db-mc-oltp-olap', 'OLAP-Datenmodelle sind häufig bewusst denormalisiert', true, 2),
  ('db-mc-oltp-olap', 'OLTP-Systeme lassen sich ausschließlich mit NoSQL-Datenbanken umsetzen', false, 3),
  -- db-mc-on-delete-set-null
  ('db-mc-on-delete-set-null', 'Die abhängigen Zeilen bleiben erhalten, nur ihr Verweis wird geleert', true, 0),
  ('db-mc-on-delete-set-null', 'Die Fremdschlüsselspalte muss NULL-Werte zulassen', true, 1),
  ('db-mc-on-delete-set-null', 'Die abhängigen Zeilen werden ebenfalls gelöscht', false, 2),
  ('db-mc-on-delete-set-null', 'Die Option funktioniert auch bei einer als NOT NULL definierten Fremdschlüsselspalte', false, 3),
  -- db-mc-unterabfragen
  ('db-mc-unterabfragen', 'Eine korrelierte Unterabfrage greift auf Spalten der äußeren Abfrage zu', true, 0),
  ('db-mc-unterabfragen', 'EXISTS prüft lediglich, ob die Unterabfrage mindestens eine Zeile liefert', true, 1),
  ('db-mc-unterabfragen', 'Eine Unterabfrage in der FROM-Klausel braucht in den meisten Systemen einen Alias', true, 2),
  ('db-mc-unterabfragen', 'Unterabfragen dürfen nicht in der WHERE-Klausel stehen', false, 3),
  ('db-mc-unterabfragen', 'Eine korrelierte Unterabfrage wird immer nur einmal ausgewertet', false, 4),
  -- db-mc-db-sicherheit
  ('db-mc-db-sicherheit', 'Das Anwendungskonto erhält nur die tatsächlich benötigten Rechte', true, 0),
  ('db-mc-db-sicherheit', 'Alle Nutzereingaben werden über Prepared Statements gebunden', true, 1),
  ('db-mc-db-sicherheit', 'Die Verbindung zwischen Anwendung und Datenbank wird verschlüsselt', true, 2),
  ('db-mc-db-sicherheit', 'Die Anwendung verbindet sich mit dem Administratorkonto der Datenbank', false, 3),
  ('db-mc-db-sicherheit', 'Auftretende SQL-Fehler werden dem Endnutzer vollständig angezeigt', false, 4),
  -- db-mc-aggregatfunktionen
  ('db-mc-aggregatfunktionen', 'COUNT(*) zählt alle Zeilen einer Gruppe, unabhängig von NULL-Werten', true, 0),
  ('db-mc-aggregatfunktionen', 'AVG und SUM lassen NULL-Werte bei der Berechnung aus', true, 1),
  ('db-mc-aggregatfunktionen', 'MIN und MAX lassen sich auch auf Datums- und Textspalten anwenden', true, 2),
  ('db-mc-aggregatfunktionen', 'Aggregatfunktionen dürfen in der WHERE-Klausel als Filter verwendet werden', false, 3),
  -- db-mc-sperrmechanismen
  ('db-mc-sperrmechanismen', 'Ein Shared Lock erlaubt weiteren Transaktionen den lesenden Zugriff', true, 0),
  ('db-mc-sperrmechanismen', 'Ein Exclusive Lock schließt jede andere Sperre auf demselben Objekt aus', true, 1),
  ('db-mc-sperrmechanismen', 'Sperren auf Zeilenebene erlauben mehr Parallelität als Tabellensperren', true, 2),
  ('db-mc-sperrmechanismen', 'Sperren werden erst beim Neustart des Datenbankservers freigegeben', false, 3),
  ('db-mc-sperrmechanismen', 'Eine reine Leseabfrage benötigt zwingend einen Exclusive Lock', false, 4),
  -- db-sg-bcnf
  ('db-sg-bcnf', 'Jede Determinante muss ein Schlüsselkandidat sein', true, 0),
  ('db-sg-bcnf', 'Alle Attributwerte müssen atomar sein', false, 1),
  ('db-sg-bcnf', 'Der Primärschlüssel darf aus höchstens einer Spalte bestehen', false, 2),
  ('db-sg-bcnf', 'Jede Tabelle muss mindestens einen Fremdschlüssel enthalten', false, 3),
  -- db-sg-isolation-serializable
  ('db-sg-isolation-serializable', 'SERIALIZABLE', true, 0),
  ('db-sg-isolation-serializable', 'REPEATABLE READ', false, 1),
  ('db-sg-isolation-serializable', 'READ COMMITTED', false, 2),
  ('db-sg-isolation-serializable', 'READ UNCOMMITTED', false, 3),
  -- db-sg-dirty-read
  ('db-sg-dirty-read', 'Eine Transaktion liest Änderungen einer anderen, noch nicht bestätigten Transaktion', true, 0),
  ('db-sg-dirty-read', 'Eine Abfrage liefert beim zweiten Aufruf zusätzliche neue Zeilen', false, 1),
  ('db-sg-dirty-read', 'Zwei Transaktionen warten gegenseitig auf Sperren des jeweils anderen', false, 2),
  ('db-sg-dirty-read', 'Eine Abfrage liest Daten aus einem veralteten Backup', false, 3),
  -- db-sg-savepoint
  ('db-sg-savepoint', 'Er erlaubt ein Zurücksetzen auf einen Zwischenstand, ohne die Transaktion zu beenden', true, 0),
  ('db-sg-savepoint', 'Er schreibt die bisherigen Änderungen dauerhaft fest', false, 1),
  ('db-sg-savepoint', 'Er legt eine Sicherungskopie der betroffenen Tabellen an', false, 2),
  ('db-sg-savepoint', 'Er hebt alle Sperren der Transaktion vorzeitig auf', false, 3),
  -- db-sg-durability
  ('db-sg-durability', 'Die Änderungen bleiben auch nach einem Systemausfall erhalten', true, 0),
  ('db-sg-durability', 'Die Transaktion kann jederzeit noch zurückgerollt werden', false, 1),
  ('db-sg-durability', 'Die Transaktion läuft garantiert ohne Sperren ab', false, 2),
  ('db-sg-durability', 'Alle Integritätsbedingungen werden erst nachträglich geprüft', false, 3),
  -- db-sg-surrogatschluessel
  ('db-sg-surrogatschluessel', 'Ein künstlich vergebener Wert ohne fachliche Bedeutung', true, 0),
  ('db-sg-surrogatschluessel', 'Ein Schlüssel, der aus mehreren fachlichen Spalten zusammengesetzt ist', false, 1),
  ('db-sg-surrogatschluessel', 'Ein Fremdschlüssel, der auf dieselbe Tabelle verweist', false, 2),
  ('db-sg-surrogatschluessel', 'Ein Schlüsselkandidat, der bewusst nicht zum Primärschlüssel erklärt wurde', false, 3),
  -- db-sg-not-in-null
  ('db-sg-not-in-null', 'Der Vergleich mit NULL ergibt "unbekannt", dadurch wird die Gesamtbedingung nie wahr', true, 0),
  ('db-sg-not-in-null', 'NOT IN ist in Kombination mit Unterabfragen syntaktisch nicht erlaubt', false, 1),
  ('db-sg-not-in-null', 'Die Datenbank bricht die Abfrage mit einem Fehler ab', false, 2),
  ('db-sg-not-in-null', 'NULL wird als kleinster möglicher Wert behandelt und filtert alle Zeilen heraus', false, 3),
  -- db-sg-cross-join
  ('db-sg-cross-join', 'Jede Zeile der einen Tabelle wird mit jeder Zeile der anderen kombiniert', true, 0),
  ('db-sg-cross-join', 'Nur Zeilen, deren Schlüsselwerte in beiden Tabellen übereinstimmen', false, 1),
  ('db-sg-cross-join', 'Alle Zeilen beider Tabellen untereinander, wie bei UNION ALL', false, 2),
  ('db-sg-cross-join', 'Nur die Zeilen der linken Tabelle ohne Entsprechung rechts', false, 3),
  -- db-sg-full-outer-join
  ('db-sg-full-outer-join', 'Alle Zeilen beider Tabellen, fehlende Gegenstücke werden mit NULL gefüllt', true, 0),
  ('db-sg-full-outer-join', 'Nur die Zeilen, die in beiden Tabellen eine Entsprechung haben', false, 1),
  ('db-sg-full-outer-join', 'Alle Zeilen der linken Tabelle und nur passende der rechten', false, 2),
  ('db-sg-full-outer-join', 'Ausschließlich die Zeilen ohne Entsprechung in der jeweils anderen Tabelle', false, 3),
  -- db-sg-alter-table-add
  ('db-sg-alter-table-add', 'ALTER TABLE kunde ADD COLUMN telefon VARCHAR(30)', true, 0),
  ('db-sg-alter-table-add', 'CREATE TABLE kunde ADD telefon VARCHAR(30)', false, 1),
  ('db-sg-alter-table-add', 'UPDATE kunde SET COLUMN telefon VARCHAR(30)', false, 2),
  ('db-sg-alter-table-add', 'INSERT INTO kunde COLUMN telefon VARCHAR(30)', false, 3),
  -- db-sg-drop-vs-truncate
  ('db-sg-drop-vs-truncate', 'DROP entfernt zusätzlich die Tabellendefinition, TRUNCATE nur die Zeilen', true, 0),
  ('db-sg-drop-vs-truncate', 'DROP löscht nur die Zeilen, TRUNCATE zusätzlich die Struktur', false, 1),
  ('db-sg-drop-vs-truncate', 'Beide Befehle unterscheiden sich nur in der Geschwindigkeit', false, 2),
  ('db-sg-drop-vs-truncate', 'DROP lässt sich im Gegensatz zu TRUNCATE über eine WHERE-Klausel einschränken', false, 3),
  -- db-sg-ausfuehrungsplan
  ('db-sg-ausfuehrungsplan', 'Er zeigt, welche Zugriffspfade und Verfahren der Optimierer für die Abfrage wählt', true, 0),
  ('db-sg-ausfuehrungsplan', 'Er legt fest, wann eine Abfrage automatisch erneut ausgeführt wird', false, 1),
  ('db-sg-ausfuehrungsplan', 'Er prüft die Abfrage auf Verstöße gegen die Rechtevergabe', false, 2),
  ('db-sg-ausfuehrungsplan', 'Er dokumentiert, welcher Benutzer die Abfrage zuletzt gestartet hat', false, 3),
  -- db-sg-full-table-scan
  ('db-sg-full-table-scan', 'Die Datenbank liest alle Zeilen der Tabelle und prüft jede einzeln', true, 0),
  ('db-sg-full-table-scan', 'Die Datenbank nutzt einen vorhandenen Index besonders effizient', false, 1),
  ('db-sg-full-table-scan', 'Die Tabelle wird während der Abfrage vollständig gesperrt', false, 2),
  ('db-sg-full-table-scan', 'Die Abfrage wird zwischengespeichert und beim nächsten Aufruf wiederverwendet', false, 3),
  -- db-sg-composite-index-reihenfolge
  ('db-sg-composite-index-reihenfolge', 'Der Index ist primär nach nachname sortiert, eine Suche nur nach vorname kann ihn kaum nutzen', true, 0),
  ('db-sg-composite-index-reihenfolge', 'Nur die zuletzt genannte Spalte wird tatsächlich indiziert', false, 1),
  ('db-sg-composite-index-reihenfolge', 'Die Reihenfolge bestimmt, in welcher Reihenfolge die Ergebniszeilen ausgegeben werden', false, 2),
  ('db-sg-composite-index-reihenfolge', 'Die Reihenfolge wirkt sich nur auf den Speicherbedarf des Index aus', false, 3),
  -- db-sg-clustered-index
  ('db-sg-clustered-index', 'Er bestimmt die physische Speicherreihenfolge der Zeilen, daher gibt es nur einen je Tabelle', true, 0),
  ('db-sg-clustered-index', 'Er verteilt die Tabelle automatisch auf mehrere Datenbankserver', false, 1),
  ('db-sg-clustered-index', 'Er wird für jede Fremdschlüsselspalte automatisch angelegt', false, 2),
  ('db-sg-clustered-index', 'Er speichert eine zusätzliche Kopie der Tabelle für Leseabfragen', false, 3),
  -- db-sg-materialized-view
  ('db-sg-materialized-view', 'Sie speichert das Abfrageergebnis physisch und muss aktualisiert werden', true, 0),
  ('db-sg-materialized-view', 'Sie darf im Gegensatz zur View keine Joins enthalten', false, 1),
  ('db-sg-materialized-view', 'Sie wird bei jedem Zugriff automatisch neu berechnet', false, 2),
  ('db-sg-materialized-view', 'Sie ist ausschließlich für einzelne Benutzer sichtbar', false, 3),
  -- db-sg-default-wert
  ('db-sg-default-wert', 'Fehlt beim INSERT eine Angabe für die Spalte, wird der hinterlegte Wert eingetragen', true, 0),
  ('db-sg-default-wert', 'Bestehende Zeilen mit NULL werden nachträglich auf den Wert gesetzt', false, 1),
  ('db-sg-default-wert', 'Die Spalte kann danach keine anderen Werte mehr aufnehmen', false, 2),
  ('db-sg-default-wert', 'Der Wert wird bei jedem UPDATE erneut erzwungen', false, 3),
  -- db-sg-like-praefix
  ('db-sg-like-praefix', 'LIKE ''Mü%''', true, 0),
  ('db-sg-like-praefix', 'LIKE ''%Mü''', false, 1),
  ('db-sg-like-praefix', 'LIKE ''Mü_''', false, 2),
  ('db-sg-like-praefix', 'LIKE ''_Mü%''', false, 3),
  -- db-sg-top-n-abfrage
  ('db-sg-top-n-abfrage', 'SELECT * FROM artikel ORDER BY preis DESC LIMIT 10', true, 0),
  ('db-sg-top-n-abfrage', 'SELECT * FROM artikel LIMIT 10 ORDER BY preis DESC', false, 1),
  ('db-sg-top-n-abfrage', 'SELECT MAX(preis) FROM artikel GROUP BY artikel_id', false, 2),
  ('db-sg-top-n-abfrage', 'SELECT * FROM artikel WHERE preis = MAX(preis)', false, 3),
  -- db-sg-loeschanomalie
  ('db-sg-loeschanomalie', 'Beim Löschen eines Datensatzes gehen ungewollt weitere Informationen mit verloren', true, 0),
  ('db-sg-loeschanomalie', 'Ein Datensatz lässt sich wegen eines Fremdschlüssels nicht löschen', false, 1),
  ('db-sg-loeschanomalie', 'Ein gelöschter Datensatz erscheint nach einem Neustart wieder', false, 2),
  ('db-sg-loeschanomalie', 'Ein DELETE ohne WHERE leert versehentlich die gesamte Tabelle', false, 3),
  -- db-sg-funktionale-abhaengigkeit
  ('db-sg-funktionale-abhaengigkeit', 'Zu jedem Wert von A gehört genau ein Wert von B', true, 0),
  ('db-sg-funktionale-abhaengigkeit', 'A und B müssen in jeder Zeile denselben Wert enthalten', false, 1),
  ('db-sg-funktionale-abhaengigkeit', 'B verweist als Fremdschlüssel auf A', false, 2),
  ('db-sg-funktionale-abhaengigkeit', 'A und B bilden gemeinsam den Primärschlüssel der Relation', false, 3),
  -- db-sg-replikation
  ('db-sg-replikation', 'Sie spiegelt den Datenbestand auf weitere Server und erhöht so Verfügbarkeit und Leselast-Verteilung', true, 0),
  ('db-sg-replikation', 'Sie verteilt die Zeilen einer Tabelle überschneidungsfrei auf mehrere Server', false, 1),
  ('db-sg-replikation', 'Sie ersetzt eine regelmäßige Datensicherung vollständig', false, 2),
  ('db-sg-replikation', 'Sie fasst mehrere Datenbanken zu einer einzigen Instanz zusammen', false, 3),
  -- db-sg-generalisierung
  ('db-sg-generalisierung', 'Gemeinsame Attribute mehrerer Entitätstypen werden in einem übergeordneten Typ zusammengefasst', true, 0),
  ('db-sg-generalisierung', 'Eine Entität wird in mehrere Tabellen mit identischer Struktur aufgeteilt', false, 1),
  ('db-sg-generalisierung', 'Eine m:n-Beziehung wird über eine Zwischentabelle aufgelöst', false, 2),
  ('db-sg-generalisierung', 'Ein Attribut wird durch mehrere Einzelattribute ersetzt, um die 1NF zu erreichen', false, 3)
) as v(source_key, text, is_correct, sort_order)
on v.source_key = q.source_key;
