-- WiSo-Erweiterung für den Prüfungskatalog fiae-ae: 45 neue, selbst formulierte
-- Fragen zur Wirtschafts- und Sozialkunde (18 x multiple, 27 x single).
-- Keine Übernahme aus realen IHK- oder AKA-Prüfungen. Die bereits vorhandenen
-- 30 WiSo-Fragen wurden vorab ausgewertet, Themen und source_keys sind neu.
-- Schwerpunkte hier: Arbeitszeit und Urlaub, Kündigungsschutz, Rechtsformen,
-- Kaufvertrag und Leistungsstörungen, Steuern, Zahlungsverkehr, Finanzierung,
-- Konjunktur und Preisbildung, Datenschutz und Nachhaltigkeit.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed, question_type)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true, v.question_type
from topics t
join exams e on e.id = t.exam_id and e.slug = 'fiae-ae'
join (values
  -- ---------- multiple choice ----------
  ('Wirtschafts- & Sozialkunde', 'wiso-m-arbeitszeitgesetz-grenzen',
   'Welche Aussagen zum Arbeitszeitgesetz treffen zu?',
   'Das ArbZG rechnet in Werktagen: acht Stunden sind der Regelfall, zehn Stunden bleiben die Ausnahme, die durch einen Ausgleich im Halbjahresschnitt wieder eingefangen werden muss. Die Ruhezeit von elf Stunden schützt die Erholung zwischen zwei Schichten.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-rechtsformen-haftung',
   'Bei welchen Rechtsformen haftet mindestens eine beteiligte Person unbeschränkt mit dem Privatvermögen?',
   'Personengesellschaften und das Einzelunternehmen kennen keine gesetzliche Haftungsbegrenzung. Bei der KG trifft die unbeschränkte Haftung nur den Komplementär, der Kommanditist haftet begrenzt. Kapitalgesellschaften haften dagegen nur mit dem Gesellschaftsvermögen.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-maengelrechte',
   'Welche Rechte stehen einem Käufer bei einem Sachmangel grundsätzlich zu?',
   'Das BGB räumt dem Verkäufer zuerst eine zweite Chance ein: Der Käufer muss Nacherfüllung verlangen. Erst wenn diese fehlschlägt oder verweigert wird, kommen Rücktritt, Minderung oder Schadensersatz in Betracht. Eine Vertragsstrafe muss vertraglich vereinbart sein, sie folgt nicht aus dem Mangel.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-betriebsrat-mitbestimmung',
   'In welchen Angelegenheiten hat der Betriebsrat ein echtes Mitbestimmungsrecht nach dem BetrVG?',
   'Echte Mitbestimmung heißt, dass der Arbeitgeber ohne Zustimmung des Betriebsrats nicht handeln darf. Sie betrifft vor allem soziale Angelegenheiten der Belegschaft. Unternehmerische Grundentscheidungen wie das Produktprogramm bleiben allein beim Arbeitgeber, Tarifentgelte werden auf Verbandsebene verhandelt.',
   4, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-dsgvo-betroffenenrechte',
   'Welche Rechte räumt die DSGVO betroffenen Personen gegenüber einem Unternehmen ein?',
   'Die DSGVO will Transparenz und Kontrolle herstellen. Betroffene dürfen erfahren, was gespeichert ist, Fehler korrigieren lassen und unter bestimmten Voraussetzungen die Löschung verlangen. Ein Entgelt für die Verarbeitung sieht die Verordnung nicht vor.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-arbeitskampf',
   'Welche Aussagen zum Arbeitskampf in Deutschland treffen zu?',
   'Der Arbeitskampf ist an die Tarifrunde gebunden. Solange ein Tarifvertrag läuft, darf über die darin geregelten Punkte nicht gestreikt werden. Während eines Streiks ruhen die Hauptpflichten, der Arbeitgeber schuldet also kein Entgelt, stattdessen zahlt die Gewerkschaft ihren Mitgliedern Streikgeld.',
   4, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-sozialversicherung-beitragstragung',
   'Welche Aussagen zur Tragung und Abführung der Sozialversicherungsbeiträge treffen zu?',
   'Die gesetzliche Unfallversicherung ist der Sonderfall: Sie wird allein vom Arbeitgeber finanziert, weil sie das Betriebsrisiko absichert. Bei den übrigen Zweigen teilen sich Arbeitgeber und Arbeitnehmer den Beitrag grundsätzlich hälftig, abgeführt wird er gebündelt über den Arbeitgeber an die Krankenkasse als Einzugsstelle.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-preisbildung-markt',
   'Welche Aussagen zur Preisbildung auf einem Markt mit freiem Wettbewerb treffen zu?',
   'Nachfrage und Angebot reagieren gegenläufig auf den Preis. Der Gleichgewichtspreis ist der Punkt, an dem beide Mengen zusammenfallen. Ein Angebotsüberhang bedeutet unverkaufte Ware und setzt den Preis deshalb unter Druck, er treibt ihn nicht nach oben.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-inflation-folgen',
   'Welche Aussagen zu den Wirkungen einer anhaltenden Inflation treffen zu?',
   'Inflation entwertet Geldforderungen. Wer Geld verliehen oder gespart hat, verliert real, wer Schulden zu festem Zins hat, gewinnt. Zur Bekämpfung erhöht eine Notenbank den Leitzins, sie senkt ihn nicht, denn teures Geld bremst Nachfrage und Preisauftrieb.',
   4, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-fremdfinanzierung',
   'Welche Aussagen zur Fremdfinanzierung eines Unternehmens treffen zu?',
   'Fremdkapital wird befristet überlassen und ist unabhängig vom Geschäftserfolg zu verzinsen und zurückzuzahlen. Dafür bleibt der Einfluss der Kapitalgeber auf die Unternehmensführung begrenzt. In der Bilanz steht es als Verbindlichkeit, es erhöht das Eigenkapital nicht.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-pflichten-auszubildende',
   'Welche Pflichten treffen Auszubildende nach dem Berufsbildungsgesetz?',
   'Die Pflichten der Auszubildenden drehen sich um das Lernen selbst: sich bemühen, die Berufsschule besuchen und den Ausbildungsnachweis führen. Die Kosten der Ausbildung trägt der Betrieb, deshalb dürfen Werkzeuge oder Prüfungsmittel den Auszubildenden nicht in Rechnung gestellt werden.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-pflichten-ausbildender',
   'Welche Pflichten hat der Ausbildungsbetrieb gegenüber seinen Auszubildenden?',
   'Der Betrieb schuldet die Vermittlung der Ausbildungsinhalte, die nötigen Mittel auf eigene Kosten, die Freistellung für Schule und Prüfung sowie eine angemessene Vergütung. Eine Übernahme nach der Ausbildung ist dagegen freiwillig, sofern kein Tarifvertrag etwas anderes regelt.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-kaufvertrag-zustandekommen',
   'Welche Aussagen zum Zustandekommen eines Kaufvertrags treffen zu?',
   'Ein Kaufvertrag entsteht durch Antrag und Annahme, also zwei übereinstimmende Willenserklärungen. Auslagen und Kataloge sind rechtlich nur eine Einladung, ein Angebot abzugeben, sonst müsste der Händler jede Bestellung annehmen. Eine allgemeine Formvorschrift gibt es beim Kaufvertrag nicht.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-indirekte-steuern',
   'Welche der folgenden Steuern zählen zu den indirekten Steuern?',
   'Bei indirekten Steuern fallen Steuerschuldner und Steuerträger auseinander: Das Unternehmen führt ab, wirtschaftlich zahlt der Verbraucher über den Preis. Einkommen- und Gewerbesteuer knüpfen dagegen unmittelbar an die Leistungsfähigkeit des Steuerpflichtigen an.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-green-it',
   'Welche Maßnahmen senken den Energieverbrauch der IT in einem Betrieb?',
   'Energie spart vor allem, wer Hardware besser auslastet oder ganz abschaltet. Virtualisierung ersetzt viele schwach ausgelastete Server durch wenige gut ausgelastete. Eine höhere Bildschirmhelligkeit erhöht den Verbrauch, sie senkt ihn nicht.',
   2, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-kuendigungsschutz-kschg',
   'Welche Aussagen zum allgemeinen Kündigungsschutz nach dem Kündigungsschutzgesetz treffen zu?',
   'Das KSchG greift erst, wenn zwei Hürden genommen sind: eine Wartezeit von mehr als sechs Monaten im Betrieb und eine Betriebsgröße von in der Regel mehr als zehn Arbeitnehmern. Wer sich wehren will, muss die Drei-Wochen-Frist beachten, sonst gilt die Kündigung als wirksam. Eine Begründung im Kündigungsschreiben verlangt das Gesetz im Normalfall nicht.',
   4, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-sepa-lastschrift',
   'Welche Aussagen zur SEPA-Basislastschrift treffen zu?',
   'Anders als bei der Überweisung geht die Zahlung vom Empfänger aus. Rechtliche Grundlage ist das erteilte Mandat, das der Zahlungspflichtige jederzeit widerrufen kann. Als Schutz besteht ein Erstattungsrecht von acht Wochen ab Belastung, ohne dass Gründe genannt werden müssen.',
   3, 'multiple'),
  ('Wirtschafts- & Sozialkunde', 'wiso-m-jugendarbeitsschutz-regeln',
   'Welche konkreten Regelungen sieht das Jugendarbeitsschutzgesetz für Jugendliche vor?',
   'Das Gesetz begrenzt Dauer und Lage der Arbeit: acht Stunden täglich als Obergrenze, Beschäftigung nur am Tag und eine Verteilung auf höchstens fünf Wochentage. Die Nachtruhe endet nicht mit dem 16. Geburtstag, sie gilt bis zur Volljährigkeit mit nur wenigen branchenbezogenen Ausnahmen.',
   3, 'multiple'),
  -- ---------- single choice ----------
  ('Wirtschafts- & Sozialkunde', 'wiso-s-urlaubsanspruch-burlg',
   'Wie hoch ist der gesetzliche Mindesturlaub nach dem Bundesurlaubsgesetz bei einer Sechs-Tage-Woche?',
   'Das BUrlG rechnet in Werktagen und nennt 24 Werktage. Bei einer Fünf-Tage-Woche entspricht das 20 Arbeitstagen, der Anspruch wird also umgerechnet und nicht gekürzt.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-ruhepause',
   'Welche Ruhepause schreibt das Arbeitszeitgesetz bei einer Arbeitszeit von mehr als sechs bis zu neun Stunden vor?',
   'Bei mehr als sechs Stunden sind 30 Minuten Pause vorgeschrieben, ab mehr als neun Stunden sind es 45 Minuten. Die Pause darf in Abschnitte von mindestens 15 Minuten aufgeteilt werden.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-kuendigungsfrist-grundfrist',
   'Welche gesetzliche Grundkündigungsfrist gilt nach dem BGB für die Kündigung eines Arbeitsverhältnisses durch den Arbeitnehmer?',
   'Die Grundfrist beträgt vier Wochen zum 15. oder zum Ende eines Kalendermonats. Die mit der Betriebszugehörigkeit steigenden längeren Fristen gelten nur für Kündigungen durch den Arbeitgeber.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-arbeitszeugnis-arten',
   'Worin unterscheidet sich ein qualifiziertes Arbeitszeugnis von einem einfachen Arbeitszeugnis?',
   'Das einfache Zeugnis belegt nur Art und Dauer der Tätigkeit. Das qualifizierte Zeugnis bewertet zusätzlich Leistung und Verhalten und muss deshalb ausdrücklich verlangt werden.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-ohg-haftung',
   'Wie haften die Gesellschafter einer offenen Handelsgesellschaft für Verbindlichkeiten der Gesellschaft?',
   'Bei der OHG haftet jeder Gesellschafter unbeschränkt, unmittelbar und gesamtschuldnerisch. Ein Gläubiger kann sich also einen Gesellschafter aussuchen und von ihm die volle Summe verlangen, der Ausgleich untereinander erfolgt danach im Innenverhältnis.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-kg-kommanditist',
   'In welchem Umfang haftet ein Kommanditist für Verbindlichkeiten der Kommanditgesellschaft?',
   'Der Kommanditist haftet nur bis zur Höhe seiner im Handelsregister eingetragenen Einlage. Ist diese erbracht, ist seine persönliche Haftung ausgeschlossen. Die unbeschränkte Haftung trägt der Komplementär.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-ag-grundkapital',
   'Wie hoch ist das gesetzliche Mindestgrundkapital einer Aktiengesellschaft?',
   'Das Aktiengesetz verlangt ein Grundkapital von mindestens 50.000 Euro. Es ist in Aktien zerlegt und dient als Haftungspolster, weil die Aktionäre darüber hinaus nicht persönlich einstehen.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-gbr-merkmale',
   'Welche Aussage zur Gesellschaft bürgerlichen Rechts (GbR) ist zutreffend?',
   'Die GbR entsteht formlos, sobald sich mindestens zwei Personen zur Verfolgung eines gemeinsamen Zwecks zusammenschließen. Ein Mindestkapital gibt es nicht, dafür haften die Gesellschafter persönlich.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-handelsregister-abteilungen',
   'Welche Unternehmen werden in Abteilung B des Handelsregisters eingetragen?',
   'Abteilung A führt Einzelkaufleute und Personenhandelsgesellschaften wie OHG und KG, Abteilung B die Kapitalgesellschaften, also insbesondere GmbH, UG und AG.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-prokura-umfang',
   'Welches Geschäft darf ein Prokurist ohne ausdrückliche Sondervollmacht nicht vornehmen?',
   'Die Prokura ist weit, aber nicht unbegrenzt. Grundstücke darf der Prokurist nur veräußern oder belasten, wenn ihm diese Befugnis besonders erteilt wurde. Auch die Erteilung weiterer Prokura bleibt dem Inhaber vorbehalten.',
   4, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-umsatzsteuer-satz',
   'Wie hoch ist der allgemeine Umsatzsteuersatz in Deutschland?',
   'Der Regelsatz beträgt 19 Prozent. Ein ermäßigter Satz von 7 Prozent gilt für bestimmte Gütergruppen wie Grundnahrungsmittel, Bücher oder den Personennahverkehr.',
   1, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-umsatzsteuer-traeger',
   'Wer trägt die Umsatzsteuer wirtschaftlich, und wer führt sie an das Finanzamt ab?',
   'Getragen wird sie vom Endverbraucher, der sie im Bruttopreis mitbezahlt. Abgeführt wird sie vom Unternehmen. Unternehmen untereinander werden entlastet, weil sie die gezahlte Umsatzsteuer als Vorsteuer abziehen können.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-lohnsteuer-abfuehrung',
   'Wer behält die Lohnsteuer vom Arbeitsentgelt ein und führt sie an das Finanzamt ab?',
   'Die Lohnsteuer ist eine Erhebungsform der Einkommensteuer. Steuerschuldner bleibt der Arbeitnehmer, doch der Arbeitgeber behält sie direkt vom Bruttolohn ein und haftet für die richtige Abführung.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-gewaehrleistungsfrist',
   'Innerhalb welcher Frist verjähren Mängelansprüche beim Kauf einer neuen beweglichen Sache in der Regel?',
   'Die regelmäßige Verjährungsfrist für Mängelansprüche beträgt zwei Jahre ab Übergabe der Sache. Bei Bauwerken sind es fünf Jahre. Von der gesetzlichen Gewährleistung zu unterscheiden ist die Garantie, die freiwillig übernommen wird.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-nacherfuellung-vorrang',
   'Was kann ein Käufer bei einem Sachmangel zunächst verlangen, bevor er zurücktritt oder mindert?',
   'Das Gesetz gibt der Nacherfüllung den Vorrang, also Nachbesserung oder Ersatzlieferung. Erst wenn sie fehlschlägt, verweigert wird oder unzumutbar ist, öffnen sich Rücktritt und Minderung.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-schuldnerverzug',
   'Welche Voraussetzungen müssen für den Schuldnerverzug bei einer Geldforderung typischerweise vorliegen?',
   'Verzug setzt eine fällige und durchsetzbare Forderung sowie regelmäßig eine Mahnung nach Fälligkeit voraus. Entbehrlich ist die Mahnung etwa bei kalendermäßig bestimmter Leistungszeit oder bei ernsthafter Erfüllungsverweigerung.',
   4, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-eigentumsvorbehalt',
   'Welche Wirkung hat ein vereinbarter Eigentumsvorbehalt beim Kauf einer Maschine?',
   'Die Maschine wird übergeben und darf genutzt werden, das Eigentum geht aber erst mit vollständiger Zahlung des Kaufpreises über. Der Verkäufer behält damit eine Sicherheit, ohne die Lieferung hinauszuzögern.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-widerrufsrecht-fernabsatz',
   'Wie lange beträgt die gesetzliche Widerrufsfrist eines Verbrauchers bei einem Fernabsatzvertrag im Regelfall?',
   'Die Frist beträgt 14 Tage und beginnt bei Warenlieferungen mit dem Erhalt der Ware. Wird der Verbraucher nicht ordnungsgemäß über sein Widerrufsrecht belehrt, verlängert sie sich erheblich.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-berichtsheft',
   'Welche Bedeutung hat der schriftliche Ausbildungsnachweis (Berichtsheft) im dualen System?',
   'Er dokumentiert den Verlauf der Ausbildung und macht überprüfbar, ob der Ausbildungsplan eingehalten wird. Sein ordnungsgemäßes Führen ist Voraussetzung für die Zulassung zur Abschlussprüfung, benotet wird er jedoch nicht.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-ausbildung-ende-pruefung',
   'Wann endet ein Berufsausbildungsverhältnis, wenn der Auszubildende die Abschlussprüfung vor Ablauf der vereinbarten Ausbildungszeit besteht?',
   'Es endet mit der Bekanntgabe des Ergebnisses durch den Prüfungsausschuss. Wird die Prüfung nicht bestanden, kann der Auszubildende eine Verlängerung bis zur nächstmöglichen Wiederholungsprüfung verlangen, höchstens jedoch um ein Jahr.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-leasing',
   'Welchen wesentlichen Unterschied hat Leasing gegenüber einem kreditfinanzierten Kauf?',
   'Beim Leasing wird die Nutzung gegen laufende Raten überlassen, das Eigentum bleibt beim Leasinggeber. Das schont die Liquidität und vermeidet eine hohe Anfangsauszahlung, über die gesamte Laufzeit ist Leasing aber oft teurer als der Kauf.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-bip',
   'Was misst das Bruttoinlandsprodukt (BIP) einer Volkswirtschaft?',
   'Das BIP erfasst den Wert aller im Inland innerhalb eines Zeitraums erzeugten Waren und Dienstleistungen. Maßgeblich ist das Inlandsprinzip, also der Ort der Leistungserstellung, nicht die Staatsangehörigkeit der Erwerbstätigen.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-magisches-viereck',
   'Welche vier Ziele bilden das sogenannte magische Viereck der Wirtschaftspolitik?',
   'Das Stabilitätsgesetz nennt Preisniveaustabilität, hohen Beschäftigungsstand, außenwirtschaftliches Gleichgewicht und stetiges, angemessenes Wirtschaftswachstum. Magisch heißt es, weil die Ziele einander teilweise widersprechen.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-konjunkturphasen',
   'Wodurch ist die Phase der Rezession im Konjunkturzyklus gekennzeichnet?',
   'In der Rezession geht die gesamtwirtschaftliche Nachfrage zurück, Produktion und Investitionen sinken, die Arbeitslosigkeit steigt. Sie folgt auf die Hochkonjunktur und kann in eine Depression übergehen.',
   2, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-rentenversicherung-umlage',
   'Nach welchem Finanzierungsprinzip arbeitet die gesetzliche Rentenversicherung in Deutschland?',
   'Sie arbeitet nach dem Umlageverfahren: Die heute gezahlten Beiträge finanzieren unmittelbar die heutigen Renten. Es wird also kein individuelles Kapital angespart, weshalb das Verhältnis von Beitragszahlern zu Rentnern entscheidend ist.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-dsgvo-meldefrist',
   'Innerhalb welcher Frist muss ein Verantwortlicher eine meldepflichtige Verletzung des Schutzes personenbezogener Daten der Aufsichtsbehörde melden?',
   'Die DSGVO verlangt eine Meldung binnen 72 Stunden nach Bekanntwerden. Die kurze Frist soll der Aufsichtsbehörde ein frühes Eingreifen ermöglichen. Bei hohem Risiko sind zusätzlich die betroffenen Personen zu benachrichtigen.',
   3, 'single'),
  ('Wirtschafts- & Sozialkunde', 'wiso-s-abfallhierarchie',
   'Welche Stufe steht in der Abfallhierarchie des Kreislaufwirtschaftsgesetzes an erster Stelle?',
   'An erster Stelle steht die Vermeidung, danach folgen Vorbereitung zur Wiederverwendung, Recycling, sonstige Verwertung und zuletzt die Beseitigung. Abfall, der gar nicht erst entsteht, verursacht weder Transport noch Behandlungsaufwand.',
   2, 'single')
) as v(topic_name, source_key, q, expl, difficulty, question_type)
on t.name = v.topic_name;

insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- wiso-m-arbeitszeitgesetz-grenzen
  ('wiso-m-arbeitszeitgesetz-grenzen', 'Die werktägliche Arbeitszeit beträgt grundsätzlich höchstens acht Stunden', true, 0),
  ('wiso-m-arbeitszeitgesetz-grenzen', 'Eine Verlängerung auf zehn Stunden ist zulässig, wenn im Ausgleichszeitraum im Schnitt acht Stunden nicht überschritten werden', true, 1),
  ('wiso-m-arbeitszeitgesetz-grenzen', 'Nach Beendigung der Arbeit ist eine ununterbrochene Ruhezeit von mindestens elf Stunden einzuhalten', true, 2),
  ('wiso-m-arbeitszeitgesetz-grenzen', 'Arbeit an Sonntagen ist ausnahmslos verboten', false, 3),
  ('wiso-m-arbeitszeitgesetz-grenzen', 'Überstunden sind nur mit Zustimmung der zuständigen IHK zulässig', false, 4),
  -- wiso-m-rechtsformen-haftung
  ('wiso-m-rechtsformen-haftung', 'Einzelunternehmen', true, 0),
  ('wiso-m-rechtsformen-haftung', 'Offene Handelsgesellschaft (OHG)', true, 1),
  ('wiso-m-rechtsformen-haftung', 'Kommanditgesellschaft (KG)', true, 2),
  ('wiso-m-rechtsformen-haftung', 'Gesellschaft mit beschränkter Haftung (GmbH)', false, 3),
  ('wiso-m-rechtsformen-haftung', 'Aktiengesellschaft (AG)', false, 4),
  -- wiso-m-maengelrechte
  ('wiso-m-maengelrechte', 'Nacherfüllung durch Nachbesserung oder Ersatzlieferung', true, 0),
  ('wiso-m-maengelrechte', 'Rücktritt vom Vertrag, wenn die Nacherfüllung fehlschlägt', true, 1),
  ('wiso-m-maengelrechte', 'Minderung des Kaufpreises', true, 2),
  ('wiso-m-maengelrechte', 'Anspruch auf eine Vertragsstrafe allein wegen des Mangels', false, 3),
  ('wiso-m-maengelrechte', 'Sofortige fristlose Kündigung des Kaufvertrags', false, 4),
  -- wiso-m-betriebsrat-mitbestimmung
  ('wiso-m-betriebsrat-mitbestimmung', 'Beginn und Ende der täglichen Arbeitszeit sowie Lage der Pausen', true, 0),
  ('wiso-m-betriebsrat-mitbestimmung', 'Aufstellung allgemeiner Urlaubsgrundsätze und des Urlaubsplans', true, 1),
  ('wiso-m-betriebsrat-mitbestimmung', 'Einführung technischer Einrichtungen, die zur Verhaltens- oder Leistungskontrolle geeignet sind', true, 2),
  ('wiso-m-betriebsrat-mitbestimmung', 'Festlegung der Produkt- und Sortimentsstrategie des Unternehmens', false, 3),
  ('wiso-m-betriebsrat-mitbestimmung', 'Festsetzung der Höhe der tariflichen Entgelte', false, 4),
  -- wiso-m-dsgvo-betroffenenrechte
  ('wiso-m-dsgvo-betroffenenrechte', 'Recht auf Auskunft über die gespeicherten Daten', true, 0),
  ('wiso-m-dsgvo-betroffenenrechte', 'Recht auf Berichtigung unrichtiger Daten', true, 1),
  ('wiso-m-dsgvo-betroffenenrechte', 'Recht auf Löschung unter bestimmten Voraussetzungen', true, 2),
  ('wiso-m-dsgvo-betroffenenrechte', 'Anspruch auf ein Entgelt für jede Verarbeitung der eigenen Daten', false, 3),
  ('wiso-m-dsgvo-betroffenenrechte', 'Recht, die Löschung auch bei gesetzlicher Aufbewahrungspflicht zu erzwingen', false, 4),
  -- wiso-m-arbeitskampf
  ('wiso-m-arbeitskampf', 'Während der Laufzeit eines Tarifvertrags gilt für die geregelten Punkte eine Friedenspflicht', true, 0),
  ('wiso-m-arbeitskampf', 'Die Aussperrung ist ein Kampfmittel der Arbeitgeberseite', true, 1),
  ('wiso-m-arbeitskampf', 'Ein Erzwingungsstreik wird in der Regel durch eine Urabstimmung der Gewerkschaftsmitglieder eingeleitet', true, 2),
  ('wiso-m-arbeitskampf', 'Der Arbeitgeber muss den Streikenden das Entgelt fortzahlen', false, 3),
  -- wiso-m-sozialversicherung-beitragstragung
  ('wiso-m-sozialversicherung-beitragstragung', 'Die Beiträge zur gesetzlichen Unfallversicherung trägt allein der Arbeitgeber', true, 0),
  ('wiso-m-sozialversicherung-beitragstragung', 'Kranken-, Renten- und Arbeitslosenversicherung werden grundsätzlich hälftig von Arbeitgeber und Arbeitnehmer getragen', true, 1),
  ('wiso-m-sozialversicherung-beitragstragung', 'Der Arbeitgeber behält den Arbeitnehmeranteil vom Bruttolohn ein und führt den Gesamtbeitrag ab', true, 2),
  ('wiso-m-sozialversicherung-beitragstragung', 'Auszubildende sind von der Sozialversicherungspflicht generell befreit', false, 3),
  ('wiso-m-sozialversicherung-beitragstragung', 'Die Beiträge werden unmittelbar an das Finanzamt überwiesen', false, 4),
  -- wiso-m-preisbildung-markt
  ('wiso-m-preisbildung-markt', 'Steigt der Preis, sinkt tendenziell die nachgefragte Menge', true, 0),
  ('wiso-m-preisbildung-markt', 'Steigt der Preis, steigt tendenziell die angebotene Menge', true, 1),
  ('wiso-m-preisbildung-markt', 'Im Gleichgewichtspreis stimmen angebotene und nachgefragte Menge überein', true, 2),
  ('wiso-m-preisbildung-markt', 'Ein Angebotsüberhang lässt den Preis steigen', false, 3),
  -- wiso-m-inflation-folgen
  ('wiso-m-inflation-folgen', 'Die Kaufkraft des Geldes sinkt', true, 0),
  ('wiso-m-inflation-folgen', 'Festverzinsliche Sparguthaben verlieren real an Wert', true, 1),
  ('wiso-m-inflation-folgen', 'Schuldner mit festverzinslichen Krediten werden real entlastet', true, 2),
  ('wiso-m-inflation-folgen', 'Zur Bekämpfung senkt die Notenbank typischerweise den Leitzins', false, 3),
  -- wiso-m-fremdfinanzierung
  ('wiso-m-fremdfinanzierung', 'Die Kapitalgeber erhalten Zinsen unabhängig vom Gewinn des Unternehmens', true, 0),
  ('wiso-m-fremdfinanzierung', 'Das Kapital wird befristet überlassen und muss zurückgezahlt werden', true, 1),
  ('wiso-m-fremdfinanzierung', 'Die Kapitalgeber haben grundsätzlich kein Stimmrecht in der Gesellschafterversammlung', true, 2),
  ('wiso-m-fremdfinanzierung', 'Das aufgenommene Kapital erhöht das ausgewiesene Eigenkapital', false, 3),
  -- wiso-m-pflichten-auszubildende
  ('wiso-m-pflichten-auszubildende', 'Sich bemühen, die Fertigkeiten und Kenntnisse des Ausbildungsberufs zu erwerben', true, 0),
  ('wiso-m-pflichten-auszubildende', 'Am Berufsschulunterricht teilnehmen', true, 1),
  ('wiso-m-pflichten-auszubildende', 'Den schriftlichen Ausbildungsnachweis führen', true, 2),
  ('wiso-m-pflichten-auszubildende', 'Die Kosten für Werkzeuge und Prüfungsmittel selbst tragen', false, 3),
  ('wiso-m-pflichten-auszubildende', 'Nach der Ausbildung mindestens zwei Jahre im Betrieb bleiben', false, 4),
  -- wiso-m-pflichten-ausbildender
  ('wiso-m-pflichten-ausbildender', 'Ausbildungsmittel wie Werkzeuge und Fachliteratur kostenlos zur Verfügung stellen', true, 0),
  ('wiso-m-pflichten-ausbildender', 'Für Berufsschulunterricht und Prüfungen freistellen', true, 1),
  ('wiso-m-pflichten-ausbildender', 'Eine angemessene Vergütung zahlen', true, 2),
  ('wiso-m-pflichten-ausbildender', 'Den Auszubildenden nach bestandener Prüfung in jedem Fall unbefristet übernehmen', false, 3),
  -- wiso-m-kaufvertrag-zustandekommen
  ('wiso-m-kaufvertrag-zustandekommen', 'Er kommt durch zwei übereinstimmende Willenserklärungen zustande', true, 0),
  ('wiso-m-kaufvertrag-zustandekommen', 'Eine Ware im Schaufenster ist rechtlich nur die Aufforderung, ein Angebot abzugeben', true, 1),
  ('wiso-m-kaufvertrag-zustandekommen', 'Er ist grundsätzlich formfrei gültig', true, 2),
  ('wiso-m-kaufvertrag-zustandekommen', 'Er wird erst mit der Bezahlung der Ware wirksam', false, 3),
  ('wiso-m-kaufvertrag-zustandekommen', 'Er bedarf zu seiner Wirksamkeit stets der Schriftform', false, 4),
  -- wiso-m-indirekte-steuern
  ('wiso-m-indirekte-steuern', 'Umsatzsteuer', true, 0),
  ('wiso-m-indirekte-steuern', 'Tabaksteuer', true, 1),
  ('wiso-m-indirekte-steuern', 'Energiesteuer', true, 2),
  ('wiso-m-indirekte-steuern', 'Einkommensteuer', false, 3),
  ('wiso-m-indirekte-steuern', 'Gewerbesteuer', false, 4),
  -- wiso-m-green-it
  ('wiso-m-green-it', 'Konsolidierung mehrerer physischer Server durch Virtualisierung', true, 0),
  ('wiso-m-green-it', 'Automatisches Abschalten nicht genutzter Arbeitsplatzrechner außerhalb der Betriebszeiten', true, 1),
  ('wiso-m-green-it', 'Betrieb im Rechenzentrum mit hoher Auslastung und Nutzung der Abwärme', true, 2),
  ('wiso-m-green-it', 'Dauerhaft maximale Bildschirmhelligkeit an allen Arbeitsplätzen', false, 3),
  -- wiso-m-kuendigungsschutz-kschg
  ('wiso-m-kuendigungsschutz-kschg', 'Er greift erst, wenn das Arbeitsverhältnis länger als sechs Monate bestanden hat', true, 0),
  ('wiso-m-kuendigungsschutz-kschg', 'Er gilt nur in Betrieben mit in der Regel mehr als zehn Arbeitnehmern', true, 1),
  ('wiso-m-kuendigungsschutz-kschg', 'Eine Kündigungsschutzklage ist binnen drei Wochen nach Zugang der Kündigung zu erheben', true, 2),
  ('wiso-m-kuendigungsschutz-kschg', 'Der Arbeitgeber muss den Kündigungsgrund stets im Kündigungsschreiben angeben', false, 3),
  ('wiso-m-kuendigungsschutz-kschg', 'Nach zehn Jahren Betriebszugehörigkeit ist jede Kündigung ausgeschlossen', false, 4),
  -- wiso-m-sepa-lastschrift
  ('wiso-m-sepa-lastschrift', 'Die Zahlung wird vom Zahlungsempfänger ausgelöst', true, 0),
  ('wiso-m-sepa-lastschrift', 'Voraussetzung ist ein vom Zahlungspflichtigen erteiltes Mandat', true, 1),
  ('wiso-m-sepa-lastschrift', 'Der Zahlungspflichtige kann die Belastung innerhalb von acht Wochen ohne Angabe von Gründen erstattet verlangen', true, 2),
  ('wiso-m-sepa-lastschrift', 'Jede einzelne Abbuchung muss vorab gesondert von der Bank des Zahlungspflichtigen genehmigt werden', false, 3),
  -- wiso-m-jugendarbeitsschutz-regeln
  ('wiso-m-jugendarbeitsschutz-regeln', 'Die tägliche Arbeitszeit beträgt grundsätzlich höchstens acht Stunden', true, 0),
  ('wiso-m-jugendarbeitsschutz-regeln', 'Eine Beschäftigung ist grundsätzlich nur zwischen 6 und 20 Uhr zulässig', true, 1),
  ('wiso-m-jugendarbeitsschutz-regeln', 'Die Arbeitszeit ist auf höchstens fünf Tage in der Woche zu verteilen', true, 2),
  ('wiso-m-jugendarbeitsschutz-regeln', 'Ab Vollendung des 16. Lebensjahres ist Nachtarbeit uneingeschränkt erlaubt', false, 3),
  ('wiso-m-jugendarbeitsschutz-regeln', 'Ruhepausen sind für Jugendliche nicht vorgeschrieben', false, 4),
  -- wiso-s-urlaubsanspruch-burlg
  ('wiso-s-urlaubsanspruch-burlg', '24 Werktage', true, 0),
  ('wiso-s-urlaubsanspruch-burlg', '20 Werktage', false, 1),
  ('wiso-s-urlaubsanspruch-burlg', '30 Werktage', false, 2),
  ('wiso-s-urlaubsanspruch-burlg', '18 Werktage', false, 3),
  -- wiso-s-ruhepause
  ('wiso-s-ruhepause', 'Mindestens 30 Minuten', true, 0),
  ('wiso-s-ruhepause', 'Mindestens 15 Minuten', false, 1),
  ('wiso-s-ruhepause', 'Mindestens 45 Minuten', false, 2),
  ('wiso-s-ruhepause', 'Mindestens 60 Minuten', false, 3),
  -- wiso-s-kuendigungsfrist-grundfrist
  ('wiso-s-kuendigungsfrist-grundfrist', 'Vier Wochen zum 15. oder zum Ende eines Kalendermonats', true, 0),
  ('wiso-s-kuendigungsfrist-grundfrist', 'Zwei Wochen zu jedem beliebigen Tag', false, 1),
  ('wiso-s-kuendigungsfrist-grundfrist', 'Drei Monate zum Quartalsende', false, 2),
  ('wiso-s-kuendigungsfrist-grundfrist', 'Sechs Wochen zum Ende eines Kalenderjahres', false, 3),
  -- wiso-s-arbeitszeugnis-arten
  ('wiso-s-arbeitszeugnis-arten', 'Es bewertet zusätzlich Leistung und Verhalten im Arbeitsverhältnis', true, 0),
  ('wiso-s-arbeitszeugnis-arten', 'Es nennt ausschließlich Art und Dauer der Tätigkeit', false, 1),
  ('wiso-s-arbeitszeugnis-arten', 'Es wird von der zuständigen IHK statt vom Arbeitgeber ausgestellt', false, 2),
  ('wiso-s-arbeitszeugnis-arten', 'Es enthält eine verbindliche Gehaltsempfehlung für den nächsten Arbeitgeber', false, 3),
  -- wiso-s-ohg-haftung
  ('wiso-s-ohg-haftung', 'Alle Gesellschafter haften unbeschränkt und gesamtschuldnerisch, auch mit dem Privatvermögen', true, 0),
  ('wiso-s-ohg-haftung', 'Die Haftung ist auf das Gesellschaftsvermögen beschränkt', false, 1),
  ('wiso-s-ohg-haftung', 'Jeder Gesellschafter haftet nur bis zur Höhe seiner Einlage', false, 2),
  ('wiso-s-ohg-haftung', 'Nur der im Handelsregister zuerst eingetragene Gesellschafter haftet persönlich', false, 3),
  -- wiso-s-kg-kommanditist
  ('wiso-s-kg-kommanditist', 'Bis zur Höhe seiner eingetragenen Einlage', true, 0),
  ('wiso-s-kg-kommanditist', 'Unbeschränkt mit seinem gesamten Privatvermögen', false, 1),
  ('wiso-s-kg-kommanditist', 'Gar nicht, er ist von jeder Haftung freigestellt', false, 2),
  ('wiso-s-kg-kommanditist', 'In Höhe des doppelten Betrags seiner Einlage', false, 3),
  -- wiso-s-ag-grundkapital
  ('wiso-s-ag-grundkapital', '50.000 Euro', true, 0),
  ('wiso-s-ag-grundkapital', '25.000 Euro', false, 1),
  ('wiso-s-ag-grundkapital', '100.000 Euro', false, 2),
  ('wiso-s-ag-grundkapital', 'Es ist kein Mindestgrundkapital vorgeschrieben', false, 3),
  -- wiso-s-gbr-merkmale
  ('wiso-s-gbr-merkmale', 'Sie entsteht formlos durch den Zusammenschluss von mindestens zwei Personen zu einem gemeinsamen Zweck', true, 0),
  ('wiso-s-gbr-merkmale', 'Sie benötigt ein Mindestkapital von 25.000 Euro', false, 1),
  ('wiso-s-gbr-merkmale', 'Sie ist eine Kapitalgesellschaft mit beschränkter Haftung', false, 2),
  ('wiso-s-gbr-merkmale', 'Ihr Gesellschaftsvertrag muss zwingend notariell beurkundet werden', false, 3),
  -- wiso-s-handelsregister-abteilungen
  ('wiso-s-handelsregister-abteilungen', 'Kapitalgesellschaften wie GmbH, UG und AG', true, 0),
  ('wiso-s-handelsregister-abteilungen', 'Einzelkaufleute und Personenhandelsgesellschaften', false, 1),
  ('wiso-s-handelsregister-abteilungen', 'Eingetragene Vereine und Stiftungen', false, 2),
  ('wiso-s-handelsregister-abteilungen', 'Ausschließlich ausländische Unternehmen mit Sitz in Deutschland', false, 3),
  -- wiso-s-prokura-umfang
  ('wiso-s-prokura-umfang', 'Ein Betriebsgrundstück verkaufen', true, 0),
  ('wiso-s-prokura-umfang', 'Waren im Namen des Unternehmens einkaufen', false, 1),
  ('wiso-s-prokura-umfang', 'Mitarbeiter einstellen und entlassen', false, 2),
  ('wiso-s-prokura-umfang', 'Ein Darlehen für das Unternehmen aufnehmen', false, 3),
  -- wiso-s-umsatzsteuer-satz
  ('wiso-s-umsatzsteuer-satz', '19 Prozent', true, 0),
  ('wiso-s-umsatzsteuer-satz', '7 Prozent', false, 1),
  ('wiso-s-umsatzsteuer-satz', '16 Prozent', false, 2),
  ('wiso-s-umsatzsteuer-satz', '25 Prozent', false, 3),
  -- wiso-s-umsatzsteuer-traeger
  ('wiso-s-umsatzsteuer-traeger', 'Wirtschaftlich getragen vom Endverbraucher, abgeführt vom Unternehmen', true, 0),
  ('wiso-s-umsatzsteuer-traeger', 'Wirtschaftlich getragen und abgeführt vom Unternehmen', false, 1),
  ('wiso-s-umsatzsteuer-traeger', 'Wirtschaftlich getragen und selbst abgeführt vom Endverbraucher', false, 2),
  ('wiso-s-umsatzsteuer-traeger', 'Wirtschaftlich getragen vom Großhändler, abgeführt vom Einzelhändler', false, 3),
  -- wiso-s-lohnsteuer-abfuehrung
  ('wiso-s-lohnsteuer-abfuehrung', 'Der Arbeitgeber', true, 0),
  ('wiso-s-lohnsteuer-abfuehrung', 'Der Arbeitnehmer im Rahmen der Steuererklärung', false, 1),
  ('wiso-s-lohnsteuer-abfuehrung', 'Die Krankenkasse als Einzugsstelle', false, 2),
  ('wiso-s-lohnsteuer-abfuehrung', 'Die zuständige Industrie- und Handelskammer', false, 3),
  -- wiso-s-gewaehrleistungsfrist
  ('wiso-s-gewaehrleistungsfrist', 'Zwei Jahre ab Übergabe der Sache', true, 0),
  ('wiso-s-gewaehrleistungsfrist', 'Sechs Monate ab Übergabe der Sache', false, 1),
  ('wiso-s-gewaehrleistungsfrist', 'Fünf Jahre ab Übergabe der Sache', false, 2),
  ('wiso-s-gewaehrleistungsfrist', 'Drei Jahre ab Kenntnis des Mangels', false, 3),
  -- wiso-s-nacherfuellung-vorrang
  ('wiso-s-nacherfuellung-vorrang', 'Nacherfüllung, also Nachbesserung oder Ersatzlieferung', true, 0),
  ('wiso-s-nacherfuellung-vorrang', 'Sofortige Rückzahlung des vollen Kaufpreises', false, 1),
  ('wiso-s-nacherfuellung-vorrang', 'Schadensersatz statt der Leistung ohne weitere Voraussetzungen', false, 2),
  ('wiso-s-nacherfuellung-vorrang', 'Eine Vertragsstrafe in Höhe von zehn Prozent des Kaufpreises', false, 3),
  -- wiso-s-schuldnerverzug
  ('wiso-s-schuldnerverzug', 'Die Forderung ist fällig und der Schuldner wurde nach Fälligkeit gemahnt', true, 0),
  ('wiso-s-schuldnerverzug', 'Die Rechnung wurde zugestellt, auf die Fälligkeit kommt es nicht an', false, 1),
  ('wiso-s-schuldnerverzug', 'Der Gläubiger hat bereits einen gerichtlichen Mahnbescheid erwirkt', false, 2),
  ('wiso-s-schuldnerverzug', 'Der Schuldner hat den Zahlungsverzug schriftlich anerkannt', false, 3),
  -- wiso-s-eigentumsvorbehalt
  ('wiso-s-eigentumsvorbehalt', 'Die Maschine bleibt bis zur vollständigen Bezahlung Eigentum des Verkäufers', true, 0),
  ('wiso-s-eigentumsvorbehalt', 'Die Maschine darf bis zur vollständigen Bezahlung nicht genutzt werden', false, 1),
  ('wiso-s-eigentumsvorbehalt', 'Der Kaufpreis wird erst mit dem Weiterverkauf fällig', false, 2),
  ('wiso-s-eigentumsvorbehalt', 'Die Gewährleistungsfrist beginnt erst mit der letzten Rate', false, 3),
  -- wiso-s-widerrufsrecht-fernabsatz
  ('wiso-s-widerrufsrecht-fernabsatz', '14 Tage', true, 0),
  ('wiso-s-widerrufsrecht-fernabsatz', '7 Tage', false, 1),
  ('wiso-s-widerrufsrecht-fernabsatz', '30 Tage', false, 2),
  ('wiso-s-widerrufsrecht-fernabsatz', 'Zwei Jahre', false, 3),
  -- wiso-s-berichtsheft
  ('wiso-s-berichtsheft', 'Er dokumentiert den Ausbildungsverlauf und ist Zulassungsvoraussetzung für die Abschlussprüfung', true, 0),
  ('wiso-s-berichtsheft', 'Er wird vom Prüfungsausschuss benotet und geht in das Prüfungsergebnis ein', false, 1),
  ('wiso-s-berichtsheft', 'Er wird vom Ausbilder geführt und dem Auszubildenden am Ende ausgehändigt', false, 2),
  ('wiso-s-berichtsheft', 'Er ersetzt bei guter Führung den schriftlichen Teil der Zwischenprüfung', false, 3),
  -- wiso-s-ausbildung-ende-pruefung
  ('wiso-s-ausbildung-ende-pruefung', 'Mit der Bekanntgabe des Prüfungsergebnisses durch den Prüfungsausschuss', true, 0),
  ('wiso-s-ausbildung-ende-pruefung', 'Erst mit Ablauf der im Vertrag vereinbarten Ausbildungszeit', false, 1),
  ('wiso-s-ausbildung-ende-pruefung', 'Mit dem letzten Tag des Berufsschulunterrichts', false, 2),
  ('wiso-s-ausbildung-ende-pruefung', 'Mit der Aushändigung des Prüfungszeugnisses durch die IHK', false, 3),
  -- wiso-s-leasing
  ('wiso-s-leasing', 'Der Leasingnehmer erwirbt kein Eigentum, sondern zahlt für die Nutzung', true, 0),
  ('wiso-s-leasing', 'Der Leasingnehmer wird mit der ersten Rate Eigentümer des Objekts', false, 1),
  ('wiso-s-leasing', 'Leasing ist über die gesamte Laufzeit stets günstiger als ein Kauf', false, 2),
  ('wiso-s-leasing', 'Die Leasingraten müssen in einer Summe im Voraus gezahlt werden', false, 3),
  -- wiso-s-bip
  ('wiso-s-bip', 'Den Wert aller im Inland in einem Zeitraum erzeugten Waren und Dienstleistungen', true, 0),
  ('wiso-s-bip', 'Das gesamte Geldvermögen der privaten Haushalte', false, 1),
  ('wiso-s-bip', 'Die Summe aller im Inland gezahlten Steuern und Abgaben', false, 2),
  ('wiso-s-bip', 'Den Wert aller exportierten Waren abzüglich der Importe', false, 3),
  -- wiso-s-magisches-viereck
  ('wiso-s-magisches-viereck', 'Preisniveaustabilität, hoher Beschäftigungsstand, außenwirtschaftliches Gleichgewicht, stetiges Wachstum', true, 0),
  ('wiso-s-magisches-viereck', 'Steuersenkung, Schuldenabbau, Exportförderung, Lohnerhöhung', false, 1),
  ('wiso-s-magisches-viereck', 'Vollbeschäftigung, Umweltschutz, Bildung, Digitalisierung', false, 2),
  ('wiso-s-magisches-viereck', 'Geldwertstabilität, Gewinnmaximierung, Marktanteil, Innovation', false, 3),
  -- wiso-s-konjunkturphasen
  ('wiso-s-konjunkturphasen', 'Nachfrage und Produktion gehen zurück, die Arbeitslosigkeit steigt', true, 0),
  ('wiso-s-konjunkturphasen', 'Die Kapazitäten sind voll ausgelastet und die Preise steigen stark', false, 1),
  ('wiso-s-konjunkturphasen', 'Auftragseingänge und Investitionen ziehen nach einer Tiefphase wieder an', false, 2),
  ('wiso-s-konjunkturphasen', 'Die Wirtschaftsleistung wächst stetig mit gleichbleibender Rate', false, 3),
  -- wiso-s-rentenversicherung-umlage
  ('wiso-s-rentenversicherung-umlage', 'Nach dem Umlageverfahren, die heutigen Beiträge finanzieren die heutigen Renten', true, 0),
  ('wiso-s-rentenversicherung-umlage', 'Nach dem Kapitaldeckungsverfahren mit individuellen Sparkonten', false, 1),
  ('wiso-s-rentenversicherung-umlage', 'Vollständig aus Steuermitteln des Bundes', false, 2),
  ('wiso-s-rentenversicherung-umlage', 'Aus den Erträgen eines staatlichen Aktienfonds', false, 3),
  -- wiso-s-dsgvo-meldefrist
  ('wiso-s-dsgvo-meldefrist', 'Binnen 72 Stunden nach Bekanntwerden', true, 0),
  ('wiso-s-dsgvo-meldefrist', 'Binnen 24 Stunden nach Bekanntwerden', false, 1),
  ('wiso-s-dsgvo-meldefrist', 'Binnen zwei Wochen nach Bekanntwerden', false, 2),
  ('wiso-s-dsgvo-meldefrist', 'Erst mit dem nächsten jährlichen Datenschutzbericht', false, 3),
  -- wiso-s-abfallhierarchie
  ('wiso-s-abfallhierarchie', 'Vermeidung', true, 0),
  ('wiso-s-abfallhierarchie', 'Recycling', false, 1),
  ('wiso-s-abfallhierarchie', 'Energetische Verwertung', false, 2),
  ('wiso-s-abfallhierarchie', 'Beseitigung auf einer Deponie', false, 3)
) as v(source_key, text, is_correct, sort_order)
on v.source_key = q.source_key;
