-- Fourth content batch: 40 more original FIAE Anwendungsentwicklung
-- questions (10 per topic). Written in the style of the IHK exam, NOT
-- copied from any real exam. New source_keys checked against all 60
-- existing/pending questions (batches 1-3) for topic/content overlap.
--
-- Unlike the earlier batches, these are seeded reviewed = true (live
-- immediately) per explicit user instruction, so they go straight into
-- the exam without an approval step. They remain fully removable
-- afterwards via /review's "Freigabe zurückziehen" / reject actions,
-- same as any other question.

insert into questions (topic_id, source_key, question_text, explanation, difficulty, reviewed)
select t.id, v.source_key, v.q, v.expl, v.difficulty, true
from topics t
join exams e on e.id = t.exam_id and e.slug = 'fiae-ae'
join (values
  -- Datenbanken
  ('Datenbanken', 'db-truncate-vs-delete',
   'Was unterscheidet TRUNCATE von DELETE beim Leeren einer Tabelle?',
   'TRUNCATE entfernt alle Zeilen ohne einzelnes Logging und setzt Auto-Increment-Zähler zurück, kann aber nicht per WHERE eingeschränkt werden. DELETE ist filterbar und vollständig protokollier-/rollbackfähig.',
   2),
  ('Datenbanken', 'db-union-vs-unionall',
   'Was ist der Unterschied zwischen UNION und UNION ALL?',
   'UNION entfernt Duplikate aus dem kombinierten Ergebnis zweier Abfragen, UNION ALL behält alle Zeilen inklusive Duplikate und ist dadurch schneller.',
   2),
  ('Datenbanken', 'db-composite-key',
   'Was ist ein zusammengesetzter Schlüssel (Composite Key)?',
   'Ein Composite Key ist ein Primärschlüssel, der aus mehreren Spalten besteht, die erst gemeinsam jede Zeile eindeutig identifizieren.',
   2),
  ('Datenbanken', 'db-nosql-vs-sql',
   'Was ist ein zentrales Merkmal von NoSQL-Datenbanken im Vergleich zu relationalen Datenbanken?',
   'NoSQL-Datenbanken verzichten meist auf ein festes relationales Schema und sind oft auf horizontale Skalierbarkeit ausgelegt.',
   2),
  ('Datenbanken', 'db-rollback',
   'Wozu dient der Befehl ROLLBACK in einer Datenbanktransaktion?',
   'ROLLBACK macht alle Änderungen der aktuellen, noch nicht committeten Transaktion rückgängig.',
   1),
  ('Datenbanken', 'db-self-join',
   'Wofür wird ein Self-Join verwendet?',
   'Ein Self-Join verknüpft eine Tabelle mit sich selbst, z. B. um hierarchische Beziehungen innerhalb derselben Tabelle abzubilden (etwa Mitarbeiter und Vorgesetzter).',
   3),
  ('Datenbanken', 'db-varchar-vs-char',
   'Was unterscheidet den Datentyp VARCHAR von CHAR?',
   'VARCHAR speichert Zeichenketten variabler Länge platzsparend, CHAR reserviert immer eine feste Länge und füllt kürzere Werte mit Leerzeichen auf.',
   2),
  ('Datenbanken', 'db-index-tradeoff',
   'Welchen Nachteil bringt das Anlegen zu vieler Indizes auf einer Tabelle mit sich?',
   'Jeder Index muss bei INSERT, UPDATE und DELETE mitgepflegt werden, was diese Operationen verlangsamt, und benötigt zusätzlichen Speicherplatz.',
   3),
  ('Datenbanken', 'db-erm-weak-entity',
   'Was ist eine schwache Entität (weak entity) im ER-Modell?',
   'Eine schwache Entität lässt sich ohne den Primärschlüssel einer anderen, starken Entität nicht eindeutig identifizieren.',
   3),
  ('Datenbanken', 'db-check-constraint',
   'Wozu dient ein CHECK-Constraint in einer Tabellendefinition?',
   'Ein CHECK-Constraint stellt sicher, dass die Werte einer Spalte eine definierte Bedingung erfüllen, z. B. dass ein Alter nicht negativ sein darf.',
   2),
  -- Programmierung
  ('Programmierung', 'prog-overloading',
   'Was versteht man unter Methodenüberladung (Overloading)?',
   'Overloading bedeutet, mehrere Methoden mit demselben Namen, aber unterschiedlicher Parameterliste innerhalb derselben Klasse zu definieren.',
   2),
  ('Programmierung', 'prog-overriding',
   'Was versteht man unter Methodenüberschreibung (Overriding)?',
   'Beim Overriding stellt eine Unterklasse eine eigene Implementierung einer bereits in der Oberklasse definierten Methode bereit.',
   2),
  ('Programmierung', 'prog-static-keyword',
   'Was bedeutet das Schlüsselwort "static" bei einer Methode oder Variable in Java?',
   'Statische Mitglieder gehören zur Klasse selbst, nicht zu einer einzelnen Instanz, und sind ohne ein Objekt aufrufbar.',
   2),
  ('Programmierung', 'prog-exception-hierarchy',
   'Warum sollten in Java spezifischere Exceptions vor allgemeineren (z. B. Exception) gefangen werden?',
   'catch-Blöcke werden der Reihe nach geprüft; ein allgemeiner Block zuerst würde spezifischere Blöcke unerreichbar machen und die gezielte Fehlerbehandlung verhindern.',
   3),
  ('Programmierung', 'prog-linked-list',
   'Welchen Vorteil hat eine verkettete Liste (Linked List) gegenüber einem Array beim Einfügen von Elementen?',
   'Elemente lassen sich an bekannter Position einfügen, ohne nachfolgende Elemente im Speicher zu verschieben, da nur Referenzen angepasst werden.',
   2),
  ('Programmierung', 'prog-immutable',
   'Was bedeutet es, dass ein Objekt "immutable" (unveränderlich) ist?',
   'Der Zustand eines unveränderlichen Objekts kann nach seiner Erzeugung nicht mehr verändert werden.',
   1),
  ('Programmierung', 'prog-scrum-sprint',
   'Was ist ein Sprint im Scrum-Vorgehensmodell?',
   'Ein Sprint ist ein fester, zeitlich begrenzter Zeitraum, meist ein bis vier Wochen, in dem ein definiertes Produktinkrement fertiggestellt wird.',
   2),
  ('Programmierung', 'prog-api-rest',
   'Was kennzeichnet eine REST-konforme API insbesondere?',
   'REST-APIs kommunizieren zustandslos zwischen Client und Server, adressieren Ressourcen über eindeutige URIs und nutzen HTTP-Methoden zu deren Bearbeitung.',
   3),
  ('Programmierung', 'prog-compiler-vs-interpreter',
   'Was ist der grundlegende Unterschied zwischen einem Compiler und einem Interpreter?',
   'Ein Compiler übersetzt den gesamten Quellcode vorab in Maschinen- bzw. Zielcode, ein Interpreter führt den Code zur Laufzeit zeilenweise aus.',
   2),
  ('Programmierung', 'prog-design-pattern-singleton',
   'Was garantiert das Singleton-Entwurfsmuster?',
   'Das Singleton-Muster stellt sicher, dass von einer Klasse zur Laufzeit nur genau eine Instanz existiert, auf die global zugegriffen werden kann.',
   3),
  -- Netzwerke
  ('Netzwerke', 'net-osi-layers-count',
   'Aus wie vielen Schichten besteht das OSI-Referenzmodell?',
   'Das OSI-Modell besteht aus 7 Schichten, von der Bitübertragungsschicht bis zur Anwendungsschicht.',
   1),
  ('Netzwerke', 'net-tcp-handshake',
   'Wie heißt der Verbindungsaufbau bei TCP korrekt?',
   'TCP baut Verbindungen über den Drei-Wege-Handshake auf: SYN, SYN-ACK, ACK.',
   2),
  ('Netzwerke', 'net-udp-usecase',
   'Für welche Art von Anwendung eignet sich UDP typischerweise besonders gut?',
   'UDP eignet sich für Echtzeitanwendungen wie Video-/Audio-Streaming oder Online-Gaming, bei denen Geschwindigkeit wichtiger ist als eine garantierte Zustellung.',
   2),
  ('Netzwerke', 'net-subnetmask',
   'Wofür wird eine Subnetzmaske benötigt?',
   'Eine Subnetzmaske teilt eine IP-Adresse in Netz- und Hostanteil auf.',
   1),
  ('Netzwerke', 'net-arp',
   'Welche Aufgabe hat das ARP-Protokoll (Address Resolution Protocol)?',
   'ARP löst eine bekannte IP-Adresse in die zugehörige MAC-Adresse im lokalen Netz auf.',
   2),
  ('Netzwerke', 'net-tls-purpose',
   'Wofür wird TLS (Transport Layer Security) hauptsächlich eingesetzt?',
   'TLS verschlüsselt und sichert die Kommunikation ab, z. B. bei HTTPS-Verbindungen.',
   1),
  ('Netzwerke', 'net-gateway',
   'Welche Funktion hat ein Standard-Gateway in einem lokalen Netzwerk?',
   'Das Standard-Gateway leitet Datenverkehr aus dem lokalen Netz in andere Netze, z. B. das Internet, weiter.',
   2),
  ('Netzwerke', 'net-loopback',
   'Welche IP-Adresse wird typischerweise als Loopback-Adresse verwendet?',
   'Die IPv4-Loopback-Adresse ist 127.0.0.1 und verweist auf den eigenen Rechner.',
   1),
  ('Netzwerke', 'net-broadcast',
   'Was ist eine Broadcast-Adresse in einem IPv4-Subnetz?',
   'Die Broadcast-Adresse ist die höchste Adresse eines Subnetzes; Nachrichten an sie erreichen alle Hosts des Netzes.',
   2),
  ('Netzwerke', 'net-ftp-purpose',
   'Wofür wird das Protokoll FTP hauptsächlich eingesetzt?',
   'FTP dient der Übertragung von Dateien zwischen einem Client und einem Server.',
   1),
  -- Wirtschafts- & Sozialkunde
  ('Wirtschafts- & Sozialkunde', 'wiso-einkommensteuer',
   'Nach welchem Prinzip wird die deutsche Einkommensteuer erhoben?',
   'Die Einkommensteuer wird progressiv erhoben: Der Steuersatz steigt mit steigendem zu versteuerndem Einkommen.',
   2),
  ('Wirtschafts- & Sozialkunde', 'wiso-mindestausbildungsverguetung',
   'Seit welchem Jahr gilt in Deutschland eine gesetzliche Mindestausbildungsvergütung nach dem BBiG?',
   'Mit der BBiG-Reform trat zum 1. Januar 2020 eine gesetzliche Mindestausbildungsvergütung in Kraft.',
   3),
  ('Wirtschafts- & Sozialkunde', 'wiso-kurzarbeit',
   'Was ist Kurzarbeit?',
   'Kurzarbeit ist die vorübergehende Reduzierung von Arbeitszeit und -entgelt bei wirtschaftlichen Schwierigkeiten des Betriebs, teilweise ausgeglichen durch Kurzarbeitergeld der Agentur für Arbeit.',
   2),
  ('Wirtschafts- & Sozialkunde', 'wiso-tarifautonomie',
   'Was versteht man unter Tarifautonomie?',
   'Tarifautonomie ist das verfassungsrechtlich geschützte Recht von Gewerkschaften und Arbeitgeberverbänden, Arbeitsbedingungen ohne staatliche Einmischung eigenständig auszuhandeln.',
   3),
  ('Wirtschafts- & Sozialkunde', 'wiso-abmahnung',
   'Welche Funktion hat eine Abmahnung im Arbeitsrecht?',
   'Eine Abmahnung rügt ein konkretes Fehlverhalten und weist auf Konsequenzen bei Wiederholung hin; sie ist häufig Voraussetzung für eine verhaltensbedingte Kündigung.',
   3),
  ('Wirtschafts- & Sozialkunde', 'wiso-elternzeit',
   'Wer hat grundsätzlich Anspruch auf Elternzeit?',
   'Arbeitnehmerinnen und Arbeitnehmer, die mit ihrem Kind in einem Haushalt leben und es selbst betreuen, haben bis zur Vollendung des dritten Lebensjahres des Kindes Anspruch auf Elternzeit.',
   2),
  ('Wirtschafts- & Sozialkunde', 'wiso-wirtschaftskreislauf',
   'Was beschreibt der einfache Wirtschaftskreislauf?',
   'Er beschreibt den Güter- und Geldfluss zwischen den zwei Wirtschaftssubjekten Haushalte und Unternehmen.',
   1),
  ('Wirtschafts- & Sozialkunde', 'wiso-marktwirtschaft',
   'Was kennzeichnet die soziale Marktwirtschaft in Deutschland?',
   'Sie kombiniert einen freien Markt (Angebot und Nachfrage) mit staatlichen Eingriffen zum sozialen Ausgleich, z. B. Sozialversicherung und Arbeitsschutz.',
   2),
  ('Wirtschafts- & Sozialkunde', 'wiso-jugendarbeitsschutz',
   'Wofür gilt das Jugendarbeitsschutzgesetz (JArbSchG)?',
   'Es gilt für Beschäftigte unter 18 Jahren und regelt u. a. Arbeitszeit, Ruhepausen und das Verbot von Nachtarbeit.',
   2),
  ('Wirtschafts- & Sozialkunde', 'wiso-ausbildungszeugnis',
   'Worauf hat ein Auszubildender nach Beendigung der Ausbildung Anspruch?',
   'Auf ein schriftliches Ausbildungszeugnis vom Ausbildungsbetrieb.',
   1)
) as v(topic_name, source_key, q, expl, difficulty) on t.name = v.topic_name;

-- Answer options (option 0 sort first). is_correct marks the right answer.
insert into answer_options (question_id, option_text, is_correct, sort_order)
select q.id, v.text, v.is_correct, v.sort_order
from questions q
join (values
  -- db-truncate-vs-delete
  ('db-truncate-vs-delete', 'TRUNCATE ist nicht filterbar und protokolliert nicht einzeln, DELETE schon', true, 0),
  ('db-truncate-vs-delete', 'TRUNCATE und DELETE verhalten sich vollkommen identisch', false, 1),
  ('db-truncate-vs-delete', 'DELETE kann keine WHERE-Klausel nutzen, TRUNCATE schon', false, 2),
  ('db-truncate-vs-delete', 'TRUNCATE löscht nur einzelne Zeilen, DELETE immer die ganze Tabelle', false, 3),
  -- db-union-vs-unionall
  ('db-union-vs-unionall', 'UNION entfernt Duplikate, UNION ALL nicht', true, 0),
  ('db-union-vs-unionall', 'UNION ALL entfernt Duplikate, UNION nicht', false, 1),
  ('db-union-vs-unionall', 'Beide entfernen immer alle Duplikate', false, 2),
  ('db-union-vs-unionall', 'UNION ALL kann nur eine Tabelle verwenden', false, 3),
  -- db-composite-key
  ('db-composite-key', 'Ein Primärschlüssel aus mehreren Spalten zusammen', true, 0),
  ('db-composite-key', 'Ein Schlüssel, der automatisch generiert wird', false, 1),
  ('db-composite-key', 'Ein Fremdschlüssel mit mehreren Werten', false, 2),
  ('db-composite-key', 'Ein Index auf einer einzelnen Spalte', false, 3),
  -- db-nosql-vs-sql
  ('db-nosql-vs-sql', 'Meist kein festes relationales Schema, oft horizontal skalierbar', true, 0),
  ('db-nosql-vs-sql', 'Immer strikt relational mit festem Schema', false, 1),
  ('db-nosql-vs-sql', 'Unterstützt grundsätzlich kein SQL-ähnliches Abfragen', false, 2),
  ('db-nosql-vs-sql', 'Kann nur auf einem einzigen Server betrieben werden', false, 3),
  -- db-rollback
  ('db-rollback', 'Es macht alle Änderungen der laufenden Transaktion rückgängig', true, 0),
  ('db-rollback', 'Es speichert alle Änderungen dauerhaft', false, 1),
  ('db-rollback', 'Es löscht die gesamte Tabelle', false, 2),
  ('db-rollback', 'Es erstellt einen neuen Index', false, 3),
  -- db-self-join
  ('db-self-join', 'Um eine Tabelle mit sich selbst zu verknüpfen, z. B. für Hierarchien', true, 0),
  ('db-self-join', 'Um zwei komplett unterschiedliche Tabellen zu verbinden', false, 1),
  ('db-self-join', 'Um eine Tabelle zu duplizieren', false, 2),
  ('db-self-join', 'Um einen Index automatisch zu erstellen', false, 3),
  -- db-varchar-vs-char
  ('db-varchar-vs-char', 'VARCHAR ist variabel lang, CHAR hat feste Länge', true, 0),
  ('db-varchar-vs-char', 'CHAR ist variabel lang, VARCHAR hat feste Länge', false, 1),
  ('db-varchar-vs-char', 'Beide speichern ausschließlich Zahlen', false, 2),
  ('db-varchar-vs-char', 'VARCHAR kann keine Buchstaben speichern', false, 3),
  -- db-index-tradeoff
  ('db-index-tradeoff', 'Langsamere Schreiboperationen und mehr Speicherbedarf', true, 0),
  ('db-index-tradeoff', 'Langsamere Leseoperationen', false, 1),
  ('db-index-tradeoff', 'Es gibt keinerlei Nachteile', false, 2),
  ('db-index-tradeoff', 'Die Datenbank wird dadurch automatisch normalisiert', false, 3),
  -- db-erm-weak-entity
  ('db-erm-weak-entity', 'Sie ist ohne den Primärschlüssel einer starken Entität nicht eindeutig identifizierbar', true, 0),
  ('db-erm-weak-entity', 'Sie hat gar keine Attribute', false, 1),
  ('db-erm-weak-entity', 'Sie kann nicht in Beziehungen stehen', false, 2),
  ('db-erm-weak-entity', 'Sie besitzt immer einen eigenen, unabhängigen Primärschlüssel', false, 3),
  -- db-check-constraint
  ('db-check-constraint', 'Es stellt sicher, dass Spaltenwerte eine definierte Bedingung erfüllen', true, 0),
  ('db-check-constraint', 'Es erstellt automatisch einen Fremdschlüssel', false, 1),
  ('db-check-constraint', 'Es verschlüsselt die Spalte', false, 2),
  ('db-check-constraint', 'Es indiziert die Spalte automatisch', false, 3),
  -- prog-overloading
  ('prog-overloading', 'Mehrere Methoden mit gleichem Namen, aber unterschiedlichen Parametern', true, 0),
  ('prog-overloading', 'Eine Unterklasse überschreibt eine Methode der Oberklasse', false, 1),
  ('prog-overloading', 'Eine Methode wird als statisch deklariert', false, 2),
  ('prog-overloading', 'Eine Klasse erbt von mehreren Klassen', false, 3),
  -- prog-overriding
  ('prog-overriding', 'Eine Unterklasse stellt eine eigene Implementierung einer geerbten Methode bereit', true, 0),
  ('prog-overriding', 'Mehrere Methoden mit gleichem Namen in derselben Klasse', false, 1),
  ('prog-overriding', 'Eine Methode wird als final deklariert', false, 2),
  ('prog-overriding', 'Eine Variable wird neu initialisiert', false, 3),
  -- prog-static-keyword
  ('prog-static-keyword', 'Sie gehört zur Klasse, nicht zu einer einzelnen Instanz', true, 0),
  ('prog-static-keyword', 'Sie kann nur einmal pro Programm existieren', false, 1),
  ('prog-static-keyword', 'Sie ist automatisch privat', false, 2),
  ('prog-static-keyword', 'Sie wird bei jedem Objektaufruf neu erzeugt', false, 3),
  -- prog-exception-hierarchy
  ('prog-exception-hierarchy', 'Ein allgemeiner Block zuerst würde spezifischere Blöcke unerreichbar machen', true, 0),
  ('prog-exception-hierarchy', 'Die Reihenfolge der catch-Blöcke spielt keine Rolle', false, 1),
  ('prog-exception-hierarchy', 'Spezifische Exceptions dürfen nicht gefangen werden', false, 2),
  ('prog-exception-hierarchy', 'Allgemeine Exceptions existieren in Java nicht', false, 3),
  -- prog-linked-list
  ('prog-linked-list', 'Einfügen an bekannter Position ohne Verschieben anderer Elemente', true, 0),
  ('prog-linked-list', 'Direkter Zugriff auf jedes Element per Index in O(1)', false, 1),
  ('prog-linked-list', 'Geringerer Speicherverbrauch als ein Array', false, 2),
  ('prog-linked-list', 'Automatische Sortierung der Elemente', false, 3),
  -- prog-immutable
  ('prog-immutable', 'Sein Zustand kann nach der Erzeugung nicht mehr verändert werden', true, 0),
  ('prog-immutable', 'Es kann beliebig oft verändert werden', false, 1),
  ('prog-immutable', 'Es existiert nur zur Laufzeit einer Methode', false, 2),
  ('prog-immutable', 'Es besitzt keine Methoden', false, 3),
  -- prog-scrum-sprint
  ('prog-scrum-sprint', 'Ein fester Zeitraum, in dem ein Produktinkrement fertiggestellt wird', true, 0),
  ('prog-scrum-sprint', 'Ein einzelnes Meeting am Ende des Projekts', false, 1),
  ('prog-scrum-sprint', 'Die Testphase nach Projektabschluss', false, 2),
  ('prog-scrum-sprint', 'Die Rolle des Scrum Masters', false, 3),
  -- prog-api-rest
  ('prog-api-rest', 'Zustandslose Kommunikation, Ressourcen über URIs, HTTP-Methoden', true, 0),
  ('prog-api-rest', 'Zwingend zustandsbehaftete Sitzungen auf dem Server', false, 1),
  ('prog-api-rest', 'Ausschließliche Nutzung von SOAP-Nachrichten', false, 2),
  ('prog-api-rest', 'Direkter Datenbankzugriff ohne Server', false, 3),
  -- prog-compiler-vs-interpreter
  ('prog-compiler-vs-interpreter', 'Compiler übersetzt vorab komplett, Interpreter führt zeilenweise zur Laufzeit aus', true, 0),
  ('prog-compiler-vs-interpreter', 'Beide übersetzen ausschließlich zur Laufzeit', false, 1),
  ('prog-compiler-vs-interpreter', 'Ein Interpreter erzeugt immer eine ausführbare Datei', false, 2),
  ('prog-compiler-vs-interpreter', 'Ein Compiler kann keine Fehler erkennen', false, 3),
  -- prog-design-pattern-singleton
  ('prog-design-pattern-singleton', 'Dass zur Laufzeit nur genau eine Instanz der Klasse existiert', true, 0),
  ('prog-design-pattern-singleton', 'Dass beliebig viele Instanzen parallel existieren', false, 1),
  ('prog-design-pattern-singleton', 'Dass eine Klasse nicht instanziiert werden kann', false, 2),
  ('prog-design-pattern-singleton', 'Dass jede Methode nur einmal aufgerufen werden darf', false, 3),
  -- net-osi-layers-count
  ('net-osi-layers-count', '7', true, 0),
  ('net-osi-layers-count', '4', false, 1),
  ('net-osi-layers-count', '5', false, 2),
  ('net-osi-layers-count', '9', false, 3),
  -- net-tcp-handshake
  ('net-tcp-handshake', 'Drei-Wege-Handshake: SYN, SYN-ACK, ACK', true, 0),
  ('net-tcp-handshake', 'Ein einzelnes SYN-Paket reicht aus', false, 1),
  ('net-tcp-handshake', 'Vier-Wege-Handshake mit zwei ACKs', false, 2),
  ('net-tcp-handshake', 'TCP benötigt keinen Verbindungsaufbau', false, 3),
  -- net-udp-usecase
  ('net-udp-usecase', 'Echtzeitanwendungen wie Streaming oder Gaming', true, 0),
  ('net-udp-usecase', 'Dateiübertragungen, bei denen kein Datenverlust toleriert wird', false, 1),
  ('net-udp-usecase', 'E-Mail-Versand', false, 2),
  ('net-udp-usecase', 'Bankgeschäfte mit garantierter Zustellung', false, 3),
  -- net-subnetmask
  ('net-subnetmask', 'Um eine IP-Adresse in Netz- und Hostanteil aufzuteilen', true, 0),
  ('net-subnetmask', 'Um eine IP-Adresse zu verschlüsseln', false, 1),
  ('net-subnetmask', 'Um MAC-Adressen zu vergeben', false, 2),
  ('net-subnetmask', 'Um DNS-Anfragen zu beschleunigen', false, 3),
  -- net-arp
  ('net-arp', 'Es löst eine IP-Adresse in die zugehörige MAC-Adresse auf', true, 0),
  ('net-arp', 'Es vergibt IP-Adressen an Clients', false, 1),
  ('net-arp', 'Es verschlüsselt den Netzwerkverkehr', false, 2),
  ('net-arp', 'Es löst Domainnamen in IP-Adressen auf', false, 3),
  -- net-tls-purpose
  ('net-tls-purpose', 'Verschlüsselung und Absicherung der Kommunikation', true, 0),
  ('net-tls-purpose', 'Vergabe von IP-Adressen', false, 1),
  ('net-tls-purpose', 'Auflösung von Domainnamen', false, 2),
  ('net-tls-purpose', 'Beschleunigung von Downloads', false, 3),
  -- net-gateway
  ('net-gateway', 'Es leitet Verkehr aus dem lokalen Netz in andere Netze weiter', true, 0),
  ('net-gateway', 'Es vergibt MAC-Adressen', false, 1),
  ('net-gateway', 'Es speichert Webseiten zwischen', false, 2),
  ('net-gateway', 'Es verschlüsselt lokale Dateien', false, 3),
  -- net-loopback
  ('net-loopback', '127.0.0.1', true, 0),
  ('net-loopback', '192.168.0.1', false, 1),
  ('net-loopback', '10.0.0.1', false, 2),
  ('net-loopback', '0.0.0.0', false, 3),
  -- net-broadcast
  ('net-broadcast', 'Die höchste Adresse eines Subnetzes, erreicht alle Hosts darin', true, 0),
  ('net-broadcast', 'Die niedrigste Adresse eines Subnetzes', false, 1),
  ('net-broadcast', 'Die Adresse des Standard-Gateways', false, 2),
  ('net-broadcast', 'Eine beliebige freie Adresse im Subnetz', false, 3),
  -- net-ftp-purpose
  ('net-ftp-purpose', 'Übertragung von Dateien zwischen Client und Server', true, 0),
  ('net-ftp-purpose', 'Auflösung von Domainnamen', false, 1),
  ('net-ftp-purpose', 'Verschlüsselung von E-Mails', false, 2),
  ('net-ftp-purpose', 'Vergabe von IP-Adressen', false, 3),
  -- wiso-einkommensteuer
  ('wiso-einkommensteuer', 'Progressiv, der Steuersatz steigt mit dem Einkommen', true, 0),
  ('wiso-einkommensteuer', 'Ein fester Steuersatz für alle Einkommen', false, 1),
  ('wiso-einkommensteuer', 'Degressiv, der Steuersatz sinkt mit dem Einkommen', false, 2),
  ('wiso-einkommensteuer', 'Nur Unternehmen zahlen Einkommensteuer', false, 3),
  -- wiso-mindestausbildungsverguetung
  ('wiso-mindestausbildungsverguetung', 'Seit 2020', true, 0),
  ('wiso-mindestausbildungsverguetung', 'Seit 2010', false, 1),
  ('wiso-mindestausbildungsverguetung', 'Seit 2000', false, 2),
  ('wiso-mindestausbildungsverguetung', 'Es gibt keine gesetzliche Mindestvergütung', false, 3),
  -- wiso-kurzarbeit
  ('wiso-kurzarbeit', 'Vorübergehend reduzierte Arbeitszeit und -entgelt bei wirtschaftlichen Schwierigkeiten', true, 0),
  ('wiso-kurzarbeit', 'Eine dauerhafte Teilzeitregelung', false, 1),
  ('wiso-kurzarbeit', 'Eine Form der Kündigung', false, 2),
  ('wiso-kurzarbeit', 'Zusätzliche bezahlte Überstunden', false, 3),
  -- wiso-tarifautonomie
  ('wiso-tarifautonomie', 'Das Recht von Gewerkschaften und Arbeitgebern, Arbeitsbedingungen ohne Staat auszuhandeln', true, 0),
  ('wiso-tarifautonomie', 'Das Recht des Staates, Löhne direkt festzulegen', false, 1),
  ('wiso-tarifautonomie', 'Das Recht jedes Arbeitnehmers auf einen individuellen Tarifvertrag', false, 2),
  ('wiso-tarifautonomie', 'Die Pflicht zur Mitgliedschaft in einer Gewerkschaft', false, 3),
  -- wiso-abmahnung
  ('wiso-abmahnung', 'Sie rügt Fehlverhalten und weist auf Konsequenzen bei Wiederholung hin', true, 0),
  ('wiso-abmahnung', 'Sie beendet automatisch das Arbeitsverhältnis', false, 1),
  ('wiso-abmahnung', 'Sie ist eine Form der Gehaltserhöhung', false, 2),
  ('wiso-abmahnung', 'Sie muss nur mündlich ausgesprochen werden', false, 3),
  -- wiso-elternzeit
  ('wiso-elternzeit', 'Eltern, die mit dem Kind zusammenleben und es selbst betreuen', true, 0),
  ('wiso-elternzeit', 'Nur die Mutter des Kindes', false, 1),
  ('wiso-elternzeit', 'Nur Arbeitnehmer in Vollzeit', false, 2),
  ('wiso-elternzeit', 'Nur Beamte', false, 3),
  -- wiso-wirtschaftskreislauf
  ('wiso-wirtschaftskreislauf', 'Güter- und Geldfluss zwischen Haushalten und Unternehmen', true, 0),
  ('wiso-wirtschaftskreislauf', 'Nur den Geldfluss innerhalb eines Unternehmens', false, 1),
  ('wiso-wirtschaftskreislauf', 'Den Handel zwischen Staaten', false, 2),
  ('wiso-wirtschaftskreislauf', 'Die Verteilung von Steuern', false, 3),
  -- wiso-marktwirtschaft
  ('wiso-marktwirtschaft', 'Freier Markt kombiniert mit staatlichen Eingriffen zum sozialen Ausgleich', true, 0),
  ('wiso-marktwirtschaft', 'Vollständig staatlich geplante Wirtschaft', false, 1),
  ('wiso-marktwirtschaft', 'Vollständig unregulierter freier Markt ohne staatliche Eingriffe', false, 2),
  ('wiso-marktwirtschaft', 'Ausschließlich genossenschaftliche Unternehmen', false, 3),
  -- wiso-jugendarbeitsschutz
  ('wiso-jugendarbeitsschutz', 'Beschäftigte unter 18 Jahren', true, 0),
  ('wiso-jugendarbeitsschutz', 'Alle Arbeitnehmer unabhängig vom Alter', false, 1),
  ('wiso-jugendarbeitsschutz', 'Nur Auszubildende über 18 Jahre', false, 2),
  ('wiso-jugendarbeitsschutz', 'Nur Praktikanten', false, 3),
  -- wiso-ausbildungszeugnis
  ('wiso-ausbildungszeugnis', 'Ein schriftliches Ausbildungszeugnis vom Betrieb', true, 0),
  ('wiso-ausbildungszeugnis', 'Eine automatische Übernahme in ein festes Arbeitsverhältnis', false, 1),
  ('wiso-ausbildungszeugnis', 'Eine Abfindung', false, 2),
  ('wiso-ausbildungszeugnis', 'Ein zusätzliches IHK-Diplom ohne Prüfung', false, 3)
) as v(source_key, text, is_correct, sort_order) on v.source_key = q.source_key;
